<div class="container">
  Tréninková skupina: <?= $this->skupina ?><br>
  Věková kategorie: <?= $this->ageGroup ?><br>
  Partner(ka): <?= $this->partner ?><br>
  Výkonnostní třída: <?= $this->class ?><br>
  <br>
  <a href="/member/profil/edit">Upravit osobní údaje</a><br/>
  <a href="/member/profil/heslo">Změnit heslo</a><br/>
  <a href="/member/profil/par">Detaily páru</a><br/>
  <a href="/member/profil/platby">Platby</a><br/>
</div>
