    <br/>
    <div id="footer">
      <table style="margin:0 auto">
        <tr>
          <td style="border:none;background:none;text-align:center">
            <div style="width:480px;margin:0 auto 40px">
              <a class="no-a" href="https://www.facebook.com/olympolomouc"
                 target="_blank">
                <img alt="Facebook, stránka Taneční klub Olymp Olomouc"
                     src="/style/fb-logo.png" />
              </a>
            </div>
            <span>Podporuje nás:</span>
            <div style="width:480px;margin:0 auto 40px">
              <a class="no-a" href="http://www.kr-olomoucky.cz/" target="_blank">
                <img alt="Olomoucký kraj" src="/style/logo-kraj.png" />
              </a>
              <br/>
              <a class="no-a" href="http://www.olomouc.eu/" target="_blank">
                <img alt="Město Olomouc" src="/style/logo-olomouc.jpg"
                     style="height:85px;width:auto;"/>
              </a>
            </div>
          </td>
          <td style="border:none;background:none;text-align:center">
            <span>Mediální partner:</span>
            <div style="width:480px;margin:0 auto 40px">
              <a class="no-a" href="http://www.kr-olomoucky.cz/" target="_blank">
                <iframe
                  src="http://poutaky.denik.cz/olomoucky.denik.cz-300x300-zpravy_region.html"
                  style="width:300px;height:300px;border:0;overflow:auto;">
                </iframe>
              </a>
            </div>
          </td>
        </tr>
      </table>

      <span>
        design a realizace:
        <a href="mailto:kuba.zarybnicky@post.cz">Jakub Zárybnický</a>
      </span>

      <span>
        © 2014 TK Olymp Olomouc
      </span>
    </div>
    <script type="text/javascript" src="/scripts/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="/scripts/masonry.pkgd.min.js"></script>
    <script type="text/javascript" src="/scripts/imagesloaded.pkgd.min.js"></script>
    <script type="text/javascript" src="/scripts/polyfill.object-fit.min.js"></script>
    <script type="text/javascript" src="/scripts/video.min.js"></script>
    <script type="text/javascript" src="/scripts/main.js"></script>
    <script type="text/javascript"
            src="//connect.facebook.net/cs_CZ/all.js#xfbml=1&appId=132983570203245"
            id="facebook-jssdk"></script>
    <script type="text/javascript">
     var _gaq = _gaq || [];
     _gaq.push(['_require','inpage_linkid','//www.google-analytics.com/plugins/ga/inpage_linkid.js'],
               ['_setAccount','UA-44456908-1'],['_trackPageview']);
     (function() {
         var ga = document.createElement('script');
         ga.type='text/javascript';
         ga.async=true;
         ga.src='//www.google-analytics.com/ga.js';
         var s=document.getElementsByTagName('script')[0];
         s.parentNode.insertBefore(ga,s);
     })();
    </script>
  </body>
</html>
