    <br/>
    <div id="footer">
      <table style="margin:0 auto">
        <tr>
          <td style="border:none;background:none;text-align:center">
            <div style="width:480px;margin:0 auto 40px">
              <a class="no-a" href="https://www.facebook.com/olympolomouc"
                 target="_blank">
                <img alt="Facebook, stránka Taneční klub Olymp Olomouc"
                     src="/style/fb-logo.png" />
              </a>
            </div>
            <span>Podporuje nás:</span>
            <div style="width:480px;margin:0 auto 40px">
              <a class="no-a" href="http://www.kr-olomoucky.cz/" target="_blank">
                <img alt="Olomoucký kraj" src="/style/logo-kraj.png" />
              </a>
              <br/>
              <a class="no-a" href="http://www.olomouc.eu/" target="_blank">
                <img alt="Město Olomouc" src="/style/logo-olomouc.jpg"
                     style="height:85px;width:auto;"/>
              </a>
            </div>
          </td>
          <td style="border:none;background:none;text-align:center">
            <span>Mediální partner:</span>
            <div style="width:480px;margin:0 auto 40px">
              <a class="no-a" href="http://www.kr-olomoucky.cz/" target="_blank">
                <iframe
                  src="http://poutaky.denik.cz/olomoucky.denik.cz-300x300-zpravy_region.html"
                  style="width:300px;height:300px;border:0;overflow:auto;">
                </iframe>
              </a>
            </div>
          </td>
        </tr>
      </table>

      <span>
        design a realizace:
        <a href="mailto:kuba.zarybnicky@post.cz">Jakub Zárybnický</a>
      </span>

      <span>
        © 2014 TK Olymp Olomouc
      </span>
    </div>
    <script type="text/javascript" src="/scripts/main.js"></script>
  </body>
</html>
