<br/>
<div id="footer">
    <div class="container">
        <div class="row" style="text-align:center">
            <div class="col" style="display:flex;flex-direction:column;justify-content:space-around;">
                <div>
                    <a class="no-a" href="https://www.facebook.com/tkolymp"
                       target="_blank">
                        <img alt="Facebook, stránka Taneční klub Olymp Olomouc"
                             src="/style/fb-logo.png" />
                    </a>
                </div>
                <div>
                    design a realizace:
                    <a href="mailto:jakub@zarybnicky.com">Jakub Zárybnický</a>
                    <br>
                    © 2018 TK Olymp Olomouc
                </div>
            </div>
            <div class="col">
                <span>Podporuje nás:</span>
                <div>
                    <a class="no-a" href="http://www.kr-olomoucky.cz/" target="_blank">
                        <img alt="Olomoucký kraj" src="/style/logo-kraj.png" />
                    </a>
                    <br/>
                    <a class="no-a" href="http://www.olomouc.eu/" target="_blank">
                        <img alt="Město Olomouc" src="/style/logo-olomouc.jpg"
                             style="height:85px;width:auto;"/>
                    </a>
                </div>
            </div>
        </tr>
    </table>
</div>

<script type="text/javascript" src="/scripts/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="/scripts/popper.min.js"></script>
<script type="text/javascript" src="/scripts/bootstrap.min.js"></script>
<script type="text/javascript" src="/scripts/jquery.sticky.js"></script>
<script type="text/javascript" src="/scripts/polyfill.object-fit.min.js"></script>
<script type="text/javascript" src="/scripts/stickyfill.min.js"></script>
<script type="text/javascript" src="/scripts/leaflet.js"></script>
<script type="text/javascript" src="/scripts/video.min.js"></script>
<script type="text/javascript" src="/scripts/select2.full.js"></script>
<script type="text/javascript" src="/scripts/main.js"></script>
<script async="true" type="text/javascript"
        src="//connect.facebook.net/cs_CZ/all.js#xfbml=1&appId=132983570203245"
        id="facebook-jssdk"></script>
<script type="text/javascript">
 var _gaq = _gaq || [];
 _gaq.push(['_require','inpage_linkid','//www.google-analytics.com/plugins/ga/inpage_linkid.js'],
           ['_setAccount','UA-44456908-1'],['_trackPageview']);
 (function() {
     var ga = document.createElement('script');
     ga.type='text/javascript';
     ga.async=true;
     ga.src='//www.google-analytics.com/ga.js';
     var s=document.getElementsByTagName('script')[0];
     s.parentNode.insertBefore(ga,s);
 })();
</script>
  </body>
</html>
