<!DOCTYPE HTML>
<html prefix="og:http://ogp.me/ns" lang="cs">
  <head>
    <meta name="keywords" content="taneční klub, tk, olymp, olomouc, tk olymp, sportovní tanec" />
    <meta name="wot-verification" content="ec0cf41ab42dae52d3d4"/>
    <meta name="ICBM" content="49.591700,17.285174"/>
    <meta name="geo.placename" content="Olomouc, Česká Republika"/>
    <meta name="geo.position" content="49.591700;17.285174"/>
    <meta name="geo.region" content="cs"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="msvalidate.01" content="7BD6C8B5748FC22EF06AB3AE89900885" />
    <meta name="google-site-verification" content="Hfe7zlgTDOIpJv4rKGQz2Xg8Aezb6sIO0aAxVhrml9w" />
    <meta name="norton-safeweb-site-verification"
          content="r44xj2vskhlgkyqcqm1hdgga2jdfj-idvyys0277y96s72k-tq0z-yyjdu7h3el6pi2gek0i4ykq3xgiguufrvuhj8nbj4n4miwjhvumhp35jfrafyynhj4ee8ctzpzh" />
    <meta property="fb:app_id" content="132983570203245"/>
    <script type="text/javascript" src="/scripts/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="/scripts/masonry.pkgd.min.js"></script>
    <script type="text/javascript" src="//connect.facebook.net/cs_CZ/all.js#xfbml=1&appId=132983570203245" id="facebook-jssdk"></script>
    <script type="text/javascript">
     var _gaq = _gaq || [];
     _gaq.push(['_require','inpage_linkid','//www.google-analytics.com/plugins/ga/inpage_linkid.js'],
               ['_setAccount','UA-44456908-1'],['_trackPageview']);
     (function() {var ga = document.createElement('script');ga.type='text/javascript';ga.async=true;
                  ga.src='//www.google-analytics.com/ga.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(ga,s);
                  })();
    </script>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
    <link rel="stylesheet" type="text/css" href="/style/style.new.css" />
    <title>TK Olymp Olomouc</title>
  </head>
  <body>
    <div id="fb-root"></div>

    <div id="top"></div>

    <div class="container">
      <div id="header">
        <div id="header-inner">
          <?php echo $this->login(); ?>

          <div id="logo">
            <a class="no-a" href="/">
              <img alt="" src="/style/logo-wide.png" />
            </a>
          </div>
        </div>
      </div>
    </div>

    <div id="menu">
      <div id="menu-logo">
        <img alt="" src="/style/logo-small.png" />
      </div>
      <ul id="menu-inner">
        <li><a href="/home">Domů</a></li>
        <li class="menu-more">
          <a href="/oklubu">O klubu</a>
          <ul>
            <li><a href="/oklubu/historie">Historie</a></li>
            <li><a href="/oklubu/uspechy">Úspěchy v číslech</a></li>
            <li><a href="/oklubu/mistrovstvi">Mistrovství ČR</a></li>
            <li><a href="/oklubu/druzstva">Mistrovství družstev</a></li>
            <li><a href="/oklubu/liga">Taneční liga</a></li>
            <li><a href="/oklubu/treneri/externi">Externí trenéři</a></li>
            <li><a href="/oklubu/treneri/klubovi">Kluboví trenéři</a></li>
            <li><a href="/oklubu/saly">Kde trénujeme</a></li>
            <li><a href="/oklubu//stanovy.pdf">Stanovy klubu</a></li>
          </ul>
        </li>
        <li><a href="/aktualne/clanky">Novinky</a></li>
        <li class="menu-more">
          <a href="/nabizime">Nabízíme</a>
          <ul>
            <li><a href="/nabizime/obecne">Taneční kurzy</a></li>
            <li><a href="/nabizime/vystoupeni">Taneční vystoupení</a></li>
            <li><a href="/nabizime/soustredeni">Taneční soustředění</a></li>
            <li><a href="/nabizime/seminare">Tancování pro děti</a></li>
            <li><a href="/nabizime/individualky">Zázemí pro taneční sport</a></li>
          </ul>
        </li>
        <li><a href="/fotogalerie">Fotogalerie</a></li>
        <li><a href="/kontakt">Kontakt</a></li>
        <li class="menu-right menu-more">
          <a href="/admin/home">Administrace</a>
        </li>
        <li class="menu-right menu-more">
          <a href="/member/home">Pro členy</a>
        </li>
      </ul>
    </div>
