<!DOCTYPE HTML>
<html prefix="og:http://ogp.me/ns" lang="cs">
  <head>
    <meta name="keywords" content="taneční klub, tk, olymp, olomouc, tk olymp, sportovní tanec" />
    <meta name="wot-verification" content="ec0cf41ab42dae52d3d4"/>
    <meta name="ICBM" content="49.591700,17.285174"/>
    <meta name="geo.placename" content="Olomouc, Česká Republika"/>
    <meta name="geo.position" content="49.591700;17.285174"/>
    <meta name="geo.region" content="cs"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="msvalidate.01" content="7BD6C8B5748FC22EF06AB3AE89900885" />
    <meta name="google-site-verification" content="Hfe7zlgTDOIpJv4rKGQz2Xg8Aezb6sIO0aAxVhrml9w" />
    <meta name="norton-safeweb-site-verification"
          content="r44xj2vskhlgkyqcqm1hdgga2jdfj-idvyys0277y96s72k-tq0z-yyjdu7h3el6pi2gek0i4ykq3xgiguufrvuhj8nbj4n4miwjhvumhp35jfrafyynhj4ee8ctzpzh" />
    <meta property="fb:app_id" content="132983570203245"/>
    <script type="text/javascript" src="/scripts/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="/scripts/masonry.pkgd.min.js"></script>
    <script type="text/javascript" src="//connect.facebook.net/cs_CZ/all.js#xfbml=1&appId=132983570203245" id="facebook-jssdk"></script>
    <script type="text/javascript">
     var _gaq = _gaq || [];
     _gaq.push(['_require','inpage_linkid','//www.google-analytics.com/plugins/ga/inpage_linkid.js'],
               ['_setAccount','UA-44456908-1'],['_trackPageview']);
     (function() {var ga = document.createElement('script');ga.type='text/javascript';ga.async=true;
                  ga.src='//www.google-analytics.com/ga.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(ga,s);
                  })();
    </script>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
    <link rel="stylesheet" type="text/css" href="/style/style.new.css" />
    <title>TK Olymp Olomouc</title>
  </head>
  <body>
    <div id="fb-root"></div>

    <div id="top"></div>

    <div class="container">
      <div id="header">
        <div id="header-inner">
          <?php echo $this->login(); ?>

          <div id="logo">
            <a class="no-a" href="/">
              <img alt="" src="/style/logo-wide.png" />
            </a>
          </div>
        </div>
      </div>
    </div>

    <?php echo View::$controller->navbar(); ?>
