// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// This file will be automatically regenerated when your Next.js server is running.
// nextjs-routes version: 2.0.0
/* eslint-disable */

// prettier-ignore
declare module "nextjs-routes" {
  import type {
    GetServerSidePropsContext as NextGetServerSidePropsContext,
    GetServerSidePropsResult as NextGetServerSidePropsResult
  } from "nextjs";

  export type Route =
    | DynamicRoute<"/admin/akce/[id]", { "id": string }>
    | StaticRoute<"/admin/akce/add">
    | StaticRoute<"/admin/akce">
    | DynamicRoute<"/admin/aktuality/[id]", { "id": string }>
    | StaticRoute<"/admin/aktuality/add">
    | StaticRoute<"/admin/aktuality">
    | DynamicRoute<"/admin/cohort-group/[id]", { "id": string }>
    | StaticRoute<"/admin/cohort-group/add">
    | StaticRoute<"/admin/cohort-group">
    | DynamicRoute<"/admin/dokumenty/[id]", { "id": string }>
    | StaticRoute<"/admin/dokumenty">
    | DynamicRoute<"/admin/nabidka/[id]", { "id": string }>
    | StaticRoute<"/admin/nabidka/add">
    | StaticRoute<"/admin/nabidka">
    | DynamicRoute<"/admin/nastenka/[id]", { "id": string }>
    | StaticRoute<"/admin/nastenka/add">
    | StaticRoute<"/admin/nastenka">
    | DynamicRoute<"/admin/pary/[id]", { "id": string }>
    | StaticRoute<"/admin/pary/add">
    | StaticRoute<"/admin/pary">
    | DynamicRoute<"/admin/platby/items/[id]", { "id": string }>
    | StaticRoute<"/admin/platby/items/add">
    | StaticRoute<"/admin/platby/items">
    | DynamicRoute<"/admin/platby/structure/category/[id]", { "id": string }>
    | StaticRoute<"/admin/platby/structure/category/add">
    | StaticRoute<"/admin/platby/structure/category">
    | DynamicRoute<"/admin/platby/structure/group/[id]", { "id": string }>
    | StaticRoute<"/admin/platby/structure/group/add">
    | StaticRoute<"/admin/platby/structure/group">
    | DynamicRoute<"/admin/rozpis/[id]", { "id": string }>
    | StaticRoute<"/admin/rozpis/add">
    | StaticRoute<"/admin/rozpis">
    | DynamicRoute<"/admin/skupiny/[id]", { "id": string }>
    | StaticRoute<"/admin/skupiny/add">
    | StaticRoute<"/admin/skupiny">
    | StaticRoute<"/admin/tenant">
    | DynamicRoute<"/admin/users/[id]", { "id": string }>
    | StaticRoute<"/admin/users/add">
    | StaticRoute<"/admin/users">
    | StaticRoute<"/admin/users/unconfirmed">
    | DynamicRoute<"/articles/[id]", { "id": string }>
    | StaticRoute<"/articles">
    | StaticRoute<"/contact">
    | StaticRoute<"/crm">
    | StaticRoute<"/dashboard">
    | StaticRoute<"/documents">
    | StaticRoute<"/error">
    | DynamicRoute<"/events/[id]", { "id": string }>
    | StaticRoute<"/events">
    | StaticRoute<"/forgotten-password">
    | StaticRoute<"/galerie-mistru">
    | StaticRoute<"/gallery">
    | StaticRoute<"/">
    | StaticRoute<"/kde-trenujeme">
    | StaticRoute<"/login">
    | StaticRoute<"/logout">
    | StaticRoute<"/o-nas">
    | StaticRoute<"/ochrana-osobnich-udaju">
    | StaticRoute<"/prijdtancit">
    | StaticRoute<"/profile">
    | DynamicRoute<"/programy/[id]/[...slug]", { "id": string; "slug": string[] }>
    | StaticRoute<"/register">
    | StaticRoute<"/schedule">
    | StaticRoute<"/skolni-krouzky">
    | StaticRoute<"/treneri">
    | StaticRoute<"/treninkove-skupiny">
    | StaticRoute<"/vyhody-clenstvi">
    | StaticRoute<"/vystoupeni">;

  interface StaticRoute<Pathname> {
    pathname: Pathname;
    query?: Query | undefined;
    hash?: string | null | undefined;
  }

  interface DynamicRoute<Pathname, Parameters> {
    pathname: Pathname;
    query: Parameters & Query;
    hash?: string | null | undefined;
  }

  interface Query {
    [key: string]: string | string[] | undefined;
  };

  export type RoutedQuery<P extends Route["pathname"]> = Extract<
    Route,
    { pathname: P }
  >["query"];

  export type Locale = undefined;

  /**
   * A typesafe utility function for generating paths in your application.
   *
   * route({ pathname: "/foos/[foo]", query: { foo: "bar" }}) will produce "/foos/bar".
   */
  export declare function route(r: Route): string;

  /**
   * Nearly identical to GetServerSidePropsContext from next, but further narrows
   * types based on nextjs-route's route data.
   */
  export type GetServerSidePropsContext<
    Pathname extends Route["pathname"] = Route["pathname"],
    Preview extends NextGetServerSidePropsContext["previewData"] = NextGetServerSidePropsContext["previewData"]
  > = Omit<NextGetServerSidePropsContext, 'params' | 'query' | 'defaultLocale' | 'locale' | 'locales'> & {
    params: Extract<Route, { pathname: Pathname }>["query"];
    query: Query;
    defaultLocale?: undefined;
    locale?: Locale;
    locales?: undefined;
  };

  /**
   * Nearly identical to GetServerSideProps from next, but further narrows
   * types based on nextjs-route's route data.
   */
  export type GetServerSideProps<
    Props extends { [key: string]: any } = { [key: string]: any },
    Pathname extends Route["pathname"] = Route["pathname"],
    Preview extends NextGetServerSideProps["previewData"] = NextGetServerSideProps["previewData"]
  > = (
    context: GetServerSidePropsContext<Pathname, Preview>
  ) => Promise<NextGetServerSidePropsResult<Props>>
}

// prettier-ignore
declare module "next/link" {
  import type { Route } from "nextjs-routes";
  import type { LinkProps as NextLinkProps } from "next/dist/client/link";
  import type {
    AnchorHTMLAttributes,
    DetailedReactHTMLElement,
    MouseEventHandler,
    PropsWithChildren,
  } from "react";
  export * from "next/dist/client/link";

  type StaticRoute = Exclude<Route, { query: any }>["pathname"];

  export interface LinkProps
    extends Omit<NextLinkProps, "href" | "locale">,
      AnchorHTMLAttributes<HTMLAnchorElement> {
    href: Route | StaticRoute | Omit<Route, "pathname">
    locale?: false;
  }

  type LinkReactElement = DetailedReactHTMLElement<
    {
      onMouseEnter?: MouseEventHandler<Element> | undefined;
      onClick: MouseEventHandler;
      href?: string | undefined;
      ref?: any;
    },
    HTMLElement
  >;

  declare function Link(props: PropsWithChildren<LinkProps>): LinkReactElement;

  export default Link;
}

// prettier-ignore
declare module "next/router" {
  import type { Locale, Route, RoutedQuery } from "nextjs-routes";
  import type { NextRouter as Router } from "next/dist/client/router";
  export * from "next/dist/client/router";
  export { default } from "next/dist/client/router";

  type NextTransitionOptions = NonNullable<Parameters<Router["push"]>[2]>;
  type StaticRoute = Exclude<Route, { query: any }>["pathname"];

  interface TransitionOptions extends Omit<NextTransitionOptions, "locale"> {
    locale?: false;
  }

  type PathnameAndQuery<Pathname> = Required<
    Pick<Extract<Route, { pathname: Pathname }>, "pathname" | "query">
  >;

  type AutomaticStaticOptimizedQuery<PaQ> = Omit<PaQ, "query"> & {
    query: Partial<PaQ["query"]>;
  };

  type BaseRouter<PaQ> =
    | ({ isReady: false } & AutomaticStaticOptimizedQuery<PaQ>)
    | ({ isReady: true } & PaQ);

  export type NextRouter<P extends Route["pathname"] = Route["pathname"]> =
    BaseRouter<PathnameAndQuery<P>> &
      Omit<
        Router,
        | "defaultLocale"
        | "domainLocales"
        | "isReady"
        | "locale"
        | "locales"
        | "pathname"
        | "push"
        | "query"
        | "replace"
        | "route"
      > & {
        defaultLocale?: undefined;
        domainLocales?: undefined;
        locale?: Locale;
        locales?: undefined;
        push(
          url: Route | StaticRoute | Omit<Route, "pathname">,
          as?: string,
          options?: TransitionOptions
        ): Promise<boolean>;
        replace(
          url: Route | StaticRoute | Omit<Route, "pathname">,
          as?: string,
          options?: TransitionOptions
        ): Promise<boolean>;
        route: P;
      };

  export function useRouter<P extends Route["pathname"]>(): NextRouter<P>;
}
