# see https://ankane.org/postgres-sslmode-explained for more info
from: postgresql://root@alfa/olymp
to: postgres://$(echo $PGHOST)/olymp
to_safe: true

# exclude tables
# exclude:
#   - table1
#   - table2

# define groups
# groups:
#   group1:
#     - table1
#     - table2

# sync specific schemas
schemas:
  - public

# protect sensitive information
# data_rules:
#   email: unique_email
#   phone: unique_phone
#   last_name: random_letter
#   birthday: random_date
#   encrypted_*: null
