compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  graphile-build-pg@*:
    peerDependencies:
      graphql: "*"
  next-urql@*:
    dependencies:
      "@urql/core": "*"
  nextjs-google-analytics@*:
    dependencies:
      tslib: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-yarnpnp2nix.cjs
    spec: "https://github.com/madjam002/yarnpnp2nix/raw/master/plugin/dist/plugin-yarnpnp2nix.js"

yarnPath: .yarn/releases/yarn-4.0.0-rc.45.cjs
