compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@sentry/nextjs@*":
    peerDependencies:
      react: "*"
    dependencies:
      "@opentelemetry/core": "*"
      "@opentelemetry/instrumentation": "*"
      "@opentelemetry/sdk-trace-base": "*"
  graphile-build-pg@*:
    peerDependencies:
      graphql: "*"
  graphql-ws@*:
    peerDependencies:
      ws: "*"
  next-urql@*:
    peerDependencies:
      "@urql/core": "*"
  nextjs-google-analytics@*:
    dependencies:
      tslib: "*"
  postgraphile@*:
    peerDependencies:
      graphql: "*"
  "@graphql-eslint/eslint-plugin@*":
    peerDependencies:
      eslint: "*"
  "@typescript-eslint/type-utils@*":
    peerDependencies:
      eslint: "*"

plugins:
  - checksum: add22d627ca8aafa931e7715c5b8f61c6438909a3a779ba11bab7395476365b65bd4cafd30c92fd88d8b2dbbe6b4e952f864aec165aa499a0087941f1ae057db
    path: .yarn/plugins/@yarnpkg/plugin-yarnpnp2nix.cjs
    spec: "https://github.com/madjam002/yarnpnp2nix/raw/master/plugin/dist/plugin-yarnpnp2nix.js"
  - checksum: 5e73a1acbb9741fce1e8335e243c9480ea2107b9b4b65ed7643785ddea9e3019aee254a92a853b1cd71023b16fff5b7d3afd5256fe57cd35a54f8785b8c30281
    path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://go.mskelton.dev/yarn-outdated/v4"

yarnPath: .yarn/releases/yarn-4.4.1.cjs
