compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@graphql-eslint/eslint-plugin@*":
    dependencies:
      eslint: "*"
  "@graphql-tools/graphql-tag-pluck@*":
    dependencies:
      "@babel/core": "*"
  eslint-config-next@*:
    dependencies:
      next: "*"
      react: "*"
      react-dom: "*"
  graphile-build-pg@*:
    peerDependencies:
      graphql: "*"
  next-urql@*:
    dependencies:
      "@urql/core": "*"
  nextjs-google-analytics@*:
    dependencies:
      tslib: "*"

plugins:
  - checksum: add22d627ca8aafa931e7715c5b8f61c6438909a3a779ba11bab7395476365b65bd4cafd30c92fd88d8b2dbbe6b4e952f864aec165aa499a0087941f1ae057db
    path: .yarn/plugins/@yarnpkg/plugin-yarnpnp2nix.cjs
    spec: "https://github.com/madjam002/yarnpnp2nix/raw/master/plugin/dist/plugin-yarnpnp2nix.js"
  - checksum: 0141f8cfb8a5ea41428cc0a49cf412f0cf13a3f3f9e51ef354768b5c988c93d0adc46c318d11b6da858b9ce9a9c8db0069712c10be35f9ac440071bc00bc4216
    path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-4.0.1.cjs
