compressionLevel: mixed

enableGlobalCache: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-yarnpnp2nix.cjs
    spec: "https://github.com/madjam002/yarnpnp2nix/raw/master/plugin/dist/plugin-yarnpnp2nix.js"

yarnPath: .yarn/releases/yarn-4.0.0-rc.48.cjs

packageExtensions:
  next-urql@*:
    dependencies:
      "@urql/core": "*"
  nextjs-google-analytics@*:
    dependencies:
      tslib: "*"
