compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  graphile-build-pg@*:
    peerDependencies:
      graphql: "*"
  eslint-config-next@*:
    dependencies:
      next: "*"
  next-urql@*:
    dependencies:
      "@urql/core": "*"
  nextjs-google-analytics@*:
    dependencies:
      tslib: "*"

plugins:
  - checksum: fd862fe99cd107543cc4fef5ac49709268f5a99dbd4b60d1fc65dcb55ae0c86752e4494e9f7cb0b5481b73203b81c1ba0f529794f93d9fdc866458898a9863c1
    path: .yarn/plugins/@yarnpkg/plugin-yarnpnp2nix.cjs
    spec: "https://raw.githubusercontent.com/zarybnicky/yarnpnp2nix/master/plugin/dist/plugin-yarnpnp2nix.js"
  - checksum: 0141f8cfb8a5ea41428cc0a49cf412f0cf13a3f3f9e51ef354768b5c988c93d0adc46c318d11b6da858b9ce9a9c8db0069712c10be35f9ac440071bc00bc4216
    path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-4.0.0-rc.45.cjs
