services:

  postgres:
    platform: linux/x86_64
    image: ivanlonel/postgis-with-extensions
    restart: always
    ports:
      - "5432:5432"
    shm_size: 2gb
    stop_grace_period: 2m30s
    environment:
      - LC_COLLATE=C
      - POSTGRES_USER=olymp
      - POSTGRES_PASSWORD=olymp
      - POSTGRES_DB=olymp
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/conf.sh:/docker-entrypoint-initdb.d/z_conf.sh

volumes:
  postgres_data:
