schema:
  - schema.graphql
  - "directive @requires(depends: String[]) on FIELD"

documents: "frontend/graphql/*.graphql"
watch: "frontend/graphql/*.graphql"
config:
  scalars:
    Datetime: "string"
    Date: "string"
    Time: "string"
    BigInt: "string"
    JSON: "{ [key: string]: unknown }"
