* Klub:
** Tréninkové skupiny
Tanečníci v klubu jsou rozdělení do tréninkových skupin dle věku a výkonnostního
stupně, každá skupina má své barevné nebo místní označení.

*** TYRKYSOVÁ SKUPINA Olomouc
Začátečníci a mírně pokročilí, 5-7 let

- Úterý 14:00 Standard, Hýžová, Holečkova O
- Čtvrtek 14:00, Latina, Hýžová, Holečkova

*** FIALOVÁ SKUPINA Olomouc
Jednotlivci a páry, mírně pokročilí, 8-13 let

- Pondělí 16:00 Standard, Hýža, Holečkova
- Pondělí 16:45 Pohybovka, Grepl, Holečkova
- Úterý 16:00 Practise, Hýžová, Holečkova
- Úterý 16:45 Performance, Hýžová/Hýžová ml., Holečkova
- Pátek 15:30 Latina, Hýžová, Holečkova

*** MODRÁ SKUPINA Olomouc
Soutěžní páry, pokročilí, 9-13 let

- Pondělí 16:00 Kondiční pohybovka, Grepl, Holečkova
- Pondělí 16:45 Standard, Hýža, Holečkova
- Úterý 16:00 Practise, Hýžová ml., Holečkova
- Úterý 16:45 Practise, Hýžová/Hýžová ml., Holečkova
- Čtvrtek 16:00 Latina, Hýža, Holečkova
- Čtvrtek 16:45 Performance, Hýža, Holečkova

*** ZELENÁ SKUPINA Olomouc
Jednotlivci a páry, mírně pokročilí, 15+ let

- Pondělí 18:15 Latina, Grepl, Holečkova
- Pondělí 19:00 Pohybová průprava, Grepl, Hýža, Holečkova
- Úterý 18:15 Performance, Hýža, SGO
- Středa 18:00 Practise, Hýža, SGO
- Pátek 15:30 Standard, Grepl, SGO

*** ČERVENÁ SKUPINA Olomouc
Soutěžní páry, ​pokročilí (výkonnostní třídy E-pokročilé, D,C), 15+ let

- Pondělí 18:15 Latina, Hýža, Holečkova
- Pondělí 19:00 Pohybová průprava, Grepl/Hýža, Holečkova
- Úterý 18:15 Performance, Hýža, SGO
- Středa 18:00 Practise, Hýža, SGO
- Pátek 16:15 Standard, Hýža, SGO

*** ŽLUTÁ SKUPINA Olomouc
Soutěžní páry, velmi pokročilí (výkonnostní třídy C-pokročilé, B, A,M), 13+ let

- Pondělí 19:00 Pohybová průprava, Grepl/Hýža, Holečkova
- Úterý 17:30 Standard, Odstrčil/Hýža, SGO
- Úterý 18:15 Performance, Hýža, SGO
- Středa 18:00 Practise, Hýža, SGO
- Středa 19:30 TOP finále, Hýža, SGO
- Čtvrtek 16:45 Latina, Karásek, Holečkova

*** ZÁKLADNÍ ČLENSTVÍ Olomouc
Pro členy bez příslušnosti ke skupině

- přístup na sály pro volný trénink
- Středa 18:00 Practise, Hýža, SGO

*** PROSTĚJOV 1 a 2
Mírně pokročilí 10-16 let

- Pondělí 17:00-18:30, Pecha
- Středa 15:45-17:15, Pecha

*** PŘEROV 1
Začátečníci a mírně pokročilí 6-15 let

- Pondělí 17:00 - 18:00, Hýžová ml, Šrámková
- Středa 17:00 - 18:00, Hýžová ml, Šrámková

*** PŘEROV 2
Mírně pokročilí 16+

- Pondělí 18:00 - 19:00, Hýžová ml, Šrámková
- Středa 18:00 - 19:00, Hýžová ml, Šrámková

** Benefity členství
Slevy na soustředění, na oblečení, obuv, popis péče o členy

- Sehraný tým pravidelně školených trenérů
- Pravidelně zvaní nejlepší trenéři v České republice
- Sportovní centrum mládeže - jediné v Olomouckém kraji v tanečním sportu
- Moderní metody sportovního tréninku (spolupráce s Fakultou tělesné kultury)
- Pravidelná tréninková soustředění - jednodenní, vícedenní, výjezdní

- Finanční podpora začátečníků - Olympteam Campy (poloviční ceny oproti skutečým nákladům)
- Finanční podpora vrcholových sportovců - příprava na vrcholné akce
- Administrativní zajištění dokumentace pro podávání individuálních dotací reprezentantům
- Workshopy s tématikou soutěžní image (česání, líčení, oblečení)
- Workshopy speciální přípravy (životospráva, mentální trénink, sportovní trénink)

- Teambuildingové aktivity tmelící kolektiv
- Možnost tréninků po boku nejlepších sportovních tanečníků ČR
- Spolupráce s mistry světa z Itálie
- Kolekce společného klubového oblečení (reprezentační soupravy, trička, mikiny)
- Online rezervační systém individuálních hodin

** Galerie mistrů
Foto – poháry (FOTKY – prolnout po  vteřinách) + popisek (fotka na banner)

** "Chci tančit"
Máte zájem o taneční sport? Potom jste na dobré adrese. Pokud jste se stále
nerozhodli, můžete se k nám přijít podívat na trénink, zjistit v jakém prostředí
a atmosféře trénujeme,

Pokud se k nám přidáte, čeká Vás milý a ambiciózní trenérský tým a velká spousta
dřiny, radosti a zážitků. A pokud jste pilní, pracovití a odhodlaní, jsme to
právě my - Olympteam - s kým můžete v tomto sportu dosáhnout až na vrchol.

Kdy a kam přijít Vám sdělí náš pracovník, který odpoví na vyplnění tohoto
formuláře.

Jméno a příjmení, věk, Taneční dovednost (rolovací seznam - začátečník, mírně
pokročilý, pokročilý). Kontaktní email, Poznámka

* Nabízíme
** Tréninkové programy
Řadu let vyvíjíme a zdokonalujeme tréninkový systém vrcholových sportovců od
dětských přípravek po členství ve Sportovním centru mládeže. Klademe důraz na
zdravý způsob tréninku i životního stylu. Vyhýbáme se rané specializaci a
výsledkovému zaměření v dětském věku. Naopak je pro nás důležitý všeobecný
sportovní rozvoj dětí - laicky řečeno: v dětském věku více sportujeme,
posilujeme a hrajeme si a méně tančíme. S přibývajícím věkem zvyšujeme taneční
specializaci, páry mají možnost spolupracovat se špičkovými trenéry z ČR i
zahraničí.

*** Přípravka tanečního sportu
Přípravky tanečního sportu probíhají v Olomouci, Prostějově a Přerově, potom
dále v projektu Olymp Dance. Jsou zaměřené na seznámení se s tanečním sportem,
rozpoznávání rytmu a všeobecnou sportovní průpravu s prvky atletiky a
gymnastiky. Do přípravek se mohou zájemci hlásit v pravidelných náborech nebo v
průběhu celého roku. Vstupní věk se pohybuje mezi 5-10 lety. Časová dotace 2-3
vyučovací hodiny týdně.

*** Základy tanečního sportu
Základy tanečního sportu jsou cílenou přípravou na soutěže Českého svazu
tanečního sportu základních výkonnostních tříd. Jedná se o tréninkový program
standardních a latinskoamerických tanců s kondiční a pohybovou průpravou,
upraveným pro věkové skupiny 12-15 let a 16 a více let. Časová dotace 6
vyučovacích hodin týdně + 2 individuální hodiny týdně.

*** Výkonnostní úroveň tanečního sportu
Tréninková činnost oproti předchozím stupňům je více specializovaná. Tento
program využívají pokročilí tanečníci, kteří se pravidelně účastní soutěží
Českého svazu tanečního sportu. Program není omezený věkem, ale pokročilou
výkonnostní třídou. Program je doprovázen pravidelnými soustředěními. Časová
dotace je 6 hodin týdně + vlastní trénink + 2-4 individuální hodiny týdně.

*** Sportovní centrum mládeže a vrcholový sport
Tohoto programu se účastni členové národního reprezentačního týmu a
aspiranti. Označení Sportovní centrum mládeže obdržel klub na základě programu
MŠMT, protože opakovaně splňuje vysokou kvalitu výchovy sportovců. Tréninkový
program složený z kondiční, taneční a speciální přípravy. Několikrát měsíčně
zajišťujeme tréninky s nejlepšími trenéry v ČR (Martin Odstrčil a Jaroslav
Kučera), kvartálně probíhají kondiční měření s následnou analýzou pro tréninkový
proces. Program je spolufinancován z dotačních titulů MŠMT, ČSTS, Olomouckého
kraje a města Olomouce.

** Školní taneční kroužky
- statický popis plus odkaz na www.olympdance.cz)
- https://www.youtube.com/watch?v=VltRLZkGXWg
- + Prostějov, Přerov
- odkaz na www.OlympDance.cz

Taneční kroužky OlympDance

Od roku 2018 probíhají kroužky s různorodou taneční tématikou přímo na školách v
Olomouci a okolí. V současnosti mohou děti základního školního věku navštěvovat
kroužky na deseti školách pod vedením Martina Matýska a lektorů TK Olymp. Děti
tak za svým kroužkem nemusí nikam dojíždět a mají ho přímo na své škole. Každé
pololetí je navíc celý projekt kroužků zakončen soutěží jednotlivých škol
Akademie OlympDance.

Více informací najdete na www.olympdance.cz.

Kontakt:
Martin Matýsek
tel: 774 090 200
email: info@olympdance.cz

** Taneční vystoupení na akcích, poptávkový formulář
Pořádáte ples, narozeninovou oslavu, svatbu nebo zábavu a hledáte vhodný článek
do Vašeho programu? Nabízíme vystoupení sportovních tanečníků standardních a
latinskoamerických tanců.

V rámci našich vystoupení nabízíme ukázky standardních a latinskoamerických
tanců v jejich soutěžním provedení. Portfolio našich tanečních párů čítá páry
všech výkonnostních tříd od nejnižší E po mezinárodní třídu M. Naši nejlepší
tanečních jsou mistři či vicemistři České republiky a čtvrtfinalisté mistrovství
světa. Oblíbená jsou rovněž vystoupení dětských tanečníků. V případě potřeby
jsme schopní připravit vystoupení na míru - showdance na speciálně připravenou
hudbu do tematicky laděné akce (v minulosti např. Queen, Velký Gatsby, James
Bond, atp.

PROSTOR PRO PROMO VIDEO

Skupiny tanců:
- Standardní tance: Waltz, Tango, Valčík, Slowfox, Quickstep
- Latinskoamerické tance: Samba, Chacha, Rumba, Paso-Doble, Jive
- Dětské tance: Waltz, Quickstep, Chacha, Jive, Polka)

Nabízíme vystoupení našich tanečních párů, které zaujmou pobaví Vaše hosty na
plesech, oslavách, galavečerech, vesnických zábavách nebo jiných akcích.

V rámci našich vystoupení nabízíme ukázky standardních (Waltz, Tango, Valšík,
Slowfox, Quickstep) a latinskoamerických tanců (Samba, Chacha, Rumba, Paso
Doble, Jive) v jejich soutěžních provedení. Portfolio našich tanečních párů čítá
páry všech výkonnostních tříd od nejnižší D po mezinárodní třídu M od děti po
dospělé či seniorské páry. Naši nejlepší tanečních jsou mistři či vicemistři
České republiky nebo čtvrtfinalisté mistrovství Evropy a světa.

Nejčastější forma vystoupení jsou dva vstupy (dvě skupiny tanců - standardní a
latinskoamerická). Naše páry jsou vedeny k profesionálnímu přístupu k akcím.

Veškerý výdělek z vystoupení putuje do vylepšení tréninkové činnosti párů.

*** Poptávkový formulář
Pro zaslání cenové nabídky vyplňte poptávkový formulář:

Kontaktní osoba (jméno a příjmení, email, telefon)
Specifikace poptávky

*** Ceník
Vystoupení páru dané výkonnostní třídy za jednu skupinu tanců:

D 1000 Kč
C 2000 Kč
B 3000 Kč
A 4000 Kč
M 5000 Kč

Vystoupení 2-4 dětských párů 2000-4000 Kč.

V případě konání vystoupení mimo město Olomouc je účtováno cestovné v ceně 5 Kč/km.

* Akce
Fotka+titulek+podtitulek+více zde

Po kliknutí na více zde se rozbalí podrobnější informace s přihlašovacím formulářem:

Kromě textu navíc počet přihlášených/volných míst (jako to máme v akcích uvnitř)

Formulář (musí reagovat na to, zda se jedná o přihlášeného uživatele)
- pro přihlášené: tlačítko přihlásit, možnost podívat se na počet přihlášených
- pro nepřihlášené=nečleny: Jméno a příjmení, Rok narození, Telefon, Email, Poznámka

** soutěže
** soustředění s jednoduchým přihlašovacím systémem
** plesy a akce s možnosti rezervace vstupenek

* Kontakt
** fakturační údaje
** kontakty na jednotlivé činovníky, sekretáře, vedoucí poboček
