packages:
  - frontend
  - graphql
  - worker
  - backend
  - wdsf
  - e2e

injectWorkspacePackages: false
nodeLinker: isolated

supportedArchitectures:
  os:
    - linux
    - current
  cpu:
    - x64
    - current
  libc:
    - glibc
