<?php header_main('Kontakty');?>
<?php header_minor('Taneční klub Olymp Olomouc');?>
<style type="text/css">
table.k {border:none;}
table.k td {border:none;background:none;}
table.k td.r {padding-right:10px;text-align:right;}
table.k b {color:#572E00;}
</style>
<table class="k">
<tr>
	<td class="r">sídlo:</td>
	<td>Jiráskova 25, 77900, Olomouc</td>
</tr>
<tr>
	<td class="r">IČO:</td>
	<td>68347285</td>
</tr>
<tr>
	<td class="r">bankovní spojení:</td>
	<td>1806875329/0800</td>
</tr>
<tr><td>&nbsp;</td><td></td></tr>
<tr>
	<td class="r"><b>Mgr. Marie Hýžová</b></td>
	<td><b>vedoucí klubu</b></td>
</tr>
<tr>
	<td class="r">mobil:</td>
	<td>604 756 085</td>
</tr>
<tr>
	<td class="r">email:</td>
	<td>tkolymp(zavináč)tkolymp.cz</td>
</tr>
<tr><td>&nbsp;</td><td></td></tr>
<tr>
	<td class="r"><b>Hana Jendrulková</b></td>
	<td><b>hospodář</b></td>
</tr>
<tr>
	<td class="r">mobil</td>
	<td>606 426 614</td>
</tr>
<tr>
	<td class="r">email:</td>
	<td>h.jendrulkova(zavináč)centrum.cz</td>
</tr>
<tr><td>&nbsp;</td><td></td></tr>
<tr>
	<td class="r"><b>Miroslav Hýža</b></td>
	<td><b>člen klubové rady</b></td>
</tr>
<tr>
	<td></td><td>informace, tréninky, vystoupení,<br/>soutěže, noví zájemci</td>
</tr>
<tr>
	<td class="r">mobil:</td>
	<td>737 545 525</td>
</tr>
<tr>
	<td class="r">email:</td>
	<td>hyzam(zavináč)tkolymp.cz</td>
</tr>
</table>