apiVersion: apps/v1
kind: Deployment
metadata:
  name: sirimbo
  labels:
    app.kubernetes.io/name: sirimbo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: sirimbo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sirimbo
    spec:
      containers:
        - name: sirimbo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GRAPHQL_BACKEND
              value: {{ .Values.runtime.graphqlBackend | quote }}
            - name: NEXT_PUBLIC_SENTRY_ENVIRONMENT
              value: {{ .Values.runtime.sentryEnvironment | quote }}
            - name: NEXT_PUBLIC_SENTRY_DSN
              value: {{ .Values.runtime.sentryDsn | quote }}
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
