/* DO NOT EDIT! This file is auto-generated by graphql-code-generator - see `codegen.yml` */
/* eslint-disable */
import * as Types from './index';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
import { parse } from 'graphql';

export type CalendarFeedSubscriptionFieldsFragment = { __typename?: 'CalendarFeedSubscription', id: string, token: string, onlyType: Types.Maybe<Types.EventType>, onlyMine: boolean, startOffsetDays: number, endOffsetDays: Types.Maybe<number>, createdAt: string, updatedAt: string };

export type CalendarFeedSubscriptionsQueryVariables = Types.Exact<{ [key: string]: never; }>;

export type CalendarFeedSubscriptionsQuery = { __typename?: 'Query', calendarFeedSubscriptionsList: Array<{ __typename?: 'CalendarFeedSubscription', id: string, token: string, onlyType: Types.Maybe<Types.EventType>, onlyMine: boolean, startOffsetDays: number, endOffsetDays: Types.Maybe<number>, createdAt: string, updatedAt: string }> };

export type CreateCalendarFeedSubscriptionMutationVariables = Types.Exact<{
  input: {
    onlyType?: Types.Maybe<Types.EventType> | null;
    onlyMine?: Types.Maybe<boolean> | null;
    startOffsetDays?: Types.Maybe<number> | null;
    endOffsetDays?: Types.Maybe<number> | null;
  };
}>;

export type CreateCalendarFeedSubscriptionMutation = { __typename?: 'Mutation', createCalendarFeedSubscription?: { __typename?: 'CreateCalendarFeedSubscriptionPayload', calendarFeedSubscription?: { __typename?: 'CalendarFeedSubscription', id: string, token: string, onlyType: Types.Maybe<Types.EventType>, onlyMine: boolean, startOffsetDays: number, endOffsetDays: Types.Maybe<number>, createdAt: string, updatedAt: string } | null } | null };

export type UpdateCalendarFeedSubscriptionMutationVariables = Types.Exact<{
  id: Types.Scalars['BigInt']['input'];
  patch: {
    onlyType?: Types.Maybe<Types.EventType> | null;
    onlyMine?: Types.Maybe<boolean> | null;
    startOffsetDays?: Types.Maybe<number> | null;
    endOffsetDays?: Types.Maybe<number> | null;
  };
}>;

export type UpdateCalendarFeedSubscriptionMutation = { __typename?: 'Mutation', updateCalendarFeedSubscription?: { __typename?: 'UpdateCalendarFeedSubscriptionPayload', calendarFeedSubscription?: { __typename?: 'CalendarFeedSubscription', id: string, token: string, onlyType: Types.Maybe<Types.EventType>, onlyMine: boolean, startOffsetDays: number, endOffsetDays: Types.Maybe<number>, createdAt: string, updatedAt: string } | null } | null };

export type DeleteCalendarFeedSubscriptionMutationVariables = Types.Exact<{
  id: Types.Scalars['BigInt']['input'];
}>;

export type DeleteCalendarFeedSubscriptionMutation = { __typename?: 'Mutation', deleteCalendarFeedSubscription?: { __typename?: 'DeleteCalendarFeedSubscriptionPayload', deletedCalendarFeedSubscriptionId?: Types.Maybe<string> } | null };

export const CalendarFeedSubscriptionFieldsFragmentDoc = parse(/* GraphQL */ `
    fragment CalendarFeedSubscriptionFields on CalendarFeedSubscription {
  id
  token
  onlyType
  onlyMine
  startOffsetDays
  endOffsetDays
  createdAt
  updatedAt
}
    `);
export const CalendarFeedSubscriptionsDocument = parse(/* GraphQL */ `
    query CalendarFeedSubscriptions {
  calendarFeedSubscriptionsList(orderBy: CREATED_AT_ASC) {
    ...CalendarFeedSubscriptionFields
  }
}
    `) as DocumentNode<CalendarFeedSubscriptionsQuery, CalendarFeedSubscriptionsQueryVariables>;
export const CreateCalendarFeedSubscriptionDocument = parse(/* GraphQL */ `
    mutation CreateCalendarFeedSubscription($input: CalendarFeedSubscriptionInput!) {
  createCalendarFeedSubscription(input: {calendarFeedSubscription: $input}) {
    calendarFeedSubscription {
      ...CalendarFeedSubscriptionFields
    }
  }
}
    `) as DocumentNode<CreateCalendarFeedSubscriptionMutation, CreateCalendarFeedSubscriptionMutationVariables>;
export const UpdateCalendarFeedSubscriptionDocument = parse(/* GraphQL */ `
    mutation UpdateCalendarFeedSubscription($id: BigInt!, $patch: CalendarFeedSubscriptionPatch!) {
  updateCalendarFeedSubscription(input: {id: $id, patch: $patch}) {
    calendarFeedSubscription {
      ...CalendarFeedSubscriptionFields
    }
  }
}
    `) as DocumentNode<UpdateCalendarFeedSubscriptionMutation, UpdateCalendarFeedSubscriptionMutationVariables>;
export const DeleteCalendarFeedSubscriptionDocument = parse(/* GraphQL */ `
    mutation DeleteCalendarFeedSubscription($id: BigInt!) {
  deleteCalendarFeedSubscription(input: {id: $id}) {
    deletedCalendarFeedSubscriptionId
  }
}
    `) as DocumentNode<DeleteCalendarFeedSubscriptionMutation, DeleteCalendarFeedSubscriptionMutationVariables>;
