/* DO NOT EDIT! This file is auto-generated by graphql-code-generator - see `codegen.yml` */
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
import * as Types from './index';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type Discipline =
  | 'CONDITIONING'
  | 'LAT'
  | 'PRACTICE'
  | 'STT';

/** An input for mutations affecting `OutlineNodeInputRecord` */
export type OutlineNodeInputRecordInput = {
  content?: any;
  id?: any;
  ordering?: string | null | undefined;
  parentId?: any;
};

/** All input for the `saveOutline` mutation. */
export type SaveOutlineInput = {
  baseVersion?: string | null | undefined;
  /**
   * An arbitrary string value with no semantic meaning. Will be included in the
   * payload verbatim. May be used to track mutations by the client.
   */
  clientMutationId?: string | null | undefined;
  nodes?: Array<OutlineNodeInputRecordInput | null | undefined> | null | undefined;
  root?: any;
};

export type DocumentNodeTagFragment = { __typename: 'DocumentNodeTag', id: string, personId: string | null, coupleId: string | null, cohortId: string | null, eventInstanceId: string | null, eventSeriesId: string | null, competitionId: string | null, danceCode: string | null, taggedMonth: string | null, discipline: Types.Discipline | null };

export type OutlineNodeFragment = { __typename: 'DocumentNode', id: any, parentId: any, ordering: string, content: any };

export type TenantOutlineQueryVariables = Exact<{ [key: string]: never; }>;


export type TenantOutlineQuery = { tenantDocument: { id: string, title: string | null, version: string } | null };

export type OutlineQueryVariables = Exact<{
  root?: any;
}>;


export type OutlineQuery = { documentSubtreeList: Array<{ __typename: 'DocumentNode', id: any, parentId: any, ordering: string, content: any }> | null };

export type OutlineBreadcrumbQueryVariables = Exact<{
  node: any;
}>;


export type OutlineBreadcrumbQuery = { documentNodePathList: Array<{ __typename: 'DocumentNode', id: any, parentId: any, ordering: string, content: any }> | null };

export type TagDancesQueryVariables = Exact<{ [key: string]: never; }>;


export type TagDancesQuery = { dancesList: Array<{ code: string, name: string | null, discipline: string | null }> | null };

export type SaveOutlineMutationVariables = Exact<{
  input: Types.SaveOutlineInput;
}>;


export type SaveOutlineMutation = { saveOutline: { document: { id: string, version: string } | null } | null };

export const DocumentNodeTagFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"DocumentNodeTag"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"DocumentNodeTag"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"}},{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"personId"}},{"kind":"Field","name":{"kind":"Name","value":"coupleId"}},{"kind":"Field","name":{"kind":"Name","value":"cohortId"}},{"kind":"Field","name":{"kind":"Name","value":"eventInstanceId"}},{"kind":"Field","name":{"kind":"Name","value":"eventSeriesId"}},{"kind":"Field","name":{"kind":"Name","value":"competitionId"}},{"kind":"Field","name":{"kind":"Name","value":"danceCode"}},{"kind":"Field","name":{"kind":"Name","value":"taggedMonth"}},{"kind":"Field","name":{"kind":"Name","value":"discipline"}}]}}]} as unknown as DocumentNode<DocumentNodeTagFragment, unknown>;
export const OutlineNodeFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"OutlineNode"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"DocumentNode"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"}},{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"parentId"}},{"kind":"Field","name":{"kind":"Name","value":"ordering"}},{"kind":"Field","name":{"kind":"Name","value":"content"}}]}}]} as unknown as DocumentNode<OutlineNodeFragment, unknown>;
export const TenantOutlineDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"TenantOutline"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"tenantDocument"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"title"}},{"kind":"Field","name":{"kind":"Name","value":"version"}}]}}]}}]} as unknown as DocumentNode<TenantOutlineQuery, TenantOutlineQueryVariables>;
export const OutlineDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"Outline"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"root"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"UUID"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"documentSubtreeList"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"root"},"value":{"kind":"Variable","name":{"kind":"Name","value":"root"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"OutlineNode"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"OutlineNode"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"DocumentNode"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"}},{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"parentId"}},{"kind":"Field","name":{"kind":"Name","value":"ordering"}},{"kind":"Field","name":{"kind":"Name","value":"content"}}]}}]} as unknown as DocumentNode<OutlineQuery, OutlineQueryVariables>;
export const OutlineBreadcrumbDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"OutlineBreadcrumb"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"node"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"UUID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"documentNodePathList"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"node"},"value":{"kind":"Variable","name":{"kind":"Name","value":"node"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"OutlineNode"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"OutlineNode"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"DocumentNode"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"}},{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"parentId"}},{"kind":"Field","name":{"kind":"Name","value":"ordering"}},{"kind":"Field","name":{"kind":"Name","value":"content"}}]}}]} as unknown as DocumentNode<OutlineBreadcrumbQuery, OutlineBreadcrumbQueryVariables>;
export const TagDancesDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"TagDances"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"dancesList"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"orderBy"},"value":{"kind":"ListValue","values":[{"kind":"EnumValue","value":"NAME_ASC"}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"discipline"}}]}}]}}]} as unknown as DocumentNode<TagDancesQuery, TagDancesQueryVariables>;
export const SaveOutlineDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"SaveOutline"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"SaveOutlineInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"saveOutline"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"document"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"version"}}]}}]}}]}}]} as unknown as DocumentNode<SaveOutlineMutation, SaveOutlineMutationVariables>;