/* DO NOT EDIT! This file is auto-generated by graphql-code-generator - see `codegen.yml` */
import * as Types from './index';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type CreateInvitationMutationVariables = Types.Exact<{
  input: Types.CreatePersonInvitationInput;
}>;


export type CreateInvitationMutation = { __typename?: 'Mutation', createPersonInvitation: { __typename?: 'CreatePersonInvitationPayload', personInvitation: { __typename?: 'PersonInvitation', id: string, email: string, createdAt: string } | null } | null };

export type DeleteInvitationMutationVariables = Types.Exact<{
  input: Types.DeletePersonInvitationInput;
}>;


export type DeleteInvitationMutation = { __typename?: 'Mutation', deletePersonInvitation: { __typename: 'DeletePersonInvitationPayload' } | null };

export type PeopleWithAnotherAccountQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type PeopleWithAnotherAccountQuery = { __typename?: 'Query', peopleWithoutAccessWithExistingAccountList: Array<{ __typename?: 'Person', id: string, name: string, email: string | null }> | null };

export type PeopleWithoutInvitationQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type PeopleWithoutInvitationQuery = { __typename?: 'Query', peopleWithoutAccessOrInvitationList: Array<{ __typename?: 'Person', id: string, name: string, email: string | null, createdAt: string }> | null };

export type PeopleWithInvitationQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type PeopleWithInvitationQuery = { __typename?: 'Query', peopleWithoutAccessWithInvitationList: Array<{ __typename?: 'Person', id: string, name: string, email: string | null, createdAt: string, personInvitationsList: Array<{ __typename?: 'PersonInvitation', id: string, createdAt: string, accessToken: any }> }> | null };


export const CreateInvitationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"CreateInvitation"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"CreatePersonInvitationInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"createPersonInvitation"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"personInvitation"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"email"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}}]}}]}}]}}]} as unknown as DocumentNode<CreateInvitationMutation, CreateInvitationMutationVariables>;
export const DeleteInvitationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"DeleteInvitation"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"DeletePersonInvitationInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"deletePersonInvitation"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"}}]}}]}}]} as unknown as DocumentNode<DeleteInvitationMutation, DeleteInvitationMutationVariables>;
export const PeopleWithAnotherAccountDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"PeopleWithAnotherAccount"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"peopleWithoutAccessWithExistingAccountList"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"email"}}]}}]}}]} as unknown as DocumentNode<PeopleWithAnotherAccountQuery, PeopleWithAnotherAccountQueryVariables>;
export const PeopleWithoutInvitationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"PeopleWithoutInvitation"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"peopleWithoutAccessOrInvitationList"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"email"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}}]}}]}}]} as unknown as DocumentNode<PeopleWithoutInvitationQuery, PeopleWithoutInvitationQueryVariables>;
export const PeopleWithInvitationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"PeopleWithInvitation"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"peopleWithoutAccessWithInvitationList"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"email"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"personInvitationsList"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"accessToken"}}]}}]}}]}}]} as unknown as DocumentNode<PeopleWithInvitationQuery, PeopleWithInvitationQueryVariables>;