ALTER DATABASE olymp CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE akce CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE akce_item CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE aktuality CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE aktuality_foto CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE dokumenty CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE galerie_dir CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE galerie_foto CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE inzerce CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE nabidka CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE nabidka_item CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE novinky CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `parameters` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE pary CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE pary_navrh CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE platby_category CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE platby_category_group CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE platby_group CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE platby_group_skupina CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE platby_item CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE platby_raw CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE rozpis CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE rozpis_item CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE skupiny CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE soutez CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE upozorneni CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE upozorneni_skupiny CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE users CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE users_platby CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE users_skupiny CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE video CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

ALTER TABLE `akce` CHANGE `a_lock` `a_lock` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `akce` CHANGE `a_visible` `a_visible` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `akce_item` CHANGE `ai_id_rodic` `ai_id_rodic` BIGINT NOT NULL;
ALTER TABLE `akce_item` ADD CONSTRAINT `akce_item_ai_id_rodic_fkey` FOREIGN KEY(`ai_id_rodic`) REFERENCES `akce`(`a_id`);
ALTER TABLE `akce_item` CHANGE `ai_user` `ai_user` BIGINT NOT NULL;
ALTER TABLE `akce_item` ADD CONSTRAINT `akce_item_ai_user_fkey` FOREIGN KEY(`ai_user`) REFERENCES `users`(`u_id`);
ALTER TABLE `aktuality` CHANGE `at_kdo` `at_kdo` BIGINT NOT NULL;
ALTER TABLE `aktuality` ADD CONSTRAINT `aktuality_at_kdo_fkey` FOREIGN KEY(`at_kdo`) REFERENCES `users`(`u_id`);
ALTER TABLE `aktuality` CHANGE `at_kat` `at_kat` TEXT CHARACTER SET utf8 NOT NULL;
ALTER TABLE `aktuality` CHANGE `at_foto` `at_foto` INT(11) NOT NULL;
ALTER TABLE `aktuality` CHANGE `at_foto_main` `at_foto_main` BIGINT NOT NULL;
ALTER TABLE `aktuality` ADD CONSTRAINT `aktuality_at_foto_main_fkey` FOREIGN KEY(`at_foto_main`) REFERENCES `galerie_foto`(`gf_id`);
ALTER TABLE `aktuality` ALTER COLUMN `at_timestamp_add` SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `dokumenty` CHANGE `d_kdo` `d_kdo` BIGINT NOT NULL;
ALTER TABLE `dokumenty` ADD CONSTRAINT `dokumenty_d_kdo_fkey` FOREIGN KEY(`d_kdo`) REFERENCES `users`(`u_id`);
ALTER TABLE `galerie_dir` CHANGE `gd_id_rodic` `gd_id_rodic` BIGINT NOT NULL;
ALTER TABLE `galerie_dir` ADD CONSTRAINT `galerie_dir_gd_id_rodic_fkey` FOREIGN KEY(`gd_id_rodic`) REFERENCES `galerie_dir`(`gd_id`);
ALTER TABLE `galerie_dir` CHANGE `gd_hidden` `gd_hidden` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `galerie_foto` CHANGE `gf_id_rodic` `gf_id_rodic` BIGINT NOT NULL;
ALTER TABLE `galerie_foto` ADD CONSTRAINT `galerie_foto_gf_id_rodic_fkey` FOREIGN KEY(`gf_id_rodic`) REFERENCES `galerie_dir`(`gd_id`);
ALTER TABLE `galerie_foto` CHANGE `gf_kdo` `gf_kdo` BIGINT NOT NULL;
ALTER TABLE `galerie_foto` ADD CONSTRAINT `galerie_foto_gf_kdo_fkey` FOREIGN KEY(`gf_kdo`) REFERENCES `users`(`u_id`);
ALTER TABLE `nabidka` CHANGE `n_trener` `n_trener` BIGINT NOT NULL;
ALTER TABLE `nabidka` ADD CONSTRAINT `nabidka_n_trener_fkey` FOREIGN KEY(`n_trener`) REFERENCES `users`(`u_id`);
ALTER TABLE `nabidka` CHANGE `n_visible` `n_visible` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `nabidka` CHANGE `n_lock` `n_lock` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `nabidka_item` CHANGE `ni_id_rodic` `ni_id_rodic` BIGINT NOT NULL;
ALTER TABLE `nabidka_item` ADD CONSTRAINT `nabidka_item_ni_id_rodic_fkey` FOREIGN KEY(`ni_id_rodic`) REFERENCES `nabidka`(`n_id`);
ALTER TABLE `nabidka_item` CHANGE `ni_partner` `ni_partner` BIGINT NOT NULL;
ALTER TABLE `nabidka_item` ADD CONSTRAINT `nabidka_item_ni_partner_fkey` FOREIGN KEY(`ni_partner`) REFERENCES `users`(`u_id`);
ALTER TABLE `nabidka_item` CHANGE `ni_lock` `ni_lock` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `novinky` CHANGE `no_id_user` `no_id_user` BIGINT NOT NULL;
ALTER TABLE `novinky` ADD CONSTRAINT `novinky_no_id_user_fkey` FOREIGN KEY(`no_id_user`) REFERENCES `users`(`u_id`);
ALTER TABLE `pary` CHANGE `p_id_partner` `p_id_partner` BIGINT NOT NULL;
ALTER TABLE `pary` ADD CONSTRAINT `pary_p_id_partner_fkey` FOREIGN KEY(`p_id_partner`) REFERENCES `users`(`u_id`);
ALTER TABLE `pary` CHANGE `p_id_partnerka` `p_id_partnerka` BIGINT NOT NULL DEFAULT 0;
ALTER TABLE `pary` ADD CONSTRAINT `pary_p_id_partnerka_fkey` FOREIGN KEY(`p_id_partnerka`) REFERENCES `users`(`u_id`);
ALTER TABLE `pary_navrh` ADD CONSTRAINT `pary_navrh_pn_navrhl_fkey` FOREIGN KEY(`pn_navrhl`) REFERENCES `users`(`u_id`);
ALTER TABLE `pary_navrh` ADD CONSTRAINT `pary_navrh_pn_partner_fkey` FOREIGN KEY(`pn_partner`) REFERENCES `users`(`u_id`);
ALTER TABLE `pary_navrh` CHANGE `pn_partnerka` `pn_partnerka` BIGINT NOT NULL;
ALTER TABLE `pary_navrh` ADD CONSTRAINT `pary_navrh_pn_partnerka_fkey` FOREIGN KEY(`pn_partnerka`) REFERENCES `users`(`u_id`);
ALTER TABLE `platby_category` CHANGE `pc_symbol` `pc_symbol` INT(11) NOT NULL;
ALTER TABLE `platby_category` CHANGE `pc_amount` `pc_amount` DECIMAL(10,2) NOT NULL;
ALTER TABLE `platby_category` CHANGE `pc_use_base` `pc_use_base` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `platby_category` CHANGE `pc_use_prefix` `pc_use_prefix` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `platby_category` CHANGE `pc_archive` `pc_archive` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `platby_category` CHANGE `pc_visible` `pc_visible` TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE `platby_category_group` CHANGE `pcg_id_group` `pcg_id_group` BIGINT NOT NULL;
ALTER TABLE `platby_category_group` ADD CONSTRAINT `platby_category_group_pcg_id_group_fkey` FOREIGN KEY(`pcg_id_group`) REFERENCES `platby_group`(`pg_id`);
ALTER TABLE `platby_category_group` CHANGE `pcg_id_category` `pcg_id_category` BIGINT NOT NULL;
ALTER TABLE `platby_category_group` ADD CONSTRAINT `platby_category_group_pcg_id_category_fkey` FOREIGN KEY(`pcg_id_category`) REFERENCES `platby_category`(`pc_id`);
ALTER TABLE `platby_group` CHANGE `pg_type` `pg_type` BIGINT NOT NULL DEFAULT 0;
ALTER TABLE `platby_group_skupina` CHANGE `pgs_id_skupina` `pgs_id_skupina` BIGINT NOT NULL;
ALTER TABLE `platby_group_skupina` ADD CONSTRAINT `platby_group_skupina_pgs_id_skupina_fkey` FOREIGN KEY(`pgs_id_skupina`) REFERENCES `skupiny`(`s_id`);
ALTER TABLE `platby_group_skupina` CHANGE `pgs_id_group` `pgs_id_group` BIGINT NOT NULL;
ALTER TABLE `platby_group_skupina` ADD CONSTRAINT `platby_group_skupina_pgs_id_group_fkey` FOREIGN KEY(`pgs_id_group`) REFERENCES `platby_group`(`pg_id`);
ALTER TABLE `platby_group_skupina` ADD CONSTRAINT `'pgs_id_skupina'` UNIQUE(`pgs_id_skupina`,`pgs_id_group`);
ALTER TABLE `platby_item` CHANGE `pi_id_user` `pi_id_user` BIGINT NOT NULL;
ALTER TABLE `platby_item` ADD CONSTRAINT `platby_item_pi_id_user_fkey` FOREIGN KEY(`pi_id_user`) REFERENCES `users`(`u_id`);
ALTER TABLE `platby_item` CHANGE `pi_id_category` `pi_id_category` BIGINT NOT NULL;
ALTER TABLE `platby_item` ADD CONSTRAINT `platby_item_pi_id_category_fkey` FOREIGN KEY(`pi_id_category`) REFERENCES `platby_category`(`pc_id`);
ALTER TABLE `platby_item` CHANGE `pi_id_raw` `pi_id_raw` BIGINT NULL;
ALTER TABLE `platby_item` ADD CONSTRAINT `platby_item_pi_id_raw_fkey` FOREIGN KEY(`pi_id_raw`) REFERENCES `platby_raw`(`pr_id`);
ALTER TABLE `platby_item` CHANGE `pi_amount` `pi_amount` DECIMAL(10,2) NOT NULL;
ALTER TABLE `platby_raw` CHANGE `pr_sorted` `pr_sorted` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `platby_raw` CHANGE `pr_discarded` `pr_discarded` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `rozpis` CHANGE `r_trener` `r_trener` BIGINT NOT NULL;
ALTER TABLE `rozpis` ADD CONSTRAINT `rozpis_r_trener_fkey` FOREIGN KEY(`r_trener`) REFERENCES `users`(`u_id`);
ALTER TABLE `rozpis` CHANGE `r_visible` `r_visible` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `rozpis` CHANGE `r_lock` `r_lock` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `rozpis_item` CHANGE `ri_id_rodic` `ri_id_rodic` BIGINT NOT NULL;
ALTER TABLE `rozpis_item` ADD CONSTRAINT `rozpis_item_ri_id_rodic_fkey` FOREIGN KEY(`ri_id_rodic`) REFERENCES `rozpis`(`r_id`);
ALTER TABLE `rozpis_item` CHANGE `ri_partner` `ri_partner` BIGINT NOT NULL DEFAULT 0;
ALTER TABLE `rozpis_item` ADD CONSTRAINT `rozpis_item_ri_partner_fkey` FOREIGN KEY(`ri_partner`) REFERENCES `users`(`u_id`);
ALTER TABLE `rozpis_item` CHANGE `ri_od` `ri_od` DATE NOT NULL;
ALTER TABLE `rozpis_item` CHANGE `ri_do` `ri_do` DATE NOT NULL;
ALTER TABLE `rozpis_item` CHANGE `ri_lock` `ri_lock` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `upozorneni` CHANGE `up_kdo` `up_kdo` BIGINT NOT NULL;
ALTER TABLE `upozorneni` ADD CONSTRAINT `upozorneni_up_kdo_fkey` FOREIGN KEY(`up_kdo`) REFERENCES `users`(`u_id`);
ALTER TABLE `upozorneni` CHANGE `up_lock` `up_lock` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `upozorneni_skupiny` CHANGE `ups_id_rodic` `ups_id_rodic` BIGINT NOT NULL;
ALTER TABLE `upozorneni_skupiny` ADD CONSTRAINT `upozorneni_skupiny_ups_id_rodic_fkey` FOREIGN KEY(`ups_id_rodic`) REFERENCES `upozorneni`(`up_id`);
ALTER TABLE `upozorneni_skupiny` CHANGE `ups_id_skupina` `ups_id_skupina` BIGINT NOT NULL;
ALTER TABLE `upozorneni_skupiny` ADD CONSTRAINT `upozorneni_skupiny_ups_id_skupina_fkey` FOREIGN KEY(`ups_id_skupina`) REFERENCES `skupiny`(`s_id`);
ALTER TABLE `users` CHANGE `u_pohlavi` `u_pohlavi` TEXT CHARACTER SET utf8 NOT NULL;
ALTER TABLE `users` CHANGE `u_email` `u_email` VARCHAR(50) NOT NULL;
ALTER TABLE `users` CHANGE `u_telefon` `u_telefon` CHAR(17) NOT NULL;
ALTER TABLE `users` CHANGE `u_poznamky` `u_poznamky` TEXT CHARACTER SET utf8 NOT NULL;
ALTER TABLE `users` CHANGE `u_level` `u_level` TINYINT(3) NOT NULL DEFAULT 0;
ALTER TABLE `users` CHANGE `u_group` `u_group` BIGINT NOT NULL;
ALTER TABLE `users` ADD CONSTRAINT `users_u_group_fkey` FOREIGN KEY(`u_group`) REFERENCES `platby_group`(`pg_id`);
ALTER TABLE `users` CHANGE `u_skupina` `u_skupina` BIGINT NOT NULL DEFAULT 1;
ALTER TABLE `users` ADD CONSTRAINT `users_u_skupina_fkey` FOREIGN KEY(`u_skupina`) REFERENCES `skupiny`(`s_id`);
ALTER TABLE `users` CHANGE `u_dancer` `u_dancer` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `users` CHANGE `u_ban` `u_ban` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `users` CHANGE `u_lock` `u_lock` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `users` CHANGE `u_confirmed` `u_confirmed` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `users` CHANGE `u_temporary` `u_temporary` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `users` CHANGE `u_system` `u_system` TINYINT(1) NOT NULL DEFAULT 0;
