CREATE TABLE `page` (
    `p_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `p_type` TEXT CHARACTER SET utf8 NULL,
    `p_url` TEXT CHARACTER SET utf8 NOT NULL,
    `p_title` TEXT CHARACTER SET utf8 NULL,
    `p_html` TEXT CHARACTER SET utf8 NULL,
    `p_json` TEXT CHARACTER SET utf8 NULL,
    `p_parameters` TEXT CHARACTER SET utf8 NULL,
    `p_created_at` TIMESTAMP NOT NULL,
    `p_updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `menu` (
    `m_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `m_key` TEXT CHARACTER SET utf8 NOT NULL,
    `m_title` TEXT CHARACTER SET utf8 NOT NULL,
    `m_content` TEXT CHARACTER SET utf8 NULL,
    `m_created_at` TIMESTAMP NOT NULL,
    `m_updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
