
DO $$
DECLARE
  seqval bigint;
BEGIN
  SELECT last_value INTO seqval FROM public.aktuality_at_id_seq;
  ALTER TABLE public.aktuality ALTER COLUMN id DROP DEFAULT;
  ALTER SEQUENCE public.aktuality_at_id_seq OWNED BY NONE;
  DROP SEQUENCE public.aktuality_at_id_seq;
  ALTER TABLE public.aktuality
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
    (START WITH seqval);
END $$;

DO $$
DECLARE
  seqval bigint;
BEGIN
  SELECT last_value INTO seqval FROM public.dokumenty_d_id_seq;
  ALTER TABLE public.dokumenty ALTER COLUMN id DROP DEFAULT;
  ALTER SEQUENCE public.dokumenty_d_id_seq OWNED BY NONE;
  DROP SEQUENCE public.dokumenty_d_id_seq;
  ALTER TABLE public.dokumenty
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
    (START WITH seqval);
END $$;

DO $$
DECLARE
  seqval bigint;
BEGIN
  SELECT last_value INTO seqval FROM public.galerie_dir_gd_id_seq;
  ALTER TABLE public.galerie_dir ALTER COLUMN id DROP DEFAULT;
  ALTER SEQUENCE public.galerie_dir_gd_id_seq OWNED BY NONE;
  DROP SEQUENCE public.galerie_dir_gd_id_seq;
  ALTER TABLE public.galerie_dir
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
    (START WITH seqval);
END $$;

DO $$
DECLARE
  seqval bigint;
BEGIN
  SELECT last_value INTO seqval FROM public.galerie_foto_gf_id_seq;
  ALTER TABLE public.galerie_foto ALTER COLUMN id DROP DEFAULT;
  ALTER SEQUENCE public.galerie_foto_gf_id_seq OWNED BY NONE;
  DROP SEQUENCE public.galerie_foto_gf_id_seq;
  ALTER TABLE public.galerie_foto
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
    (START WITH seqval);
END $$;

DO $$
DECLARE
  seqval bigint;
BEGIN
  SELECT last_value INTO seqval FROM public.platby_category_pc_id_seq;
  ALTER TABLE public.platby_category ALTER COLUMN pc_id DROP DEFAULT;
  ALTER SEQUENCE public.platby_category_pc_id_seq OWNED BY NONE;
  DROP SEQUENCE public.platby_category_pc_id_seq;
  ALTER TABLE public.platby_category
    ALTER COLUMN pc_id ADD GENERATED BY DEFAULT AS IDENTITY
    (START WITH seqval);
END $$;

DO $$
DECLARE
  seqval bigint;
BEGIN
  SELECT last_value INTO seqval FROM public.platby_category_group_pcg_id_seq;
  ALTER TABLE public.platby_category_group ALTER COLUMN pcg_id DROP DEFAULT;
  ALTER SEQUENCE public.platby_category_group_pcg_id_seq OWNED BY NONE;
  DROP SEQUENCE public.platby_category_group_pcg_id_seq;
  ALTER TABLE public.platby_category_group
    ALTER COLUMN pcg_id ADD GENERATED BY DEFAULT AS IDENTITY
    (START WITH seqval);
END $$;

DO $$
DECLARE
  seqval bigint;
BEGIN
  SELECT last_value INTO seqval FROM public.platby_group_pg_id_seq;
  ALTER TABLE public.platby_group ALTER COLUMN pg_id DROP DEFAULT;
  ALTER SEQUENCE public.platby_group_pg_id_seq OWNED BY NONE;
  DROP SEQUENCE public.platby_group_pg_id_seq;
  ALTER TABLE public.platby_group
    ALTER COLUMN pg_id ADD GENERATED BY DEFAULT AS IDENTITY
    (START WITH seqval);
END $$;

DO $$
DECLARE
  seqval bigint;
BEGIN
  SELECT last_value INTO seqval FROM public.platby_group_skupina_pgs_id_seq;
  ALTER TABLE public.platby_group_skupina ALTER COLUMN pgs_id DROP DEFAULT;
  ALTER SEQUENCE public.platby_group_skupina_pgs_id_seq OWNED BY NONE;
  DROP SEQUENCE public.platby_group_skupina_pgs_id_seq;
  ALTER TABLE public.platby_group_skupina
    ALTER COLUMN pgs_id ADD GENERATED BY DEFAULT AS IDENTITY
    (START WITH seqval);
END $$;

DO $$
DECLARE
  seqval bigint;
BEGIN
  SELECT last_value INTO seqval FROM public.platby_item_pi_id_seq;
  ALTER TABLE public.platby_item ALTER COLUMN pi_id DROP DEFAULT;
  ALTER SEQUENCE public.platby_item_pi_id_seq OWNED BY NONE;
  DROP SEQUENCE public.platby_item_pi_id_seq;
  ALTER TABLE public.platby_item
    ALTER COLUMN pi_id ADD GENERATED BY DEFAULT AS IDENTITY
    (START WITH seqval);
END $$;

DO $$
DECLARE
  seqval bigint;
BEGIN
  SELECT last_value INTO seqval FROM public.platby_raw_pr_id_seq;
  ALTER TABLE public.platby_raw ALTER COLUMN pr_id DROP DEFAULT;
  ALTER SEQUENCE public.platby_raw_pr_id_seq OWNED BY NONE;
  DROP SEQUENCE public.platby_raw_pr_id_seq;
  ALTER TABLE public.platby_raw
    ALTER COLUMN pr_id ADD GENERATED BY DEFAULT AS IDENTITY
    (START WITH seqval);
END $$;

DO $$
DECLARE
  seqval bigint;
BEGIN
  SELECT last_value INTO seqval FROM public.scoreboard_manual_adjustment_id_seq;
  ALTER TABLE public.scoreboard_manual_adjustment ALTER COLUMN id DROP DEFAULT;
  ALTER SEQUENCE public.scoreboard_manual_adjustment_id_seq OWNED BY NONE;
  DROP SEQUENCE public.scoreboard_manual_adjustment_id_seq;
  ALTER TABLE public.scoreboard_manual_adjustment
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
    (START WITH seqval);
END $$;

DO $$
DECLARE
  seqval bigint;
BEGIN
  SELECT last_value INTO seqval FROM public.users_u_id_seq;
  ALTER TABLE public.users ALTER COLUMN id DROP DEFAULT;
  ALTER SEQUENCE public.users_u_id_seq OWNED BY NONE;
  DROP SEQUENCE public.users_u_id_seq;
  ALTER TABLE public.users
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
    (START WITH seqval);
END $$;
