<div style="text-align:center;">
<h2>Vítejte na stránkách TK Olymp Olomouc</h2>
<p><img alt="" src="/images/logo.gif" /></p>
<hr />
<p style="line-height:200%;margin-left:25%;margin-right:25%;">
TK Olymp Olomouc je tradiční taneční klub zabývající se<br/>
výchovou standardních a latinskoamerických tanečníků. V novém tisíciletí patří mezi<br/>
nejúspěšnější české kluby. Naše páry pravidelně sbírají úspěchy<br/>
v České republice i na mezinárodním poli. Nabízíme atraktivní<br/>
volnočasovou aktivitu dětem,<br/>
kvalitní zázemí sportovním tanečníkům a příjemné prostředí<br/>
pro všechny, co mají rádi tanec.</p>
<hr />
</div>