<?php header_main('Výsledky našich družstev na Mistrovství České republiky')?>
<style type="text/css">
.main {text-size:120%;font-weight:bold;}
</style>
<?php header_minor('Most, 1999');?>
<table style="width:500px;">
	<tr>
		<td><span class="main">Jun STT</span></td>
		<td>4. místo</td>
		<td>Martin Kordek - Tereza Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Pavel Řehulka - Jana Safernová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Tomáš Hroch - Veronika Benýšková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Miroslav Hýža - Denisa Walterová</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitán:</td>
		<td>Marie Hýžová</td>
	</tr>
</table>
<br/>
<?php header_minor('Most, 2000');?>
<table style="width:500px;">
	<tr>
		<td><span class="main">Jun STT</span></td>
		<td>3.místo</td>
		<td>Radim Kotrba - Markéta Vlčková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Martin Kordek - Tereza Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Miroslav Hýža - Denisa Walterová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Tomáš Hroch - Veronika Benýšková</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitán:</td>
		<td>Marie Hýžová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>8.-9.místo</td>
		<td>Pavel John - Anita Šmídová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Jiří Řehulka - Kateřina Pabišková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Jiří Mišák - Nikol Nezvalová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Pavel Skála - Petra Gromesová</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitán:</td>
		<td>Hana Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td><span class="main">Jun LAT</span></td>
		<td>7.místo</td>
		<td>Radim Kotrba - Markéta Vlčková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Martin Kordek - Tereza Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Miroslav Hýža - Denisa Walterová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Pavel John - Anita Šmídová</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitán:</td>
		<td>Tomáš Kraina</td>
	</tr>
</table>
<br/>
<?php header_minor('Třinec, 2001');?>
<table style="width:500px;">
	<tr>
		<td><span class="main">Jun STT</span></td>
		<td>2. místo</td>
		<td>Radim Kotrba - Markéta Vlčková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Miroslav Hýža - Denisa Walterová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Pavel John - Tereza Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Tomáš Hroch - Veronika Benýšková</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitán:</td>
		<td>Marie Hýžová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>6.místo</td>
		<td>Jan Matoušek - Vendula Vojáková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Pavel Skála - Petra Gromesová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Jiří Mišák - Nikol Nezvalová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Michal Fodor - Anita Šmídová</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitán:</td>
		<td>Hana Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td><span class="main">Jun LAT</span></td>
		<td>3. místo</td>
		<td>Radim Kotrba - Markéta Vlčková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Jan Matoušek - Vendula Vojáková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Miroslav Hýža - Denisa Walterová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Pavel John - Tereza Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitán:</td>
		<td>Tomáš Kraina</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td></td>
	</tr>
</table>
<br/>
<?php header_minor('Pardubice, 2002');?>
<table style="width:500px;">
	<tr>
		<td><span class="main">Jun STT</span></td>
		<td>1. místo</td>
		<td>Miroslav Hýža - Denisa Walterová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Pavel John - Tereza Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Petr Pohlodek - Petra Gromesová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Tomáš Hroch - Veronika Benýšková</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitán:</td>
		<td>Marie Hýžová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td><span class="main">Jun LAT</span></td>
		<td>1.místo</td>
		<td>Tomáš Hroch - Veronika Benýšková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Pavel John - Tereza Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Miroslav Hýža - Denisa Walterová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Petr Pohlodek - Petra Gromesová</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitán:</td>
		<td>Tomáš Kraina</td>
	</tr>
</table>
<br/>
<?php header_minor('Most, 2004');?>
<table style="width:500px;">
	<tr>
		<td><span class="main">Mládež STT</span></td>
		<td>1.místo</td>
		<td>Radim Kotrba - Markéta Vlčková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Pavel John - Tereza Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Miroslav Hýža - Denisa Walterová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Petr Pohlodek - Petra Gromesová</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitán:</td>
		<td>Hana Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td><span class="main">Dospělí STT</span></td>
		<td>5. místo</td>
		<td>Radim Kotrba - Markéta Vlčková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Petr Pohlodek - Petra Gromesová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Miroslav Hýža - Denisa Walterová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Pavel John - Tereza Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitán:</td>
		<td>Marie Hýžová</td>
	</tr>
</table>
<br/>
<?php header_minor('Třinec, 2005');?>
<table style="width:500px;">
	<tr>
		<td><span class="main">Mládež STT</span></td>
		<td>1. místo</td>
		<td>Petr Pohlodek - Petra Gromesová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Pavel John - Tereza Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Tomáš Hroch - Veronika Benýšková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Miroslav Hýža - Lucie Benýšková</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitán:</td>
		<td>Marie Hýžová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td><span class="main">Mládež LAT</span></td>
		<td>6.místo</td>
		<td>Pavel John - Tereza Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Petr Pohlodek - Petra Gromesová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Adam Jendrulek - Vendula Benýšková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Tomáš Hroch - Veronika Benýšková</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitán:</td>
		<td>Tomáš Kraina</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td><span class="main">Dospělí STT</span></td>
		<td>2.místo</td>
		<td>Pavel John - Tereza Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Radim Kotrba - Markéta Vlčková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Petr Pohlodek - Petra Gromesová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Miroslav Hýža - Lucie Benýšková</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitán:</td>
		<td>Hana Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td><span class="main">Dospělí LAT</span></td>
		<td>8.místo</td>
		<td>Martin Kordek - Jitka Szabó</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Pavel John - Tereza Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Tomáš Hroch - Vendula Benýšková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Petr Pohlodek - Petra Gromesová</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitán:</td>
		<td>Tomáš Kraina</td>
	</tr>
</table>
<br/>
<?php header_minor('Roudnice nad Labem, 2006');?>
<table style="width:500px;">
	<tr>
		<td><span class="main">Dospělí STT</span></td>
		<td>5. místo</td>
		<td>Miroslav Hýža - Lucie Benýšková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Pavel John - Tereza Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Tomáš Hroch - Vendula Benýšková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Petr Pohlodek - Michaela Vitulová</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitán:</td>
		<td>Marie Hýžová</td>
	</tr>
</table>
<br/>
<?php header_minor('Praha, 2010');?>
<table style="width:500px;">
	<tr>
		<td><span class="main">Junioři STT</span></td>
		<td>5. místo</td>
		<td>Marek Švarc - Monika Vymětalová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Matěj Očenášek - Marie Smyslilová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Jakub Zárybnický - Kristýna Dovčiaková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Dominik Homola - Mirka Uvízlová</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitán:</td>
		<td>Miroslav Hýža</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td><span class="main">Junioři LAT</span></td>
		<td>3.místo</td>
		<td>Jiří Anderle - Veronika Chromcová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Dominik Homola - Mirka Uvízlová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Jakub Zárybnický - Kristýna Dovčiakov</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Marek Švarc - Monika Vymětalová</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitáni:</td>
		<td>Tereza Jendrulková a Miroslav Hýža</td>
	</tr>
</table>
<br/>
<?php header_minor('Otrokovice, 2011');?>
<table style="width:500px;">
	<tr>
		<td><span class="main">Dospělí STT</span></td>
		<td>8. místo</td>
		<td>Vít Navrátil - Petra Chytilová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Radim Stupka - Tereza Jendrulková</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Rudolf Stupka - Kristýna Hlavicová</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>Miroslav Hýža - Marie Hýžová</td>
	</tr>
	<tr>
		<td></td>
		<td>kapitán:</td>
		<td>Mgr. Marie Hýžová</td>
	</tr>
</table>