<?php header_main('Výsledky našich párů na taneční lize'); ?>
<style type="text/css">
.year {font-size:150%;color:#572E00;text-align:center;font-weight:bold;}
.kat {font-size:115%;color:#572E00;text-align:center;}
.mcr td {text-align:center;}
.mcr td:last-child {text-align:left;}
.st td {color:#EBBC00;font-weight:bold;}
.nd td {color:#3366FF;font-weight:bold;}
.rd td {color:#993300;font-weight:bold;}
.fin td {font-weight:bold;}
.st td:first-child, .nd td:first-child,
	.rd td:first-child, .fin td:first-child,
	.st td:first-child + td, .nd td:first-child + td,
	.rd td:first-child + td, .fin td:first-child + td {color:black;font-weight:normal;}
</style>
<table style="width: 595px">
	<colgroup>
		<col span="2" style="width: 64px" />
		<col style="width: 44px" />
		<col style="width: 309px" />
		<col style="width: 43px" />
		<col style="width: 71px" />
	</colgroup>
	<tr>
		<td class="year">2002</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td class="kat">STT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr class="nd">
		<td></td>
		<td>Jun II</td>
		<td>2-3.</td>
		<td>Pavel John - Tereza Jendrulková</td>
		<td>1080</td>
		<td>6</td>
	</tr>
	<tr class="fin">
		<td></td>
		<td></td>
		<td>4.</td>
		<td>Miroslav Hýža - Denisa Walterová</td>
		<td>1040</td>
		<td>5</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>8.</td>
		<td>Tomáš Hroch - Veronika Benýšková</td>
		<td>620</td>
		<td>5</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>24.-26.</td>
		<td>Petr Pohlodek - Petra Gromesová</td>
		<td>90</td>
		<td>1</td>
	</tr>
	<tr>
		<td></td>
		<td>Mládež</td>
		<td>17.</td>
		<td>Radim Kotrba - Markéta Vlčková</td>
		<td>370</td>
		<td>3</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>21.</td>
		<td>Pavel John - Kristýna Coufalová</td>
		<td>258</td>
		<td>6</td>
	</tr>
	<tr>
		<td></td>
		<td>Dospělí</td>
		<td>61.</td>
		<td>Radim Kotrba - Markéta Vlčková</td>
		<td>50</td>
		<td>2</td>
	</tr>
	<tr>
		<td class="kat">LAT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr class="fin">
		<td></td>
		<td>Jun II</td>
		<td>5.-6.</td>
		<td>Pavel John - Tereza Jendrulková</td>
		<td>800</td>
		<td>6</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>8.</td>
		<td>Miroslav Hýža - Denisa Walterová</td>
		<td>580</td>
		<td>5</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>18.</td>
		<td>Tomáš Hroch - Veronika Benýšková</td>
		<td>237</td>
		<td>6</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>41.</td>
		<td>Petr Pohlodek - Petra Gromesová</td>
		<td>44</td>
		<td>1</td>
	</tr>
	<tr>
		<td></td>
		<td>Mládež</td>
		<td>25.</td>
		<td>Pavel John - Kristýna Coufalová</td>
		<td>214</td>
		<td>6</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>31.</td>
		<td>Radim Kotrba - Markéta Vlčková</td>
		<td>133</td>
		<td>3</td>
	</tr>
	<tr>
		<td class="year">2003</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td class="kat">STT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr class="nd">
		<td></td>
		<td>Jun I</td>
		<td>2.</td>
		<td>Adam Jendrulek - Vendula Benýšková</td>
		<td>220</td>
		<td>1</td>
	</tr>
	<tr class="nd">
		<td></td>
		<td>Jun II</td>
		<td>2.</td>
		<td>Miroslav Hýža - Denisa Walterová</td>
		<td>1080</td>
		<td>6</td>
	</tr>
	<tr class="nd">
		<td></td>
		<td>Mládež</td>
		<td>2.</td>
		<td>Pavel John - Tereza Jendrulková</td>
		<td>960</td>
		<td>5</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>14.</td>
		<td>Radim Kotrba - Markéta Vlčková</td>
		<td>300</td>
		<td>2</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>22.</td>
		<td>Petr Pohlodek - Petra Gromesová</td>
		<td>130</td>
		<td>2</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>24.</td>
		<td>Tomáš Hroch - Veronika Benýšková</td>
		<td>93</td>
		<td>2</td>
	</tr>
	<tr>
		<td></td>
		<td>Dospělí</td>
		<td>70.</td>
		<td>Pavel John - Tereza Jendrulková</td>
		<td>41</td>
		<td>1</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>26.</td>
		<td>Radim Kotrba - Markéta Vlčková</td>
		<td>244</td>
		<td>4</td>
	</tr>
	<tr>
		<td class="kat">LAT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Jun I</td>
		<td>9.</td>
		<td>Adam Jendrulek - Vendula Benýšková</td>
		<td>300</td>
		<td>3</td>
	</tr>
	<tr>
		<td></td>
		<td>Jun II</td>
		<td>11.</td>
		<td>Miroslav Hýža - Denisa Walterová</td>
		<td>535</td>
		<td>6</td>
	</tr>
	<tr>
		<td></td>
		<td>Mládež</td>
		<td>14.</td>
		<td>Pavel John - Tereza Jendrulková</td>
		<td>358</td>
		<td>4</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>40.</td>
		<td>Petr Pohlodek - Petra Gromesová</td>
		<td>89</td>
		<td>2</td>
	</tr>
	<tr>
		<td></td>
		<td>Dospělí</td>
		<td>52.</td>
		<td>Martin Kordek - Jitka Szabó</td>
		<td>60</td>
		<td>2</td>
	</tr>
	<tr>
		<td class="year">2004</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td class="kat">STT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr class="st">
		<td></td>
		<td>Jun I</td>
		<td>1.</td>
		<td>Adam Jendrulek - Vendula Benýšková</td>
		<td>1200</td>
		<td>8</td>
	</tr>
	<tr class="nd">
		<td></td>
		<td>Mládež</td>
		<td>2.</td>
		<td>Radim Kotrba - Markéta Vlčková</td>
		<td>1100</td>
		<td>7</td>
	</tr>
	<tr class="rd">
		<td></td>
		<td></td>
		<td>3.</td>
		<td>Pavel John - Tereza Jendrulková</td>
		<td>1080</td>
		<td>8</td>
	</tr>
	<tr class="fin">
		<td></td>
		<td></td>
		<td>5.</td>
		<td>Miroslav Hýža - Denisa Walterová</td>
		<td>880</td>
		<td>6</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>8.</td>
		<td>Petr Pohlodek - Petra Gromesová</td>
		<td>620</td>
		<td>5</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>13.</td>
		<td>Tomáš Hroch - Veronika Benýšková</td>
		<td>435</td>
		<td>6</td>
	</tr>
	<tr>
		<td></td>
		<td>Dospělí</td>
		<td>8.</td>
		<td>Radim Kotrba - Markéta Vlčková</td>
		<td>618</td>
		<td>6</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>15.</td>
		<td>Pavel John - Tereza Jendrulková</td>
		<td>487</td>
		<td>5</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>49.-50.</td>
		<td>Miroslav Hýža - Denisa Walterová</td>
		<td>89</td>
		<td>2</td>
	</tr>
	<tr>
		<td class="kat">LAT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr class="fin">
		<td></td>
		<td>Jun I</td>
		<td>5.</td>
		<td>Adam Jendrulek - Vendula Benýšková</td>
		<td>660</td>
		<td>5</td>
	</tr>
	<tr>
		<td></td>
		<td>Mládež</td>
		<td>8.</td>
		<td>Pavel John - Tereza Jendrulková</td>
		<td>585</td>
		<td>6</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>14.</td>
		<td>Miroslav Hýža - Denisa Walterová</td>
		<td>368</td>
		<td>5</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>15.</td>
		<td>Tomáš Hroch - Veronika Benýšková</td>
		<td>332</td>
		<td>6</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>29.-31.</td>
		<td>Petr Pohlodek - Petra Gromesová</td>
		<td>60</td>
		<td>1</td>
	</tr>
	<tr>
		<td></td>
		<td>Dospělí</td>
		<td>16.</td>
		<td>Martin Kordek - Jitka Szabó</td>
		<td>360</td>
		<td>6</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>57.</td>
		<td>Pavel John - Tereza Jendrulková</td>
		<td>33</td>
		<td>1</td>
	</tr>
	<tr>
		<td class="year">2005</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td class="kat">STT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Jun II</td>
		<td>8.</td>
		<td>Adam Jendrulek - Přibylová Kateřina</td>
		<td>240</td>
		<td>1</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>13.-14.</td>
		<td>Adam Jendrulek - Vendula Benýšková</td>
		<td>140</td>
		<td>1</td>
	</tr>
	<tr class="st">
		<td></td>
		<td>Mládež</td>
		<td>1.</td>
		<td>Pavel John - Tereza Jendrulková</td>
		<td>1120</td>
		<td>5</td>
	</tr>
	<tr class="fin">
		<td></td>
		<td></td>
		<td>6.-8.</td>
		<td>Miroslav Hýža - Lucie Benýšková</td>
		<td>400</td>
		<td>2</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>12.</td>
		<td>Miroslav Hýža - Denisa Walterová</td>
		<td>240</td>
		<td>1</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>25.</td>
		<td>Tomáš Hroch - Vendula Benýšková</td>
		<td>95</td>
		<td>1</td>
	</tr>
	<tr>
		<td></td>
		<td>Dospělí</td>
		<td>7.</td>
		<td>Pavel John - Tereza Jendrulková</td>
		<td>825</td>
		<td>6</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>11.</td>
		<td>Radim Kotrba - Markéta Vlčková</td>
		<td>608</td>
		<td>5</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>19.</td>
		<td>Miroslav Hýža - Lucie Benýšková</td>
		<td>322</td>
		<td>4</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>68.</td>
		<td>Petr Pohlodek - Petra Gromesová</td>
		<td>37</td>
		<td>1</td>
	</tr>
	<tr>
		<td class="kat">LAT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Mládež</td>
		<td>8.-9.</td>
		<td>Pavel John - Tereza Jendrulková</td>
		<td>460</td>
		<td>4</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>27.</td>
		<td>Miroslav Hýža - Lucie Benýšková</td>
		<td>110</td>
		<td>1</td>
	</tr>
	<tr>
		<td></td>
		<td>Dospělí</td>
		<td>13.</td>
		<td>Martin Kordek - Jitka Szabó</td>
		<td>403</td>
		<td>4</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>48.</td>
		<td>Pavel John - Tereza Jendrulková</td>
		<td>64</td>
		<td>2</td>
	</tr>
	<tr>
		<td class="year">2006</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td class="kat">STT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Jun I</td>
		<td>13.-14.</td>
		<td>Radim Stupka - Kristýna Hlavicová</td>
		<td>120</td>
		<td>1</td>
	</tr>
	<tr class="st">
		<td></td>
		<td>Jun II</td>
		<td>1.</td>
		<td>Adam Jendrulek - Přibylová Kateřina</td>
		<td>660</td>
		<td>3</td>
	</tr>
	<tr class="rd">
		<td></td>
		<td>Mládež</td>
		<td>3.</td>
		<td>Miroslav Hýža - Lucie Benýšková</td>
		<td>900</td>
		<td>4</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>21.</td>
		<td>Tomáš Hroch - Vendula Benýšková</td>
		<td>60</td>
		<td>1</td>
	</tr>
	<tr class="nd">
		<td></td>
		<td>Dospělí</td>
		<td>2.</td>
		<td>Miroslav Hýža - Lucie Benýšková</td>
		<td>953</td>
		<td>7</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>26.</td>
		<td>Pavel John - Tereza Jendrulková</td>
		<td>293</td>
		<td>2</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>36.</td>
		<td>Petr Pohlodek - Michaela Vitulová</td>
		<td>166</td>
		<td>5</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>63.</td>
		<td>Tomáš Hroch - Vendula Benýšková</td>
		<td>24</td>
		<td>1</td>
	</tr>
	<tr>
		<td class="kat">LAT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Jun I</td>
		<td>17.-19.</td>
		<td>Radim Stupka - Kristýna Hlavicová</td>
		<td>100</td>
		<td>1</td>
	</tr>
	<tr>
		<td></td>
		<td>Jun II</td>
		<td>8.</td>
		<td>Adam Jendrulek - Přibylová Kateřina</td>
		<td>480</td>
		<td>4</td>
	</tr>
	<tr>
		<td></td>
		<td>Mládež</td>
		<td>20.</td>
		<td>Miroslav Hýža - Lucie Benýšková</td>
		<td>220</td>
		<td>2</td>
	</tr>
	<tr>
		<td></td>
		<td>Dospělí</td>
		<td>11.</td>
		<td>Martin Kordek - Michaela Gatěková</td>
		<td>474</td>
		<td>4</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>49.</td>
		<td>Petr Pohlodek - Michaela Vitulová</td>
		<td>27</td>
		<td>1</td>
	</tr>
	<tr>
		<td class="year">2007</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td class="kat">STT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Jun I</td>
		<td>8.-9.</td>
		<td>Jakub Brablec - Marie Hýžová</td>
		<td>260</td>
		<td>2</td>
	</tr>
	<tr class="rd">
		<td></td>
		<td>Jun II</td>
		<td>3.</td>
		<td>Radim Stupka - Kristýna Hlavicová</td>
		<td>720</td>
		<td>5</td>
	</tr>
	<tr>
		<td></td>
		<td>Dospělí</td>
		<td>23.</td>
		<td>Miroslav Hýža - Tereza Jendrulková</td>
		<td>329</td>
		<td>4</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>41.</td>
		<td>Pavel John - Markéta Vlčková</td>
		<td>4</td>
		<td>1</td>
	</tr>
	<tr>
		<td class="kat">LAT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Jun I</td>
		<td>8.</td>
		<td>Jakub Brablec - Marie Hýžová</td>
		<td>230</td>
		<td>2</td>
	</tr>
	<tr class="fin">
		<td></td>
		<td>Jun II</td>
		<td>5.</td>
		<td>Radim Stupka - Kristýna Hlavicová</td>
		<td>620</td>
		<td>5</td>
	</tr>
	<tr>
		<td class="year">2008</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td class="kat">STT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Jun I</td>
		<td>9.</td>
		<td>Jakub Zárybnický - Marie Hýžová</td>
		<td>350</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Jun II</td>
		<td>3.</td>
		<td>Radim Stupka - Kristýna Hlavicová</td>
		<td>980</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Dospělí</td>
		<td>12.</td>
		<td>Miroslav Hýža - Kristýna Hudeová</td>
		<td>453</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>22.</td>
		<td>Miroslav Hýža - Tereza Jendrulková</td>
		<td>263</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>40.</td>
		<td>Adam Jendrulek - Lucie Benýšková</td>
		<td>138</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>58.</td>
		<td>Jiří Pohlodek - Lucie Fojtíková</td>
		<td>72</td>
		<td></td>
	</tr>
	<tr>
		<td class="kat">LAT</td>
		<td>Jun I</td>
		<td>8.</td>
		<td>Jakub Zárybnický - Marie Hýžová</td>
		<td>450</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Jun II</td>
		<td>3.</td>
		<td>Radim Stupka - Kristýna Hlavicová</td>
		<td>900</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Dospělí</td>
		<td>31.-32.</td>
		<td>Jan Kůle - Tereza Jendrulková</td>
		<td>180</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>35.</td>
		<td>Miroslav Hýža - Kristýna Hudeová</td>
		<td>144</td>
		<td></td>
	</tr>
	<tr>
		<td class="year">2009</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td class="kat">STT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Jun I</td>
		<td>8.</td>
		<td>Jakub Zárybnický - Marie Hýžová</td>
		<td>500</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Mládež</td>
		<td>5.</td>
		<td>Adam Jendrůlek - Anna Starečková</td>
		<td>640</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>15.</td>
		<td>Radim Stupka - Kristýna Hlavicová</td>
		<td>160</td>
		<td></td>
	</tr>
	<tr>
		<td class="kat">LAT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Jun I</td>
		<td>10.</td>
		<td>Jakub Zárybnický - Marie Hýžová</td>
		<td>400</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Mládež</td>
		<td>9.</td>
		<td>Adam Jendrulek - Anna Starečková</td>
		<td>360</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>13.-14.</td>
		<td>Radim Stupka - Kristýna Hlavicová</td>
		<td>200</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Dospělí</td>
		<td>26.</td>
		<td>Miroslav Hýža - Kristýna Hudeová</td>
		<td>225</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>38.</td>
		<td>Jan Kůla - Tereza Jendrulková</td>
		<td>540</td>
		<td></td>
	</tr>
	<tr>
		<td class="year">2010</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td class="kat">STT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Jun II</td>
		<td>20.-21.</td>
		<td>Jakub Zárybnický - Marie Hýžová</td>
		<td>55</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Mládež</td>
		<td>19.-20.</td>
		<td>Radim Stupka - Michaela Riedlová</td>
		<td>80</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Dospělí</td>
		<td>16.</td>
		<td>Adam Jendrulek - Anna Starečková</td>
		<td>403</td>
		<td></td>
	</tr>
	<tr>
		<td class="kat">LAT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Jun II</td>
		<td>26.</td>
		<td>Jakub Zárybnický - Marie Hýžová</td>
		<td>50</td>
		<td></td>
	</tr>
	<tr>
		<td class="year">2011</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td class="kat">STT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Jun I</td>
		<td>18.-19.</td>
		<td>Dominik Homola - Mirka Uvízlová</td>
		<td>140</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Dospělí</td>
		<td>9.</td>
		<td>Radim Stupka - Tereza Jendrulková</td>
		<td>520</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>14.-15.</td>
		<td>Miroslav Háža - Marie Hýžová</td>
		<td>404</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td>27.</td>
		<td>Rudolf Stupka - Kristýna Hlavicová</td>
		<td>259</td>
		<td></td>
	</tr>
	<tr>
		<td class="kat">LAT</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Jun I</td>
		<td>10.-13.</td>
		<td>Dominik Homola - Mirka Uvízlová</td>
		<td>300</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>Dospělí</td>
		<td>30.</td>
		<td>Radim Stupka - Tereza Jendrulková</td>
		<td>195</td>
		<td></td>
	</tr>
</table>