<?php header_main('O klubu');?>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TK Olymp Olomouc je tradiční taneční
klub zabývající se výchovou standardních a latinskoamerických
tanečníků. V novém tisíciletí patří mezi nejúspěšnější české kluby.
Naše páry pravidelně sbírají úspěchy v České republice i na
mezinárodním poli.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nabízíme atraktivní volnočasovou
aktivitu dětem, kvalitní zázemí sportovním tanečníkům a příjemné
prostředí pro všechny, co mají rádi tanec.</p>

<img alt="" src="/images/logo.gif" style="display: block; margin: 20px auto;" />
