<?php header_main('Externí trenéři'); ?>
<div style="margin-bottom:2em;">
<img src="/images/treneri/jerry.jpg" class="f_doc_right" style="height:150px;"/>
<?php header_minor('Ing. Jaroslav Kučera');?>
<ul class="list">
<li>vicemistr ČR v latinskoamerických tancích (1992, 1993, 1995)</li>
<li>finalista mistrovství ČR v deseti tancích (1993)</li>
<li>trenér mistrů České republiky všech věkových kategorií</li>
<li>trenér finalistů mistrovství světa</li>
<li>trenér předních českých, slovenských, maďarských párů</li>
<li>trenér a porotce první třídy</li>
<li>porotce s nejvyšší mezinárodní licencí WDSF</li>
<li>porotce mistrovství Evropy</li>
</ul>
</div>
<div style="margin-bottom:2em;">
<img src="/images/treneri/filip_sabka.jpg" class="f_doc_right" style="height:150px;" />
<?php header_minor('Ing. Filip Karásek a Sabina Pišková');?>
<ul class="list">
<li>aktivní tanečníci, držitelé mezinárodní třídy v latinskoamerických tancích</li>
<li>členové národního reprezentačního týmu České republiky</li>
<li>vicemistři České republiky v latinskoamerických tancích (2012)</li>
<li>nejlepší současný latinskoamerický pár v ČR (2011)</li>
<li>2. místo v Taneční lize (žebříček párů mezinárodní třídy)</li>
<li>čtvrtfinalisté mistrovství Evropy</li>
<li>titul Vicemistr České republiky družstev</li>
<li>Filip: absolvent kvalifikačního studia pro porotce a trenéry 3. třídy tanečního sportu</li>
</ul>
</div>
<div style="margin-bottom:2em;">
<img src="/images/treneri/kamca.jpg" class="f_doc_right" style="height:150px;" />
<?php header_minor('Kamila Limberková (Dostálová)');?>
<ul class="list">
<li>2x titul Mistr České republiky v latinskoamerických tancích (2004 a 2006)</li>
<li>2x titul Vicemistr České republiky v latinskoamerických tancích (2003 a 2005)</li>
<li>1x titul Vicemistr České republiky kategorie děti 3 (1996)</li>
<li>členka národního reprezentačního týmu České republiky</li>
<li>1. místo v Taneční lize (žebříček párů mezinárodní třídy)</li>
<li>vítěžka a finalistka významných evropských soutěží</li>
<li>čtvrtfinalistka mistrovství světa a Evropy</li>
<li>trenérka semifinalistů mistrovství ČR v deseti tancích</li>
</ul>
</div>
<div style="margin-bottom:2em;">
<img src="/images/treneri/martin.jpg" class="f_doc_right" style="height:150px;" />
<?php header_minor('Martin Odstrčil');?>
<ul class="list">
<li>6x titul Mistr České republiky v deseti tancích (1995-2000)</li>
<li>titul Mistr České republiky ve standardních tancích (2000)</li>
<li>5x titul Vicemistr České republiky ve standardních tancích (1995-1999)</li>
<li>finalista mistrovství ČR v latinskoamerických tancích (1996)</li>
<li>trenér a porotce 1. třídy</li>
<li>trenér mistrů České republiky všech věkových kategorií</li>
<li>porotce s nejvyšší mezinárodní licencí WDSF – porotce mistrovství světa a Evropy</li>
</ul>
</div>
<div style="margin-bottom:4em;">
<img src="/images/treneri/pavla.jpg" class="f_doc_right" style="height:150px;" />
<?php header_minor('Pavla Landsfeldová');?>
<ul class="list">
<li>finalistka mistrovství ČSSR ve standardních tancích</li>
<li>titul Mistr České republiky ve standardních tancích (senior)</li>
<li>trenérka a porotkyně první třídy</li>
<li>trenérka mistrů České republiky ve standardních tancích</li>
<li>porotkyně Mistrovství České republiky</li>
</ul>
</div>
<div style="margin-bottom:2em;">
<img src="/images/treneri/zdenek.jpg" class="f_doc_right" style="height:150px;" />
<?php header_minor('Ing. Zdeněk Landsfeld');?>
<ul class="list">
<li>2x titul Vicemistr ČSSR ve standardních tancích (1978 a 1979)</li>
<li>2x titul Mistr ČR ve standardních tancích – kategorie senior (1994 a 1995)</li>
<li>titul Mistr Prahy v latinskoamerických tancích (1978)</li>
<li>Účastník mistrovství světa a Evropy (1979, 1980 a 1995)</li>
<li>3. Místo na MS formací 1977 v Mnichově</li>
<li>trenér a porotce první třídy</li>
<li>trenér mistrů České republiky všech věkových kategorií</li>
<li>profesionální taneční trenér a kouč významných českých, německých, rakouských a slovenských párů</li>
<li>lektor na Univerzitě Karlově v Praze a Univerzitě Palackého v Olomouci (studium trenérů a porotců II. a III. třídy)</li>
<li>porotce s nejvyšší mezinárodní licencí WDSF – porotce mistrovství světa</li>
</ul>
</div>
