do $$
begin
  if not exists (select 1 from pg_catalog.pg_type where typname = 'document_kind') then
    create type document_kind as enum ('plan', 'evaluation');
  end if;
  if not exists (select 1 from pg_catalog.pg_type where typname = 'discipline') then
    create type discipline as enum ('stt', 'lat', 'conditioning', 'practice');
  end if;
end
$$;

create table if not exists document (
  id bigint primary key generated by default as identity,
  tenant_id bigint not null default current_tenant_id(),
  kind document_kind not null default 'plan',
  title text,
  created_by bigint default current_user_id(),
  event_instance_id bigint,
  event_series_id bigint,
  cohort_id bigint,
  show_to_members boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint document_tenant_id_id_key unique (tenant_id, id),
  constraint document_subject_check
    check (num_nonnulls(event_instance_id, event_series_id, cohort_id) <= 1),

  constraint document_tenant_fkey foreign key (tenant_id)
    references tenant (id) on delete cascade,
  constraint document_author_fkey foreign key (created_by)
    references users (id) on delete set null,
  -- The column list keeps `set null` off tenant_id, which is not nullable.
  constraint document_event_instance_fkey foreign key (tenant_id, event_instance_id)
    references event_instance (tenant_id, id) on delete set null (event_instance_id),
  constraint document_event_series_fkey foreign key (tenant_id, event_series_id)
    references event_series (tenant_id, id) on delete set null (event_series_id),
  constraint document_cohort_fkey foreign key (tenant_id, cohort_id)
    references cohort (tenant_id, id) on delete set null (cohort_id)
);

create table if not exists document_node (
  id uuid primary key default uuidv7(),
  tenant_id bigint not null default current_tenant_id(),
  document_id bigint not null,
  parent_id uuid,
  ordering numeric not null default 1,
  content jsonb not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint document_node_tenant_id_id_key unique (tenant_id, id),
  constraint document_node_tenant_document_id_key unique (tenant_id, document_id, id),
  constraint document_node_parent_not_self check (parent_id is null or parent_id <> id),

  constraint document_node_tenant_fkey foreign key (tenant_id)
    references tenant (id) on delete cascade,
  constraint document_node_document_fkey foreign key (tenant_id, document_id)
    references document (tenant_id, id) on delete cascade,
  constraint document_node_parent_fkey foreign key (tenant_id, document_id, parent_id)
    references document_node (tenant_id, document_id, id) on delete cascade
);

create table if not exists document_node_tag (
  id bigint primary key generated by default as identity,
  tenant_id bigint not null default current_tenant_id(),
  node_id uuid not null,
  person_id bigint,
  couple_id bigint,
  cohort_id bigint,
  event_instance_id bigint,
  competition_id bigint,
  dance_code text,
  tagged_month date,
  discipline discipline,
  created_at timestamp with time zone not null default now(),

  constraint document_node_tag_target_check
    check (num_nonnulls(person_id, couple_id, cohort_id, event_instance_id,
                        competition_id, dance_code, tagged_month, discipline) = 1),
  constraint document_node_tag_month_check
    check (tagged_month is null or extract(day from tagged_month) = 1),
  constraint document_node_tag_unique
    unique nulls not distinct (node_id, person_id, couple_id, cohort_id, event_instance_id,
                               competition_id, dance_code, tagged_month, discipline),

  constraint document_node_tag_tenant_fkey foreign key (tenant_id)
    references tenant (id) on delete cascade,
  constraint document_node_tag_node_fkey foreign key (tenant_id, node_id)
    references document_node (tenant_id, id) on delete cascade,
  constraint document_node_tag_person_fkey foreign key (person_id)
    references person (id) on delete cascade,
  constraint document_node_tag_couple_fkey foreign key (couple_id)
    references couple (id) on delete cascade,
  constraint document_node_tag_cohort_fkey foreign key (tenant_id, cohort_id)
    references cohort (tenant_id, id) on delete cascade,
  constraint document_node_tag_event_instance_fkey foreign key (tenant_id, event_instance_id)
    references event_instance (tenant_id, id) on delete cascade,
  constraint document_node_tag_competition_fkey foreign key (competition_id)
    references federated.competition (id) on delete cascade,
  constraint document_node_tag_dance_fkey foreign key (dance_code)
    references federated.dance (code) on delete cascade
);

-- Composite keys otherwise surface as tenantCohort, documentNodesByTenantIdAndDocumentId
-- and the like, so each relation is named the way the rest of the schema names them.
-- Writes go through upsert_document, and nodes and tags are only ever reached
-- from a document or from a tagged entity, so the generated surface is cut back
-- to what is actually called.
comment on table document is '@simpleCollections only
@behavior -insert -update -query:resource:list -query:resource:connection';
comment on table document_node is '@simpleCollections only
@behavior -insert -update -delete -query:resource:single -query:resource:list -query:resource:connection';
comment on table document_node_tag is '@simpleCollections only
@behavior -insert -update -delete -query:resource:single -query:resource:list -query:resource:connection';

-- The composite uniques exist for the tenant-scoped foreign keys, not as
-- accessors; without this each one generates its own by-key query and mutation.
comment on constraint document_tenant_id_id_key on document is '@omit';
comment on constraint document_node_tenant_id_id_key on document_node is '@omit';
comment on constraint document_node_tenant_document_id_key on document_node is '@omit';
comment on constraint document_node_tag_unique on document_node_tag is '@omit';

comment on constraint document_tenant_fkey on document is '@fieldName tenant';
comment on constraint document_author_fkey on document is '@fieldName author
@foreignFieldName authoredDocuments';
comment on constraint document_event_instance_fkey on document is '@fieldName eventInstance
@foreignFieldName documents';
comment on constraint document_event_series_fkey on document is '@fieldName eventSeries
@foreignFieldName documents';
comment on constraint document_cohort_fkey on document is '@fieldName cohort
@foreignFieldName documents';

comment on constraint document_node_tenant_fkey on document_node is '@fieldName tenant';
comment on constraint document_node_document_fkey on document_node is '@fieldName document
@foreignFieldName nodes';
comment on constraint document_node_parent_fkey on document_node is '@fieldName parent
@foreignFieldName children';

comment on constraint document_node_tag_tenant_fkey on document_node_tag is '@fieldName tenant';
comment on constraint document_node_tag_node_fkey on document_node_tag is '@fieldName node
@foreignFieldName tags';
comment on constraint document_node_tag_cohort_fkey on document_node_tag is '@fieldName cohort
@foreignFieldName documentNodeTags';
comment on constraint document_node_tag_event_instance_fkey on document_node_tag is '@fieldName eventInstance
@foreignFieldName documentNodeTags';

create index if not exists document_event_instance_id_idx
  on document (event_instance_id) where event_instance_id is not null;
create index if not exists document_event_series_id_idx
  on document (event_series_id) where event_series_id is not null;
create index if not exists document_cohort_id_idx
  on document (cohort_id) where cohort_id is not null;

create index if not exists document_node_document_ordering_idx
  on document_node (document_id, parent_id, ordering);

create index if not exists document_node_tag_node_id_idx
  on document_node_tag (node_id);
create index if not exists document_node_tag_person_id_idx
  on document_node_tag (person_id) where person_id is not null;
create index if not exists document_node_tag_couple_id_idx
  on document_node_tag (couple_id) where couple_id is not null;
create index if not exists document_node_tag_cohort_id_idx
  on document_node_tag (cohort_id) where cohort_id is not null;
create index if not exists document_node_tag_event_instance_id_idx
  on document_node_tag (event_instance_id) where event_instance_id is not null;
create index if not exists document_node_tag_competition_id_idx
  on document_node_tag (competition_id) where competition_id is not null;
create index if not exists document_node_tag_dance_code_idx
  on document_node_tag (dance_code) where dance_code is not null;
create index if not exists document_node_tag_tagged_month_idx
  on document_node_tag (tagged_month) where tagged_month is not null;
create index if not exists document_node_tag_discipline_idx
  on document_node_tag (discipline) where discipline is not null;

drop trigger if exists _100_timestamps on document;
create trigger _100_timestamps before insert or update on document
  for each row execute function app_private.tg__timestamps();

drop trigger if exists _100_timestamps on document_node;
create trigger _100_timestamps before insert or update on document_node
  for each row execute function app_private.tg__timestamps();

alter table document enable row level security;
alter table document_node enable row level security;
alter table document_node_tag enable row level security;

-- The aggregator stays unexposed; `public` takes only what the club API needs.
create or replace view dance as
  select code, name, discipline from federated.dance;

comment on view dance is '@primaryKey code
@simpleCollections only
@behavior -insert -update -delete';

grant select on dance to anonymous;

--!include functions/document_node_tags.sql
--!include functions/upsert_document.sql
--!include functions/orphaned_documents.sql
--!include policies/document.sql
