comment on table public.event_instance_registration is E'@omit create,update,delete\n@simpleCollections both';

comment on function public.register_to_event_many(public.register_to_event_type[]) is '@omit';
comment on function public.edit_registration(bigint, text) is '@omit';
comment on function public.cancel_registration(bigint) is '@omit';

do $$
begin
  if not exists (
    select 1
    from pg_catalog.pg_type type
    join pg_catalog.pg_namespace namespace on namespace.oid = type.typnamespace
    where namespace.nspname = 'public'
      and type.typname = 'event_registration_source'
  ) then
    create type public.event_registration_source
      as enum ('self', 'manager', 'cohort');
  end if;
end;
$$;

alter table public.event_instance_registration
  add column if not exists source public.event_registration_source;

create table if not exists public.event_instance_target_cohort (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default public.current_tenant_id()
    references public.tenant(id) on update cascade on delete cascade,
  instance_id bigint not null
    references public.event_instance(id) on update cascade on delete cascade,
  cohort_id bigint not null
    references public.cohort(id) on update cascade on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (instance_id, cohort_id)
);

comment on constraint event_instance_target_cohort_instance_id_fkey
  on public.event_instance_target_cohort is
  E'@fieldName instance\n@foreignFieldName targetCohorts';

comment on table public.event_instance_target_cohort is E'@omit create,update,delete\n@behavior -query:resource:list -query:resource:connection -query:resource:single\n@simpleCollections only';
grant all on table public.event_instance_target_cohort to anonymous;
grant usage, select on sequence public.event_instance_target_cohort_id_seq to anonymous;
alter table public.event_instance_target_cohort enable row level security;

create index if not exists event_instance_target_cohort_tenant_id_idx
  on public.event_instance_target_cohort (tenant_id);
create index if not exists event_instance_target_cohort_cohort_id_idx
  on public.event_instance_target_cohort (cohort_id);

drop trigger if exists _100_timestamps on public.event_instance_target_cohort;

do $$
begin
  if exists (
    select 1 from pg_constraint
    where conname = 'event_instance_registration_target_cohort_id_fkey'
      and conrelid = 'public.event_instance_registration'::regclass
      and confrelid = 'public.event_target_cohort'::regclass
  ) then
    insert into public.event_instance_target_cohort (
      tenant_id, instance_id, cohort_id, created_at, updated_at
    )
    select target.tenant_id, instance.id, target.cohort_id,
      target.created_at, target.updated_at
    from public.event_target_cohort target
    join public.event_instance instance on instance.event_id = target.event_id
    on conflict (instance_id, cohort_id) do nothing;

    alter table public.event_instance_registration
      drop constraint event_instance_registration_target_cohort_id_fkey;

    alter table public.event_instance_registration disable trigger _100_timestamps;
    update public.event_instance_registration registration
    set target_cohort_id = target.cohort_id
    from public.event_target_cohort target
    where target.id = registration.target_cohort_id;
    alter table public.event_instance_registration enable trigger _100_timestamps;

    alter table public.event_instance_registration
      add constraint event_instance_registration_target_cohort_id_fkey
      foreign key (target_cohort_id) references public.cohort(id)
      on update cascade on delete restrict;
  end if;
end;
$$;

alter table public.event_instance_registration disable trigger _100_timestamps;
update public.event_instance_registration
set source = 'cohort'
where parent_registration_id is null
  and target_cohort_id is not null
  and source is null;
alter table public.event_instance_registration enable trigger _100_timestamps;

create trigger _100_timestamps before insert or update on public.event_instance_target_cohort
  for each row execute function app_private.tg__timestamps();

drop trigger if exists _500_register_members on public.event_target_cohort;
drop trigger if exists _500_unregister_members on public.event_target_cohort;

--! include policies/event_instance_target_cohort.sql
--! include functions/sync_eir_registrations.sql
--! include functions/reconcile_event_instance_cohort_registrations.sql
--! include functions/tg_cohort_membership__on_status.sql
--! include functions/event_instance_target_cohorts.sql
--! include functions/scoreboard.sql
--! include functions/set_event_instance_registration.sql
--! include functions/update_event_instance_details.sql
--! include functions/quick_create_event_instances.sql
--! include functions/detach_event_instance.sql
--! include functions/upsert_event.sql
