--!include functions/register_without_invitation.sql

-- Guarded creation of the announcement audience role enum
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'announcement_audience_role'
      AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public.announcement_audience_role AS ENUM (
      'member',
      'trainer',
      'administrator'
    );
  END IF;
END;
$$;

-- Tenant-scoped announcement audience table with cohort/role exclusivity
CREATE TABLE IF NOT EXISTS public.announcement_audience (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  announcement_id BIGINT NOT NULL REFERENCES public.upozorneni(up_id) ON UPDATE CASCADE ON DELETE CASCADE,
  cohort_id BIGINT REFERENCES public.cohort(id),
  audience_role public.announcement_audience_role,
  tenant_id BIGINT NOT NULL DEFAULT public.current_tenant_id() REFERENCES public.tenant(id) ON DELETE CASCADE,
  CONSTRAINT announcement_audience_audience_check CHECK ((cohort_id IS NULL) <> (audience_role IS NULL))
);

CREATE UNIQUE INDEX IF NOT EXISTS announcement_audience_announcement_cohort_idx
  ON public.announcement_audience (announcement_id, cohort_id);

CREATE UNIQUE INDEX IF NOT EXISTS announcement_audience_announcement_role_idx
  ON public.announcement_audience (announcement_id, audience_role);

CREATE INDEX IF NOT EXISTS announcement_audience_tenant_idx
  ON public.announcement_audience (tenant_id);

-- Copy existing cohort audiences from the legacy table without dropping it yet
DO $$
BEGIN
  IF to_regclass('public.upozorneni_skupiny') IS NOT NULL THEN
    INSERT INTO public.announcement_audience (id, announcement_id, cohort_id, tenant_id)
    SELECT
      ups_id AS id,
      ups_id_rodic AS announcement_id,
      ups_id_skupina AS cohort_id,
      tenant_id
    FROM public.upozorneni_skupiny
    ON CONFLICT (id) DO UPDATE
    SET
      announcement_id = EXCLUDED.announcement_id,
      cohort_id = EXCLUDED.cohort_id,
      tenant_id = EXCLUDED.tenant_id;
  END IF;
END;
$$;

-- Recreate row level security policies and grants for GraphQL exposure
SELECT app_private.drop_policies('public.announcement_audience');

ALTER TABLE public.announcement_audience ENABLE ROW LEVEL SECURITY;

CREATE POLICY admin_all ON public.announcement_audience
  TO administrator USING (TRUE) WITH CHECK (TRUE);

CREATE POLICY current_tenant ON public.announcement_audience AS RESTRICTIVE
  USING (tenant_id = public.current_tenant_id());

CREATE POLICY member_view ON public.announcement_audience FOR SELECT
  TO member USING (TRUE);

GRANT ALL ON TABLE public.announcement_audience TO anonymous;

COMMENT ON TABLE public.announcement_audience IS E'@foreignKey (announcement_id) references announcement (id)
@foreignKey (cohort_id) references cohort (id)';
COMMENT ON CONSTRAINT announcement_audience_announcement_id_fkey ON announcement_audience IS '@fieldName upozorneni';
