version: '2'

services:
  mysqldb:
    image: mysql/mysql-server:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: olymp
      MYSQL_USER: olymp
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf

  phpfpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    links:
      - mysqldb
    volumes:
      - ..:/app
    tty: true

  nginx:
    image: bitnami/nginx:latest
    depends_on:
      - phpfpm
    ports:
      - 3000:3000
    volumes:
      - ..:/app
      - ./conf/vhost.conf:/bitnami/nginx/conf/vhosts/olymp.conf
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    restart: always
    environment:
      - "PMA_HOST=mysqldb"
      - "PMA_PORT=3306"
      - "PMA_ABSOLUTE_URI=http://localhost:3001/"
    ports:
      - 3001:80
