<?= $this->header('Výsledky našich párů na Mistrovství České republiky družstev') ?>

<div class="container full">
  <h2>Otrokovice, 2011</h2>
  <h3>Dospělí STT</h3>
  <table style="width:500px;">
    <tr>
      <td>8. místo</td>
      <td>Vít Navrátil - Petra Chytilová</td>
    </tr>
    <tr>
      <td></td>
      <td>Radim Stupka - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td>Rudolf Stupka - Kristýna Hlavicová</td>
    </tr>
    <tr>
      <td></td>
      <td>Miroslav Hýža - Marie Hýžová</td>
    </tr>
    <tr>
      <td>kapitán:</td>
      <td>Mgr. Marie Hýžová</td>
    </tr>
  </table>
  <br/>

  <h2>Praha, 2010</h2>
  <h3>Junioři STT</h3>
  <table style="width:500px;">
    <tr>
      <td>5. místo</td>
      <td>Marek Švarc - Monika Vymětalová</td>
    </tr>
    <tr>
      <td></td>
      <td>Matěj Očenášek - Marie Smyslilová</td>
    </tr>
    <tr>
      <td></td>
      <td>Jakub Zárybnický - Kristýna Dovčiaková</td>
    </tr>
    <tr>
      <td></td>
      <td>Dominik Homola - Mirka Uvízlová</td>
    </tr>
    <tr>
      <td>kapitán:</td>
      <td>Miroslav Hýža</td>
    </tr>
  </table>

  <h3>Junioři LAT</h3>
  <table style="width:500px">
    <tr>
      <td>3.místo</td>
      <td>Jiří Anderle - Veronika Chromcová</td>
    </tr>
    <tr>
      <td></td>
      <td>Dominik Homola - Mirka Uvízlová</td>
    </tr>
    <tr>
      <td></td>
      <td>Jakub Zárybnický - Kristýna Dovčiakov</td>
    </tr>
    <tr>
      <td></td>
      <td>Marek Švarc - Monika Vymětalová</td>
    </tr>
    <tr>
      <td>kapitáni:</td>
      <td>Tereza Jendrulková a Miroslav Hýža</td>
    </tr>
  </table>
  <br/>

  <h2>Roudnice nad Labem, 2006</h2>
  <h3>Dospělí STT</h3>
  <table style="width:500px;">
    <tr>
      <td>5. místo</td>
      <td>Miroslav Hýža - Lucie Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td>Tomáš Hroch - Vendula Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td>Petr Pohlodek - Michaela Vitulová</td>
    </tr>
    <tr>
      <td>kapitán:</td>
      <td>Marie Hýžová</td>
    </tr>
  </table>
  <br/>

  <h2>Třinec, 2005</h2>
  <h3>Mládež STT</h3>
  <table style="width:500px;">
    <tr>
      <td>1. místo</td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr>
      <td></td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td>Tomáš Hroch - Veronika Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td>Miroslav Hýža - Lucie Benýšková</td>
    </tr>
    <tr>
      <td>kapitán:</td>
      <td>Marie Hýžová</td>
    </tr>
  </table>

  <h3>Mládež LAT</h3>
  <table style="width:500px">
    <tr>
      <td>6.místo</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr>
      <td></td>
      <td>Adam Jendrulek - Vendula Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td>Tomáš Hroch - Veronika Benýšková</td>
    </tr>
    <tr>
      <td>kapitán:</td>
      <td>Tomáš Kraina</td>
    </tr>
  </table>

  <h3>Dospělí STT</h3>
  <table style="width:500px;">
    <tr>
      <td>2.místo</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td>Radim Kotrba - Markéta Vlčková</td>
    </tr>
    <tr>
      <td></td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr>
      <td></td>
      <td>Miroslav Hýža - Lucie Benýšková</td>
    </tr>
    <tr>
      <td>kapitán:</td>
      <td>Hana Jendrulková</td>
    </tr>
  </table>

  <h3>Dospělí LAT</h3>
  <table style="width:500px;">
    <tr>
      <td>8.místo</td>
      <td>Martin Kordek - Jitka Szabó</td>
    </tr>
    <tr>
      <td></td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td>Tomáš Hroch - Vendula Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr>
      <td>kapitán:</td>
      <td>Tomáš Kraina</td>
    </tr>
  </table>
  <br/>

  <h2>Pardubice, 2002</h2>
  <h3>Junioři STT</h3>
  <table style="width:500px;">
    <tr>
      <td>1. místo</td>
      <td>Miroslav Hýža - Denisa Walterová</td>
    </tr>
    <tr>
      <td></td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr>
      <td></td>
      <td>Tomáš Hroch - Veronika Benýšková</td>
    </tr>
    <tr>
      <td>kapitán:</td>
      <td>Marie Hýžová</td>
    </tr>
  </table>

  <h3>Junioři LAT</h3>
  <table style="width:500px;">
    <tr>
      <td>1.místo</td>
      <td>Tomáš Hroch - Veronika Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td>Miroslav Hýža - Denisa Walterová</td>
    </tr>
    <tr>
      <td></td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr>
      <td>kapitán:</td>
      <td>Tomáš Kraina</td>
    </tr>
  </table>
  <br/>

  <h2>Most, 2004</h2>
  <h3>Mládež STT</h3>
  <table style="width:500px;">
    <tr>
      <td>1.místo</td>
      <td>Radim Kotrba - Markéta Vlčková</td>
    </tr>
    <tr>
      <td></td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td>Miroslav Hýža - Denisa Walterová</td>
    </tr>
    <tr>
      <td></td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr>
      <td>kapitán:</td>
      <td>Hana Jendrulková</td>
    </tr>
  </table>

  <h3>Dospělí STT</h3>
  <table style="width:500px">
    <tr>
      <td>5. místo</td>
      <td>Radim Kotrba - Markéta Vlčková</td>
    </tr>
    <tr>
      <td></td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr>
      <td></td>
      <td>Miroslav Hýža - Denisa Walterová</td>
    </tr>
    <tr>
      <td></td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td>kapitán:</td>
      <td>Marie Hýžová</td>
    </tr>
  </table>
  <br/>

  <h2>Třinec, 2001</h2>
  <h3>Junioři STT</h3>
  <table style="width:500px;">
    <tr>
      <td>2. místo</td>
      <td>Radim Kotrba - Markéta Vlčková</td>
    </tr>
    <tr>
      <td></td>
      <td>Miroslav Hýža - Denisa Walterová</td>
    </tr>
    <tr>
      <td></td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td>Tomáš Hroch - Veronika Benýšková</td>
    </tr>
    <tr>
      <td>kapitán:</td>
      <td>Marie Hýžová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>6.místo</td>
      <td>Jan Matoušek - Vendula Vojáková</td>
    </tr>
    <tr>
      <td></td>
      <td>Pavel Skála - Petra Gromesová</td>
    </tr>
    <tr>
      <td></td>
      <td>Jiří Mišák - Nikol Nezvalová</td>
    </tr>
    <tr>
      <td></td>
      <td>Michal Fodor - Anita Šmídová</td>
    </tr>
    <tr>
      <td>kapitán:</td>
      <td>Hana Jendrulková</td>
    </tr>
  </table>

  <h3>Junioři LAT</h3>
  <table style="width:500px">
    <tr>
      <td>3. místo</td>
      <td>Radim Kotrba - Markéta Vlčková</td>
    </tr>
    <tr>
      <td></td>
      <td>Jan Matoušek - Vendula Vojáková</td>
    </tr>
    <tr>
      <td></td>
      <td>Miroslav Hýža - Denisa Walterová</td>
    </tr>
    <tr>
      <td></td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td>kapitán:</td>
      <td>Tomáš Kraina</td>
    </tr>
  </table>
  <br/>

  <h2>Most, 2000</h2>
  <h3>Junioři STT</h3>
  <table style="width:500px;">
    <tr>
      <td>3.místo</td>
      <td>Radim Kotrba - Markéta Vlčková</td>
    </tr>
    <tr>
      <td></td>
      <td>Martin Kordek - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td>Miroslav Hýža - Denisa Walterová</td>
    </tr>
    <tr>
      <td></td>
      <td>Tomáš Hroch - Veronika Benýšková</td>
    </tr>
    <tr>
      <td>kapitán:</td>
      <td>Marie Hýžová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>8.-9.místo</td>
      <td>Pavel John - Anita Šmídová</td>
    </tr>
    <tr>
      <td></td>
      <td>Jiří Řehulka - Kateřina Pabišková</td>
    </tr>
    <tr>
      <td></td>
      <td>Jiří Mišák - Nikol Nezvalová</td>
    </tr>
    <tr>
      <td></td>
      <td>Pavel Skála - Petra Gromesová</td>
    </tr>
    <tr>
      <td>kapitán:</td>
      <td>Hana Jendrulková</td>
    </tr>

  </table>

  <h3>Junioři LAT</h3>
  <table style="width:500px">
    <tr>
      <td>7.místo</td>
      <td>Radim Kotrba - Markéta Vlčková</td>
    </tr>
    <tr>
      <td></td>
      <td>Martin Kordek - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td>Miroslav Hýža - Denisa Walterová</td>
    </tr>
    <tr>
      <td></td>
      <td>Pavel John - Anita Šmídová</td>
    </tr>
    <tr>
      <td>kapitán:</td>
      <td>Tomáš Kraina</td>
    </tr>
  </table>
  <br/>

  <h2>Most, 1999</h2>
  <h3>Junioři STT</h3>
  <table style="width:500px;">
    <tr>
      <td>4. místo</td>
      <td>Martin Kordek - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td>Pavel Řehulka - Jana Safernová</td>
    </tr>
    <tr>
      <td></td>
      <td>Tomáš Hroch - Veronika Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td>Miroslav Hýža - Denisa Walterová</td>
    </tr>
    <tr>
      <td>kapitán:</td>
      <td>Marie Hýžová</td>
    </tr>
  </table>
</div>
