<?= $this->header('Historie klubu') ?>

<div class="container full">
    <div class="container two-thirds">
        <h2>1989</h2>
        <p>
            První zmínka o Tanečním klubu Olymp Olomouc se datuje k roku 1989,
            když navázal na fungování na Tanečního klubu Parku kultury a
            oddechu. U zrodu nového TK stál PhDr. Miroslav Hýža, který se stal
            jeho hlavním vedoucím. V klubu byly zpočátku jen dospělé taneční
            páry, největších úspěchů klub dosáhl hlavně díky práci s dětmi a
            mládeží na Základní škole Holečkova v Olomouci. Jak se později
            ukázalo, zejména taneční třídy, založené v letech 1993 a 1994 se
            staly základem generace mladých tanečníků, kteří později pronikli
            do české taneční špičky.
        </p>
        <img alt="TK Olymp, založen 1989"
             src="/images/historie/historie.jpg"
             class="block-center"
             style="height:257px;" />

        <h2>1995</h2>
        <p>
            Poprvé o sobě dal TK Olymp Olomouc výrazněji vědět v roce 1995, kdy
            se formace s názvem Karlštejn, pod vedením PhDr. Miroslava Hýži a
            Marie Hýžové dostala do republikového finále.
        </p>
        <p>
            Na podzim roku 1995 se hlavní vedoucí klubu stala Mgr. Marie Hýžová
            a hned v následujícím roce s dětskou formací Zlatovláska navázala
            na předešlý úspěch, když se probojovala znovu do republikového
            finále v Ústí nad Labem. Formace tehdy získala nečekané, ale o to
            krásnější třetí místo.
        </p>
        <p>
            V říjnu 1996 se Olymp sloučil s konkurenční Proximou (TK Proxima
            Olymp Olomouc). Spolupráce dvou nejúspěšnějších olomouckých klubů
            trvala pouze do konce roku 1998.
        </p>
        <img alt="Tři oříšky pro Popelku"
             src="/images/historie/tri_orisky.jpg"
             class="block-center"
             style="height:222px;" />

        <h2>1997</h2>
        <p>
            I v těchto letech se dařilo našim formacím. V roce 1997 se dostala
            choreografie s názvem Vltava znovu do finále Mistrovství České
            republiky a znovu slavila úspěch. Tentokrát v podobě stříbrné
            medaile.
        </p>
        <p>
            Do třetice všeho dobrého medaile - a konečně zlatá. V roce 1999 se
            Olymp dočkal svého prvního titulu Mistra České republiky, když
            juniorská formace s názvem Tři Oříšky pro Popelku, opět pod vedením
            Marie Hýžové, porazila pražský MADAT.
        </p>
        <p>
            V této době už slavily úspěchy i samostatné taneční páry. Nejlépe
            si vedl zejména pár Martin Kordek - Hana Švajdová, kteří v roce
            1997 na Mistrovství ČR ve standardních tancích vybojovali bronzovou
            medaili v juniorech 1(1. Bič - Konderlová, 2. M. Dvořák -
            Kettnerová). O rok později získal stejný pár ve standardních
            tancích medaili stříbrnou (1. M. Dvořák - Kettnerová) a v latině
            obsadil krásné čtvrté místo.
        </p>
        <img alt="mistři Martin Korder s Hanou Švajdovou"
             src="/images/historie/martin_hanca.jpg"
             class="block-center"
             style="height:222px" />

        <h2>2000</h2>
        <p>
            Do nového tisíciletí vykročil Olymp ve velkém stylu. Do roku 2006
            získaly naše páry 13 bronzových, 4 stříbrné a 3 zlaté medaile a
            spoustu finálových účastí na republikových šampionátech. Za zmínku
            stojí především pár Miroslav Hýža - Denisa Walterová, který v roce
            2001 posbíral všechny tři tituly Mistra České republiky (kombinace,
            standardní a latinskoamerické tance), vyhrál Taneční ligu ve
            standardu i latině a totéž se mu povedlo v tehdy prestižní soutěži
            IDSF Hradec Králové Open.
        </p>
        <p>
            Velké úspěchy slavil klub také v soutěžích družstev. Do roku 2006
            jsme nasbírali 8 medailí na mistrovstvích České republiky, včetně
            čtyř titulů Mistrů České republiky (2x 2002, 2004 a 2005) a
            překvapivého, ale o to krásnějšího stříbra ve standardních tancích
            v kategorii dospělých roku 2005.
        </p>
        <img alt="mistři Miroslav Hýža s Denisou Walterovou"
             src="/images/historie/mistr_desitky.jpg"
             class="block-center"
             style="height:222px" />

        <h2>2004</h2>
        <p>
            Olympácké páry o sobě dávaly vědět i na mezinárodní úrovni. Výborné
            výsledky zaznamenali naši tanečníci zejména v prestižní soutěži
            Summer Dance Festival Berlin. V roce 2004 se pár Radim Kotrba -
            Markéta Vlčková umístil na druhém místě. O rok později se do finále
            stejné soutěže probojoval pár Pavel John - Tereza Jendrulková,
            kteří obsadili třetí příčku.
        </p>
        <p>
            Mezi největší úspěchy klubu určitě patří účast našich párů na
            Mistrovství světa. V roce 2004 se ve standardních tancích
            představil v čínské Šanghaji pár Radim Kotrba - Markéta Vlčková. Z
            celkového počtu 64 párů se umístili na krásném 20. místě
            (mistrovství se účastnil ještě další český pár Malý - Doležalová,
            skončili na 25. místě). V témže roce se Mistrovství světa v deseti
            tancích v estonském Talinu zúčastnil Pavel John s Terezou
            Jendrulkovou. Jako jediní čeští zástupci vybojovali 17. pozici z
            celkového počtu 29 párů.
        </p>
        <img alt="Mistrovství světa 2004"
             src="/images/historie/slowfox_nice.jpg"
             class="block-center"
             style="height:222px" />

        <h2>2006</h2>
        <p>
            Úspěšní tanečníci z juniorských a mládežnických kategoriích výrazně
            promluvili i do dění v kategorii dospělých tanečních párů. Pavel
            John s Terezou Jendrulkovou byli v roce 2004 osmí v republice ve
            standardních tancích.  Republikové semifinále si zopakovali i v
            následujících dvou letech. V roce 2006 se týž pár probojoval do
            finále Mistrovství České republiky v deseti tancích, kde se zapsali
            do historie 4. místem. V latinskoamerických tancích se do
            republikového semifinále probojoval Martin Kordek se svou novou
            ostravskou partnerkou Michaelou Gatěkovou.
        </p>
        <p>
            Ve stejném roce se velmi dařilo páru Miroslav Hýža - Lucie
            Benýšková, kteří v celoročním žebříčku Taneční ligy ve standardních
            tancích obsadili druhé místo (1. Houška - Třeštíková). Republikové
            semifinále v kategorii dospělých si zatančili jak v tancích
            standardních, tak v kombinaci. Na mistrovství republiky mládeže (do
            18 let) ve standardních tancích získali bronzovou medaili.
        </p>
        <p>
            Žebříček taneční ligy v kategorii junior 2 vyhrál Adam Jendrulek s
            Kateřinou Přibylovou.
        </p>
        <img alt="Pavel John s Terezou Jendrulkovou"
             src="/images/historie/pavel_terka.jpg"
             class="block-center"
             style="height:222px" />

        <h2>2008</h2>
        <p>
            "Zlatá" generace párů, která byla v rámci českého tanečního sportu
            v mnoha směrech unikátní, se pomalu rozutekla po studiích a řada
            přišla na další páry. Semifinále mistrovství České republiky v
            deseti tancích si zatančili nově složení Miroslav Hýža s Terezou
            Jendrulkovou. Mezi největší naděje patřili bezesporu Radim Stupka a
            Kristýna Hlavicová, kteří se v roce 2008 probojovali do finále
            mistrovství České republiky jak ve standardních, latinských, tak i
            deseti tancích, kde v kategorii junior 2 (do 15 let) obsadili
            4. místo.  V následujícím roce se ve standardních tancích dokázali
            probojovat do finále Mistrovství ČR ve standardních tancích
            (5. místo), kde porazili dalšího člena TK Olymp - Adama Jendrulka
            se svojí kroměřížskou partnerkou Alenou Starečkovou. Tento pár se v
            roce 2009 probojoval do i do finále Mistrovství České republiky v
            deseti tancích (5. místo) v kategorii mládež.
        </p>
        <img alt="Radim Stupka s Kristýnou Hlavicovou"
             src="/images/historie/radim_kiki.jpg"
             class="block-center"
             style="height:302px" />
        <p>
            V kategorii dospělých se nejlépe umístil Miroslav Hýža s novou
            partnerkou Kristýnou Hudeovou, kteří se na Mistrovství ČR v deseti
            tancích probojovali do semifinále (11. místo).
        </p>
        <img alt="Miroslav Hýža s Kristýnou Hudeovou"
             src="/images/historie/mirek_kiki.jpg"
             class="block-center"
             style="320px" />

        <h2>2010</h2>
        <p>
            V roce 2010 zaznamenal největší úspěchy Radim Stupka se svou novou
            ostravskou partnerkou Michaelou Riedlovou.  V kategorii mládež se
            ve všech skupinách tanců (standard, latina, kombinace) probojovali
            do finále mistrovství republiky. Nejvíce se jim zadařilo v soutěži
            kombinace deseti tanců, kde získali bronzovou medaili. Adam
            Jendrulek s Alenou Starečkovou se na stejném mistrovství, ale v
            kategorii dospělých probojovali do semifinále, kde obsadili
            jedenáctou příčku.
        </p>
        <img alt="Adam Jendrulek s Alenou Starečkovou"
             src="/images/historie/adam_alena.jpg"
             class="block-center"
             style="height:200px" />
        <p>
            Velký úspěch zaznamenala juniorská družstva. Jak ve standardních,
            tak v latinskoamerických tancích, si naši junioři zatančili finále,
            v latinskoamerických tancích vybojovali bronzovou medaili!
        </p>
        <img alt="Mistrovství družstev 2010"
             src="/images/historie/druzstvo2010.jpg"
             class="block-center"
             style="222px" />

        <h2>2011</h2>
        <p>
            V roce 2011 jsme měli znovu zastoupení v semifinále Mistrovství
            České republiky deseti tanců, kategorie dospělých.  Nově složený
            pár Radim Stupka a Tereza Jendrulková obsadil deváté místo. Na
            stejné soutěži v kategorii junior 1 (do 13 let) se velkého úspěchu
            dočkali Dominik Homola a Mirka Uvízlová, když vybojovali své první
            republikové finále.
        </p>
        <p>
            Po pěti letech nás na Mistrovství České republiky družstev
            reprezentovalo standardní družstvo, které obsadilo 8. příčku
            (startovalo 18 družstev).
         </p>
        <p>Co bude dál?</p>
    </div>
</div>
