<div class="container">
  <style type="text/css">
   .mcr td {text-align:center;}
   .mcr td:last-child {text-align:left;}
   .st td {color:#EBBC00;font-weight:bold;}
   .nd td {color:#3366FF;font-weight:bold;}
   .rd td {color:#993300;font-weight:bold;}
   .fin td {font-weight:bold;}
   .st td:first-child, .nd td:first-child,
   .rd td:first-child, .fin td:first-child,
   .st td:first-child + td, .nd td:first-child + td,
   .rd td:first-child + td, .fin td:first-child + td {color:black;font-weight:normal;}
  </style>
  <table class="mcr">
    <col style="width:75px;" />
    <col style="width:65px;" />
    <col style="width:65px;" />
    <col style="width:300px;" />

    <tr>
      <td><h2>2011</h2></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><h3>10T</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr class="fin">
      <td></td>
      <td>Jun I</td>
      <td>6</td>
      <td>Dominik Homola - Mirka Uvízlová</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>9-10</td>
      <td>Radim Stupka - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>14-15</td>
      <td>*Adam Jendrulek - Alena Starečková</td>
    </tr>
    <tr>
      <td><h3>STT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun I</td>
      <td>12</td>
      <td>Dominik Homola - Mirka Uvízlová</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>19-20</td>
      <td>*Adam Jendrulek - Alena Starečková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>42-44</td>
      <td>Rudolf Stupka - Kristýna Hlavicová</td>
    </tr>
    <tr>
      <td><h3>LAT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun I</td>
      <td>18-20</td>
      <td>Dominik Homola - Mirka Uvízlová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>38-41</td>
      <td>Jiří Anderle - Veronika Chromcová</td>
    </tr>

    <tr>
      <td><h2>2010</h2></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><h3>10T</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun I</td>
      <td>10</td>
      <td>Dominik Homola - Mirka Uvízlová</td>
    </tr>
    <tr>
      <td></td>
      <td>Jun II</td>
      <td>17</td>
      <td>Jakub Zárybnický - Marie Hýžová</td>
    </tr>
    <tr class="rd">
      <td></td>
      <td>Mládež</td>
      <td>3</td>
      <td>*Radim Stupka - Michaela Riedlová</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>11</td>
      <td>*Adam Jendrulek - Anna Starečková</td>
    </tr>
    <tr>
      <td><h3>STT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun I</td>
      <td>12</td>
      <td>Dominik Homola - Mirka Uvízlová</td>
    </tr>
    <tr>
      <td></td>
      <td>Jun II</td>
      <td>15-16</td>
      <td>Marek Švarc - Monika Vymětalová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>17</td>
      <td>Jakub Zárybnický - Marie Hýžová</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td>Mládež</td>
      <td>4</td>
      <td>*Radim Stupka - Michaela Riedlová</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>17</td>
      <td>*Adam Jendrulek - Alena Starečková</td>
    </tr>
    <tr>
      <td><h3>LAT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun I</td>
      <td>10-12</td>
      <td>Dominik Homola - Mirka Uvízlová</td>
    </tr>
    <tr>
      <td></td>
      <td>Jun II</td>
      <td>15</td>
      <td>Jakub Zárybnicky - Marie Hýžová</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td>Mládež</td>
      <td>5</td>
      <td>*Radim Stupka - Michaela Riedlová</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>34-35</td>
      <td>*Jan Kúla - Tereza Jendrulková</td>
    </tr>

    <tr>
      <td><h2>2009</h2></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><h3>10T</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun I</td>
      <td>14</td>
      <td>Jakub Zárybnický - Marie Hýžová</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td>Mládež</td>
      <td>5</td>
      <td>*Adam Jendrulek - Alena Starečková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>7</td>
      <td>Radim Stupka - Kristýna Hlavicová</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>11</td>
      <td>Miroslav Hýža - Kristýna Hudeová</td>
    </tr>
    <tr>
      <td><h3>STT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun I</td>
      <td>11</td>
      <td>Jakub Zárybnický - Marie Hýžová</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td>Mládež</td>
      <td>5</td>
      <td>Radim Stupka - Kristýna Hlavicová</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td></td>
      <td>6</td>
      <td>*Adam Jendrulek - Alena Starečková</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>15</td>
      <td>Miroslav Hýža - Kristýna Hudeová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>27</td>
      <td>*Adam Jendrulek - Alena Starečková</td>
    </tr>
    <tr>
      <td><h3>LAT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun I</td>
      <td>9</td>
      <td>Jakub Zárybnický - Marie Hýžová</td>
    </tr>
    <tr>
      <td></td>
      <td>Mládež</td>
      <td>12</td>
      <td>Radim Stupka - Kristýna Hlavicová</td>
    </tr>

    <tr>
      <td><h2>2008</h2></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><h3>10T</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr class="fin">
      <td></td>
      <td>Jun II</td>
      <td>4</td>
      <td>*Radim Stupka - Kristýna Hlavicová</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>12</td>
      <td>Miroslav Hýža - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td><h3>STT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun I</td>
      <td>8</td>
      <td>Jakub Brablec - Marie Hýžová</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td>Jun II</td>
      <td>6</td>
      <td>Radim Stupka - Kristýna Hlavicová</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>13-14</td>
      <td>Miroslav Hýža - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>17</td>
      <td>Jiří Pohlodek - Lucie Fojtíková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>34</td>
      <td>Adam Jendrulek - Lucie Benýšková</td>
    </tr>
    <tr>
      <td><h3>LAT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun I</td>
      <td>11</td>
      <td>Jakub Brablec - Marie Hýžová</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td>Jun II</td>
      <td>6</td>
      <td>Radim Stupka - Kristýna Hlavicová</td>
    </tr>

    <tr>
      <td><h2>2007</h2></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><h3>10T</h3></td>
      <td></td>
      <td></td>
      <td></td>
      <!-- http://web.archive.org/web/20091212143513im_/http://tkolymp.cz/AKCE/06_Mistrovstv%C3%AD%20%C4%8CR/IMG_1216.jpg -->
    </tr>
    <tr>
      <td></td>
      <td>Jun II</td>
      <td>22</td>
      <td>Radim Stupka - Kristýna Hlavicová</td>
    </tr>
    <tr>
      <td><h3>STT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>11</td>
      <td>Radim Stupka - Kristýna Hlavicová</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>14</td>
      <td>Miroslav Hýža - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>17</td>
      <td>Pavel John - Markéta Vlčková</td>
    </tr>
    <tr>
      <td><h3>LAT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun II</td>
      <td>12</td>
      <td>Radim Stupka - Kristýna Hlavicová</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>13</td>
      <td>*Martin Kordek - Michaela Gatěková</td>
    </tr>

    <tr>
      <td><h2>2006</h2></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><h3>10T</h3></td>
      <td></td>
      <td></td>
      <td></td>
      <!-- http://web.archive.org/web/20091212143513im_/http://tkolymp.cz/AKCE/06_Mistrovstv%C3%AD%20%C4%8CR/nova%202.jpg -->
    </tr>
    <tr class="rd">
      <td></td>
      <td>Jun II</td>
      <td>3</td>
      <td>*Adam Jendrulek - Kateřina Přibylová</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td>Mládež</td>
      <td>5</td>
      <td>Miroslav Hýža – Lucie Benýšková</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td>Dospělí</td>
      <td>4</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>11</td>
      <td>Miroslav Hýža - Lucie Benýšková</td>
    </tr>
    <tr>
      <td><h3>STT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr class="rd">
      <td></td>
      <td>Jun II</td>
      <td>3</td>
      <td>*Adam Jendrulek - Kateřina Přibylová</td>
    </tr>
    <tr class="rd">
      <td></td>
      <td>Mládež</td>
      <td>3</td>
      <td>Miroslav Hýža - Lucie Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>25-26</td>
      <td>Tomáš Hroch – Vendula Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>10</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>13</td>
      <td>Miroslav Hýža - Lucie Benýšková</td>
    </tr>
    <tr>
      <td><h3>LAT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun I</td>
      <td>10-11</td>
      <td>Radim Stupka - Kristýna Hlavicová</td>
    </tr>
    <tr>
      <td></td>
      <td>Jun II</td>
      <td>16-17</td>
      <td>*Adam Jendrulek - Kateřina Přibylová</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>12</td>
      <td>*Martin Kordek - Michaela Gatěková</td>
    </tr>

    <tr>
      <td><h2>2005</h2></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><h3>10T</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr class="rd">
      <td></td>
      <td>Mládež</td>
      <td>3</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td></td>
      <td>5</td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td></td>
      <td>6</td>
      <td>Miroslav Hýža – Denisa Walterová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>18</td>
      <td>Tomáš Hroch – Veronika Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>7</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td><h3>STT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun II</td>
      <td>12</td>
      <td>Adam Jendrulek - Vendula Benýšková</td>
      <!-- p://web.archive.org/web/20091212143513im_/http://tkolymp.cz/AKCE/06_Mistrovstv%C3%AD%20%C4%8CR/nova%204.JPG -->
    </tr>
    <tr class="rd">
      <td></td>
      <td>Mládež</td>
      <td>3</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>13</td>
      <td>Tomáš Hroch – Veronika Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>31-33</td>
      <td>Michal Zlámal - Lucie Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>8-9</td>
      <td>Radim Kotrba – Markéta Vlčková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>10-11</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td><h3>LAT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Mládež</td>
      <td>13</td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>17</td>
      <td>Martin Kordek - Jitka Szabó</td>
    </tr>

    <tr>
      <td><h2>2004</h2></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><h3>10T</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun I</td>
      <td>7</td>
      <td>Adam Jendrulek - Vendula Benýšková</td>
    </tr>
    <tr class="nd">
      <td></td>
      <td>Mládež</td>
      <td>2</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>7</td>
      <td>Miroslav Hýža – Denisa Walterová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>8-9</td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>7</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td><h3>STT</h3></td>
      <td></td>
      <td></td>
      <td></td>
      <!-- http://web.archive.org/web/20091212143513im_/http://tkolymp.cz/AKCE/06_Mistrovstv%C3%AD%20%C4%8CR/xxxxxxx.jpg -->
    </tr>
    <tr class="rd">
      <td></td>
      <td>Jun I</td>
      <td>3</td>
      <td>Adam Jendrulek - Vendula Benýšková</td>
    </tr>
    <tr class="nd">
      <td></td>
      <td>Mládež</td>
      <td>2</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr class="rd">
      <td></td>
      <td></td>
      <td>3</td>
      <td>Radim Kotrba – Markéta Vlčková</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td></td>
      <td>5</td>
      <td>Miroslav Hýža – Denisa Walterová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>12</td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>17-18</td>
      <td>Tomáš Hroch – Veronika Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>8</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>16-17</td>
      <td>Radim Kotrba – Markéta Vlčková</td>
    </tr>
    <tr>
      <td><h3>LAT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun I</td>
      <td>7</td>
      <td>Adam Jendrulek - Vendula Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td>Mládež</td>
      <td>10-11</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>18</td>
      <td>Miroslav Hýža – Denisa Walterová</td>
      <!-- http://web.archive.org/web/20091212143513im_/http://tkolymp.cz/AKCE/06_Mistrovstv%C3%AD%20%C4%8CR/nova.JPG -->
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>24</td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>28</td>
      <td>Martin Kordek – Jitka Szabová</td>
    </tr>

    <tr>
      <td><h2>2003</h2></td>
      <td></td>
      <td></td>
      <td></td>
      <!-- http://web.archive.org/web/20091212143513im_/http://tkolymp.cz/AKCE/06_Mistrovstv%C3%AD%20%C4%8CR/P1010005.JPG -->
    </tr>
    <tr>
      <td><h3>10T</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun I</td>
      <td>7</td>
      <td>Adam Jendrulek - Vendula Benýšková</td>
    </tr>
    <tr class="nd">
      <td></td>
      <td>Jun II</td>
      <td>2</td>
      <td>Miroslav Hýža – Denisa Walterová</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td>Mládež</td>
      <td>4</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>9</td>
      <td>Radim Kotrba – Markéta Vlčková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>13</td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>17-18</td>
      <td>Pavel John - Kristýna Coufalová</td>
    </tr>
    <tr>
      <td><h3>STT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun I</td>
      <td>7</td>
      <td>Adam Jendrulek - Vendula Benýšková</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td>Jun II</td>
      <td>4</td>
      <td>Miroslav Hýža – Denisa Walterová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>32</td>
      <td>Pavel Skála - Kateřina Kratochvílová</td>
    </tr>
    <tr>
      <td></td>
      <td>Mládež</td>
      <td>7</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>9</td>
      <td>Radim Kotrba – Markéta Vlčková</td>
      <!-- http://web.archive.org/web/20091212143513im_/http://tkolymp.cz/AKCE/06_Mistrovstv%C3%AD%20%C4%8CR/P1010007.JPG -->
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>15</td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>24</td>
      <td>Tomáš Hroch - Veronika Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>25</td>
      <td>Pavel Řehulka - Jana Safernová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>30</td>
      <td>Tomáš Perlovský - Anita Šmídová</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>22</td>
      <td>Radim Kotrba – Markéta Vlčková</td>
    </tr>
    <tr>
      <td><h3>LAT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun I</td>
      <td>12</td>
      <td>Adam Jendrulek - Vendula Benýšková</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td>Jun II</td>
      <td>6</td>
      <td>Miroslav Hýža – Denisa Walterová</td>
    </tr>
    <tr>
      <td></td>
      <td>Mládež</td>
      <td>25-26</td>
      <td>Pavel John - Kristýna Coufalová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>30</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>31-33</td>
      <td>Radim Kotrba – Markéta Vlčková</td>
      <!-- http://web.archive.org/web/20091212143513im_/http://tkolymp.cz/AKCE/06_Mistrovstv%C3%AD%20%C4%8CR/nova%205.JPG -->
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>43-44</td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr>
      <td></td>
      <td>Dospělí</td>
      <td>43-46</td>
      <td>Martin Kordek - Jitka Szabová</td>
    </tr>

    <tr>
      <td><h2>2002</h2></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><h3>10T</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr class="rd">
      <td></td>
      <td>Jun II</td>
      <td>3</td>
      <td>Miroslav Hýža – Denisa Walterová</td>
      <!-- http://web.archive.org/web/20091212143513im_/http://tkolymp.cz/AKCE/06_Mistrovstv%C3%AD%20%C4%8CR/P1010003.JPG -->
    </tr>
    <tr class="fin">
      <td></td>
      <td></td>
      <td>5</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>7</td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>12</td>
      <td>Tomáš Hroch – Veronika Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td>Mládež</td>
      <td>12</td>
      <td>Radim Kotrba – Markéta Vlčková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>22-23</td>
      <td>Pavel John - Kristýna Coufalová</td>
    </tr>
    <tr>
      <td><h3>STT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr class="rd">
      <td></td>
      <td>Jun II</td>
      <td>3</td>
      <td>Miroslav Hýža – Denisa Walterová</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td></td>
      <td>4</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>7</td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>13</td>
      <td>Tomáš Hroch – Veronika Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td>Mládež</td>
      <td>10-11</td>
      <td>Radim Kotrba – Markéta Vlčková</td>
      <!-- http://web.archive.org/web/20091212143513im_/http://tkolymp.cz/AKCE/06_Mistrovstv%C3%AD%20%C4%8CR/nova%203.JPG -->
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>30</td>
      <td>Tomáš Perlovský - Anita Šmídová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>31-32</td>
      <td>Pavel John - Kristýna Coufalová</td>
    </tr>
    <tr>
      <td><h3>LAT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>Jun II</td>
      <td>10</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>11</td>
      <td>Miroslav Hýža – Denisa Walterová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>21</td>
      <td>Petr Pohlodek - Petra Gromesová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>25</td>
      <td>Tomáš Hroch – Veronika Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td>Mládež</td>
      <td>33-34</td>
      <td>Pavel John - Kristýna Coufalová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>36-37</td>
      <td>Radim Kotrba – Markéta Vlčková</td>
    </tr>

    <tr>
      <td><h2>2001</h2></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><h3>10T</h3></td>
      <td></td>
      <td></td>
      <td></td>
      <!-- http://web.archive.org/web/20091212143513im_/http://tkolymp.cz/AKCE/06_Mistrovstv%C3%AD%20%C4%8CR/P1010009.JPG -->
    </tr>
    <tr class="st">
      <td></td>
      <td>Jun I</td>
      <td>1</td>
      <td>Miroslav Hýža – Denisa Walterová</td>
    </tr>
    <tr class="rd">
      <td></td>
      <td></td>
      <td>3</td>
      <td>Pavel Skála - Petra Gromesová</td>
    </tr>
    <tr>
      <td></td>
      <td>Jun II</td>
      <td>8</td>
      <td>Jan Matoušek - Vendula Vojáková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>13-14</td>
      <td>Tomáš Hroch – Veronika Benýšková</td>
    </tr>
    <tr>
      <td><h3>STT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr class="st">
      <td></td>
      <td>Jun I</td>
      <td>1</td>
      <td>Miroslav Hýža – Denisa Walterová</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td></td>
      <td>6</td>
      <td>Pavel Skála - Petra Gromesová</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td>Jun II</td>
      <td>5</td>
      <td>Radim Kotrba – Markéta Vlčková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>8</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>11-12</td>
      <td>Tomáš Hroch – Veronika Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>23-26</td>
      <td>Jiří Mišák - Nikol Nezvalová</td>
      <!-- http://web.archive.org/web/20091212143513im_/http://tkolymp.cz/AKCE/06_Mistrovstv%C3%AD%20%C4%8CR/P1010006.JPG -->
    </tr>
    <tr>
      <td><h3>LAT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr class="st">
      <td></td>
      <td>Jun I</td>
      <td>1</td>
      <td>Miroslav Hýža – Denisa Walterová</td>
    </tr>
    <tr class="rd">
      <td></td>
      <td></td>
      <td>3</td>
      <td>Pavel Skála - Petra Gromesová</td>
    </tr>
    <tr>
      <td></td>
      <td>Jun II</td>
      <td>10</td>
      <td>Radim Kotrba – Markéta Vlčková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>19-20</td>
      <td>Jan Matoušek - Vendula Vojáková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>30</td>
      <td>Tomáš Hroch – Veronika Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>31-32</td>
      <td>Pavel John - Tereza Jendrulková</td>
    </tr>

    <tr>
      <td><h2>2000</h2></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><h3>10T</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr class="rd">
      <td></td>
      <td>Jun I</td>
      <td>3</td>
      <td>Miroslav Hýža – Denisa Walterová</td>
      <!-- http://web.archive.org/web/20091212143513im_/http://tkolymp.cz/AKCE/06_Mistrovstv%C3%AD%20%C4%8CR/P1100021.JPG -->
    </tr>
    <tr class="fin">
      <td></td>
      <td></td>
      <td>5</td>
      <td>Tomáš Hroch – Veronika Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>15</td>
      <td>Pavel John - Anita Šmídová</td>
    </tr>
    <tr class="rd">
      <td></td>
      <td>Jun II</td>
      <td>3</td>
      <td>Martin Kordek – Tereza Jendrulková</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td></td>
      <td>6</td>
      <td>Radim Kotrba – Markéta Vlčková</td>
    </tr>
    <tr>
      <td><h3>STT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr class="rd">
      <td></td>
      <td>Jun I</td>
      <td>3</td>
      <td>Miroslav Hýža – Denisa Walterová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>8-10</td>
      <td>Tomáš Hroch – Veronika Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>17-18</td>
      <td>Pavel John - Anita Šmídová</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td>Jun II</td>
      <td>5</td>
      <td>Radim Kotrba – Markéta Vlčková</td>
    </tr>
    <tr class="fin">
      <td></td>
      <td></td>
      <td>6</td>
      <td>Martin Kordek – Tereza Jendrulková</td>
      <!-- http://web.archive.org/web/20091212143513im_/http://tkolymp.cz/AKCE/06_Mistrovstv%C3%AD%20%C4%8CR/P1010010.JPG -->
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>23-24</td>
      <td>Pavel Řehulka - Jana Safernová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>28-29</td>
      <td>Jiří Řehulka - Kateřina Pabišková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>35</td>
      <td>Jiří Mišák - Nikol Nezvalová</td>
    </tr>
    <tr>
      <td><h3>LAT</h3></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr class="fin">
      <td></td>
      <td>Jun I</td>
      <td>4</td>
      <td>Miroslav Hýža – Denisa Walterová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>9</td>
      <td>Pavel John - Anita Šmídová</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>13</td>
      <td>Tomáš Hroch – Veronika Benýšková</td>
    </tr>
    <tr>
      <td></td>
      <td>Jun II</td>
      <td>7-8</td>
      <td>Radim Kotrba – Markéta Vlčková</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>9</td>
      <td>Martin Kordek – Tereza Jendrulková</td>
    </tr>
  </table>
  <br/>
  Páry označené * jsou složené z různých klubů, ale jeden člen byl právoplatným členem TK Olymp Olomouc
</div>
