<div class="container">
  <div class="row">
    <div class="col-12 col-md-6">
      <p>
        <h2>Fakultní základní škola Holečkova</h2>
        Holečkova 10, Olomouc<br/>
        <a href="http://www.zsholeckova.cz/">http://www.zsholeckova.cz/</a>
      </p>
      <div id="holeckova" style="height:300px;margin-bottom:2rem"></div>
    </div>

    <div class="col-12 col-md-6">
      <p>
        <h2>Slovanské gymnázium Olomouc</h2>
        Jiřího z Poděbrad 13, Olomouc<br/>
        <a href="http://www.sgo.cz/">http://www.sgo.cz/</a>
      </p>
      <div id="slovan" style="height:300px;margin-bottom:2rem"></div>
    </div>
  </div>
</div>
