<?= $this->header('Kde trénujeme') ?>

<div class="container">
  <p>
    <h2>Fakultní základní škola Holečkova</h2>
    Holečkova 10, Olomouc<br/>
    <a href="http://www.zsholeckova.cz/">http://www.zsholeckova.cz/</a>
  </p>
  <div id="holeckova" style="height:300px;margin-bottom:2rem"></div>

  <div class="row">
    <div class="col-md-6">
        <p class="text-center">
          <img alt="baletní sál" src="/images/trenujeme/baletak.jpg" style="height:300px;" />
        </p>
    </div>
    <div class="col-md-6">
      <p class="text-center">
        <img alt="ZŠ Holečkova" src="/images/trenujeme/holeckova.jpg" style="height:300px;" />
      </p>
    </div>
  </div>

  <p>
    <h2>Slovanské gymnázium Olomouc</h2>
    Jiřího z Poděbrad 13, Olomouc<br/>
    <a href="http://www.sgo.cz/">http://www.sgo.cz/</a>
  </p>
  <div id="slovan" style="height:300px;margin-bottom:2rem"></div>

  <div class="row">
    <div class="col-md-6">
      <p class="text-center">
        <img alt="Slovanské gymnázium" src="/images/trenujeme/sgo.jpg" style="height:300px;">
      </p>
    </div>
    <div class="col-md-6">
      <p class="text-center">
        <img alt="Slovanské gymnázium" src="/images/trenujeme/sgo2.jpg" style="height:300px;">
      </p>
    </div>
  </div>
</div>
