<h1>Kluboví trenéři</h1>
<div style="margin-bottom:1.5em;">
<h2>Miroslav Hýža</h2>
<img alt="Miroslav Hýža" alt="" src="/images/treneri/mirek.jpg" class="f_doc_right" style="height:150px;"/>
<ul class="list">
<li>šéftrenér TK Olymp</li>
<li>aktivní tanečník, držitel mezinárodní třídy ve standardních tancích</li>
<li>semifinalista mistrovství ČR v deseti tancích</li>
<li>semifinalista mistrovství ČR ve standardních tancích</li>
<li>člen národního reprezentačního týmu České republiky</li>
<li>3x titul Mistr České republiky v kategorii junior</li>
<li>15x finalista mistrovství ČR juniorů a mládeže (9x medaile)</li>
<li>4x titul Mistr České republiky družstev </li>
<li>2. místo v Taneční lize (žebříček párů mezinárodní třídy)</li>
<li>finalista významných evropských soutěží (Linz, Ostrava, Bratislava, Brno)</li>
<li>akreditovaný trenér ČSTS 3. třídy</li>
<li>trenér finalistů mistrovství ČR juniorů</li>
</ul>
</div>
<div style="margin-bottom:3em;">
<img alt="Mgr. Marie Hýžová" src="/images/treneri/marie.jpg" class="f_doc_right" style="height:150px;" />
<h2>Mgr. Marie Hýžová</h2>
<ul class="list">
<li>dlouholetá tanečnice mezinárodní třídy</li>
<li>dlouholetá trenérka mládežnických přípravek na ZŠ Holečkova</li>
<li>absolventka kvalifikačního studia trenér a porotce 1. třídy
    na Fakultě tělesné kultury Univerzity Palackého v Olomouce</li>
<li>porotkyně první třídy</li>
</ul>
</div>
<div style="margin-bottom:1.5em;">
<img alt="Lucie Benýšková" src="/images/treneri/lucka.jpg" class="f_doc_right" style="height:150px;" />
<h2>Lucie Benýšková</h2>
<ul class="list">
<li>semifinalistka mistrovství ČR v deseti tancích</li>
<li>semifinalistka mistrovství ČR ve standardních tancích</li>
<li>členka národního reprezentačního týmu České republiky</li>
<li>3x finalistka mistrovství ČR juniorů a mládeže (1x medaile)</li>
<li>titul Mistr České republiky družstev</li>
<li>2. místo v Taneční lize (žebříček párů mezinárodní třídy)</li>
<li>finalistka významných evropských soutěží v kategorii mládež (Bratislava, Ostrava)</li>
<li>studentka Fakulty tělesné kultury na UP v Olomouci</li>
</ul>
</div>
<div style="margin-bottom:3em;">
<img alt="Kristýna Hlavicová" src="/images/treneri/kristina.jpg" class="f_doc_right" style="height:150px;"/>
<h2>Kristýna Hlavicová</h2>
<ul class="list">
<li>aktivní tanečnice, držitelka mezinárodní třídy ve standardních tancích</li>
<li>4x finalistka mistrovství ČR juniorů a mládeže </li>
<li>členka národního reprezentačního týmu České republiky</li>
<li>finalistka významných evropských soutěží (Maribor, Varazdn, Zagreb, Isola)</li>
<li>absolventka kvalifikačního studia pro porotce a trenéry 3. třídy tanečního sportu</li>
</ul>
</div>
<div style="margin-bottom:1.5em;">
<img alt="Tereza Jendrulková" src="/images/treneri/terka.jpg" class="f_doc_right" style="height:150px;"/>
<h2>Tereza Jendrulková</h2>
<ul class="list">
<li>aktivní tanečnice, držitelka mezinárodní třídy ve standardních a latinskoamerických tancích</li>
<li>finalistka mistrovství ČR v deseti tancích</li>
<li>semifinalistka mistrovství ČR ve standardních tancích</li>
<li>10x finalistka mistrovství ČR juniorů a mládeže (5x medaile)</li>
<li>členka národního reprezentačního týmu České republiky</li>
<li>4x titul Mistr České republiky družstev  </li>
<li>finalistka významných evropských soutěží v kategorii mládež (Berlín, Wels, Bratislava, Ostrava)</li>
<li>účastníce mistrovství světa do 18 let v deseti tancích (Tallin - Estonsko)</li>
</ul>
</div>
<div style="margin-bottom:1.5em;">
<img alt="Adam Jendrulek" src="/images/treneri/adam.jpg" class="f_doc_right" style="height:150px;"/>
<h2>Adam Jendrulek</h2>
<ul class="list">
<li>semifinalista mistrovství ČR v deseti tancích</li>
<li>čtvrtfinalista mistrovství ČR ve standardních tancích</li>
<li>6x finalista mistrovství ČR juniorů a mládeže (3x medaile)</li>
<li>člen národního reprezentačního týmu České republiky</li>
<li>finalista mistrovství ČR juniorů a mládeže</li>
<li>finalista významných evropských soutěží v kategorii mládež (Szeged, Oradea, Bratislava)</li>
<li>účastník mistrovství světa ve standardních tancích do 18 let (Lotyšsko - Riga)</li>
</ul>
</div>
<div style="margin-bottom:2em;">
<h2>Bc. Pavel John</h2>
<img alt="Bc. Pavel John" src="/images/treneri/pavel.jpg" class="f_doc_right" style="height:150px;"/>
<ul class="list">
<li>finalista mistrovství ČR v deseti tancích</li>
<li>semifinalista mistrovství ČR ve standardních tancích</li>
<li>člen národního reprezentačního týmu České republiky</li>
<li>8x finalista mistrovství ČR juniorů a mládeže (4x medaile)</li>
<li>4x titul Mistr České republiky družstev </li>
<li>finalista významných evropských soutěží v kategorii mládež (Berlín, Wels, Bratislava, Ostrava)</li>
<li>účastník mistrovství světa do 18 let v deseti tancích (Estonsko)</li>
<li>absolvent kvalifikačního studia pro porotce a trenéry 3. třídy tanečního sportu</li>
</ul>
</div>
<div style="margin-bottom:2.5em;">
<img alt="Radim Stupka" src="/images/treneri/radim.jpg" class="f_doc_right" style="height:150px;"/>
<h2>Radim Stupka</h2>
<ul class="list">
<li>aktivní tanečník, držitel mezinárodní třídy ve standardních i latinskoamerických tancích</li>
<li>semifinalista mistrovství ČR v deseti tancích</li>
<li>7x finále mistrovství ČR juniorů a mládeže (1x medaile)</li>
<li>člen národního reprezentačního týmu České republiky</li>
<li>finalista významných evropských soutěží (Maribor, Varazdn, Zagreb, Isola, Paříž)</li>
<li>absolvent kvalifikačního studia pro porotce a trenéry 3. třídy tanečního sportu</li>
</ul>
</div>
<div>
<img alt="Rudolf Stupka" src="/images/treneri/ruda2.jpg" class="f_doc_right" style="height:150px;"/>
<h2>Rudolf Stupka</h2>
<ul class="list">
<li>aktivní tanečník, držitel mezinárodní třídy ve standardních tancích</li>
<li>účastník mistrovství ČR ve standardních tancích</li>
<li>absolvent kvalifikačního studia pro porotce a trenéry 3. třídy tanečního sportu</li>
</ul>
</div>
