<?= $this->header('Kluboví trenéři') ?>

<div class="container full">
  <div style="margin-bottom:1.5em;">
    <h2>Miroslav Hýža</h2>
    <img alt="Miroslav Hýža" alt="" src="/images/treneri/mirek.jpg" class="f_doc_right" style="height:150px;"/>
    <ul class="list">
      <li>šéftrenér TK Olymp</li>
      <li>aktivní tanečník, držitel mezinárodní třídy ve standardních tancích</li>
      <li>semifinalista mistrovství ČR v deseti tancích</li>
      <li>semifinalista mistrovství ČR ve standardních tancích</li>
      <li>člen národního reprezentačního týmu České republiky</li>
      <li>3x titul Mistr České republiky v kategorii junior</li>
      <li>15x finalista mistrovství ČR juniorů a mládeže (9x medaile)</li>
      <li>4x titul Mistr České republiky družstev </li>
      <li>2. místo v Taneční lize (žebříček párů mezinárodní třídy)</li>
      <li>finalista významných evropských soutěží (Linz, Ostrava, Bratislava, Brno)</li>
      <li>akreditovaný trenér ČSTS 3. třídy</li>
      <li>trenér finalistů mistrovství ČR juniorů</li>
    </ul>
  </div>

  <div style="margin-bottom:3em;">
    <img alt="Mgr. Marie Hýžová" src="/images/treneri/marie.jpg" class="f_doc_right" style="height:150px;" />
    <h2>Mgr. Marie Hýžová</h2>
    <ul class="list">
      <li>dlouholetá tanečnice mezinárodní třídy</li>
      <li>dlouholetá trenérka mládežnických přípravek na ZŠ Holečkova</li>
      <li>absolventka kvalifikačního studia trenér a porotce 1. třídy
        na Fakultě tělesné kultury Univerzity Palackého v Olomouce</li>
      <li>porotkyně první třídy</li>
    </ul>
  </div>

  <div style="margin-bottom:1.5em;">
    <h2>Lucie Benýšková</h2>
    <img alt="Lucie Benýšková" src="/images/treneri/lucka.jpg" class="f_doc_right" style="height:150px;" />
    <ul class="list">
      <li>semifinalistka mistrovství ČR v deseti tancích</li>
      <li>semifinalistka mistrovství ČR ve standardních tancích</li>
      <li>členka národního reprezentačního týmu České republiky</li>
      <li>3x finalistka mistrovství ČR juniorů a mládeže (1x medaile)</li>
      <li>titul Mistr České republiky družstev</li>
      <li>2. místo v Taneční lize (žebříček párů mezinárodní třídy)</li>
      <li>finalistka významných evropských soutěží v kategorii mládež (Bratislava, Ostrava)</li>
      <li>studentka Fakulty tělesné kultury na UP v Olomouci</li>
    </ul>
  </div>
</div>
