<?= $this->header('Kluboví trenéři') ?>

<div class="container">
    <div style="margin-bottom:1.5em;">
        <h2>Mgr. Miroslav Hýža</h2>
        <img alt="Mgr. Miroslav Hýža" alt="" src="/images/treneri/mirek2.jpg" class="f_doc_right" style="height:150px;"/>
        <ul class="list">
            <li>šéftrenér TK Olymp</li>
            <li>trenér tří mistrů ČR</li>
            <li>absolvent kvalifikačního studia pro trenéry a porotce II. třídy</li>
            <li>titul Vicemistr ČR ve standardních tancích v hlavní kategorii 2018</li>
            <li>3x titul Mistr ČR v kategorii junior</li>
            <li>finalista Akademického mistrovství Evropy 2016</li>
            <li>držitel ocenění TOP 30 sportovních trenérů mládeže 2017</li>
        </ul>
    </div>

    <div style="margin-bottom:2em;">
        <h2>Ing. Filip Karásek</h2>
        <img alt="Ing. Filip Karásek" src="/images/treneri/filip.jpg" class="f_doc_right" style="height:150px;" />
        <ul class="list">
            <li>absolvent kvalifikačního studia pro trenéry a porotce II. třídy</li>
            <li>2x titul mistr ČR v latinsko-amerických tancích v kategorii profesionálů</li>
            <li>3x titul mistr ČR v latinsko-amerických tancích v hlavní kategorii</li>
            <li>semifinalista mistrovství světa a Evropy v kategorii profesionálů</li>
            <li>semifinalista mistroství Evropy v hlavní kategorii</li>
            <li>čtvrtfinalista mistrovství světa v hlavní kategorii</li>
            <li>finalista GOC ve Stuttgartu kategorii profesionálů</li>
            <li>semifinalista Světových her v Kolumbii</li>
            <li>předseda Komise sportovců (od r. 2017)</li>
        </ul>
    </div>

    <div style="margin-bottom:3em;">
        <img alt="Mgr. Marie Hýžová" src="/images/treneri/marie2.jpg" class="f_doc_right" style="height:150px;" />
        <h2>Mgr. Marie Hýžová</h2>
        <ul class="list">
            <li>absolventka kvalifikačního studia trenér a porotce I. třídy na
                Fakultě tělesné kultury UP v Olomouci
            </li>
            <li>dlouholetá tanečnice mezinárodní třídy</li>
            <li>zkušená trenérka dětských a juniorských přípravek</li>
            <li>švadlena tanečního oblečení (řadu let šatí finalisty i medailisty mistrovství ČR)</li>
        </ul>
    </div>

    <div style="margin-bottom:2em;">
        <h2>Mgr. Lucie Benýšková</h2>
        <img alt="Mgr. Lucie Benýšková" src="/images/treneri/lucka3.jpg" class="f_doc_right" style="height:150px;" />
        <ul class="list">
            <li>absolventka kvalifikačního studia pro trenéry a porotce II. třídy</li>
            <li>semifinalistka mistrovství ČR v hlavní kategorii (v deseti tancích a ve standardních tancích)</li>
            <li>
                3x finalistka mistrovství ČR juniorů a mládeže (titul druhý
                vicemistr ČR ve standardních tancích v kategorii mládež)
            </li>
            <li>titul mistr ČR družstev v hlavní kategorii</li>
            <li>2. místo v Taneční lize (žebříček párů mezinárodní třídy)</li>
            <li>trenérka dětských a juniorských přípravek (11 let praxe)</li>
            <li>trenérka finalistů mistrovství ČR juniorů</li>
            <li>absolventka Fakulty tělesné kultury na UP v Olomouci (obor: Tělesná výchova a sport – Biologie)</li>
        </ul>
    </div>

    <div style="margin-bottom:3em;">
        <img alt="Pavel Grepl" src="/images/treneri/pavel2.jpg" class="f_doc_right" style="height:150px;" />
        <h2>Pavel Grepl</h2>
        <ul class="list">
            <li>absolvent kvalifikačního studia pro trenéry a porotce II. třídy</li>
            <li>tanečník mezinárodní třídy</li>
            <li>finalista Akademického mistrovství Evropy ve standardních tancích</li>
            <li>student Fakulty tělesné kultury na UP v Olomouci (obor: Trenérství a Sport) </li>
        </ul>
    </div>

    <div style="margin-bottom:3em;">
        <img alt="Marie Hýžová ml." src="/images/treneri/maruska.jpg" class="f_doc_right" style="height:150px;" />
        <h2>Marie Hýžová ml.</h2>
        <ul class="list">
            <li>absolventka kvalifikačního studia pro trenéry a porotce III. třídy</li>
            <li>finalistka mistrovství ČR v deseti tancích</li>
            <li>semifinalistka mistrovství ČR ve standardních tancích</li>
            <li>čtvrtfinalistka mistrovství ČR v latinsko-amerických tancích</li>
        </ul>
    </div>

    <div style="margin-bottom:2em;">
        <img alt="Matěj Očenášek" src="/images/treneri/matej.jpg" class="f_doc_right" style="height:120px;" />
        <h2>Matěj Očenášek</h2>
        <ul class="list">
            <li>absolvent kvalifikačního studia pro trenéry a porotce III. třídy</li>
            <li>tanečník mezinárodní třídy</li>
            <li>2x finalista mistrovství ČR mládeže</li>
            <li>
                3x finalista mistrovství ČR U21 (titul druhý vicemistr ČR
                v deseti tancích v kategorii U21)
            </li>
            <li>student VUT FEKT</li>
        </ul>
    </div>
</div>
