<?php
header_main('Úspěchy v číslech');
header_minor('Výsledky párů na soutěžích Mistrovství České republiky - kategorie junior a mládež');
?>
<span class="big">3</span> páry získaly titul Mistr České republiky<br/>
<span class="big">24</span> párů získalo medaili<br/>
<span class="big">53</span> párů tančilo finále<br/><br/>
<?php header_minor('Výsledky párů na soutěžích Mistrovství České republiky - kategorie dospělí');?>
<span class="big">1</span> pár tančil finále<br/>
<span class="big">13</span> párů tančilo semifinále<br/><br/>
<?php header_minor('Výsledky družstev na soutěžích Mistrovství České republiky družstev');?>
<span class="big">4</span> družstva získala titul Mistr České republiky<br/>
<span class="big">9</span> družstev získalo medaili<br/>
<span class="big">15</span> družstev tančilo finále<br/>