<?= $this->header('Úspěchy v číslech') ?>

<div class="container full">
  <h2>Mistrovství České republiky:</h2>
  <h3>kategorie junior a mládež</h3>
  <span class="big">3</span> páry získaly titul Mistr České republiky<br/>
  <span class="big">24</span> párů získalo medaili<br/>
  <span class="big">53</span> párů tančilo finále<br/><br/>
  <h3>kategorie dospělí</h3>
  <span class="big">1</span> pár tančil finále<br/>
  <span class="big">13</span> párů tančilo semifinále<br/><br/>
  <h3>Mistrovství České republiky družstev:</h3>
  <span class="big">4</span> družstva získala titul Mistr České republiky<br/>
  <span class="big">9</span> družstev získalo medaili<br/>
  <span class="big">15</span> družstev tančilo finále<br/>
</div>
