<div class="container">
    <style type="text/css">
     table.k {border:none;}
     table.k td {border:none;background:none;}
     table.k td.r {padding-right:10px;text-align:right;}
     table.k b {color:#333;}
    </style>
    <table class="k">
        <tr><td><h2>Taneční klub Olymp Olomouc</h2></td></tr>
        <tr>
            <td class="r">sídlo:</td>
            <td>Jiráskova 25, 77900, Olomouc</td>
        </tr>
        <tr>
            <td class="r">IČO:</td>
            <td>68347286</td>
        </tr>
        <tr>
            <td class="r">bankovní spojení:</td>
            <td>1806875329/0800</td>
        </tr>
        <tr><td><h3>Klubová rada</h3></td></tr>
        <tr>
            <td class="r"><b>Mgr. Miroslav Hýža</b></td>
            <td><b>předseda, šéftrenér</b></td>
        </tr>
        <tr>
            <td></td><td>kontaktní osoba pro vystoupení a soutěže a organizaci tréninků</td>
        </tr>
        <tr>
            <td class="r">mobil:</td>
            <td>737 545 525</td>
        </tr>
        <tr>
            <td class="r">email:</td>
            <td>hyzam(zavináč)seznam.cz</td>
        </tr>
        <tr><td>&nbsp;</td><td></td></tr>
        <tr>
            <td class="r"><b>Mgr. Marie Hýžová</b></td>
            <td><b>místopředseda</b></td>
        </tr>
        <tr>
            <td></td><td>kontaktní osoba pro dětské skupiny na ZŠ Holečkova</td>
        </tr>
        <tr>
            <td class="r">mobil:</td>
            <td>604 756 085</td>
        </tr>
        <tr>
            <td class="r">email:</td>
            <td>tkolymp(zavináč)tkolymp.cz</td>
        </tr>
        <tr><td>&nbsp;</td><td></td></tr>
        <tr>
            <td class="r"><b>Mgr. Lucie Benýšková</b></td>
            <td><b>vedoucí klubových agend</b></td>
        </tr>
        <tr>
            <td></td><td>kontaktní osoba pro nové zájemce a členské příspěvky</td>
        </tr>
        <tr>
            <td class="r">email:</td>
            <td>lucishek(zavinac)seznam.cz</td>
        </tr>
        <tr><td>&nbsp;</td><td></td></tr>
        <tr><td><h3>Dozorčí rada</h3></td></tr>
        <tr>
            <td class="r"><b>RNDr. Radim Slouka</b></td>
        </tr>
        <tr>
            <td class="r">mobil:</td>
            <td>774 731 282</td>
        </tr>
        <tr>
            <td class="r">email:</td>
            <td>slouka(zavináč)sgo.cz</td>
        </tr>
        <tr><td>&nbsp;</td><td></td></tr>
        <tr>
            <td class="r"><b>Martin Tonner</b></td>
        </tr>
        <tr>
            <td class="r">mobil:</td>
            <td>603 230 972</td>
        </tr>
        <tr>
            <td class="r">email:</td>
            <td>martin.to(zavináč)seznam.cz</td>
        </tr>
        <tr><td>&nbsp;</td><td></td></tr>
        <tr>
            <td class="r"><b>Vít Spurný</b></td>
        </tr>
        <tr>
            <td class="r">mobil:</td>
            <td>728 887 084</td>
        </tr>
        <tr>
            <td class="r">email:</td>
            <td>vit.spurny(zavináč)gmail.com</td>
        </tr>
    </table>
</div>
