<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>TK Olymp</title>
<style type="text/css">
<!--
body {
	font: 100%/1.3 Arial,Helvetica,sans-serif;
	background: #42413C;
	margin: 0;
	padding: 0;
	color: #000;
	background-color:#CCC;
}
h1, h2, h3, h4, h5, h6, p {
	margin-top: 0;
	padding-right: 15px;
	padding-left: 15px;
	background-color:#F00;
	color:#FFF;
	text-align: left;
}
a img {
	border: none;
}
a:link {
	color: #42413C;
	text-decoration: underline;
}
a:visited {
	color: #6E6C64;
	text-decoration: underline;
	width: 720px;
}
a:hover, a:active, a:focus {
	text-decoration: none;
}
.container {
	width: 720px;
	background:#F00;
	margin: 0 auto;
}
.header {
	border:solid #FFF;
	border-width: 0 0 thin 0;
}
.content {
	padding: 10px 0;
	border-bottom-width: thin;
	border-bottom-style: solid;
	border-bottom-color: #FFF;
	border-top-style: none;
}
.footer {
	padding: 10px 0;
	background-color: #990000;
	color:#FFFFFF;
	text-align:center;
}
.fltrt {
	float: right;
	margin-left: 8px;
}
.clearfloat {
	clear:both;
	height:0;
	font-size: 1px;
	line-height: 0px;
}
-->
</style></head>

<body>

<div class="container">
	<div class="header">
		<a href="/home">
			<img src="/images/nabor/header.png" alt="" width="721" height="360" align="middle" style="display:block;" />
			<img src="/images/nabor/banner.gif" alt="" width="721" height="88" align="middle" class="header" />
		</a> 
	</div>
	<div class="content">
		<p>Taneční klub Olymp Olomouc pořádá v rámci náboru nových členů </p>
		<h2>Ukázkový taneční trénink pro veřejnost </h2>
		<p class="fltrt">
			<img src="/images/nabor/DSC_0251.jpg" width="173" height="264" />
		</p>
		<p>Zváni jsou všichni žáci a studenti základních a středních škol. <br />
			Přijďte se podívat, jak vypadá taneční sport na tréninku, ukážeme Vám, jak tančí děti ve věku 6-11 let, junioři od 12 do 15 let, mládežníci od 16 do 18 let a dospělí. <br />
		</p>
		<p>U nás může tančit opravdu každý, v našem klubu máme bývalé výborné fotbalisty, rugbysty, hokejisty nebo profesionální vojáky. </p>
		<h2>Co Vám nabízíme: </h2>
		<p>Pololetní taneční kurz pro začátečníky a mírně pokročilé s možností zařadit se mezi sportovní tanečníky nebo pokračovat v tzv. hobby dancing.</p>
		<p class="fltrt">
			<img src="/images/nabor/latina3.jpg" width="173" height="258" />
		</p>
		<p>Tanec je párová disciplína, nejlepší je tedy přihlásit se s partnerem, ale pokud žádného nenajdete, nezoufejte a přijďte sami, třeba tu právě na Vás ideální protějšek čeká.</p>
		<p>	Náš taneční klub pro Vás připravil taneční tréninky 2x týdně se zkušenými tanečníky, navíc jednou týdně kondiční pohybovou průpravu a možnost vlastního procvičování v našich nových tréninkových prostorách. Naši trenéři pro Vás budou k dispozici i k individuálnímu tréninku podle Vašich představ. </p>
		<p>Cena pololetního kurzu je 1500 Kč, v ceně budou tři tréninky týdně + třídenní intenzivní soustředění s celodenní taneční náplní a vstupenka na prestižní soutěž v tanečním sportu - Taneční ligu, která se uskuteční 4. listopadu ve Slovanském domě v Olomouci. 
		</p>
		<p>Více na <a href="/home">www.tkolymp.cz</a>.</p>
		<h2>Kam přijít: </h2>
		<p class="fltrt">
			<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=cs&amp;geocode=&amp;q=Vlastiv%C4%9Bdn%C3%A9+muzeum+v+Olomouci,+n%C3%A1m%C4%9Bst%C3%AD+Republiky,+Olomouc,+%C4%8Cesk%C3%A1+republika&amp;aq=0&amp;oq=vlastivedne&amp;sll=37.0625,-95.677068&amp;sspn=46.543597,106.611328&amp;t=h&amp;ie=UTF8&amp;hq=Vlastiv%C4%9Bdn%C3%A9+muzeum&amp;hnear=n%C3%A1m%C4%9Bst%C3%AD+Republiky,+Olomouc,+%C4%8Cesk%C3%A1+republika&amp;cid=1548493467373770624&amp;ll=49.600169,17.259007&amp;spn=0.009735,0.018239&amp;z=15&amp;iwloc=A&amp;output=embed"></iframe><br />
			<small><a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=cs&amp;geocode=&amp;q=Vlastiv%C4%9Bdn%C3%A9+muzeum+v+Olomouci,+n%C3%A1m%C4%9Bst%C3%AD+Republiky,+Olomouc,+%C4%8Cesk%C3%A1+republika&amp;aq=0&amp;oq=vlastivedne&amp;sll=37.0625,-95.677068&amp;sspn=46.543597,106.611328&amp;t=h&amp;ie=UTF8&amp;hq=Vlastiv%C4%9Bdn%C3%A9+muzeum&amp;hnear=n%C3%A1m%C4%9Bst%C3%AD+Republiky,+Olomouc,+%C4%8Cesk%C3%A1+republika&amp;cid=1548493467373770624&amp;ll=49.600169,17.259007&amp;spn=0.009735,0.018239&amp;z=15&amp;iwloc=A" style="color:#0000FF;text-align:left">Zvětšit mapu</a></small>
		</p>
		<p><b>ve středu 17.října v 17:30</b></p>
		<p><b>do Vlastivědného muzea <br />
		(Náměstí republiky 5) <br />
		v Olomouci </b></p>
		<p>&nbsp;</p>
		<p><br /></p>
		<p><a href="http://www.tkolymp.cz/"><img src="/images/nabor/logo_stin.png" width="191" height="168" /></a></p>
	</div>
	<div class="footer">
		<strong>Těšíme se na Vás, Taneční klub Olymp Olomouc</strong>
	</div>
</div>
</body>
</html>
