fragment Article on Aktuality {
  __typename
  id
  atPreview
  atKdo
  atJmeno
  atText
  createdAt
  updatedAt
  titlePhotoUrl
  isVisible
  explicitAttachments: attachments(condition: {inline: false}) {
    nodes {
      file {
        ...File
      }
    }
  }
}

query Article($id: BigInt!) {
  aktuality(id: $id) {
    ...Article
  }
}

query Articles($first: Int, $offset: Int, $visibleOnly: Boolean) {
  aktualities(first: $first, offset: $offset, orderBy: [CREATED_AT_DESC], condition:  {
     isVisible: $visibleOnly
  }) {
    totalCount
    nodes {
      ...Article
    }
  }
}

mutation UpsertArticle($input: UpsertArticleInput!) {
  upsertArticle(input: $input) {
    aktuality {
      ...Article
    }
  }
}

mutation DeleteArticle($id: BigInt!) {
  deleteAktuality(input: {id: $id}) {
    __typename
  }
}
