fragment OutlineNode on DocumentNode {
  __typename
  id
  parentId
  ordering
  content
}

query TenantOutline {
  tenantDocument {
    id
    title
    version
  }
}

query Outline($root: UUID) {
  documentSubtreeList(root: $root) {
    ...OutlineNode
  }
}

query OutlineBreadcrumb($node: UUID!) {
  documentNodePathList(node: $node) {
    ...OutlineNode
  }
}

query OutlineMentions(
  $person: BigInt
  $couple: BigInt
  $cohort: BigInt
  $eventInstance: BigInt
  $eventSeries: BigInt
) {
  documentMentionsList(
    person: $person
    couple: $couple
    cohort: $cohort
    eventInstance: $eventInstance
    eventSeries: $eventSeries
  ) {
    ...OutlineNode
    ancestorsList {
      ...OutlineNode
    }
    subtreeList {
      ...OutlineNode
    }
  }
}

query TagDances {
  dancesList(orderBy: [NAME_ASC]) {
    code
    name
    discipline
  }
}

mutation SaveOutline($input: SaveOutlineInput!) {
  saveOutline(input: $input) {
    document {
      id
      version
    }
  }
}

mutation AddOutlineNode($input: AddOutlineNodeInput!) {
  addOutlineNode(input: $input) {
    documentNode {
      ...OutlineNode
    }
  }
}
