fragment DocumentNodeTag on DocumentNodeTag {
  __typename
  id
  personId
  coupleId
  cohortId
  eventInstanceId
  competitionId
  danceCode
  taggedMonth
  discipline
  person {
    id
    name
  }
  cohort {
    ...CohortBasic
  }
  couple {
    id
  }
}

fragment DocumentNode on DocumentNode {
  __typename
  id
  parentId
  ordering
  content
  tagsList {
    ...DocumentNodeTag
  }
}

fragment DocumentBasic on Document {
  __typename
  id
  kind
  title
  showToMembers
  updatedAt
}

fragment Document on Document {
  ...DocumentBasic
  eventInstanceId
  eventSeriesId
  cohortId
  nodesList(orderBy: [ORDERING_ASC]) {
    ...DocumentNode
  }
}

query Document($id: BigInt!) {
  document(id: $id) {
    ...Document
  }
}

query TagDances {
  dancesList(orderBy: [NAME_ASC]) {
    code
    name
    discipline
  }
}

mutation UpsertDocument($input: UpsertDocumentInput!) {
  upsertDocument(input: $input) {
    document {
      ...Document
    }
  }
}
