fragment EventConflict on EventConflict {
  overlapRange {
    start {
      value
    }
    end {
      value
    }
  }
  person {
    id
    name
  }
  first: firstInstance {
    ...EventWithTrainer
  }
  second: secondInstance {
    ...EventWithTrainer
  }
}

query EventConflictsReport($since: Datetime!, $until: Datetime) {
  attendeeConflicts: eventOverlapsAttendeeReportList(pSince: $since, pUntil: $until) {
    ...EventConflict
  }
  trainerConflicts: eventOverlapsTrainerReportList(pSince: $since, pUntil: $until) {
    ...EventConflict
  }
}
