
mutation CreateInvitation($input: CreatePersonInvitationInput!) {
  createPersonInvitation(input: $input) {
    personInvitation {
      id
      email
      createdAt
    }
  }
}

mutation DeleteInvitation($input: DeletePersonInvitationInput!) {
  deletePersonInvitation(input: $input) {
    __typename
  }
}

query InvitationOverview {
  users {
    nodes {
      id
      uEmail
    }
  }
  people(condition: { membership: {} }) {
    nodes {
      id
      name
      email
      createdAt
      userProxiesList(condition: { status: ACTIVE }) {
        id
      }
      personInvitationsList(condition: { usedAt: null }) {
        id
        createdAt
        accessToken
      }
    }
  }
}
