fragment Location on TenantLocation {
  id
  tenantId
  name
  longName
  description
  showInLists
  ordering
  latitude
  longitude
  coverImageId
  coverImage {
    ...File
  }
  imagesList {
    fileId
    file {
      ...File
    }
  }
  address {
    city
    conscriptionNumber
    district
    orientationNumber
    postalCode
    region
    street
  }
}

query LocationOptions {
  tenant: getCurrentTenant {
    id
    locationsList: tenantLocationsList(orderBy: [ORDERING_ASC, NAME_ASC, PRIMARY_KEY_ASC]) {
      id
      name
      showInLists
    }
  }
}

query PublicLocations {
  tenant: getCurrentTenant {
    id
    locationsList: tenantLocationsList(condition: { showInLists: true }, orderBy: [ORDERING_ASC, NAME_ASC, PRIMARY_KEY_ASC]) {
      ...Location
    }
  }
}

query Location($id: BigInt!) {
  location: tenantLocation(id: $id) {
    ...Location
  }
}

query LocationPage($id: BigInt!, $start: Datetime!) {
  location: tenantLocation(id: $id) {
    ...Location
    accessEventsList(first: 20, orderBy: OCCURRED_AT_DESC) {
      ...AccessEvent
    }
  }
  events: eventInstancesForRangeList(
    first: 10
    startRange: $start
    locationIds: [$id]
  ) {
    ...EventWithTrainer
  }
}

mutation UpsertLocation($input: UpsertLocationInput!) {
  upsertLocation(input: $input) {
    location {
      id
      tenantId
    }
  }
}
