query SystemAdminTenants {
  systemAdminTenants {
    nodes {
      id
      name
      bankAccount
      origins
      czIco
      czDic
      address {
        street
        conscriptionNumber
        orientationNumber
        district
        city
        region
        postalCode
      }
      settings
      membershipCount
      trainerCount
      administratorCount
      sessionCountLast30Days
      sessionCountPerTrainerLast30Days
    }
  }
}

mutation SystemAdminUpdateTenant($input: SystemAdminUpdateTenantInput!) {
  systemAdminUpdateTenant(input: $input) {
    tenant {
      id
      name
      bankAccount
      origins
      czIco
      czDic
      address {
        street
        conscriptionNumber
        orientationNumber
        district
        city
        region
        postalCode
      }
    }
  }
}
