fragment Tenant on Tenant {
  id
  name
  bankAccount
  czIco
  czDic
  description
  tenantAdministratorsList(condition: { status: ACTIVE }, orderBy: SINCE_ASC) {
    ...TenantAdministrator
  }
  tenantTrainersList(condition: { status: ACTIVE }, orderBy: SINCE_ASC) {
    ...TenantTrainer
  }
  tenantLocationsList {
    ...TenantLocation
  }
  cohortsList {
    id
    name
  }
  tenantMembershipsList(condition: { status: ACTIVE }) {
    ...TenantMembership
  }
  couplesList {
    ...Couple
  }
}

fragment TenantFull on Tenant {
  id
  name
  bankAccount
  origins
  czIco
  czDic
  description
  address {
    street
    conscriptionNumber
    orientationNumber
    district
    city
    region
    postalCode
  }
  tenantSetting {
    tenantId
    settings
  }
  memberships: tenantMemberships(condition: { status: ACTIVE }) {
    totalCount
  }
  trainers: tenantTrainers(condition: { status: ACTIVE }) {
    totalCount
  }
  administrators: tenantAdministrators(condition: { status: ACTIVE }) {
    totalCount
  }
}

query TenantsFull {
  tenantsList(orderBy: [NAME_ASC]) {
    ...TenantFull
  }
}

mutation ReplaceTenantSettings($tenantId: BigInt!, $settings: JSON!) {
  updateTenantSetting(input: { tenantId: $tenantId, patch: { settings: $settings } }) {
    tenantSetting {
      tenantId
      settings
    }
  }
}


fragment TenantLocation on TenantLocation {
  id
  name
  description
  isPublic
  address {
    city
    conscriptionNumber
    district
    orientationNumber
    postalCode
    region
    street
  }
}

query CurrentTenant {
  tenant: getCurrentTenant {
    ...Tenant
  }
}

mutation UpdateTenant($input: UpdateTenantInput!) {
  updateTenant(input: $input) {
    tenant {
      ...TenantFull
    }
  }
}

query TenantLocation($id: BigInt!) {
  tenantLocation(id: $id) {
    ...TenantLocation
  }
}

mutation UpdateTenantLocation($input: UpdateTenantLocationInput!) {
  updateTenantLocation(input: $input) {
    tenantLocation {
      ...TenantLocation
    }
  }
}

mutation CreateTenantLocation($input: CreateTenantLocationInput!) {
  createTenantLocation(input: $input) {
    tenantLocation {
      ...TenantLocation
    }
  }
}
