fragment LocationSummary on TenantLocation {
  id
  name
}

fragment TenantFull on Tenant {
  id
  name
  bankAccount
  origins
  czIco
  czDic
  description
  address {
    street
    conscriptionNumber
    orientationNumber
    district
    city
    region
    postalCode
  }
  tenantSetting {
    tenantId
    settings
  }
  memberships: tenantMemberships(condition: { status: ACTIVE }) {
    totalCount
  }
  trainers: tenantTrainers(condition: { status: ACTIVE }) {
    totalCount
  }
  administrators: tenantAdministrators(condition: { status: ACTIVE }) {
    totalCount
  }
}

query TenantsFull {
  tenantsList(orderBy: [NAME_ASC]) {
    ...TenantFull
  }
}

mutation ReplaceTenantSettings($tenantId: BigInt!, $settings: JSON!) {
  updateTenantSetting(input: { tenantId: $tenantId, patch: { settings: $settings } }) {
    tenantSetting {
      tenantId
      settings
    }
  }
}

query Club {
  tenant: getCurrentTenant {
    id
    description
    tenantAdministratorsList(condition: { status: ACTIVE }, orderBy: SINCE_ASC) {
      ...TenantAdministrator
    }
    tenantTrainersList(condition: { status: ACTIVE }, orderBy: SINCE_ASC) {
      ...TenantTrainer
    }
    locationsList: tenantLocationsList {
      ...LocationSummary
    }
  }
}

query TenantForm {
  tenant: getCurrentTenant {
    id
    name
    bankAccount
    description
  }
}

query TrainerOptions {
  tenant: getCurrentTenant {
    tenantTrainersList(condition: { status: ACTIVE }, orderBy: SINCE_ASC) {
      person {
        id
        name
        firstName
        lastName
      }
    }
  }
}

mutation UpdateTenant($input: UpdateTenantInput!) {
  updateTenant(input: $input) {
    tenant {
      ...TenantFull
    }
  }
}
