<form action="" method="post">
  <div id="userbox">
    <div id="userbox-inner">
      <input style="width:70px;" type="text" name="login" placeholder="Uživatel" autocomplete="username" />
      <input style="width:70px;" type="password" name="pass" placeholder="Heslo" autocomplete="current-password" /><br />
      <a href="/registrace">Registrace</a>&nbsp;
      <button type="submit">Přihlásit se</button>
    </div>
  </div>
</form>
