<h1>O klubu</h1>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TK Olymp Olomouc je tradiční taneční
klub zabývající se výchovou standardních a latinskoamerických
tanečníků. V novém tisíciletí patří mezi nejúspěšnější české kluby.
Naše páry pravidelně sbírají úspěchy v České republice i na
mezinárodním poli.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nabízíme atraktivní volnočasovou
aktivitu dětem, kvalitní zázemí sportovním tanečníkům a příjemné
prostředí pro všechny, co mají rádi tanec.</p>

<img alt="Mistrovství družstev 2010" src="/images/akce/druzstva2010_4.jpg" style="display:block;margin:20px auto;width:450px;" />
