/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	Query:{
		node:{

		},
		akces:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"AkcesOrderBy",
			condition:"AkceCondition"
		},
		akceItems:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"AkceItemsOrderBy",
			condition:"AkceItemCondition"
		},
		aktualities:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"AktualitiesOrderBy",
			condition:"AktualityCondition"
		},
		dokumenties:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"DokumentiesOrderBy",
			condition:"DokumentyCondition"
		},
		galerieDirs:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"GalerieDirsOrderBy",
			condition:"GalerieDirCondition"
		},
		galerieFotos:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"GalerieFotosOrderBy",
			condition:"GalerieFotoCondition"
		},
		members:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"MembersOrderBy",
			condition:"MemberCondition"
		},
		nabidkas:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"NabidkasOrderBy",
			condition:"NabidkaCondition"
		},
		nabidkaItems:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"NabidkaItemsOrderBy",
			condition:"NabidkaItemCondition"
		},
		pages:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"PagesOrderBy",
			condition:"PageCondition"
		},
		pageRevisions:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"PageRevisionsOrderBy",
			condition:"PageRevisionCondition"
		},
		parameters:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"ParametersOrderBy",
			condition:"ParameterCondition"
		},
		paries:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"PariesOrderBy",
			condition:"ParyCondition"
		},
		paryNavrhs:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"ParyNavrhsOrderBy",
			condition:"ParyNavrhCondition"
		},
		permissions:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"PermissionsOrderBy",
			condition:"PermissionCondition"
		},
		platbyCategories:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"PlatbyCategoriesOrderBy",
			condition:"PlatbyCategoryCondition"
		},
		platbyCategoryGroups:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"PlatbyCategoryGroupsOrderBy",
			condition:"PlatbyCategoryGroupCondition"
		},
		platbyGroups:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"PlatbyGroupsOrderBy",
			condition:"PlatbyGroupCondition"
		},
		platbyGroupSkupinas:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"PlatbyGroupSkupinasOrderBy",
			condition:"PlatbyGroupSkupinaCondition"
		},
		platbyItems:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"PlatbyItemsOrderBy",
			condition:"PlatbyItemCondition"
		},
		platbyRaws:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"PlatbyRawsOrderBy",
			condition:"PlatbyRawCondition"
		},
		rozpis:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"RozpisOrderBy",
			condition:"RozpiCondition"
		},
		rozpisItems:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"RozpisItemsOrderBy",
			condition:"RozpisItemCondition"
		},
		sessions:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"SessionsOrderBy",
			condition:"SessionCondition"
		},
		skupinies:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"SkupiniesOrderBy",
			condition:"SkupinyCondition"
		},
		upozornenis:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"UpozornenisOrderBy",
			condition:"UpozorneniCondition"
		},
		upozorneniSkupinies:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"UpozorneniSkupiniesOrderBy",
			condition:"UpozorneniSkupinyCondition"
		},
		users:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"UsersOrderBy",
			condition:"UserCondition"
		},
		usersSkupinies:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"UsersSkupiniesOrderBy",
			condition:"UsersSkupinyCondition"
		},
		videos:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"VideosOrderBy",
			condition:"VideoCondition"
		},
		videoLists:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"VideoListsOrderBy",
			condition:"VideoListCondition"
		},
		videoSources:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"VideoSourcesOrderBy",
			condition:"VideoSourceCondition"
		},
		akce:{
			aId:"BigInt"
		},
		akceItem:{
			aiId:"BigInt"
		},
		aktuality:{
			atId:"BigInt"
		},
		dokumenty:{
			dId:"BigInt"
		},
		galerieDir:{
			gdId:"BigInt"
		},
		galerieFoto:{
			gfId:"BigInt"
		},
		nabidka:{
			nId:"BigInt"
		},
		nabidkaItem:{
			niId:"BigInt"
		},
		page:{

		},
		pageByUrl:{

		},
		pageRevision:{

		},
		parameter:{

		},
		pary:{
			pId:"BigInt"
		},
		paryNavrh:{
			pnId:"BigInt"
		},
		permission:{
			peId:"BigInt"
		},
		platbyCategory:{
			pcId:"BigInt"
		},
		platbyCategoryGroup:{
			pcgId:"BigInt"
		},
		platbyGroup:{
			pgId:"BigInt"
		},
		platbyGroupSkupina:{
			pgsId:"BigInt"
		},
		platbyItem:{
			piId:"BigInt"
		},
		platbyRaw:{
			prId:"BigInt"
		},
		rozpi:{
			rId:"BigInt"
		},
		rozpisItem:{
			riId:"BigInt"
		},
		session:{

		},
		skupiny:{
			sId:"BigInt"
		},
		upozorneni:{
			upId:"BigInt"
		},
		upozorneniSkupiny:{
			upsId:"BigInt"
		},
		user:{
			uId:"BigInt"
		},
		usersSkupiny:{
			usId:"BigInt"
		},
		video:{
			vId:"BigInt"
		},
		videoList:{
			vlId:"BigInt"
		},
		videoSource:{
			vsId:"BigInt"
		},
		activeProspects:{
			before:"Cursor",
			after:"Cursor"
		},
		cohortMembers:{
			before:"Cursor",
			after:"Cursor"
		},
		currentCoupleIds:{
			before:"Cursor",
			after:"Cursor"
		},
		reservationsForRange:{
			startDate:"Date",
			endDate:"Date",
			before:"Cursor",
			after:"Cursor"
		},
		schedulesForRange:{
			startDate:"Date",
			endDate:"Date",
			before:"Cursor",
			after:"Cursor"
		},
		titleVideos:{
			before:"Cursor",
			after:"Cursor"
		},
		akceByNodeId:{

		},
		akceItemByNodeId:{

		},
		aktualityByNodeId:{

		},
		dokumentyByNodeId:{

		},
		galerieDirByNodeId:{

		},
		galerieFotoByNodeId:{

		},
		nabidkaByNodeId:{

		},
		nabidkaItemByNodeId:{

		},
		pageByNodeId:{

		},
		pageRevisionByNodeId:{

		},
		parameterByNodeId:{

		},
		paryByNodeId:{

		},
		paryNavrhByNodeId:{

		},
		permissionByNodeId:{

		},
		platbyCategoryByNodeId:{

		},
		platbyCategoryGroupByNodeId:{

		},
		platbyGroupByNodeId:{

		},
		platbyGroupSkupinaByNodeId:{

		},
		platbyItemByNodeId:{

		},
		platbyRawByNodeId:{

		},
		rozpiByNodeId:{

		},
		rozpisItemByNodeId:{

		},
		sessionByNodeId:{

		},
		skupinyByNodeId:{

		},
		upozorneniByNodeId:{

		},
		upozorneniSkupinyByNodeId:{

		},
		userByNodeId:{

		},
		usersSkupinyByNodeId:{

		},
		videoByNodeId:{

		},
		videoListByNodeId:{

		},
		videoSourceByNodeId:{

		}
	},
	Akce:{
		akceItemsByAiIdRodic:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"AkceItemsOrderBy",
			condition:"AkceItemCondition"
		}
	},
	BigInt: `scalar.BigInt` as const,
	Date: `scalar.Date` as const,
	Datetime: `scalar.Datetime` as const,
	User:{
		aktualitiesByAtKdo:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"AktualitiesOrderBy",
			condition:"AktualityCondition"
		},
		nabidkasByNTrener:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"NabidkasOrderBy",
			condition:"NabidkaCondition"
		},
		rozpisByRTrener:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"RozpisOrderBy",
			condition:"RozpiCondition"
		},
		platbyItemsByPiIdUser:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"PlatbyItemsOrderBy",
			condition:"PlatbyItemCondition"
		},
		pariesByPIdPartner:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"PariesOrderBy",
			condition:"ParyCondition"
		},
		sessionsBySsUser:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"SessionsOrderBy",
			condition:"SessionCondition"
		},
		akceItemsByAiUser:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"AkceItemsOrderBy",
			condition:"AkceItemCondition"
		},
		dokumentiesByDKdo:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"DokumentiesOrderBy",
			condition:"DokumentyCondition"
		},
		galerieFotosByGfKdo:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"GalerieFotosOrderBy",
			condition:"GalerieFotoCondition"
		},
		paryNavrhsByPnNavrhl:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"ParyNavrhsOrderBy",
			condition:"ParyNavrhCondition"
		},
		paryNavrhsByPnPartner:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"ParyNavrhsOrderBy",
			condition:"ParyNavrhCondition"
		},
		paryNavrhsByPnPartnerka:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"ParyNavrhsOrderBy",
			condition:"ParyNavrhCondition"
		},
		upozornenisByUpKdo:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"UpozornenisOrderBy",
			condition:"UpozorneniCondition"
		}
	},
	Permission:{
		usersByUGroup:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"UsersOrderBy",
			condition:"UserCondition"
		}
	},
	Cursor: `scalar.Cursor` as const,
	UsersOrderBy: "enum" as const,
	UserCondition:{
		uId:"BigInt",
		uNarozeni:"Date",
		uTimestamp:"Datetime",
		uGroup:"BigInt",
		uSkupina:"BigInt",
		uMemberSince:"Datetime",
		uMemberUntil:"Datetime",
		uCreatedAt:"Datetime",
		uGdprSignedAt:"Datetime"
	},
	Skupiny:{
		usersByUSkupina:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"UsersOrderBy",
			condition:"UserCondition"
		},
		platbyGroupSkupinasByPgsIdSkupina:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"PlatbyGroupSkupinasOrderBy",
			condition:"PlatbyGroupSkupinaCondition"
		},
		upozorneniSkupiniesByUpsIdSkupina:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"UpozorneniSkupiniesOrderBy",
			condition:"UpozorneniSkupinyCondition"
		}
	},
	PlatbyGroup:{
		platbyCategoryGroupsByPcgIdGroup:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"PlatbyCategoryGroupsOrderBy",
			condition:"PlatbyCategoryGroupCondition"
		},
		platbyGroupSkupinasByPgsIdGroup:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"PlatbyGroupSkupinasOrderBy",
			condition:"PlatbyGroupSkupinaCondition"
		}
	},
	BigFloat: `scalar.BigFloat` as const,
	PlatbyCategory:{
		platbyCategoryGroupsByPcgIdCategory:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"PlatbyCategoryGroupsOrderBy",
			condition:"PlatbyCategoryGroupCondition"
		},
		platbyItemsByPiIdCategory:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"PlatbyItemsOrderBy",
			condition:"PlatbyItemCondition"
		}
	},
	PlatbyCategoryGroupsOrderBy: "enum" as const,
	PlatbyCategoryGroupCondition:{
		pcgId:"BigInt",
		pcgIdGroup:"BigInt",
		pcgIdCategory:"BigInt"
	},
	PlatbyRaw:{
		platbyItemsByPiIdRaw:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"PlatbyItemsOrderBy",
			condition:"PlatbyItemCondition"
		}
	},
	PlatbyItemsOrderBy: "enum" as const,
	PlatbyItemCondition:{
		piId:"BigInt",
		piIdUser:"BigInt",
		piIdCategory:"BigInt",
		piIdRaw:"BigInt",
		piAmount:"BigFloat",
		piDate:"Date"
	},
	PlatbyGroupSkupinasOrderBy: "enum" as const,
	PlatbyGroupSkupinaCondition:{
		pgsId:"BigInt",
		pgsIdSkupina:"BigInt",
		pgsIdGroup:"BigInt"
	},
	Upozorneni:{
		upozorneniSkupiniesByUpsIdRodic:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"UpozorneniSkupiniesOrderBy",
			condition:"UpozorneniSkupinyCondition"
		}
	},
	UpozorneniSkupiniesOrderBy: "enum" as const,
	UpozorneniSkupinyCondition:{
		upsId:"BigInt",
		upsIdRodic:"BigInt",
		upsIdSkupina:"BigInt"
	},
	GalerieFoto:{
		aktualitiesByAtFotoMain:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"AktualitiesOrderBy",
			condition:"AktualityCondition"
		}
	},
	GalerieDir:{
		galerieFotosByGfIdRodic:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"GalerieFotosOrderBy",
			condition:"GalerieFotoCondition"
		}
	},
	GalerieFotosOrderBy: "enum" as const,
	GalerieFotoCondition:{
		gfId:"BigInt",
		gfIdRodic:"BigInt",
		gfKdo:"BigInt",
		gfTimestamp:"Datetime"
	},
	AktualitiesOrderBy: "enum" as const,
	AktualityCondition:{
		atId:"BigInt",
		atKdo:"BigInt",
		atFoto:"BigInt",
		atFotoMain:"BigInt",
		atTimestamp:"Datetime",
		atTimestampAdd:"Datetime"
	},
	Nabidka:{
		nabidkaItemsByNiIdRodic:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"NabidkaItemsOrderBy",
			condition:"NabidkaItemCondition"
		}
	},
	Pary:{
		nabidkaItemsByNiPartner:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"NabidkaItemsOrderBy",
			condition:"NabidkaItemCondition"
		},
		rozpisItemsByRiPartner:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"RozpisItemsOrderBy",
			condition:"RozpisItemCondition"
		}
	},
	ParyPSttTrida: "enum" as const,
	ParyPLatTrida: "enum" as const,
	NabidkaItemsOrderBy: "enum" as const,
	NabidkaItemCondition:{
		niId:"BigInt",
		niIdRodic:"BigInt",
		niPartner:"BigInt"
	},
	Time: `scalar.Time` as const,
	Rozpi:{
		rozpisItemsByRiIdRodic:{
			before:"Cursor",
			after:"Cursor",
			orderBy:"RozpisItemsOrderBy",
			condition:"RozpisItemCondition"
		}
	},
	RozpisItemsOrderBy: "enum" as const,
	RozpisItemCondition:{
		riId:"BigInt",
		riIdRodic:"BigInt",
		riPartner:"BigInt",
		riOd:"Time",
		riDo:"Time"
	},
	NabidkasOrderBy: "enum" as const,
	NabidkaCondition:{
		nId:"BigInt",
		nTrener:"BigInt",
		nMaxPocetHod:"BigInt",
		nOd:"Date",
		nDo:"Date",
		nTimestamp:"Datetime"
	},
	RozpisOrderBy: "enum" as const,
	RozpiCondition:{
		rId:"BigInt",
		rTrener:"BigInt",
		rDatum:"Date",
		rTimestamp:"Datetime"
	},
	PariesOrderBy: "enum" as const,
	ParyCondition:{
		pId:"BigInt",
		pIdPartner:"BigInt",
		pIdPartnerka:"BigInt",
		pSttTrida:"ParyPSttTrida",
		pLatTrida:"ParyPLatTrida",
		pTimestampAdd:"Datetime",
		pTimestampArchive:"Datetime"
	},
	SessionsOrderBy: "enum" as const,
	SessionCondition:{
		ssUpdatedAt:"Datetime",
		ssLifetime:"BigInt",
		ssUser:"BigInt"
	},
	AkceItemsOrderBy: "enum" as const,
	AkceItemCondition:{
		aiId:"BigInt",
		aiIdRodic:"BigInt",
		aiUser:"BigInt"
	},
	DokumentiesOrderBy: "enum" as const,
	DokumentyCondition:{
		dId:"BigInt",
		dKdo:"BigInt",
		dTimestamp:"Datetime"
	},
	ParyNavrhsOrderBy: "enum" as const,
	ParyNavrhCondition:{
		pnId:"BigInt",
		pnNavrhl:"BigInt",
		pnPartner:"BigInt",
		pnPartnerka:"BigInt"
	},
	UpozornenisOrderBy: "enum" as const,
	UpozorneniCondition:{
		upId:"BigInt",
		upKdo:"BigInt",
		upBarvy:"BigInt",
		upTimestamp:"Datetime",
		upTimestampAdd:"Datetime"
	},
	AkcesOrderBy: "enum" as const,
	AkceCondition:{
		aId:"BigInt",
		aOd:"Date",
		aDo:"Date",
		aKapacita:"BigInt",
		aTimestamp:"Datetime"
	},
	GalerieDirsOrderBy: "enum" as const,
	GalerieDirCondition:{
		gdId:"BigInt",
		gdIdRodic:"BigInt"
	},
	MembersOrderBy: "enum" as const,
	MemberCondition:{
		uId:"BigInt",
		uNarozeni:"Date",
		uTimestamp:"Datetime",
		uGroup:"BigInt",
		uSkupina:"BigInt",
		uMemberSince:"Datetime",
		uMemberUntil:"Datetime",
		uCreatedAt:"Datetime",
		uGdprSignedAt:"Datetime",
		sId:"BigInt"
	},
	JSON: `scalar.JSON` as const,
	PagesOrderBy: "enum" as const,
	PageCondition:{
		content:"JSON",
		createdAt:"Datetime",
		updatedAt:"Datetime"
	},
	PageRevisionsOrderBy: "enum" as const,
	PageRevisionCondition:{
		revTimestamp:"Datetime",
		content:"JSON",
		createdAt:"Datetime",
		updatedAt:"Datetime"
	},
	ParametersOrderBy: "enum" as const,
	ParameterCondition:{

	},
	PermissionsOrderBy: "enum" as const,
	PermissionCondition:{
		peId:"BigInt"
	},
	PlatbyCategoriesOrderBy: "enum" as const,
	PlatbyCategoryCondition:{
		pcId:"BigInt",
		pcSymbol:"BigInt",
		pcAmount:"BigFloat",
		pcDateDue:"Date",
		pcValidFrom:"Date",
		pcValidTo:"Date"
	},
	PlatbyGroupsOrderBy: "enum" as const,
	PlatbyGroupCondition:{
		pgId:"BigInt",
		pgType:"BigFloat",
		pgBase:"BigInt"
	},
	PlatbyRawsOrderBy: "enum" as const,
	PlatbyRawCondition:{
		prId:"BigInt"
	},
	SkupiniesOrderBy: "enum" as const,
	SkupinyCondition:{
		sId:"BigInt"
	},
	UsersSkupiniesOrderBy: "enum" as const,
	UsersSkupinyCondition:{
		usId:"BigInt",
		usPlatbaMesic:"BigInt",
		usPlatbaCtvrtrok:"BigInt",
		usPlatbaPulrok:"BigInt"
	},
	VideosOrderBy: "enum" as const,
	VideoCondition:{
		vId:"BigInt",
		vCreatedAt:"Datetime",
		vUpdatedAt:"Datetime"
	},
	VideoListsOrderBy: "enum" as const,
	VideoListCondition:{
		vlId:"BigInt",
		vlCount:"BigInt",
		vlCreatedAt:"Datetime",
		vlLastChecked:"Datetime"
	},
	VideoSourcesOrderBy: "enum" as const,
	VideoSourceCondition:{
		vsId:"BigInt",
		vsCreatedAt:"Datetime",
		vsLastChecked:"Datetime"
	},
	CrmCohort: "enum" as const,
	Mutation:{
		createAkce:{
			input:"CreateAkceInput"
		},
		createAkceItem:{
			input:"CreateAkceItemInput"
		},
		createAktuality:{
			input:"CreateAktualityInput"
		},
		createDokumenty:{
			input:"CreateDokumentyInput"
		},
		createGalerieDir:{
			input:"CreateGalerieDirInput"
		},
		createGalerieFoto:{
			input:"CreateGalerieFotoInput"
		},
		createNabidka:{
			input:"CreateNabidkaInput"
		},
		createNabidkaItem:{
			input:"CreateNabidkaItemInput"
		},
		createPage:{
			input:"CreatePageInput"
		},
		createParameter:{
			input:"CreateParameterInput"
		},
		createPary:{
			input:"CreateParyInput"
		},
		createParyNavrh:{
			input:"CreateParyNavrhInput"
		},
		createPermission:{
			input:"CreatePermissionInput"
		},
		createPlatbyCategory:{
			input:"CreatePlatbyCategoryInput"
		},
		createPlatbyCategoryGroup:{
			input:"CreatePlatbyCategoryGroupInput"
		},
		createPlatbyGroup:{
			input:"CreatePlatbyGroupInput"
		},
		createPlatbyGroupSkupina:{
			input:"CreatePlatbyGroupSkupinaInput"
		},
		createPlatbyItem:{
			input:"CreatePlatbyItemInput"
		},
		createPlatbyRaw:{
			input:"CreatePlatbyRawInput"
		},
		createRozpi:{
			input:"CreateRozpiInput"
		},
		createRozpisItem:{
			input:"CreateRozpisItemInput"
		},
		createSession:{
			input:"CreateSessionInput"
		},
		createSkupiny:{
			input:"CreateSkupinyInput"
		},
		createUpozorneni:{
			input:"CreateUpozorneniInput"
		},
		createUpozorneniSkupiny:{
			input:"CreateUpozorneniSkupinyInput"
		},
		createUser:{
			input:"CreateUserInput"
		},
		createUsersSkupiny:{
			input:"CreateUsersSkupinyInput"
		},
		createVideo:{
			input:"CreateVideoInput"
		},
		createVideoList:{
			input:"CreateVideoListInput"
		},
		createVideoSource:{
			input:"CreateVideoSourceInput"
		},
		updateAkceByNodeId:{
			input:"UpdateAkceByNodeIdInput"
		},
		updateAkce:{
			input:"UpdateAkceInput"
		},
		updateAkceItemByNodeId:{
			input:"UpdateAkceItemByNodeIdInput"
		},
		updateAkceItem:{
			input:"UpdateAkceItemInput"
		},
		updateAktualityByNodeId:{
			input:"UpdateAktualityByNodeIdInput"
		},
		updateAktuality:{
			input:"UpdateAktualityInput"
		},
		updateDokumentyByNodeId:{
			input:"UpdateDokumentyByNodeIdInput"
		},
		updateDokumenty:{
			input:"UpdateDokumentyInput"
		},
		updateGalerieDirByNodeId:{
			input:"UpdateGalerieDirByNodeIdInput"
		},
		updateGalerieDir:{
			input:"UpdateGalerieDirInput"
		},
		updateGalerieFotoByNodeId:{
			input:"UpdateGalerieFotoByNodeIdInput"
		},
		updateGalerieFoto:{
			input:"UpdateGalerieFotoInput"
		},
		updateNabidkaByNodeId:{
			input:"UpdateNabidkaByNodeIdInput"
		},
		updateNabidka:{
			input:"UpdateNabidkaInput"
		},
		updateNabidkaItemByNodeId:{
			input:"UpdateNabidkaItemByNodeIdInput"
		},
		updateNabidkaItem:{
			input:"UpdateNabidkaItemInput"
		},
		updatePageByNodeId:{
			input:"UpdatePageByNodeIdInput"
		},
		updatePage:{
			input:"UpdatePageInput"
		},
		updatePageByUrl:{
			input:"UpdatePageByUrlInput"
		},
		updateParameterByNodeId:{
			input:"UpdateParameterByNodeIdInput"
		},
		updateParameter:{
			input:"UpdateParameterInput"
		},
		updateParyByNodeId:{
			input:"UpdateParyByNodeIdInput"
		},
		updatePary:{
			input:"UpdateParyInput"
		},
		updateParyNavrhByNodeId:{
			input:"UpdateParyNavrhByNodeIdInput"
		},
		updateParyNavrh:{
			input:"UpdateParyNavrhInput"
		},
		updatePermissionByNodeId:{
			input:"UpdatePermissionByNodeIdInput"
		},
		updatePermission:{
			input:"UpdatePermissionInput"
		},
		updatePlatbyCategoryByNodeId:{
			input:"UpdatePlatbyCategoryByNodeIdInput"
		},
		updatePlatbyCategory:{
			input:"UpdatePlatbyCategoryInput"
		},
		updatePlatbyCategoryGroupByNodeId:{
			input:"UpdatePlatbyCategoryGroupByNodeIdInput"
		},
		updatePlatbyCategoryGroup:{
			input:"UpdatePlatbyCategoryGroupInput"
		},
		updatePlatbyGroupByNodeId:{
			input:"UpdatePlatbyGroupByNodeIdInput"
		},
		updatePlatbyGroup:{
			input:"UpdatePlatbyGroupInput"
		},
		updatePlatbyGroupSkupinaByNodeId:{
			input:"UpdatePlatbyGroupSkupinaByNodeIdInput"
		},
		updatePlatbyGroupSkupina:{
			input:"UpdatePlatbyGroupSkupinaInput"
		},
		updatePlatbyItemByNodeId:{
			input:"UpdatePlatbyItemByNodeIdInput"
		},
		updatePlatbyItem:{
			input:"UpdatePlatbyItemInput"
		},
		updatePlatbyRawByNodeId:{
			input:"UpdatePlatbyRawByNodeIdInput"
		},
		updatePlatbyRaw:{
			input:"UpdatePlatbyRawInput"
		},
		updateRozpiByNodeId:{
			input:"UpdateRozpiByNodeIdInput"
		},
		updateRozpi:{
			input:"UpdateRozpiInput"
		},
		updateRozpisItemByNodeId:{
			input:"UpdateRozpisItemByNodeIdInput"
		},
		updateRozpisItem:{
			input:"UpdateRozpisItemInput"
		},
		updateSessionByNodeId:{
			input:"UpdateSessionByNodeIdInput"
		},
		updateSession:{
			input:"UpdateSessionInput"
		},
		updateSkupinyByNodeId:{
			input:"UpdateSkupinyByNodeIdInput"
		},
		updateSkupiny:{
			input:"UpdateSkupinyInput"
		},
		updateUpozorneniByNodeId:{
			input:"UpdateUpozorneniByNodeIdInput"
		},
		updateUpozorneni:{
			input:"UpdateUpozorneniInput"
		},
		updateUpozorneniSkupinyByNodeId:{
			input:"UpdateUpozorneniSkupinyByNodeIdInput"
		},
		updateUpozorneniSkupiny:{
			input:"UpdateUpozorneniSkupinyInput"
		},
		updateUserByNodeId:{
			input:"UpdateUserByNodeIdInput"
		},
		updateUser:{
			input:"UpdateUserInput"
		},
		updateUsersSkupinyByNodeId:{
			input:"UpdateUsersSkupinyByNodeIdInput"
		},
		updateUsersSkupiny:{
			input:"UpdateUsersSkupinyInput"
		},
		updateVideoByNodeId:{
			input:"UpdateVideoByNodeIdInput"
		},
		updateVideo:{
			input:"UpdateVideoInput"
		},
		updateVideoListByNodeId:{
			input:"UpdateVideoListByNodeIdInput"
		},
		updateVideoList:{
			input:"UpdateVideoListInput"
		},
		updateVideoSourceByNodeId:{
			input:"UpdateVideoSourceByNodeIdInput"
		},
		updateVideoSource:{
			input:"UpdateVideoSourceInput"
		},
		deleteAkceByNodeId:{
			input:"DeleteAkceByNodeIdInput"
		},
		deleteAkce:{
			input:"DeleteAkceInput"
		},
		deleteAkceItemByNodeId:{
			input:"DeleteAkceItemByNodeIdInput"
		},
		deleteAkceItem:{
			input:"DeleteAkceItemInput"
		},
		deleteAktualityByNodeId:{
			input:"DeleteAktualityByNodeIdInput"
		},
		deleteAktuality:{
			input:"DeleteAktualityInput"
		},
		deleteDokumentyByNodeId:{
			input:"DeleteDokumentyByNodeIdInput"
		},
		deleteDokumenty:{
			input:"DeleteDokumentyInput"
		},
		deleteGalerieDirByNodeId:{
			input:"DeleteGalerieDirByNodeIdInput"
		},
		deleteGalerieDir:{
			input:"DeleteGalerieDirInput"
		},
		deleteGalerieFotoByNodeId:{
			input:"DeleteGalerieFotoByNodeIdInput"
		},
		deleteGalerieFoto:{
			input:"DeleteGalerieFotoInput"
		},
		deleteNabidkaByNodeId:{
			input:"DeleteNabidkaByNodeIdInput"
		},
		deleteNabidka:{
			input:"DeleteNabidkaInput"
		},
		deleteNabidkaItemByNodeId:{
			input:"DeleteNabidkaItemByNodeIdInput"
		},
		deleteNabidkaItem:{
			input:"DeleteNabidkaItemInput"
		},
		deleteParameterByNodeId:{
			input:"DeleteParameterByNodeIdInput"
		},
		deleteParameter:{
			input:"DeleteParameterInput"
		},
		deleteParyByNodeId:{
			input:"DeleteParyByNodeIdInput"
		},
		deletePary:{
			input:"DeleteParyInput"
		},
		deleteParyNavrhByNodeId:{
			input:"DeleteParyNavrhByNodeIdInput"
		},
		deleteParyNavrh:{
			input:"DeleteParyNavrhInput"
		},
		deletePermissionByNodeId:{
			input:"DeletePermissionByNodeIdInput"
		},
		deletePermission:{
			input:"DeletePermissionInput"
		},
		deletePlatbyCategoryByNodeId:{
			input:"DeletePlatbyCategoryByNodeIdInput"
		},
		deletePlatbyCategory:{
			input:"DeletePlatbyCategoryInput"
		},
		deletePlatbyCategoryGroupByNodeId:{
			input:"DeletePlatbyCategoryGroupByNodeIdInput"
		},
		deletePlatbyCategoryGroup:{
			input:"DeletePlatbyCategoryGroupInput"
		},
		deletePlatbyGroupByNodeId:{
			input:"DeletePlatbyGroupByNodeIdInput"
		},
		deletePlatbyGroup:{
			input:"DeletePlatbyGroupInput"
		},
		deletePlatbyGroupSkupinaByNodeId:{
			input:"DeletePlatbyGroupSkupinaByNodeIdInput"
		},
		deletePlatbyGroupSkupina:{
			input:"DeletePlatbyGroupSkupinaInput"
		},
		deletePlatbyItemByNodeId:{
			input:"DeletePlatbyItemByNodeIdInput"
		},
		deletePlatbyItem:{
			input:"DeletePlatbyItemInput"
		},
		deletePlatbyRawByNodeId:{
			input:"DeletePlatbyRawByNodeIdInput"
		},
		deletePlatbyRaw:{
			input:"DeletePlatbyRawInput"
		},
		deleteRozpiByNodeId:{
			input:"DeleteRozpiByNodeIdInput"
		},
		deleteRozpi:{
			input:"DeleteRozpiInput"
		},
		deleteRozpisItemByNodeId:{
			input:"DeleteRozpisItemByNodeIdInput"
		},
		deleteRozpisItem:{
			input:"DeleteRozpisItemInput"
		},
		deleteSessionByNodeId:{
			input:"DeleteSessionByNodeIdInput"
		},
		deleteSession:{
			input:"DeleteSessionInput"
		},
		deleteSkupinyByNodeId:{
			input:"DeleteSkupinyByNodeIdInput"
		},
		deleteSkupiny:{
			input:"DeleteSkupinyInput"
		},
		deleteUpozorneniByNodeId:{
			input:"DeleteUpozorneniByNodeIdInput"
		},
		deleteUpozorneni:{
			input:"DeleteUpozorneniInput"
		},
		deleteUpozorneniSkupinyByNodeId:{
			input:"DeleteUpozorneniSkupinyByNodeIdInput"
		},
		deleteUpozorneniSkupiny:{
			input:"DeleteUpozorneniSkupinyInput"
		},
		deleteUserByNodeId:{
			input:"DeleteUserByNodeIdInput"
		},
		deleteUser:{
			input:"DeleteUserInput"
		},
		deleteUsersSkupinyByNodeId:{
			input:"DeleteUsersSkupinyByNodeIdInput"
		},
		deleteUsersSkupiny:{
			input:"DeleteUsersSkupinyInput"
		},
		deleteVideoByNodeId:{
			input:"DeleteVideoByNodeIdInput"
		},
		deleteVideo:{
			input:"DeleteVideoInput"
		},
		deleteVideoListByNodeId:{
			input:"DeleteVideoListByNodeIdInput"
		},
		deleteVideoList:{
			input:"DeleteVideoListInput"
		},
		deleteVideoSourceByNodeId:{
			input:"DeleteVideoSourceByNodeIdInput"
		},
		deleteVideoSource:{
			input:"DeleteVideoSourceInput"
		},
		login:{
			input:"LoginInput"
		},
		logout:{
			input:"LogoutInput"
		},
		prospectFormDancer:{
			input:"ProspectFormDancerInput"
		},
		uploadFile:{
			input:"UploadInput"
		}
	},
	CreateAkcePayload:{
		akceEdge:{
			orderBy:"AkcesOrderBy"
		}
	},
	CreateAkceInput:{
		akce:"AkceInput"
	},
	AkceInput:{
		aId:"BigInt",
		aOd:"Date",
		aDo:"Date",
		aKapacita:"BigInt",
		aTimestamp:"Datetime"
	},
	CreateAkceItemPayload:{
		akceItemEdge:{
			orderBy:"AkceItemsOrderBy"
		}
	},
	CreateAkceItemInput:{
		akceItem:"AkceItemInput"
	},
	AkceItemInput:{
		aiId:"BigInt",
		aiIdRodic:"BigInt",
		aiUser:"BigInt"
	},
	CreateAktualityPayload:{
		aktualityEdge:{
			orderBy:"AktualitiesOrderBy"
		}
	},
	CreateAktualityInput:{
		aktuality:"AktualityInput"
	},
	AktualityInput:{
		atId:"BigInt",
		atKdo:"BigInt",
		atFoto:"BigInt",
		atFotoMain:"BigInt",
		atTimestamp:"Datetime",
		atTimestampAdd:"Datetime"
	},
	CreateDokumentyPayload:{
		dokumentyEdge:{
			orderBy:"DokumentiesOrderBy"
		}
	},
	CreateDokumentyInput:{
		dokumenty:"DokumentyInput"
	},
	DokumentyInput:{
		dId:"BigInt",
		dKdo:"BigInt",
		dTimestamp:"Datetime"
	},
	CreateGalerieDirPayload:{
		galerieDirEdge:{
			orderBy:"GalerieDirsOrderBy"
		}
	},
	CreateGalerieDirInput:{
		galerieDir:"GalerieDirInput"
	},
	GalerieDirInput:{
		gdId:"BigInt",
		gdIdRodic:"BigInt"
	},
	CreateGalerieFotoPayload:{
		galerieFotoEdge:{
			orderBy:"GalerieFotosOrderBy"
		}
	},
	CreateGalerieFotoInput:{
		galerieFoto:"GalerieFotoInput"
	},
	GalerieFotoInput:{
		gfId:"BigInt",
		gfIdRodic:"BigInt",
		gfKdo:"BigInt",
		gfTimestamp:"Datetime"
	},
	CreateNabidkaPayload:{
		nabidkaEdge:{
			orderBy:"NabidkasOrderBy"
		}
	},
	CreateNabidkaInput:{
		nabidka:"NabidkaInput"
	},
	NabidkaInput:{
		nId:"BigInt",
		nTrener:"BigInt",
		nMaxPocetHod:"BigInt",
		nOd:"Date",
		nDo:"Date",
		nTimestamp:"Datetime"
	},
	CreateNabidkaItemPayload:{
		nabidkaItemEdge:{
			orderBy:"NabidkaItemsOrderBy"
		}
	},
	CreateNabidkaItemInput:{
		nabidkaItem:"NabidkaItemInput"
	},
	NabidkaItemInput:{
		niId:"BigInt",
		niIdRodic:"BigInt",
		niPartner:"BigInt"
	},
	CreatePagePayload:{
		pageEdge:{
			orderBy:"PagesOrderBy"
		}
	},
	CreatePageInput:{
		page:"PageInput"
	},
	PageInput:{
		content:"JSON",
		createdAt:"Datetime",
		updatedAt:"Datetime"
	},
	CreateParameterPayload:{
		parameterEdge:{
			orderBy:"ParametersOrderBy"
		}
	},
	CreateParameterInput:{
		parameter:"ParameterInput"
	},
	ParameterInput:{

	},
	CreateParyPayload:{
		paryEdge:{
			orderBy:"PariesOrderBy"
		}
	},
	CreateParyInput:{
		pary:"ParyInput"
	},
	ParyInput:{
		pId:"BigInt",
		pIdPartner:"BigInt",
		pIdPartnerka:"BigInt",
		pSttTrida:"ParyPSttTrida",
		pLatTrida:"ParyPLatTrida",
		pTimestampAdd:"Datetime",
		pTimestampArchive:"Datetime"
	},
	CreateParyNavrhPayload:{
		paryNavrhEdge:{
			orderBy:"ParyNavrhsOrderBy"
		}
	},
	CreateParyNavrhInput:{
		paryNavrh:"ParyNavrhInput"
	},
	ParyNavrhInput:{
		pnId:"BigInt",
		pnNavrhl:"BigInt",
		pnPartner:"BigInt",
		pnPartnerka:"BigInt"
	},
	CreatePermissionPayload:{
		permissionEdge:{
			orderBy:"PermissionsOrderBy"
		}
	},
	CreatePermissionInput:{
		permission:"PermissionInput"
	},
	PermissionInput:{
		peId:"BigInt"
	},
	CreatePlatbyCategoryPayload:{
		platbyCategoryEdge:{
			orderBy:"PlatbyCategoriesOrderBy"
		}
	},
	CreatePlatbyCategoryInput:{
		platbyCategory:"PlatbyCategoryInput"
	},
	PlatbyCategoryInput:{
		pcId:"BigInt",
		pcSymbol:"BigInt",
		pcAmount:"BigFloat",
		pcDateDue:"Date",
		pcValidFrom:"Date",
		pcValidTo:"Date"
	},
	CreatePlatbyCategoryGroupPayload:{
		platbyCategoryGroupEdge:{
			orderBy:"PlatbyCategoryGroupsOrderBy"
		}
	},
	CreatePlatbyCategoryGroupInput:{
		platbyCategoryGroup:"PlatbyCategoryGroupInput"
	},
	PlatbyCategoryGroupInput:{
		pcgId:"BigInt",
		pcgIdGroup:"BigInt",
		pcgIdCategory:"BigInt"
	},
	CreatePlatbyGroupPayload:{
		platbyGroupEdge:{
			orderBy:"PlatbyGroupsOrderBy"
		}
	},
	CreatePlatbyGroupInput:{
		platbyGroup:"PlatbyGroupInput"
	},
	PlatbyGroupInput:{
		pgId:"BigInt",
		pgType:"BigFloat",
		pgBase:"BigInt"
	},
	CreatePlatbyGroupSkupinaPayload:{
		platbyGroupSkupinaEdge:{
			orderBy:"PlatbyGroupSkupinasOrderBy"
		}
	},
	CreatePlatbyGroupSkupinaInput:{
		platbyGroupSkupina:"PlatbyGroupSkupinaInput"
	},
	PlatbyGroupSkupinaInput:{
		pgsId:"BigInt",
		pgsIdSkupina:"BigInt",
		pgsIdGroup:"BigInt"
	},
	CreatePlatbyItemPayload:{
		platbyItemEdge:{
			orderBy:"PlatbyItemsOrderBy"
		}
	},
	CreatePlatbyItemInput:{
		platbyItem:"PlatbyItemInput"
	},
	PlatbyItemInput:{
		piId:"BigInt",
		piIdUser:"BigInt",
		piIdCategory:"BigInt",
		piIdRaw:"BigInt",
		piAmount:"BigFloat",
		piDate:"Date"
	},
	CreatePlatbyRawPayload:{
		platbyRawEdge:{
			orderBy:"PlatbyRawsOrderBy"
		}
	},
	CreatePlatbyRawInput:{
		platbyRaw:"PlatbyRawInput"
	},
	PlatbyRawInput:{
		prId:"BigInt"
	},
	CreateRozpiPayload:{
		rozpiEdge:{
			orderBy:"RozpisOrderBy"
		}
	},
	CreateRozpiInput:{
		rozpi:"RozpiInput"
	},
	RozpiInput:{
		rId:"BigInt",
		rTrener:"BigInt",
		rDatum:"Date",
		rTimestamp:"Datetime"
	},
	CreateRozpisItemPayload:{
		rozpisItemEdge:{
			orderBy:"RozpisItemsOrderBy"
		}
	},
	CreateRozpisItemInput:{
		rozpisItem:"RozpisItemInput"
	},
	RozpisItemInput:{
		riId:"BigInt",
		riIdRodic:"BigInt",
		riPartner:"BigInt",
		riOd:"Time",
		riDo:"Time"
	},
	CreateSessionPayload:{
		sessionEdge:{
			orderBy:"SessionsOrderBy"
		}
	},
	CreateSessionInput:{
		session:"SessionInput"
	},
	SessionInput:{
		ssUpdatedAt:"Datetime",
		ssLifetime:"BigInt",
		ssUser:"BigInt"
	},
	CreateSkupinyPayload:{
		skupinyEdge:{
			orderBy:"SkupiniesOrderBy"
		}
	},
	CreateSkupinyInput:{
		skupiny:"SkupinyInput"
	},
	SkupinyInput:{
		sId:"BigInt"
	},
	CreateUpozorneniPayload:{
		upozorneniEdge:{
			orderBy:"UpozornenisOrderBy"
		}
	},
	CreateUpozorneniInput:{
		upozorneni:"UpozorneniInput"
	},
	UpozorneniInput:{
		upId:"BigInt",
		upKdo:"BigInt",
		upBarvy:"BigInt",
		upTimestamp:"Datetime",
		upTimestampAdd:"Datetime"
	},
	CreateUpozorneniSkupinyPayload:{
		upozorneniSkupinyEdge:{
			orderBy:"UpozorneniSkupiniesOrderBy"
		}
	},
	CreateUpozorneniSkupinyInput:{
		upozorneniSkupiny:"UpozorneniSkupinyInput"
	},
	UpozorneniSkupinyInput:{
		upsId:"BigInt",
		upsIdRodic:"BigInt",
		upsIdSkupina:"BigInt"
	},
	CreateUserPayload:{
		userEdge:{
			orderBy:"UsersOrderBy"
		}
	},
	CreateUserInput:{
		user:"UserInput"
	},
	UserInput:{
		uId:"BigInt",
		uNarozeni:"Date",
		uTimestamp:"Datetime",
		uGroup:"BigInt",
		uSkupina:"BigInt",
		uMemberSince:"Datetime",
		uMemberUntil:"Datetime",
		uCreatedAt:"Datetime",
		uGdprSignedAt:"Datetime"
	},
	CreateUsersSkupinyPayload:{
		usersSkupinyEdge:{
			orderBy:"UsersSkupiniesOrderBy"
		}
	},
	CreateUsersSkupinyInput:{
		usersSkupiny:"UsersSkupinyInput"
	},
	UsersSkupinyInput:{
		usId:"BigInt",
		usPlatbaMesic:"BigInt",
		usPlatbaCtvrtrok:"BigInt",
		usPlatbaPulrok:"BigInt"
	},
	CreateVideoPayload:{
		videoEdge:{
			orderBy:"VideosOrderBy"
		}
	},
	CreateVideoInput:{
		video:"VideoInput"
	},
	VideoInput:{
		vId:"BigInt",
		vCreatedAt:"Datetime",
		vUpdatedAt:"Datetime"
	},
	CreateVideoListPayload:{
		videoListEdge:{
			orderBy:"VideoListsOrderBy"
		}
	},
	CreateVideoListInput:{
		videoList:"VideoListInput"
	},
	VideoListInput:{
		vlId:"BigInt",
		vlCount:"BigInt",
		vlCreatedAt:"Datetime",
		vlLastChecked:"Datetime"
	},
	CreateVideoSourcePayload:{
		videoSourceEdge:{
			orderBy:"VideoSourcesOrderBy"
		}
	},
	CreateVideoSourceInput:{
		videoSource:"VideoSourceInput"
	},
	VideoSourceInput:{
		vsId:"BigInt",
		vsCreatedAt:"Datetime",
		vsLastChecked:"Datetime"
	},
	UpdateAkcePayload:{
		akceEdge:{
			orderBy:"AkcesOrderBy"
		}
	},
	UpdateAkceByNodeIdInput:{
		patch:"AkcePatch"
	},
	AkcePatch:{
		aId:"BigInt",
		aOd:"Date",
		aDo:"Date",
		aKapacita:"BigInt",
		aTimestamp:"Datetime"
	},
	UpdateAkceInput:{
		patch:"AkcePatch",
		aId:"BigInt"
	},
	UpdateAkceItemPayload:{
		akceItemEdge:{
			orderBy:"AkceItemsOrderBy"
		}
	},
	UpdateAkceItemByNodeIdInput:{
		patch:"AkceItemPatch"
	},
	AkceItemPatch:{
		aiId:"BigInt",
		aiIdRodic:"BigInt",
		aiUser:"BigInt"
	},
	UpdateAkceItemInput:{
		patch:"AkceItemPatch",
		aiId:"BigInt"
	},
	UpdateAktualityPayload:{
		aktualityEdge:{
			orderBy:"AktualitiesOrderBy"
		}
	},
	UpdateAktualityByNodeIdInput:{
		patch:"AktualityPatch"
	},
	AktualityPatch:{
		atId:"BigInt",
		atKdo:"BigInt",
		atFoto:"BigInt",
		atFotoMain:"BigInt",
		atTimestamp:"Datetime",
		atTimestampAdd:"Datetime"
	},
	UpdateAktualityInput:{
		patch:"AktualityPatch",
		atId:"BigInt"
	},
	UpdateDokumentyPayload:{
		dokumentyEdge:{
			orderBy:"DokumentiesOrderBy"
		}
	},
	UpdateDokumentyByNodeIdInput:{
		patch:"DokumentyPatch"
	},
	DokumentyPatch:{
		dId:"BigInt",
		dKdo:"BigInt",
		dTimestamp:"Datetime"
	},
	UpdateDokumentyInput:{
		patch:"DokumentyPatch",
		dId:"BigInt"
	},
	UpdateGalerieDirPayload:{
		galerieDirEdge:{
			orderBy:"GalerieDirsOrderBy"
		}
	},
	UpdateGalerieDirByNodeIdInput:{
		patch:"GalerieDirPatch"
	},
	GalerieDirPatch:{
		gdId:"BigInt",
		gdIdRodic:"BigInt"
	},
	UpdateGalerieDirInput:{
		patch:"GalerieDirPatch",
		gdId:"BigInt"
	},
	UpdateGalerieFotoPayload:{
		galerieFotoEdge:{
			orderBy:"GalerieFotosOrderBy"
		}
	},
	UpdateGalerieFotoByNodeIdInput:{
		patch:"GalerieFotoPatch"
	},
	GalerieFotoPatch:{
		gfId:"BigInt",
		gfIdRodic:"BigInt",
		gfKdo:"BigInt",
		gfTimestamp:"Datetime"
	},
	UpdateGalerieFotoInput:{
		patch:"GalerieFotoPatch",
		gfId:"BigInt"
	},
	UpdateNabidkaPayload:{
		nabidkaEdge:{
			orderBy:"NabidkasOrderBy"
		}
	},
	UpdateNabidkaByNodeIdInput:{
		patch:"NabidkaPatch"
	},
	NabidkaPatch:{
		nId:"BigInt",
		nTrener:"BigInt",
		nMaxPocetHod:"BigInt",
		nOd:"Date",
		nDo:"Date",
		nTimestamp:"Datetime"
	},
	UpdateNabidkaInput:{
		patch:"NabidkaPatch",
		nId:"BigInt"
	},
	UpdateNabidkaItemPayload:{
		nabidkaItemEdge:{
			orderBy:"NabidkaItemsOrderBy"
		}
	},
	UpdateNabidkaItemByNodeIdInput:{
		patch:"NabidkaItemPatch"
	},
	NabidkaItemPatch:{
		niId:"BigInt",
		niIdRodic:"BigInt",
		niPartner:"BigInt"
	},
	UpdateNabidkaItemInput:{
		patch:"NabidkaItemPatch",
		niId:"BigInt"
	},
	UpdatePagePayload:{
		pageEdge:{
			orderBy:"PagesOrderBy"
		}
	},
	UpdatePageByNodeIdInput:{
		patch:"PagePatch"
	},
	PagePatch:{
		content:"JSON",
		createdAt:"Datetime",
		updatedAt:"Datetime"
	},
	UpdatePageInput:{
		patch:"PagePatch"
	},
	UpdatePageByUrlInput:{
		patch:"PagePatch"
	},
	UpdateParameterPayload:{
		parameterEdge:{
			orderBy:"ParametersOrderBy"
		}
	},
	UpdateParameterByNodeIdInput:{
		patch:"ParameterPatch"
	},
	ParameterPatch:{

	},
	UpdateParameterInput:{
		patch:"ParameterPatch"
	},
	UpdateParyPayload:{
		paryEdge:{
			orderBy:"PariesOrderBy"
		}
	},
	UpdateParyByNodeIdInput:{
		patch:"ParyPatch"
	},
	ParyPatch:{
		pId:"BigInt",
		pIdPartner:"BigInt",
		pIdPartnerka:"BigInt",
		pSttTrida:"ParyPSttTrida",
		pLatTrida:"ParyPLatTrida",
		pTimestampAdd:"Datetime",
		pTimestampArchive:"Datetime"
	},
	UpdateParyInput:{
		patch:"ParyPatch",
		pId:"BigInt"
	},
	UpdateParyNavrhPayload:{
		paryNavrhEdge:{
			orderBy:"ParyNavrhsOrderBy"
		}
	},
	UpdateParyNavrhByNodeIdInput:{
		patch:"ParyNavrhPatch"
	},
	ParyNavrhPatch:{
		pnId:"BigInt",
		pnNavrhl:"BigInt",
		pnPartner:"BigInt",
		pnPartnerka:"BigInt"
	},
	UpdateParyNavrhInput:{
		patch:"ParyNavrhPatch",
		pnId:"BigInt"
	},
	UpdatePermissionPayload:{
		permissionEdge:{
			orderBy:"PermissionsOrderBy"
		}
	},
	UpdatePermissionByNodeIdInput:{
		patch:"PermissionPatch"
	},
	PermissionPatch:{
		peId:"BigInt"
	},
	UpdatePermissionInput:{
		patch:"PermissionPatch",
		peId:"BigInt"
	},
	UpdatePlatbyCategoryPayload:{
		platbyCategoryEdge:{
			orderBy:"PlatbyCategoriesOrderBy"
		}
	},
	UpdatePlatbyCategoryByNodeIdInput:{
		patch:"PlatbyCategoryPatch"
	},
	PlatbyCategoryPatch:{
		pcId:"BigInt",
		pcSymbol:"BigInt",
		pcAmount:"BigFloat",
		pcDateDue:"Date",
		pcValidFrom:"Date",
		pcValidTo:"Date"
	},
	UpdatePlatbyCategoryInput:{
		patch:"PlatbyCategoryPatch",
		pcId:"BigInt"
	},
	UpdatePlatbyCategoryGroupPayload:{
		platbyCategoryGroupEdge:{
			orderBy:"PlatbyCategoryGroupsOrderBy"
		}
	},
	UpdatePlatbyCategoryGroupByNodeIdInput:{
		patch:"PlatbyCategoryGroupPatch"
	},
	PlatbyCategoryGroupPatch:{
		pcgId:"BigInt",
		pcgIdGroup:"BigInt",
		pcgIdCategory:"BigInt"
	},
	UpdatePlatbyCategoryGroupInput:{
		patch:"PlatbyCategoryGroupPatch",
		pcgId:"BigInt"
	},
	UpdatePlatbyGroupPayload:{
		platbyGroupEdge:{
			orderBy:"PlatbyGroupsOrderBy"
		}
	},
	UpdatePlatbyGroupByNodeIdInput:{
		patch:"PlatbyGroupPatch"
	},
	PlatbyGroupPatch:{
		pgId:"BigInt",
		pgType:"BigFloat",
		pgBase:"BigInt"
	},
	UpdatePlatbyGroupInput:{
		patch:"PlatbyGroupPatch",
		pgId:"BigInt"
	},
	UpdatePlatbyGroupSkupinaPayload:{
		platbyGroupSkupinaEdge:{
			orderBy:"PlatbyGroupSkupinasOrderBy"
		}
	},
	UpdatePlatbyGroupSkupinaByNodeIdInput:{
		patch:"PlatbyGroupSkupinaPatch"
	},
	PlatbyGroupSkupinaPatch:{
		pgsId:"BigInt",
		pgsIdSkupina:"BigInt",
		pgsIdGroup:"BigInt"
	},
	UpdatePlatbyGroupSkupinaInput:{
		patch:"PlatbyGroupSkupinaPatch",
		pgsId:"BigInt"
	},
	UpdatePlatbyItemPayload:{
		platbyItemEdge:{
			orderBy:"PlatbyItemsOrderBy"
		}
	},
	UpdatePlatbyItemByNodeIdInput:{
		patch:"PlatbyItemPatch"
	},
	PlatbyItemPatch:{
		piId:"BigInt",
		piIdUser:"BigInt",
		piIdCategory:"BigInt",
		piIdRaw:"BigInt",
		piAmount:"BigFloat",
		piDate:"Date"
	},
	UpdatePlatbyItemInput:{
		patch:"PlatbyItemPatch",
		piId:"BigInt"
	},
	UpdatePlatbyRawPayload:{
		platbyRawEdge:{
			orderBy:"PlatbyRawsOrderBy"
		}
	},
	UpdatePlatbyRawByNodeIdInput:{
		patch:"PlatbyRawPatch"
	},
	PlatbyRawPatch:{
		prId:"BigInt"
	},
	UpdatePlatbyRawInput:{
		patch:"PlatbyRawPatch",
		prId:"BigInt"
	},
	UpdateRozpiPayload:{
		rozpiEdge:{
			orderBy:"RozpisOrderBy"
		}
	},
	UpdateRozpiByNodeIdInput:{
		patch:"RozpiPatch"
	},
	RozpiPatch:{
		rId:"BigInt",
		rTrener:"BigInt",
		rDatum:"Date",
		rTimestamp:"Datetime"
	},
	UpdateRozpiInput:{
		patch:"RozpiPatch",
		rId:"BigInt"
	},
	UpdateRozpisItemPayload:{
		rozpisItemEdge:{
			orderBy:"RozpisItemsOrderBy"
		}
	},
	UpdateRozpisItemByNodeIdInput:{
		patch:"RozpisItemPatch"
	},
	RozpisItemPatch:{
		riId:"BigInt",
		riIdRodic:"BigInt",
		riPartner:"BigInt",
		riOd:"Time",
		riDo:"Time"
	},
	UpdateRozpisItemInput:{
		patch:"RozpisItemPatch",
		riId:"BigInt"
	},
	UpdateSessionPayload:{
		sessionEdge:{
			orderBy:"SessionsOrderBy"
		}
	},
	UpdateSessionByNodeIdInput:{
		patch:"SessionPatch"
	},
	SessionPatch:{
		ssUpdatedAt:"Datetime",
		ssLifetime:"BigInt",
		ssUser:"BigInt"
	},
	UpdateSessionInput:{
		patch:"SessionPatch"
	},
	UpdateSkupinyPayload:{
		skupinyEdge:{
			orderBy:"SkupiniesOrderBy"
		}
	},
	UpdateSkupinyByNodeIdInput:{
		patch:"SkupinyPatch"
	},
	SkupinyPatch:{
		sId:"BigInt"
	},
	UpdateSkupinyInput:{
		patch:"SkupinyPatch",
		sId:"BigInt"
	},
	UpdateUpozorneniPayload:{
		upozorneniEdge:{
			orderBy:"UpozornenisOrderBy"
		}
	},
	UpdateUpozorneniByNodeIdInput:{
		patch:"UpozorneniPatch"
	},
	UpozorneniPatch:{
		upId:"BigInt",
		upKdo:"BigInt",
		upBarvy:"BigInt",
		upTimestamp:"Datetime",
		upTimestampAdd:"Datetime"
	},
	UpdateUpozorneniInput:{
		patch:"UpozorneniPatch",
		upId:"BigInt"
	},
	UpdateUpozorneniSkupinyPayload:{
		upozorneniSkupinyEdge:{
			orderBy:"UpozorneniSkupiniesOrderBy"
		}
	},
	UpdateUpozorneniSkupinyByNodeIdInput:{
		patch:"UpozorneniSkupinyPatch"
	},
	UpozorneniSkupinyPatch:{
		upsId:"BigInt",
		upsIdRodic:"BigInt",
		upsIdSkupina:"BigInt"
	},
	UpdateUpozorneniSkupinyInput:{
		patch:"UpozorneniSkupinyPatch",
		upsId:"BigInt"
	},
	UpdateUserPayload:{
		userEdge:{
			orderBy:"UsersOrderBy"
		}
	},
	UpdateUserByNodeIdInput:{
		patch:"UserPatch"
	},
	UserPatch:{
		uId:"BigInt",
		uNarozeni:"Date",
		uTimestamp:"Datetime",
		uGroup:"BigInt",
		uSkupina:"BigInt",
		uMemberSince:"Datetime",
		uMemberUntil:"Datetime",
		uCreatedAt:"Datetime",
		uGdprSignedAt:"Datetime"
	},
	UpdateUserInput:{
		patch:"UserPatch",
		uId:"BigInt"
	},
	UpdateUsersSkupinyPayload:{
		usersSkupinyEdge:{
			orderBy:"UsersSkupiniesOrderBy"
		}
	},
	UpdateUsersSkupinyByNodeIdInput:{
		patch:"UsersSkupinyPatch"
	},
	UsersSkupinyPatch:{
		usId:"BigInt",
		usPlatbaMesic:"BigInt",
		usPlatbaCtvrtrok:"BigInt",
		usPlatbaPulrok:"BigInt"
	},
	UpdateUsersSkupinyInput:{
		patch:"UsersSkupinyPatch",
		usId:"BigInt"
	},
	UpdateVideoPayload:{
		videoEdge:{
			orderBy:"VideosOrderBy"
		}
	},
	UpdateVideoByNodeIdInput:{
		patch:"VideoPatch"
	},
	VideoPatch:{
		vId:"BigInt",
		vCreatedAt:"Datetime",
		vUpdatedAt:"Datetime"
	},
	UpdateVideoInput:{
		patch:"VideoPatch",
		vId:"BigInt"
	},
	UpdateVideoListPayload:{
		videoListEdge:{
			orderBy:"VideoListsOrderBy"
		}
	},
	UpdateVideoListByNodeIdInput:{
		patch:"VideoListPatch"
	},
	VideoListPatch:{
		vlId:"BigInt",
		vlCount:"BigInt",
		vlCreatedAt:"Datetime",
		vlLastChecked:"Datetime"
	},
	UpdateVideoListInput:{
		patch:"VideoListPatch",
		vlId:"BigInt"
	},
	UpdateVideoSourcePayload:{
		videoSourceEdge:{
			orderBy:"VideoSourcesOrderBy"
		}
	},
	UpdateVideoSourceByNodeIdInput:{
		patch:"VideoSourcePatch"
	},
	VideoSourcePatch:{
		vsId:"BigInt",
		vsCreatedAt:"Datetime",
		vsLastChecked:"Datetime"
	},
	UpdateVideoSourceInput:{
		patch:"VideoSourcePatch",
		vsId:"BigInt"
	},
	DeleteAkcePayload:{
		akceEdge:{
			orderBy:"AkcesOrderBy"
		}
	},
	DeleteAkceByNodeIdInput:{

	},
	DeleteAkceInput:{
		aId:"BigInt"
	},
	DeleteAkceItemPayload:{
		akceItemEdge:{
			orderBy:"AkceItemsOrderBy"
		}
	},
	DeleteAkceItemByNodeIdInput:{

	},
	DeleteAkceItemInput:{
		aiId:"BigInt"
	},
	DeleteAktualityPayload:{
		aktualityEdge:{
			orderBy:"AktualitiesOrderBy"
		}
	},
	DeleteAktualityByNodeIdInput:{

	},
	DeleteAktualityInput:{
		atId:"BigInt"
	},
	DeleteDokumentyPayload:{
		dokumentyEdge:{
			orderBy:"DokumentiesOrderBy"
		}
	},
	DeleteDokumentyByNodeIdInput:{

	},
	DeleteDokumentyInput:{
		dId:"BigInt"
	},
	DeleteGalerieDirPayload:{
		galerieDirEdge:{
			orderBy:"GalerieDirsOrderBy"
		}
	},
	DeleteGalerieDirByNodeIdInput:{

	},
	DeleteGalerieDirInput:{
		gdId:"BigInt"
	},
	DeleteGalerieFotoPayload:{
		galerieFotoEdge:{
			orderBy:"GalerieFotosOrderBy"
		}
	},
	DeleteGalerieFotoByNodeIdInput:{

	},
	DeleteGalerieFotoInput:{
		gfId:"BigInt"
	},
	DeleteNabidkaPayload:{
		nabidkaEdge:{
			orderBy:"NabidkasOrderBy"
		}
	},
	DeleteNabidkaByNodeIdInput:{

	},
	DeleteNabidkaInput:{
		nId:"BigInt"
	},
	DeleteNabidkaItemPayload:{
		nabidkaItemEdge:{
			orderBy:"NabidkaItemsOrderBy"
		}
	},
	DeleteNabidkaItemByNodeIdInput:{

	},
	DeleteNabidkaItemInput:{
		niId:"BigInt"
	},
	DeleteParameterPayload:{
		parameterEdge:{
			orderBy:"ParametersOrderBy"
		}
	},
	DeleteParameterByNodeIdInput:{

	},
	DeleteParameterInput:{

	},
	DeleteParyPayload:{
		paryEdge:{
			orderBy:"PariesOrderBy"
		}
	},
	DeleteParyByNodeIdInput:{

	},
	DeleteParyInput:{
		pId:"BigInt"
	},
	DeleteParyNavrhPayload:{
		paryNavrhEdge:{
			orderBy:"ParyNavrhsOrderBy"
		}
	},
	DeleteParyNavrhByNodeIdInput:{

	},
	DeleteParyNavrhInput:{
		pnId:"BigInt"
	},
	DeletePermissionPayload:{
		permissionEdge:{
			orderBy:"PermissionsOrderBy"
		}
	},
	DeletePermissionByNodeIdInput:{

	},
	DeletePermissionInput:{
		peId:"BigInt"
	},
	DeletePlatbyCategoryPayload:{
		platbyCategoryEdge:{
			orderBy:"PlatbyCategoriesOrderBy"
		}
	},
	DeletePlatbyCategoryByNodeIdInput:{

	},
	DeletePlatbyCategoryInput:{
		pcId:"BigInt"
	},
	DeletePlatbyCategoryGroupPayload:{
		platbyCategoryGroupEdge:{
			orderBy:"PlatbyCategoryGroupsOrderBy"
		}
	},
	DeletePlatbyCategoryGroupByNodeIdInput:{

	},
	DeletePlatbyCategoryGroupInput:{
		pcgId:"BigInt"
	},
	DeletePlatbyGroupPayload:{
		platbyGroupEdge:{
			orderBy:"PlatbyGroupsOrderBy"
		}
	},
	DeletePlatbyGroupByNodeIdInput:{

	},
	DeletePlatbyGroupInput:{
		pgId:"BigInt"
	},
	DeletePlatbyGroupSkupinaPayload:{
		platbyGroupSkupinaEdge:{
			orderBy:"PlatbyGroupSkupinasOrderBy"
		}
	},
	DeletePlatbyGroupSkupinaByNodeIdInput:{

	},
	DeletePlatbyGroupSkupinaInput:{
		pgsId:"BigInt"
	},
	DeletePlatbyItemPayload:{
		platbyItemEdge:{
			orderBy:"PlatbyItemsOrderBy"
		}
	},
	DeletePlatbyItemByNodeIdInput:{

	},
	DeletePlatbyItemInput:{
		piId:"BigInt"
	},
	DeletePlatbyRawPayload:{
		platbyRawEdge:{
			orderBy:"PlatbyRawsOrderBy"
		}
	},
	DeletePlatbyRawByNodeIdInput:{

	},
	DeletePlatbyRawInput:{
		prId:"BigInt"
	},
	DeleteRozpiPayload:{
		rozpiEdge:{
			orderBy:"RozpisOrderBy"
		}
	},
	DeleteRozpiByNodeIdInput:{

	},
	DeleteRozpiInput:{
		rId:"BigInt"
	},
	DeleteRozpisItemPayload:{
		rozpisItemEdge:{
			orderBy:"RozpisItemsOrderBy"
		}
	},
	DeleteRozpisItemByNodeIdInput:{

	},
	DeleteRozpisItemInput:{
		riId:"BigInt"
	},
	DeleteSessionPayload:{
		sessionEdge:{
			orderBy:"SessionsOrderBy"
		}
	},
	DeleteSessionByNodeIdInput:{

	},
	DeleteSessionInput:{

	},
	DeleteSkupinyPayload:{
		skupinyEdge:{
			orderBy:"SkupiniesOrderBy"
		}
	},
	DeleteSkupinyByNodeIdInput:{

	},
	DeleteSkupinyInput:{
		sId:"BigInt"
	},
	DeleteUpozorneniPayload:{
		upozorneniEdge:{
			orderBy:"UpozornenisOrderBy"
		}
	},
	DeleteUpozorneniByNodeIdInput:{

	},
	DeleteUpozorneniInput:{
		upId:"BigInt"
	},
	DeleteUpozorneniSkupinyPayload:{
		upozorneniSkupinyEdge:{
			orderBy:"UpozorneniSkupiniesOrderBy"
		}
	},
	DeleteUpozorneniSkupinyByNodeIdInput:{

	},
	DeleteUpozorneniSkupinyInput:{
		upsId:"BigInt"
	},
	DeleteUserPayload:{
		userEdge:{
			orderBy:"UsersOrderBy"
		}
	},
	DeleteUserByNodeIdInput:{

	},
	DeleteUserInput:{
		uId:"BigInt"
	},
	DeleteUsersSkupinyPayload:{
		usersSkupinyEdge:{
			orderBy:"UsersSkupiniesOrderBy"
		}
	},
	DeleteUsersSkupinyByNodeIdInput:{

	},
	DeleteUsersSkupinyInput:{
		usId:"BigInt"
	},
	DeleteVideoPayload:{
		videoEdge:{
			orderBy:"VideosOrderBy"
		}
	},
	DeleteVideoByNodeIdInput:{

	},
	DeleteVideoInput:{
		vId:"BigInt"
	},
	DeleteVideoListPayload:{
		videoListEdge:{
			orderBy:"VideoListsOrderBy"
		}
	},
	DeleteVideoListByNodeIdInput:{

	},
	DeleteVideoListInput:{
		vlId:"BigInt"
	},
	DeleteVideoSourcePayload:{
		videoSourceEdge:{
			orderBy:"VideoSourcesOrderBy"
		}
	},
	DeleteVideoSourceByNodeIdInput:{

	},
	DeleteVideoSourceInput:{
		vsId:"BigInt"
	},
	LoginInput:{

	},
	LogoutInput:{

	},
	ProspectFormDancerInput:{
		cohort:"CrmCohort",
		prospectData:"ProspectDatumInput"
	},
	ProspectDatumInput:{

	},
	UploadInput:{

	}
}

export const ReturnTypes: Record<string,any> = {
	Query:{
		query:"Query",
		nodeId:"ID",
		node:"Node",
		akces:"AkcesConnection",
		akceItems:"AkceItemsConnection",
		aktualities:"AktualitiesConnection",
		dokumenties:"DokumentiesConnection",
		galerieDirs:"GalerieDirsConnection",
		galerieFotos:"GalerieFotosConnection",
		members:"MembersConnection",
		nabidkas:"NabidkasConnection",
		nabidkaItems:"NabidkaItemsConnection",
		pages:"PagesConnection",
		pageRevisions:"PageRevisionsConnection",
		parameters:"ParametersConnection",
		paries:"PariesConnection",
		paryNavrhs:"ParyNavrhsConnection",
		permissions:"PermissionsConnection",
		platbyCategories:"PlatbyCategoriesConnection",
		platbyCategoryGroups:"PlatbyCategoryGroupsConnection",
		platbyGroups:"PlatbyGroupsConnection",
		platbyGroupSkupinas:"PlatbyGroupSkupinasConnection",
		platbyItems:"PlatbyItemsConnection",
		platbyRaws:"PlatbyRawsConnection",
		rozpis:"RozpisConnection",
		rozpisItems:"RozpisItemsConnection",
		sessions:"SessionsConnection",
		skupinies:"SkupiniesConnection",
		upozornenis:"UpozornenisConnection",
		upozorneniSkupinies:"UpozorneniSkupiniesConnection",
		users:"UsersConnection",
		usersSkupinies:"UsersSkupiniesConnection",
		videos:"VideosConnection",
		videoLists:"VideoListsConnection",
		videoSources:"VideoSourcesConnection",
		akce:"Akce",
		akceItem:"AkceItem",
		aktuality:"Aktuality",
		dokumenty:"Dokumenty",
		galerieDir:"GalerieDir",
		galerieFoto:"GalerieFoto",
		nabidka:"Nabidka",
		nabidkaItem:"NabidkaItem",
		page:"Page",
		pageByUrl:"Page",
		pageRevision:"PageRevision",
		parameter:"Parameter",
		pary:"Pary",
		paryNavrh:"ParyNavrh",
		permission:"Permission",
		platbyCategory:"PlatbyCategory",
		platbyCategoryGroup:"PlatbyCategoryGroup",
		platbyGroup:"PlatbyGroup",
		platbyGroupSkupina:"PlatbyGroupSkupina",
		platbyItem:"PlatbyItem",
		platbyRaw:"PlatbyRaw",
		rozpi:"Rozpi",
		rozpisItem:"RozpisItem",
		session:"Session",
		skupiny:"Skupiny",
		upozorneni:"Upozorneni",
		upozorneniSkupiny:"UpozorneniSkupiny",
		user:"User",
		usersSkupiny:"UsersSkupiny",
		video:"Video",
		videoList:"VideoList",
		videoSource:"VideoSource",
		activeProspects:"ActiveProspectsConnection",
		cohortMembers:"MembersConnection",
		currentCoupleIds:"CurrentCoupleIdsConnection",
		currentSessionId:"String",
		currentUserId:"BigInt",
		getCurrentUser:"User",
		reservationsForRange:"NabidkasConnection",
		schedulesForRange:"RozpisConnection",
		titleVideos:"VideosConnection",
		akceByNodeId:"Akce",
		akceItemByNodeId:"AkceItem",
		aktualityByNodeId:"Aktuality",
		dokumentyByNodeId:"Dokumenty",
		galerieDirByNodeId:"GalerieDir",
		galerieFotoByNodeId:"GalerieFoto",
		nabidkaByNodeId:"Nabidka",
		nabidkaItemByNodeId:"NabidkaItem",
		pageByNodeId:"Page",
		pageRevisionByNodeId:"PageRevision",
		parameterByNodeId:"Parameter",
		paryByNodeId:"Pary",
		paryNavrhByNodeId:"ParyNavrh",
		permissionByNodeId:"Permission",
		platbyCategoryByNodeId:"PlatbyCategory",
		platbyCategoryGroupByNodeId:"PlatbyCategoryGroup",
		platbyGroupByNodeId:"PlatbyGroup",
		platbyGroupSkupinaByNodeId:"PlatbyGroupSkupina",
		platbyItemByNodeId:"PlatbyItem",
		platbyRawByNodeId:"PlatbyRaw",
		rozpiByNodeId:"Rozpi",
		rozpisItemByNodeId:"RozpisItem",
		sessionByNodeId:"Session",
		skupinyByNodeId:"Skupiny",
		upozorneniByNodeId:"Upozorneni",
		upozorneniSkupinyByNodeId:"UpozorneniSkupiny",
		userByNodeId:"User",
		usersSkupinyByNodeId:"UsersSkupiny",
		videoByNodeId:"Video",
		videoListByNodeId:"VideoList",
		videoSourceByNodeId:"VideoSource"
	},
	Node:{
		"...on Query": "Query",
		"...on Akce": "Akce",
		"...on AkceItem": "AkceItem",
		"...on User": "User",
		"...on Permission": "Permission",
		"...on Skupiny": "Skupiny",
		"...on PlatbyGroupSkupina": "PlatbyGroupSkupina",
		"...on PlatbyGroup": "PlatbyGroup",
		"...on PlatbyCategoryGroup": "PlatbyCategoryGroup",
		"...on PlatbyCategory": "PlatbyCategory",
		"...on PlatbyItem": "PlatbyItem",
		"...on PlatbyRaw": "PlatbyRaw",
		"...on UpozorneniSkupiny": "UpozorneniSkupiny",
		"...on Upozorneni": "Upozorneni",
		"...on Aktuality": "Aktuality",
		"...on GalerieFoto": "GalerieFoto",
		"...on GalerieDir": "GalerieDir",
		"...on Nabidka": "Nabidka",
		"...on NabidkaItem": "NabidkaItem",
		"...on Pary": "Pary",
		"...on RozpisItem": "RozpisItem",
		"...on Rozpi": "Rozpi",
		"...on Session": "Session",
		"...on Dokumenty": "Dokumenty",
		"...on ParyNavrh": "ParyNavrh",
		"...on Page": "Page",
		"...on PageRevision": "PageRevision",
		"...on Parameter": "Parameter",
		"...on UsersSkupiny": "UsersSkupiny",
		"...on Video": "Video",
		"...on VideoList": "VideoList",
		"...on VideoSource": "VideoSource",
		nodeId:"ID"
	},
	AkcesConnection:{
		nodes:"Akce",
		edges:"AkcesEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	Akce:{
		nodeId:"ID",
		aId:"BigInt",
		aJmeno:"String",
		aKde:"String",
		aInfo:"String",
		aOd:"Date",
		aDo:"Date",
		aKapacita:"BigInt",
		aDokumenty:"String",
		aTimestamp:"Datetime",
		aLock:"Boolean",
		aVisible:"Boolean",
		akceItemsByAiIdRodic:"AkceItemsConnection"
	},
	BigInt: `scalar.BigInt` as const,
	Date: `scalar.Date` as const,
	Datetime: `scalar.Datetime` as const,
	AkceItemsConnection:{
		nodes:"AkceItem",
		edges:"AkceItemsEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	AkceItem:{
		nodeId:"ID",
		aiId:"BigInt",
		aiIdRodic:"BigInt",
		aiUser:"BigInt",
		aiRokNarozeni:"Int",
		akceByAiIdRodic:"Akce",
		userByAiUser:"User"
	},
	User:{
		nodeId:"ID",
		uId:"BigInt",
		uLogin:"String",
		uPass:"String",
		uJmeno:"String",
		uPrijmeni:"String",
		uPohlavi:"String",
		uEmail:"String",
		uTelefon:"String",
		uNarozeni:"Date",
		uRodneCislo:"String",
		uPoznamky:"String",
		uTimestamp:"Datetime",
		uLevel:"Int",
		uGroup:"BigInt",
		uSkupina:"BigInt",
		uDancer:"Boolean",
		uBan:"Boolean",
		uLock:"Boolean",
		uConfirmed:"Boolean",
		uSystem:"Boolean",
		uStreet:"String",
		uConscriptionNumber:"String",
		uOrientationNumber:"String",
		uDistrict:"String",
		uCity:"String",
		uPostalCode:"String",
		uNationality:"String",
		uMemberSince:"Datetime",
		uMemberUntil:"Datetime",
		uCreatedAt:"Datetime",
		uTeacher:"Boolean",
		uGdprSignedAt:"Datetime",
		permissionByUGroup:"Permission",
		skupinyByUSkupina:"Skupiny",
		aktualitiesByAtKdo:"AktualitiesConnection",
		nabidkasByNTrener:"NabidkasConnection",
		rozpisByRTrener:"RozpisConnection",
		platbyItemsByPiIdUser:"PlatbyItemsConnection",
		pariesByPIdPartner:"PariesConnection",
		sessionsBySsUser:"SessionsConnection",
		akceItemsByAiUser:"AkceItemsConnection",
		dokumentiesByDKdo:"DokumentiesConnection",
		galerieFotosByGfKdo:"GalerieFotosConnection",
		paryNavrhsByPnNavrhl:"ParyNavrhsConnection",
		paryNavrhsByPnPartner:"ParyNavrhsConnection",
		paryNavrhsByPnPartnerka:"ParyNavrhsConnection",
		upozornenisByUpKdo:"UpozornenisConnection"
	},
	Permission:{
		nodeId:"ID",
		peId:"BigInt",
		peName:"String",
		peDescription:"String",
		peAkce:"Int",
		peAktuality:"Int",
		peAnkety:"Int",
		peDokumenty:"Int",
		peGalerie:"Int",
		peInzerce:"Int",
		peKonzole:"Int",
		peNabidka:"Int",
		peNastenka:"Int",
		peNovinky:"Int",
		pePary:"Int",
		pePlatby:"Int",
		pePermissions:"Int",
		peRozpis:"Int",
		peSkupiny:"Int",
		peUsers:"Int",
		peMain:"Int",
		usersByUGroup:"UsersConnection"
	},
	UsersConnection:{
		nodes:"User",
		edges:"UsersEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	UsersEdge:{
		cursor:"Cursor",
		node:"User"
	},
	Cursor: `scalar.Cursor` as const,
	PageInfo:{
		hasNextPage:"Boolean",
		hasPreviousPage:"Boolean",
		startCursor:"Cursor",
		endCursor:"Cursor"
	},
	Skupiny:{
		nodeId:"ID",
		sId:"BigInt",
		sName:"String",
		sDescription:"String",
		sColorRgb:"String",
		sColorText:"String",
		sLocation:"String",
		sVisible:"Boolean",
		usersByUSkupina:"UsersConnection",
		platbyGroupSkupinasByPgsIdSkupina:"PlatbyGroupSkupinasConnection",
		upozorneniSkupiniesByUpsIdSkupina:"UpozorneniSkupiniesConnection"
	},
	PlatbyGroupSkupinasConnection:{
		nodes:"PlatbyGroupSkupina",
		edges:"PlatbyGroupSkupinasEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	PlatbyGroupSkupina:{
		nodeId:"ID",
		pgsId:"BigInt",
		pgsIdSkupina:"BigInt",
		pgsIdGroup:"BigInt",
		skupinyByPgsIdSkupina:"Skupiny",
		platbyGroupByPgsIdGroup:"PlatbyGroup"
	},
	PlatbyGroup:{
		nodeId:"ID",
		pgId:"BigInt",
		pgType:"BigFloat",
		pgName:"String",
		pgDescription:"String",
		pgBase:"BigInt",
		platbyCategoryGroupsByPcgIdGroup:"PlatbyCategoryGroupsConnection",
		platbyGroupSkupinasByPgsIdGroup:"PlatbyGroupSkupinasConnection"
	},
	BigFloat: `scalar.BigFloat` as const,
	PlatbyCategoryGroupsConnection:{
		nodes:"PlatbyCategoryGroup",
		edges:"PlatbyCategoryGroupsEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	PlatbyCategoryGroup:{
		nodeId:"ID",
		pcgId:"BigInt",
		pcgIdGroup:"BigInt",
		pcgIdCategory:"BigInt",
		platbyGroupByPcgIdGroup:"PlatbyGroup",
		platbyCategoryByPcgIdCategory:"PlatbyCategory"
	},
	PlatbyCategory:{
		nodeId:"ID",
		pcId:"BigInt",
		pcName:"String",
		pcSymbol:"BigInt",
		pcAmount:"BigFloat",
		pcDateDue:"Date",
		pcValidFrom:"Date",
		pcValidTo:"Date",
		pcUseBase:"Boolean",
		pcUsePrefix:"Boolean",
		pcArchive:"Boolean",
		pcVisible:"Boolean",
		platbyCategoryGroupsByPcgIdCategory:"PlatbyCategoryGroupsConnection",
		platbyItemsByPiIdCategory:"PlatbyItemsConnection"
	},
	PlatbyItemsConnection:{
		nodes:"PlatbyItem",
		edges:"PlatbyItemsEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	PlatbyItem:{
		nodeId:"ID",
		piId:"BigInt",
		piIdUser:"BigInt",
		piIdCategory:"BigInt",
		piIdRaw:"BigInt",
		piAmount:"BigFloat",
		piDate:"Date",
		piPrefix:"Int",
		userByPiIdUser:"User",
		platbyCategoryByPiIdCategory:"PlatbyCategory",
		platbyRawByPiIdRaw:"PlatbyRaw"
	},
	PlatbyRaw:{
		nodeId:"ID",
		prId:"BigInt",
		prRaw:"String",
		prHash:"String",
		prSorted:"Boolean",
		prDiscarded:"Boolean",
		platbyItemsByPiIdRaw:"PlatbyItemsConnection"
	},
	PlatbyItemsEdge:{
		cursor:"Cursor",
		node:"PlatbyItem"
	},
	PlatbyCategoryGroupsEdge:{
		cursor:"Cursor",
		node:"PlatbyCategoryGroup"
	},
	PlatbyGroupSkupinasEdge:{
		cursor:"Cursor",
		node:"PlatbyGroupSkupina"
	},
	UpozorneniSkupiniesConnection:{
		nodes:"UpozorneniSkupiny",
		edges:"UpozorneniSkupiniesEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	UpozorneniSkupiny:{
		nodeId:"ID",
		upsId:"BigInt",
		upsIdRodic:"BigInt",
		upsIdSkupina:"BigInt",
		upsColor:"String",
		upsPopis:"String",
		upozorneniByUpsIdRodic:"Upozorneni",
		skupinyByUpsIdSkupina:"Skupiny"
	},
	Upozorneni:{
		nodeId:"ID",
		upId:"BigInt",
		upKdo:"BigInt",
		upNadpis:"String",
		upText:"String",
		upBarvy:"BigInt",
		upLock:"Boolean",
		upTimestamp:"Datetime",
		upTimestampAdd:"Datetime",
		userByUpKdo:"User",
		upozorneniSkupiniesByUpsIdRodic:"UpozorneniSkupiniesConnection"
	},
	UpozorneniSkupiniesEdge:{
		cursor:"Cursor",
		node:"UpozorneniSkupiny"
	},
	AktualitiesConnection:{
		nodes:"Aktuality",
		edges:"AktualitiesEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	Aktuality:{
		nodeId:"ID",
		atId:"BigInt",
		atKdo:"BigInt",
		atKat:"String",
		atJmeno:"String",
		atText:"String",
		atPreview:"String",
		atFoto:"BigInt",
		atFotoMain:"BigInt",
		atTimestamp:"Datetime",
		atTimestampAdd:"Datetime",
		userByAtKdo:"User",
		galerieFotoByAtFotoMain:"GalerieFoto"
	},
	GalerieFoto:{
		nodeId:"ID",
		gfId:"BigInt",
		gfIdRodic:"BigInt",
		gfName:"String",
		gfPath:"String",
		gfKdo:"BigInt",
		gfTimestamp:"Datetime",
		galerieDirByGfIdRodic:"GalerieDir",
		userByGfKdo:"User",
		aktualitiesByAtFotoMain:"AktualitiesConnection"
	},
	GalerieDir:{
		nodeId:"ID",
		gdId:"BigInt",
		gdIdRodic:"BigInt",
		gdName:"String",
		gdLevel:"Int",
		gdPath:"String",
		gdHidden:"Boolean",
		galerieFotosByGfIdRodic:"GalerieFotosConnection"
	},
	GalerieFotosConnection:{
		nodes:"GalerieFoto",
		edges:"GalerieFotosEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	GalerieFotosEdge:{
		cursor:"Cursor",
		node:"GalerieFoto"
	},
	AktualitiesEdge:{
		cursor:"Cursor",
		node:"Aktuality"
	},
	NabidkasConnection:{
		nodes:"Nabidka",
		edges:"NabidkasEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	Nabidka:{
		nodeId:"ID",
		nId:"BigInt",
		nTrener:"BigInt",
		nPocetHod:"Int",
		nMaxPocetHod:"BigInt",
		nOd:"Date",
		nDo:"Date",
		nVisible:"Boolean",
		nLock:"Boolean",
		nTimestamp:"Datetime",
		userByNTrener:"User",
		nabidkaItemsByNiIdRodic:"NabidkaItemsConnection"
	},
	NabidkaItemsConnection:{
		nodes:"NabidkaItem",
		edges:"NabidkaItemsEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	NabidkaItem:{
		nodeId:"ID",
		niId:"BigInt",
		niIdRodic:"BigInt",
		niPartner:"BigInt",
		niPocetHod:"Int",
		niLock:"Boolean",
		nabidkaByNiIdRodic:"Nabidka",
		paryByNiPartner:"Pary"
	},
	Pary:{
		nodeId:"ID",
		pId:"BigInt",
		pIdPartner:"BigInt",
		pIdPartnerka:"BigInt",
		pSttTrida:"ParyPSttTrida",
		pSttBody:"Int",
		pSttFinale:"Boolean",
		pLatTrida:"ParyPLatTrida",
		pLatBody:"Int",
		pLatFinale:"Boolean",
		pHodnoceni:"Int",
		pArchiv:"Boolean",
		pTimestampAdd:"Datetime",
		pTimestampArchive:"Datetime",
		userByPIdPartner:"User",
		nabidkaItemsByNiPartner:"NabidkaItemsConnection",
		rozpisItemsByRiPartner:"RozpisItemsConnection"
	},
	RozpisItemsConnection:{
		nodes:"RozpisItem",
		edges:"RozpisItemsEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	RozpisItem:{
		nodeId:"ID",
		riId:"BigInt",
		riIdRodic:"BigInt",
		riPartner:"BigInt",
		riOd:"Time",
		riDo:"Time",
		riLock:"Boolean",
		rozpiByRiIdRodic:"Rozpi",
		paryByRiPartner:"Pary"
	},
	Time: `scalar.Time` as const,
	Rozpi:{
		nodeId:"ID",
		rId:"BigInt",
		rTrener:"BigInt",
		rKde:"String",
		rDatum:"Date",
		rVisible:"Boolean",
		rLock:"Boolean",
		rTimestamp:"Datetime",
		userByRTrener:"User",
		rozpisItemsByRiIdRodic:"RozpisItemsConnection"
	},
	RozpisItemsEdge:{
		cursor:"Cursor",
		node:"RozpisItem"
	},
	NabidkaItemsEdge:{
		cursor:"Cursor",
		node:"NabidkaItem"
	},
	NabidkasEdge:{
		cursor:"Cursor",
		node:"Nabidka"
	},
	RozpisConnection:{
		nodes:"Rozpi",
		edges:"RozpisEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	RozpisEdge:{
		cursor:"Cursor",
		node:"Rozpi"
	},
	PariesConnection:{
		nodes:"Pary",
		edges:"PariesEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	PariesEdge:{
		cursor:"Cursor",
		node:"Pary"
	},
	SessionsConnection:{
		nodes:"Session",
		edges:"SessionsEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	Session:{
		nodeId:"ID",
		ssId:"String",
		ssData:"String",
		ssUpdatedAt:"Datetime",
		ssLifetime:"BigInt",
		ssUser:"BigInt",
		userBySsUser:"User"
	},
	SessionsEdge:{
		cursor:"Cursor",
		node:"Session"
	},
	DokumentiesConnection:{
		nodes:"Dokumenty",
		edges:"DokumentiesEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	Dokumenty:{
		nodeId:"ID",
		dId:"BigInt",
		dPath:"String",
		dName:"String",
		dFilename:"String",
		dKategorie:"Int",
		dKdo:"BigInt",
		dTimestamp:"Datetime",
		userByDKdo:"User"
	},
	DokumentiesEdge:{
		cursor:"Cursor",
		node:"Dokumenty"
	},
	ParyNavrhsConnection:{
		nodes:"ParyNavrh",
		edges:"ParyNavrhsEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	ParyNavrh:{
		nodeId:"ID",
		pnId:"BigInt",
		pnNavrhl:"BigInt",
		pnPartner:"BigInt",
		pnPartnerka:"BigInt",
		userByPnNavrhl:"User",
		userByPnPartner:"User",
		userByPnPartnerka:"User"
	},
	ParyNavrhsEdge:{
		cursor:"Cursor",
		node:"ParyNavrh"
	},
	UpozornenisConnection:{
		nodes:"Upozorneni",
		edges:"UpozornenisEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	UpozornenisEdge:{
		cursor:"Cursor",
		node:"Upozorneni"
	},
	AkceItemsEdge:{
		cursor:"Cursor",
		node:"AkceItem"
	},
	AkcesEdge:{
		cursor:"Cursor",
		node:"Akce"
	},
	GalerieDirsConnection:{
		nodes:"GalerieDir",
		edges:"GalerieDirsEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	GalerieDirsEdge:{
		cursor:"Cursor",
		node:"GalerieDir"
	},
	MembersConnection:{
		nodes:"Member",
		edges:"MembersEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	Member:{
		uId:"BigInt",
		uLogin:"String",
		uPass:"String",
		uJmeno:"String",
		uPrijmeni:"String",
		uPohlavi:"String",
		uEmail:"String",
		uTelefon:"String",
		uNarozeni:"Date",
		uRodneCislo:"String",
		uPoznamky:"String",
		uTimestamp:"Datetime",
		uLevel:"Int",
		uGroup:"BigInt",
		uSkupina:"BigInt",
		uDancer:"Boolean",
		uBan:"Boolean",
		uLock:"Boolean",
		uConfirmed:"Boolean",
		uSystem:"Boolean",
		uStreet:"String",
		uConscriptionNumber:"String",
		uOrientationNumber:"String",
		uDistrict:"String",
		uCity:"String",
		uPostalCode:"String",
		uNationality:"String",
		uMemberSince:"Datetime",
		uMemberUntil:"Datetime",
		uCreatedAt:"Datetime",
		uTeacher:"Boolean",
		uGdprSignedAt:"Datetime",
		sId:"BigInt",
		sName:"String",
		paymentValid:"Boolean"
	},
	MembersEdge:{
		cursor:"Cursor",
		node:"Member"
	},
	PagesConnection:{
		nodes:"Page",
		edges:"PagesEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	Page:{
		nodeId:"ID",
		id:"Int",
		url:"String",
		content:"JSON",
		createdAt:"Datetime",
		updatedAt:"Datetime",
		title:"String"
	},
	JSON: `scalar.JSON` as const,
	PagesEdge:{
		cursor:"Cursor",
		node:"Page"
	},
	PageRevisionsConnection:{
		nodes:"PageRevision",
		edges:"PageRevisionsEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	PageRevision:{
		nodeId:"ID",
		revNumber:"Int",
		revOperation:"String",
		revTimestamp:"Datetime",
		id:"Int",
		url:"String",
		content:"JSON",
		createdAt:"Datetime",
		updatedAt:"Datetime",
		title:"String"
	},
	PageRevisionsEdge:{
		cursor:"Cursor",
		node:"PageRevision"
	},
	ParametersConnection:{
		nodes:"Parameter",
		edges:"ParametersEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	Parameter:{
		nodeId:"ID",
		paName:"String",
		paValue:"String"
	},
	ParametersEdge:{
		cursor:"Cursor",
		node:"Parameter"
	},
	PermissionsConnection:{
		nodes:"Permission",
		edges:"PermissionsEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	PermissionsEdge:{
		cursor:"Cursor",
		node:"Permission"
	},
	PlatbyCategoriesConnection:{
		nodes:"PlatbyCategory",
		edges:"PlatbyCategoriesEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	PlatbyCategoriesEdge:{
		cursor:"Cursor",
		node:"PlatbyCategory"
	},
	PlatbyGroupsConnection:{
		nodes:"PlatbyGroup",
		edges:"PlatbyGroupsEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	PlatbyGroupsEdge:{
		cursor:"Cursor",
		node:"PlatbyGroup"
	},
	PlatbyRawsConnection:{
		nodes:"PlatbyRaw",
		edges:"PlatbyRawsEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	PlatbyRawsEdge:{
		cursor:"Cursor",
		node:"PlatbyRaw"
	},
	SkupiniesConnection:{
		nodes:"Skupiny",
		edges:"SkupiniesEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	SkupiniesEdge:{
		cursor:"Cursor",
		node:"Skupiny"
	},
	UsersSkupiniesConnection:{
		nodes:"UsersSkupiny",
		edges:"UsersSkupiniesEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	UsersSkupiny:{
		nodeId:"ID",
		usId:"BigInt",
		usColor:"String",
		usPlatbaMesic:"BigInt",
		usPlatbaCtvrtrok:"BigInt",
		usPlatbaPulrok:"BigInt",
		usPopis:"String"
	},
	UsersSkupiniesEdge:{
		cursor:"Cursor",
		node:"UsersSkupiny"
	},
	VideosConnection:{
		nodes:"Video",
		edges:"VideosEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	Video:{
		nodeId:"ID",
		vId:"BigInt",
		vUri:"String",
		vTitle:"String",
		vAuthor:"String",
		vDescription:"String",
		vPlaylist:"String",
		vCreatedAt:"Datetime",
		vUpdatedAt:"Datetime"
	},
	VideosEdge:{
		cursor:"Cursor",
		node:"Video"
	},
	VideoListsConnection:{
		nodes:"VideoList",
		edges:"VideoListsEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	VideoList:{
		nodeId:"ID",
		vlId:"BigInt",
		vlUrl:"String",
		vlTitle:"String",
		vlDescription:"String",
		vlCount:"BigInt",
		vlCreatedAt:"Datetime",
		vlLastChecked:"Datetime"
	},
	VideoListsEdge:{
		cursor:"Cursor",
		node:"VideoList"
	},
	VideoSourcesConnection:{
		nodes:"VideoSource",
		edges:"VideoSourcesEdge",
		pageInfo:"PageInfo",
		totalCount:"Int"
	},
	VideoSource:{
		nodeId:"ID",
		vsId:"BigInt",
		vsUrl:"String",
		vsTitle:"String",
		vsDescription:"String",
		vsCreatedAt:"Datetime",
		vsLastChecked:"Datetime"
	},
	VideoSourcesEdge:{
		cursor:"Cursor",
		node:"VideoSource"
	},
	ActiveProspectsConnection:{
		nodes:"ActiveProspectsRecord",
		edges:"ActiveProspectEdge",
		totalCount:"Int"
	},
	ActiveProspectsRecord:{
		id:"BigInt",
		data:"ProspectDatum",
		cohort:"CrmCohort",
		updatedAt:"Datetime"
	},
	ProspectDatum:{
		name:"String",
		surname:"String",
		email:"String",
		phone:"String",
		yearofbirth:"String"
	},
	ActiveProspectEdge:{
		cursor:"Cursor",
		node:"ActiveProspectsRecord"
	},
	CurrentCoupleIdsConnection:{
		nodes:"BigInt",
		edges:"CurrentCoupleIdEdge",
		totalCount:"Int"
	},
	CurrentCoupleIdEdge:{
		cursor:"Cursor",
		node:"BigInt"
	},
	Mutation:{
		createAkce:"CreateAkcePayload",
		createAkceItem:"CreateAkceItemPayload",
		createAktuality:"CreateAktualityPayload",
		createDokumenty:"CreateDokumentyPayload",
		createGalerieDir:"CreateGalerieDirPayload",
		createGalerieFoto:"CreateGalerieFotoPayload",
		createNabidka:"CreateNabidkaPayload",
		createNabidkaItem:"CreateNabidkaItemPayload",
		createPage:"CreatePagePayload",
		createParameter:"CreateParameterPayload",
		createPary:"CreateParyPayload",
		createParyNavrh:"CreateParyNavrhPayload",
		createPermission:"CreatePermissionPayload",
		createPlatbyCategory:"CreatePlatbyCategoryPayload",
		createPlatbyCategoryGroup:"CreatePlatbyCategoryGroupPayload",
		createPlatbyGroup:"CreatePlatbyGroupPayload",
		createPlatbyGroupSkupina:"CreatePlatbyGroupSkupinaPayload",
		createPlatbyItem:"CreatePlatbyItemPayload",
		createPlatbyRaw:"CreatePlatbyRawPayload",
		createRozpi:"CreateRozpiPayload",
		createRozpisItem:"CreateRozpisItemPayload",
		createSession:"CreateSessionPayload",
		createSkupiny:"CreateSkupinyPayload",
		createUpozorneni:"CreateUpozorneniPayload",
		createUpozorneniSkupiny:"CreateUpozorneniSkupinyPayload",
		createUser:"CreateUserPayload",
		createUsersSkupiny:"CreateUsersSkupinyPayload",
		createVideo:"CreateVideoPayload",
		createVideoList:"CreateVideoListPayload",
		createVideoSource:"CreateVideoSourcePayload",
		updateAkceByNodeId:"UpdateAkcePayload",
		updateAkce:"UpdateAkcePayload",
		updateAkceItemByNodeId:"UpdateAkceItemPayload",
		updateAkceItem:"UpdateAkceItemPayload",
		updateAktualityByNodeId:"UpdateAktualityPayload",
		updateAktuality:"UpdateAktualityPayload",
		updateDokumentyByNodeId:"UpdateDokumentyPayload",
		updateDokumenty:"UpdateDokumentyPayload",
		updateGalerieDirByNodeId:"UpdateGalerieDirPayload",
		updateGalerieDir:"UpdateGalerieDirPayload",
		updateGalerieFotoByNodeId:"UpdateGalerieFotoPayload",
		updateGalerieFoto:"UpdateGalerieFotoPayload",
		updateNabidkaByNodeId:"UpdateNabidkaPayload",
		updateNabidka:"UpdateNabidkaPayload",
		updateNabidkaItemByNodeId:"UpdateNabidkaItemPayload",
		updateNabidkaItem:"UpdateNabidkaItemPayload",
		updatePageByNodeId:"UpdatePagePayload",
		updatePage:"UpdatePagePayload",
		updatePageByUrl:"UpdatePagePayload",
		updateParameterByNodeId:"UpdateParameterPayload",
		updateParameter:"UpdateParameterPayload",
		updateParyByNodeId:"UpdateParyPayload",
		updatePary:"UpdateParyPayload",
		updateParyNavrhByNodeId:"UpdateParyNavrhPayload",
		updateParyNavrh:"UpdateParyNavrhPayload",
		updatePermissionByNodeId:"UpdatePermissionPayload",
		updatePermission:"UpdatePermissionPayload",
		updatePlatbyCategoryByNodeId:"UpdatePlatbyCategoryPayload",
		updatePlatbyCategory:"UpdatePlatbyCategoryPayload",
		updatePlatbyCategoryGroupByNodeId:"UpdatePlatbyCategoryGroupPayload",
		updatePlatbyCategoryGroup:"UpdatePlatbyCategoryGroupPayload",
		updatePlatbyGroupByNodeId:"UpdatePlatbyGroupPayload",
		updatePlatbyGroup:"UpdatePlatbyGroupPayload",
		updatePlatbyGroupSkupinaByNodeId:"UpdatePlatbyGroupSkupinaPayload",
		updatePlatbyGroupSkupina:"UpdatePlatbyGroupSkupinaPayload",
		updatePlatbyItemByNodeId:"UpdatePlatbyItemPayload",
		updatePlatbyItem:"UpdatePlatbyItemPayload",
		updatePlatbyRawByNodeId:"UpdatePlatbyRawPayload",
		updatePlatbyRaw:"UpdatePlatbyRawPayload",
		updateRozpiByNodeId:"UpdateRozpiPayload",
		updateRozpi:"UpdateRozpiPayload",
		updateRozpisItemByNodeId:"UpdateRozpisItemPayload",
		updateRozpisItem:"UpdateRozpisItemPayload",
		updateSessionByNodeId:"UpdateSessionPayload",
		updateSession:"UpdateSessionPayload",
		updateSkupinyByNodeId:"UpdateSkupinyPayload",
		updateSkupiny:"UpdateSkupinyPayload",
		updateUpozorneniByNodeId:"UpdateUpozorneniPayload",
		updateUpozorneni:"UpdateUpozorneniPayload",
		updateUpozorneniSkupinyByNodeId:"UpdateUpozorneniSkupinyPayload",
		updateUpozorneniSkupiny:"UpdateUpozorneniSkupinyPayload",
		updateUserByNodeId:"UpdateUserPayload",
		updateUser:"UpdateUserPayload",
		updateUsersSkupinyByNodeId:"UpdateUsersSkupinyPayload",
		updateUsersSkupiny:"UpdateUsersSkupinyPayload",
		updateVideoByNodeId:"UpdateVideoPayload",
		updateVideo:"UpdateVideoPayload",
		updateVideoListByNodeId:"UpdateVideoListPayload",
		updateVideoList:"UpdateVideoListPayload",
		updateVideoSourceByNodeId:"UpdateVideoSourcePayload",
		updateVideoSource:"UpdateVideoSourcePayload",
		deleteAkceByNodeId:"DeleteAkcePayload",
		deleteAkce:"DeleteAkcePayload",
		deleteAkceItemByNodeId:"DeleteAkceItemPayload",
		deleteAkceItem:"DeleteAkceItemPayload",
		deleteAktualityByNodeId:"DeleteAktualityPayload",
		deleteAktuality:"DeleteAktualityPayload",
		deleteDokumentyByNodeId:"DeleteDokumentyPayload",
		deleteDokumenty:"DeleteDokumentyPayload",
		deleteGalerieDirByNodeId:"DeleteGalerieDirPayload",
		deleteGalerieDir:"DeleteGalerieDirPayload",
		deleteGalerieFotoByNodeId:"DeleteGalerieFotoPayload",
		deleteGalerieFoto:"DeleteGalerieFotoPayload",
		deleteNabidkaByNodeId:"DeleteNabidkaPayload",
		deleteNabidka:"DeleteNabidkaPayload",
		deleteNabidkaItemByNodeId:"DeleteNabidkaItemPayload",
		deleteNabidkaItem:"DeleteNabidkaItemPayload",
		deleteParameterByNodeId:"DeleteParameterPayload",
		deleteParameter:"DeleteParameterPayload",
		deleteParyByNodeId:"DeleteParyPayload",
		deletePary:"DeleteParyPayload",
		deleteParyNavrhByNodeId:"DeleteParyNavrhPayload",
		deleteParyNavrh:"DeleteParyNavrhPayload",
		deletePermissionByNodeId:"DeletePermissionPayload",
		deletePermission:"DeletePermissionPayload",
		deletePlatbyCategoryByNodeId:"DeletePlatbyCategoryPayload",
		deletePlatbyCategory:"DeletePlatbyCategoryPayload",
		deletePlatbyCategoryGroupByNodeId:"DeletePlatbyCategoryGroupPayload",
		deletePlatbyCategoryGroup:"DeletePlatbyCategoryGroupPayload",
		deletePlatbyGroupByNodeId:"DeletePlatbyGroupPayload",
		deletePlatbyGroup:"DeletePlatbyGroupPayload",
		deletePlatbyGroupSkupinaByNodeId:"DeletePlatbyGroupSkupinaPayload",
		deletePlatbyGroupSkupina:"DeletePlatbyGroupSkupinaPayload",
		deletePlatbyItemByNodeId:"DeletePlatbyItemPayload",
		deletePlatbyItem:"DeletePlatbyItemPayload",
		deletePlatbyRawByNodeId:"DeletePlatbyRawPayload",
		deletePlatbyRaw:"DeletePlatbyRawPayload",
		deleteRozpiByNodeId:"DeleteRozpiPayload",
		deleteRozpi:"DeleteRozpiPayload",
		deleteRozpisItemByNodeId:"DeleteRozpisItemPayload",
		deleteRozpisItem:"DeleteRozpisItemPayload",
		deleteSessionByNodeId:"DeleteSessionPayload",
		deleteSession:"DeleteSessionPayload",
		deleteSkupinyByNodeId:"DeleteSkupinyPayload",
		deleteSkupiny:"DeleteSkupinyPayload",
		deleteUpozorneniByNodeId:"DeleteUpozorneniPayload",
		deleteUpozorneni:"DeleteUpozorneniPayload",
		deleteUpozorneniSkupinyByNodeId:"DeleteUpozorneniSkupinyPayload",
		deleteUpozorneniSkupiny:"DeleteUpozorneniSkupinyPayload",
		deleteUserByNodeId:"DeleteUserPayload",
		deleteUser:"DeleteUserPayload",
		deleteUsersSkupinyByNodeId:"DeleteUsersSkupinyPayload",
		deleteUsersSkupiny:"DeleteUsersSkupinyPayload",
		deleteVideoByNodeId:"DeleteVideoPayload",
		deleteVideo:"DeleteVideoPayload",
		deleteVideoListByNodeId:"DeleteVideoListPayload",
		deleteVideoList:"DeleteVideoListPayload",
		deleteVideoSourceByNodeId:"DeleteVideoSourcePayload",
		deleteVideoSource:"DeleteVideoSourcePayload",
		login:"LoginPayload",
		logout:"LogoutPayload",
		prospectFormDancer:"ProspectFormDancerPayload",
		uploadFile:"Upload"
	},
	CreateAkcePayload:{
		clientMutationId:"String",
		akce:"Akce",
		query:"Query",
		akceEdge:"AkcesEdge"
	},
	CreateAkceItemPayload:{
		clientMutationId:"String",
		akceItem:"AkceItem",
		query:"Query",
		akceByAiIdRodic:"Akce",
		userByAiUser:"User",
		akceItemEdge:"AkceItemsEdge"
	},
	CreateAktualityPayload:{
		clientMutationId:"String",
		aktuality:"Aktuality",
		query:"Query",
		userByAtKdo:"User",
		galerieFotoByAtFotoMain:"GalerieFoto",
		aktualityEdge:"AktualitiesEdge"
	},
	CreateDokumentyPayload:{
		clientMutationId:"String",
		dokumenty:"Dokumenty",
		query:"Query",
		userByDKdo:"User",
		dokumentyEdge:"DokumentiesEdge"
	},
	CreateGalerieDirPayload:{
		clientMutationId:"String",
		galerieDir:"GalerieDir",
		query:"Query",
		galerieDirEdge:"GalerieDirsEdge"
	},
	CreateGalerieFotoPayload:{
		clientMutationId:"String",
		galerieFoto:"GalerieFoto",
		query:"Query",
		galerieDirByGfIdRodic:"GalerieDir",
		userByGfKdo:"User",
		galerieFotoEdge:"GalerieFotosEdge"
	},
	CreateNabidkaPayload:{
		clientMutationId:"String",
		nabidka:"Nabidka",
		query:"Query",
		userByNTrener:"User",
		nabidkaEdge:"NabidkasEdge"
	},
	CreateNabidkaItemPayload:{
		clientMutationId:"String",
		nabidkaItem:"NabidkaItem",
		query:"Query",
		nabidkaByNiIdRodic:"Nabidka",
		paryByNiPartner:"Pary",
		nabidkaItemEdge:"NabidkaItemsEdge"
	},
	CreatePagePayload:{
		clientMutationId:"String",
		page:"Page",
		query:"Query",
		pageEdge:"PagesEdge"
	},
	CreateParameterPayload:{
		clientMutationId:"String",
		parameter:"Parameter",
		query:"Query",
		parameterEdge:"ParametersEdge"
	},
	CreateParyPayload:{
		clientMutationId:"String",
		pary:"Pary",
		query:"Query",
		userByPIdPartner:"User",
		paryEdge:"PariesEdge"
	},
	CreateParyNavrhPayload:{
		clientMutationId:"String",
		paryNavrh:"ParyNavrh",
		query:"Query",
		userByPnNavrhl:"User",
		userByPnPartner:"User",
		userByPnPartnerka:"User",
		paryNavrhEdge:"ParyNavrhsEdge"
	},
	CreatePermissionPayload:{
		clientMutationId:"String",
		permission:"Permission",
		query:"Query",
		permissionEdge:"PermissionsEdge"
	},
	CreatePlatbyCategoryPayload:{
		clientMutationId:"String",
		platbyCategory:"PlatbyCategory",
		query:"Query",
		platbyCategoryEdge:"PlatbyCategoriesEdge"
	},
	CreatePlatbyCategoryGroupPayload:{
		clientMutationId:"String",
		platbyCategoryGroup:"PlatbyCategoryGroup",
		query:"Query",
		platbyGroupByPcgIdGroup:"PlatbyGroup",
		platbyCategoryByPcgIdCategory:"PlatbyCategory",
		platbyCategoryGroupEdge:"PlatbyCategoryGroupsEdge"
	},
	CreatePlatbyGroupPayload:{
		clientMutationId:"String",
		platbyGroup:"PlatbyGroup",
		query:"Query",
		platbyGroupEdge:"PlatbyGroupsEdge"
	},
	CreatePlatbyGroupSkupinaPayload:{
		clientMutationId:"String",
		platbyGroupSkupina:"PlatbyGroupSkupina",
		query:"Query",
		skupinyByPgsIdSkupina:"Skupiny",
		platbyGroupByPgsIdGroup:"PlatbyGroup",
		platbyGroupSkupinaEdge:"PlatbyGroupSkupinasEdge"
	},
	CreatePlatbyItemPayload:{
		clientMutationId:"String",
		platbyItem:"PlatbyItem",
		query:"Query",
		userByPiIdUser:"User",
		platbyCategoryByPiIdCategory:"PlatbyCategory",
		platbyRawByPiIdRaw:"PlatbyRaw",
		platbyItemEdge:"PlatbyItemsEdge"
	},
	CreatePlatbyRawPayload:{
		clientMutationId:"String",
		platbyRaw:"PlatbyRaw",
		query:"Query",
		platbyRawEdge:"PlatbyRawsEdge"
	},
	CreateRozpiPayload:{
		clientMutationId:"String",
		rozpi:"Rozpi",
		query:"Query",
		userByRTrener:"User",
		rozpiEdge:"RozpisEdge"
	},
	CreateRozpisItemPayload:{
		clientMutationId:"String",
		rozpisItem:"RozpisItem",
		query:"Query",
		rozpiByRiIdRodic:"Rozpi",
		paryByRiPartner:"Pary",
		rozpisItemEdge:"RozpisItemsEdge"
	},
	CreateSessionPayload:{
		clientMutationId:"String",
		session:"Session",
		query:"Query",
		userBySsUser:"User",
		sessionEdge:"SessionsEdge"
	},
	CreateSkupinyPayload:{
		clientMutationId:"String",
		skupiny:"Skupiny",
		query:"Query",
		skupinyEdge:"SkupiniesEdge"
	},
	CreateUpozorneniPayload:{
		clientMutationId:"String",
		upozorneni:"Upozorneni",
		query:"Query",
		userByUpKdo:"User",
		upozorneniEdge:"UpozornenisEdge"
	},
	CreateUpozorneniSkupinyPayload:{
		clientMutationId:"String",
		upozorneniSkupiny:"UpozorneniSkupiny",
		query:"Query",
		upozorneniByUpsIdRodic:"Upozorneni",
		skupinyByUpsIdSkupina:"Skupiny",
		upozorneniSkupinyEdge:"UpozorneniSkupiniesEdge"
	},
	CreateUserPayload:{
		clientMutationId:"String",
		user:"User",
		query:"Query",
		permissionByUGroup:"Permission",
		skupinyByUSkupina:"Skupiny",
		userEdge:"UsersEdge"
	},
	CreateUsersSkupinyPayload:{
		clientMutationId:"String",
		usersSkupiny:"UsersSkupiny",
		query:"Query",
		usersSkupinyEdge:"UsersSkupiniesEdge"
	},
	CreateVideoPayload:{
		clientMutationId:"String",
		video:"Video",
		query:"Query",
		videoEdge:"VideosEdge"
	},
	CreateVideoListPayload:{
		clientMutationId:"String",
		videoList:"VideoList",
		query:"Query",
		videoListEdge:"VideoListsEdge"
	},
	CreateVideoSourcePayload:{
		clientMutationId:"String",
		videoSource:"VideoSource",
		query:"Query",
		videoSourceEdge:"VideoSourcesEdge"
	},
	UpdateAkcePayload:{
		clientMutationId:"String",
		akce:"Akce",
		query:"Query",
		akceEdge:"AkcesEdge"
	},
	UpdateAkceItemPayload:{
		clientMutationId:"String",
		akceItem:"AkceItem",
		query:"Query",
		akceByAiIdRodic:"Akce",
		userByAiUser:"User",
		akceItemEdge:"AkceItemsEdge"
	},
	UpdateAktualityPayload:{
		clientMutationId:"String",
		aktuality:"Aktuality",
		query:"Query",
		userByAtKdo:"User",
		galerieFotoByAtFotoMain:"GalerieFoto",
		aktualityEdge:"AktualitiesEdge"
	},
	UpdateDokumentyPayload:{
		clientMutationId:"String",
		dokumenty:"Dokumenty",
		query:"Query",
		userByDKdo:"User",
		dokumentyEdge:"DokumentiesEdge"
	},
	UpdateGalerieDirPayload:{
		clientMutationId:"String",
		galerieDir:"GalerieDir",
		query:"Query",
		galerieDirEdge:"GalerieDirsEdge"
	},
	UpdateGalerieFotoPayload:{
		clientMutationId:"String",
		galerieFoto:"GalerieFoto",
		query:"Query",
		galerieDirByGfIdRodic:"GalerieDir",
		userByGfKdo:"User",
		galerieFotoEdge:"GalerieFotosEdge"
	},
	UpdateNabidkaPayload:{
		clientMutationId:"String",
		nabidka:"Nabidka",
		query:"Query",
		userByNTrener:"User",
		nabidkaEdge:"NabidkasEdge"
	},
	UpdateNabidkaItemPayload:{
		clientMutationId:"String",
		nabidkaItem:"NabidkaItem",
		query:"Query",
		nabidkaByNiIdRodic:"Nabidka",
		paryByNiPartner:"Pary",
		nabidkaItemEdge:"NabidkaItemsEdge"
	},
	UpdatePagePayload:{
		clientMutationId:"String",
		page:"Page",
		query:"Query",
		pageEdge:"PagesEdge"
	},
	UpdateParameterPayload:{
		clientMutationId:"String",
		parameter:"Parameter",
		query:"Query",
		parameterEdge:"ParametersEdge"
	},
	UpdateParyPayload:{
		clientMutationId:"String",
		pary:"Pary",
		query:"Query",
		userByPIdPartner:"User",
		paryEdge:"PariesEdge"
	},
	UpdateParyNavrhPayload:{
		clientMutationId:"String",
		paryNavrh:"ParyNavrh",
		query:"Query",
		userByPnNavrhl:"User",
		userByPnPartner:"User",
		userByPnPartnerka:"User",
		paryNavrhEdge:"ParyNavrhsEdge"
	},
	UpdatePermissionPayload:{
		clientMutationId:"String",
		permission:"Permission",
		query:"Query",
		permissionEdge:"PermissionsEdge"
	},
	UpdatePlatbyCategoryPayload:{
		clientMutationId:"String",
		platbyCategory:"PlatbyCategory",
		query:"Query",
		platbyCategoryEdge:"PlatbyCategoriesEdge"
	},
	UpdatePlatbyCategoryGroupPayload:{
		clientMutationId:"String",
		platbyCategoryGroup:"PlatbyCategoryGroup",
		query:"Query",
		platbyGroupByPcgIdGroup:"PlatbyGroup",
		platbyCategoryByPcgIdCategory:"PlatbyCategory",
		platbyCategoryGroupEdge:"PlatbyCategoryGroupsEdge"
	},
	UpdatePlatbyGroupPayload:{
		clientMutationId:"String",
		platbyGroup:"PlatbyGroup",
		query:"Query",
		platbyGroupEdge:"PlatbyGroupsEdge"
	},
	UpdatePlatbyGroupSkupinaPayload:{
		clientMutationId:"String",
		platbyGroupSkupina:"PlatbyGroupSkupina",
		query:"Query",
		skupinyByPgsIdSkupina:"Skupiny",
		platbyGroupByPgsIdGroup:"PlatbyGroup",
		platbyGroupSkupinaEdge:"PlatbyGroupSkupinasEdge"
	},
	UpdatePlatbyItemPayload:{
		clientMutationId:"String",
		platbyItem:"PlatbyItem",
		query:"Query",
		userByPiIdUser:"User",
		platbyCategoryByPiIdCategory:"PlatbyCategory",
		platbyRawByPiIdRaw:"PlatbyRaw",
		platbyItemEdge:"PlatbyItemsEdge"
	},
	UpdatePlatbyRawPayload:{
		clientMutationId:"String",
		platbyRaw:"PlatbyRaw",
		query:"Query",
		platbyRawEdge:"PlatbyRawsEdge"
	},
	UpdateRozpiPayload:{
		clientMutationId:"String",
		rozpi:"Rozpi",
		query:"Query",
		userByRTrener:"User",
		rozpiEdge:"RozpisEdge"
	},
	UpdateRozpisItemPayload:{
		clientMutationId:"String",
		rozpisItem:"RozpisItem",
		query:"Query",
		rozpiByRiIdRodic:"Rozpi",
		paryByRiPartner:"Pary",
		rozpisItemEdge:"RozpisItemsEdge"
	},
	UpdateSessionPayload:{
		clientMutationId:"String",
		session:"Session",
		query:"Query",
		userBySsUser:"User",
		sessionEdge:"SessionsEdge"
	},
	UpdateSkupinyPayload:{
		clientMutationId:"String",
		skupiny:"Skupiny",
		query:"Query",
		skupinyEdge:"SkupiniesEdge"
	},
	UpdateUpozorneniPayload:{
		clientMutationId:"String",
		upozorneni:"Upozorneni",
		query:"Query",
		userByUpKdo:"User",
		upozorneniEdge:"UpozornenisEdge"
	},
	UpdateUpozorneniSkupinyPayload:{
		clientMutationId:"String",
		upozorneniSkupiny:"UpozorneniSkupiny",
		query:"Query",
		upozorneniByUpsIdRodic:"Upozorneni",
		skupinyByUpsIdSkupina:"Skupiny",
		upozorneniSkupinyEdge:"UpozorneniSkupiniesEdge"
	},
	UpdateUserPayload:{
		clientMutationId:"String",
		user:"User",
		query:"Query",
		permissionByUGroup:"Permission",
		skupinyByUSkupina:"Skupiny",
		userEdge:"UsersEdge"
	},
	UpdateUsersSkupinyPayload:{
		clientMutationId:"String",
		usersSkupiny:"UsersSkupiny",
		query:"Query",
		usersSkupinyEdge:"UsersSkupiniesEdge"
	},
	UpdateVideoPayload:{
		clientMutationId:"String",
		video:"Video",
		query:"Query",
		videoEdge:"VideosEdge"
	},
	UpdateVideoListPayload:{
		clientMutationId:"String",
		videoList:"VideoList",
		query:"Query",
		videoListEdge:"VideoListsEdge"
	},
	UpdateVideoSourcePayload:{
		clientMutationId:"String",
		videoSource:"VideoSource",
		query:"Query",
		videoSourceEdge:"VideoSourcesEdge"
	},
	DeleteAkcePayload:{
		clientMutationId:"String",
		akce:"Akce",
		deletedAkceNodeId:"ID",
		query:"Query",
		akceEdge:"AkcesEdge"
	},
	DeleteAkceItemPayload:{
		clientMutationId:"String",
		akceItem:"AkceItem",
		deletedAkceItemNodeId:"ID",
		query:"Query",
		akceByAiIdRodic:"Akce",
		userByAiUser:"User",
		akceItemEdge:"AkceItemsEdge"
	},
	DeleteAktualityPayload:{
		clientMutationId:"String",
		aktuality:"Aktuality",
		deletedAktualityNodeId:"ID",
		query:"Query",
		userByAtKdo:"User",
		galerieFotoByAtFotoMain:"GalerieFoto",
		aktualityEdge:"AktualitiesEdge"
	},
	DeleteDokumentyPayload:{
		clientMutationId:"String",
		dokumenty:"Dokumenty",
		deletedDokumentyNodeId:"ID",
		query:"Query",
		userByDKdo:"User",
		dokumentyEdge:"DokumentiesEdge"
	},
	DeleteGalerieDirPayload:{
		clientMutationId:"String",
		galerieDir:"GalerieDir",
		deletedGalerieDirNodeId:"ID",
		query:"Query",
		galerieDirEdge:"GalerieDirsEdge"
	},
	DeleteGalerieFotoPayload:{
		clientMutationId:"String",
		galerieFoto:"GalerieFoto",
		deletedGalerieFotoNodeId:"ID",
		query:"Query",
		galerieDirByGfIdRodic:"GalerieDir",
		userByGfKdo:"User",
		galerieFotoEdge:"GalerieFotosEdge"
	},
	DeleteNabidkaPayload:{
		clientMutationId:"String",
		nabidka:"Nabidka",
		deletedNabidkaNodeId:"ID",
		query:"Query",
		userByNTrener:"User",
		nabidkaEdge:"NabidkasEdge"
	},
	DeleteNabidkaItemPayload:{
		clientMutationId:"String",
		nabidkaItem:"NabidkaItem",
		deletedNabidkaItemNodeId:"ID",
		query:"Query",
		nabidkaByNiIdRodic:"Nabidka",
		paryByNiPartner:"Pary",
		nabidkaItemEdge:"NabidkaItemsEdge"
	},
	DeleteParameterPayload:{
		clientMutationId:"String",
		parameter:"Parameter",
		deletedParameterNodeId:"ID",
		query:"Query",
		parameterEdge:"ParametersEdge"
	},
	DeleteParyPayload:{
		clientMutationId:"String",
		pary:"Pary",
		deletedParyNodeId:"ID",
		query:"Query",
		userByPIdPartner:"User",
		paryEdge:"PariesEdge"
	},
	DeleteParyNavrhPayload:{
		clientMutationId:"String",
		paryNavrh:"ParyNavrh",
		deletedParyNavrhNodeId:"ID",
		query:"Query",
		userByPnNavrhl:"User",
		userByPnPartner:"User",
		userByPnPartnerka:"User",
		paryNavrhEdge:"ParyNavrhsEdge"
	},
	DeletePermissionPayload:{
		clientMutationId:"String",
		permission:"Permission",
		deletedPermissionNodeId:"ID",
		query:"Query",
		permissionEdge:"PermissionsEdge"
	},
	DeletePlatbyCategoryPayload:{
		clientMutationId:"String",
		platbyCategory:"PlatbyCategory",
		deletedPlatbyCategoryNodeId:"ID",
		query:"Query",
		platbyCategoryEdge:"PlatbyCategoriesEdge"
	},
	DeletePlatbyCategoryGroupPayload:{
		clientMutationId:"String",
		platbyCategoryGroup:"PlatbyCategoryGroup",
		deletedPlatbyCategoryGroupNodeId:"ID",
		query:"Query",
		platbyGroupByPcgIdGroup:"PlatbyGroup",
		platbyCategoryByPcgIdCategory:"PlatbyCategory",
		platbyCategoryGroupEdge:"PlatbyCategoryGroupsEdge"
	},
	DeletePlatbyGroupPayload:{
		clientMutationId:"String",
		platbyGroup:"PlatbyGroup",
		deletedPlatbyGroupNodeId:"ID",
		query:"Query",
		platbyGroupEdge:"PlatbyGroupsEdge"
	},
	DeletePlatbyGroupSkupinaPayload:{
		clientMutationId:"String",
		platbyGroupSkupina:"PlatbyGroupSkupina",
		deletedPlatbyGroupSkupinaNodeId:"ID",
		query:"Query",
		skupinyByPgsIdSkupina:"Skupiny",
		platbyGroupByPgsIdGroup:"PlatbyGroup",
		platbyGroupSkupinaEdge:"PlatbyGroupSkupinasEdge"
	},
	DeletePlatbyItemPayload:{
		clientMutationId:"String",
		platbyItem:"PlatbyItem",
		deletedPlatbyItemNodeId:"ID",
		query:"Query",
		userByPiIdUser:"User",
		platbyCategoryByPiIdCategory:"PlatbyCategory",
		platbyRawByPiIdRaw:"PlatbyRaw",
		platbyItemEdge:"PlatbyItemsEdge"
	},
	DeletePlatbyRawPayload:{
		clientMutationId:"String",
		platbyRaw:"PlatbyRaw",
		deletedPlatbyRawNodeId:"ID",
		query:"Query",
		platbyRawEdge:"PlatbyRawsEdge"
	},
	DeleteRozpiPayload:{
		clientMutationId:"String",
		rozpi:"Rozpi",
		deletedRozpiNodeId:"ID",
		query:"Query",
		userByRTrener:"User",
		rozpiEdge:"RozpisEdge"
	},
	DeleteRozpisItemPayload:{
		clientMutationId:"String",
		rozpisItem:"RozpisItem",
		deletedRozpisItemNodeId:"ID",
		query:"Query",
		rozpiByRiIdRodic:"Rozpi",
		paryByRiPartner:"Pary",
		rozpisItemEdge:"RozpisItemsEdge"
	},
	DeleteSessionPayload:{
		clientMutationId:"String",
		session:"Session",
		deletedSessionNodeId:"ID",
		query:"Query",
		userBySsUser:"User",
		sessionEdge:"SessionsEdge"
	},
	DeleteSkupinyPayload:{
		clientMutationId:"String",
		skupiny:"Skupiny",
		deletedSkupinyNodeId:"ID",
		query:"Query",
		skupinyEdge:"SkupiniesEdge"
	},
	DeleteUpozorneniPayload:{
		clientMutationId:"String",
		upozorneni:"Upozorneni",
		deletedUpozorneniNodeId:"ID",
		query:"Query",
		userByUpKdo:"User",
		upozorneniEdge:"UpozornenisEdge"
	},
	DeleteUpozorneniSkupinyPayload:{
		clientMutationId:"String",
		upozorneniSkupiny:"UpozorneniSkupiny",
		deletedUpozorneniSkupinyNodeId:"ID",
		query:"Query",
		upozorneniByUpsIdRodic:"Upozorneni",
		skupinyByUpsIdSkupina:"Skupiny",
		upozorneniSkupinyEdge:"UpozorneniSkupiniesEdge"
	},
	DeleteUserPayload:{
		clientMutationId:"String",
		user:"User",
		deletedUserNodeId:"ID",
		query:"Query",
		permissionByUGroup:"Permission",
		skupinyByUSkupina:"Skupiny",
		userEdge:"UsersEdge"
	},
	DeleteUsersSkupinyPayload:{
		clientMutationId:"String",
		usersSkupiny:"UsersSkupiny",
		deletedUsersSkupinyNodeId:"ID",
		query:"Query",
		usersSkupinyEdge:"UsersSkupiniesEdge"
	},
	DeleteVideoPayload:{
		clientMutationId:"String",
		video:"Video",
		deletedVideoNodeId:"ID",
		query:"Query",
		videoEdge:"VideosEdge"
	},
	DeleteVideoListPayload:{
		clientMutationId:"String",
		videoList:"VideoList",
		deletedVideoListNodeId:"ID",
		query:"Query",
		videoListEdge:"VideoListsEdge"
	},
	DeleteVideoSourcePayload:{
		clientMutationId:"String",
		videoSource:"VideoSource",
		deletedVideoSourceNodeId:"ID",
		query:"Query",
		videoSourceEdge:"VideoSourcesEdge"
	},
	LoginPayload:{
		clientMutationId:"String",
		result:"LoginRecord",
		query:"Query"
	},
	LoginRecord:{
		couple:"Pary",
		sess:"Session",
		usr:"User"
	},
	LogoutPayload:{
		clientMutationId:"String",
		query:"Query"
	},
	ProspectFormDancerPayload:{
		clientMutationId:"String",
		query:"Query"
	},
	Upload:{
		uploadUrl:"String"
	}
}

export const Ops = {
query: "Query" as const,
	mutation: "Mutation" as const
}