<?php header_main('Taneční vystoupení'); ?>
<ul class="list">
	<li>vystoupení standardních a latinskoamerických tanců na reprezentační
		plesy, firemní akce, oslavy</li>
	<li>vystupují páry od nejmenších dětí (do 10 let), přes juniory (11-15 roků)
		po mládežnické a dospělé páry (16 a více)</li>
	<li>vystoupení ,,šijeme na míru" požadavkům organizátora akce</li>
	<li>cena vystoupení závisí na počtu vystupujících, délce a
		počtu vstupů a její kvalitě, zpravidla se pohybuje od 2 do 5 tisíc Kč</li>
</ul>
Reference: každoročně vystupujeme na reprezentačních plesů středních škol a
gymnázií, univerzity a jednotlivých fakult, politických stran a dalších akcí
jako na vesnických slavnostech, tanečních zábavách atp.