import { Selector } from './zeus';

export const CouplePartial = Selector("Pary")({
  pId: true,
  pIdPartner: true,
  pIdPartnerka: true,
  pArchiv: true,
});

export const UserPartial = Selector("User")({
  permissionByUGroup: {
    peAkce: true,
    peAnkety: true,
    peAktuality: true,
    peDescription: true,
    peDokumenty: true,
    peGalerie: true,
    peId: true,
    peNabidka: true,
    peMain: true,
    peName: true,
    peNastenka: true,
    peNovinky: true,
    pePary: true,
    pePermissions: true,
    pePlatby: true,
    peRozpis: true,
    peSkupiny: true,
    peUsers: true,
  },
  uTimestamp: true,
  uSystem: true,
  uTelefon: true,
  uTeacher: true,
  uStreet: true,
  uRodneCislo: true,
  uSkupina: true,
  uPrijmeni: true,
  uPoznamky: true,
  uPostalCode: true,
  uPohlavi: true,
  uOrientationNumber: true,
  uNationality: true,
  uNarozeni: true,
  uMemberUntil: true,
  uLogin: true,
  uMemberSince: true,
  uLock: true,
  uLevel: true,
  uJmeno: true,
  uGroup: true,
  uId: true,
  uGdprSignedAt: true,
  uEmail: true,
  uDancer: true,
  uDistrict: true,
  uCreatedAt: true,
  uConfirmed: true,
  uConscriptionNumber: true,
  uBan: true,
  uCity: true,
});

export const UserQuery = Selector("Query")({
  getCurrentUser: UserPartial,
});
