/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Reservation,
    ReservationFromJSON,
    ReservationFromJSONTyped,
    ReservationToJSON,
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './';

/**
 * 
 * @export
 * @interface ReservationResponse
 */
export interface ReservationResponse {
    /**
     * 
     * @type {User}
     * @memberof ReservationResponse
     */
    trainer: User;
    /**
     * 
     * @type {Reservation}
     * @memberof ReservationResponse
     */
    reservation: Reservation;
    /**
     * 
     * @type {Array<Array>}
     * @memberof ReservationResponse
     */
    items: Array<Array>;
}

export function ReservationResponseFromJSON(json: any): ReservationResponse {
    return ReservationResponseFromJSONTyped(json, false);
}

export function ReservationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'trainer': UserFromJSON(json['trainer']),
        'reservation': ReservationFromJSON(json['reservation']),
        'items': json['items'],
    };
}

export function ReservationResponseToJSON(value?: ReservationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'trainer': UserToJSON(value.trainer),
        'reservation': ReservationToJSON(value.reservation),
        'items': value.items,
    };
}


