/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Reservation
 */
export interface Reservation {
    /**
     * 
     * @type {number}
     * @memberof Reservation
     */
    reservationTrainer: number;
    /**
     * 
     * @type {number}
     * @memberof Reservation
     */
    reservationMaximumPerPair: number;
    /**
     * 
     * @type {number}
     * @memberof Reservation
     */
    reservationNumberLessons: number;
    /**
     * 
     * @type {Date}
     * @memberof Reservation
     */
    reservationTo: Date;
    /**
     * 
     * @type {Date}
     * @memberof Reservation
     */
    reservationFrom: Date;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    reservationVisible: string;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    reservationUpdatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    reservationLock: string;
}

export function ReservationFromJSON(json: any): Reservation {
    return ReservationFromJSONTyped(json, false);
}

export function ReservationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reservation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reservationTrainer': json['reservationTrainer'],
        'reservationMaximumPerPair': json['reservationMaximumPerPair'],
        'reservationNumberLessons': json['reservationNumberLessons'],
        'reservationTo': (new Date(json['reservationTo'])),
        'reservationFrom': (new Date(json['reservationFrom'])),
        'reservationVisible': json['reservationVisible'],
        'reservationUpdatedAt': json['reservationUpdatedAt'],
        'reservationLock': json['reservationLock'],
    };
}

export function ReservationToJSON(value?: Reservation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reservationTrainer': value.reservationTrainer,
        'reservationMaximumPerPair': value.reservationMaximumPerPair,
        'reservationNumberLessons': value.reservationNumberLessons,
        'reservationTo': (value.reservationTo.toISOString().substr(0,10)),
        'reservationFrom': (value.reservationFrom.toISOString().substr(0,10)),
        'reservationVisible': value.reservationVisible,
        'reservationUpdatedAt': value.reservationUpdatedAt,
        'reservationLock': value.reservationLock,
    };
}


