/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    userPaymentGroup: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userOrientationNumber: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userSystem: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userBan: string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    userUserGroup: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userConscriptionNumber: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userDistrict: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userSurname: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userConfirmed: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userNotes: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userLogin: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userTeacher: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userStreet: string;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    userBirthDate: Date;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userPassword: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userCity: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userGender: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userUpdatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userPostalCode: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userCreatedAt: string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    userLevel: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userGdprSignedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userLock: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userEmail: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userPhone: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userNationality: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userMemberUntil?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userMemberSince?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userDancer: string;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userPaymentGroup': json['userPaymentGroup'],
        'userOrientationNumber': json['userOrientationNumber'],
        'userSystem': json['userSystem'],
        'userBan': json['userBan'],
        'userUserGroup': json['userUserGroup'],
        'userConscriptionNumber': json['userConscriptionNumber'],
        'userDistrict': json['userDistrict'],
        'userSurname': json['userSurname'],
        'userConfirmed': json['userConfirmed'],
        'userNotes': json['userNotes'],
        'userLogin': json['userLogin'],
        'userTeacher': json['userTeacher'],
        'userStreet': json['userStreet'],
        'userBirthDate': (new Date(json['userBirthDate'])),
        'userPassword': json['userPassword'],
        'userCity': json['userCity'],
        'userGender': json['userGender'],
        'userName': json['userName'],
        'userUpdatedAt': json['userUpdatedAt'],
        'userPostalCode': json['userPostalCode'],
        'userCreatedAt': json['userCreatedAt'],
        'userLevel': json['userLevel'],
        'userGdprSignedAt': !exists(json, 'userGdprSignedAt') ? undefined : json['userGdprSignedAt'],
        'userLock': json['userLock'],
        'userEmail': json['userEmail'],
        'userPhone': json['userPhone'],
        'userNationality': json['userNationality'],
        'userMemberUntil': !exists(json, 'userMemberUntil') ? undefined : json['userMemberUntil'],
        'userMemberSince': !exists(json, 'userMemberSince') ? undefined : json['userMemberSince'],
        'userDancer': json['userDancer'],
    };
}

export function UserToJSON(value?: User | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userPaymentGroup': value.userPaymentGroup,
        'userOrientationNumber': value.userOrientationNumber,
        'userSystem': value.userSystem,
        'userBan': value.userBan,
        'userUserGroup': value.userUserGroup,
        'userConscriptionNumber': value.userConscriptionNumber,
        'userDistrict': value.userDistrict,
        'userSurname': value.userSurname,
        'userConfirmed': value.userConfirmed,
        'userNotes': value.userNotes,
        'userLogin': value.userLogin,
        'userTeacher': value.userTeacher,
        'userStreet': value.userStreet,
        'userBirthDate': (value.userBirthDate.toISOString().substr(0,10)),
        'userPassword': value.userPassword,
        'userCity': value.userCity,
        'userGender': value.userGender,
        'userName': value.userName,
        'userUpdatedAt': value.userUpdatedAt,
        'userPostalCode': value.userPostalCode,
        'userCreatedAt': value.userCreatedAt,
        'userLevel': value.userLevel,
        'userGdprSignedAt': value.userGdprSignedAt,
        'userLock': value.userLock,
        'userEmail': value.userEmail,
        'userPhone': value.userPhone,
        'userNationality': value.userNationality,
        'userMemberUntil': value.userMemberUntil,
        'userMemberSince': value.userMemberSince,
        'userDancer': value.userDancer,
    };
}


