<?php
header_main('Atletická příprava');
?>
<p>Na přelomu měsíců července a srpna zorganizoval náš klub ve spolupráci s profesionálními atletickými 
trenéry Atletického klubu Olomouc fyzickou přípravu zaměřenou na taneční sport.</p>

<p>Ve čtyřech týdnech proběhlo celkem osm dvouhodinových tréninků, které zpestřily a doplnily přípravu 
na novou taneční sezónu. Atletických tréninků se účastnilo více než dvacet členů od juniorů po dospěláky.</p>

<p>U drtivé většiny zúčastněných měla akce velmi pozitivní ohlasy a určitě ji hodláme v budoucnu zopakovat. 
Tímto děkujeme i trenérům Radkovi a Davidovi, kteří odvedli výbornou práci.</p>

<img src="/images/atletika/atletika01.jpg" class="f_doc_left" style="height:200px;">
<img src="/images/atletika/atletika02.jpg" class="f_doc_right" style="height:200px;">
<img src="/images/atletika/atletika03.jpg" class="f_doc_left" style="height:200px;">
<img src="/images/atletika/atletika04.jpg" class="f_doc_right" style="height:200px;">
