<?php
header_main('Letní soustředění');
?>

<p>
<img src="/images/soustredeni/hotel2.jpg" class="f_doc_right" style="height:150px;">
Na konci měsíce srpna náš klub zorganizoval taneční soustředění Loštice 2011. Soustředění se konalo 
poprvé v útulném areálu hotelu Střelnice v Lošticích, který nám poskytl ty nejlepší podmínky pro vrchol 
letní přípravy. </p>

<p>Na soustředění se vyučovali ti nejlepší trenéři v České republice. Latinu měl na Starosti Jarda Kučera, 
Filip Karásek, Sabina Pišková a Kamila Limberková, standardní tance měl na starosti Martin Odstrčil, Pavla 
Landsfeldová a Miroslav Hýža. Velký kus práce odvedli další kluboví trenéři Tereza Jendrulková, Lucie Benýšková, 
Adam Jendrulek, Pavel John, Radim a Ruda Stupkovi, Kristýna Hlavicová, Vít Navrátil a Petra Chytilová.</p>

<p>Tito všichni se dohromady podíleli na více než 200 odučených individuálních lekcích a 24 skupinových seminářích. 
Na pohybovou průpravu byli přizváni specialisté na pilates a zdravotní posilování.</p>

<p>Z řad tanečníků se soustředění účastnilo přes šedesát členů TK Olymp Olomouc od nejmenších dětí po dospěláky. 
Počtem tanečníků i trenérů se stalo největším soustředěním, které kdy náš klub uspořádal, takže za rok bude 
co překonávat. :-)</p>

<p>Tady je několik ze statusů, které se začaly na Facebooku rojit po příjezdu domů. I podle nich můžeme 
konstatovat, že soustředění se povedlo:</p>

<ul class="list">
<li>nějak moc rychle to uteklo.. za rok znovu? :)</li>
<li>nejskvělejší týden s těma nejlepšíma lidma co kolem sebe mam !:) TK Olymp Olomouc 
a parta trenérů z loštickýho soustřéďa !:) všem děkuju za skvělý soustředění :)</li>
<li>zažila jsem LUXUSNÍ soustředění</li>
<li>nejlepší soustředená v Lošticích :)</li>
<li>zpět z úžasného soustřeďka v Lošticích :-)</li>
<li>super soustředko se skvělýma lidičkama je za mnou :( ale spousta tréningů před námi ... aneb od zítřka zase makáme :))</li>
<li>Paráda, dal bych si to znova... a teď to už "jen" natrénovat :-)</li>
</ul>

<img src="/images/soustredeni/lostice2011.jpg" class="f_doc" style="height:300px;">
