--! Previous: sha1:2aae0093ecf6c788960193f6a040113b9f1d569a
--! Hash: sha1:b56663014bef9515f08cdb511970516ef716ab88

-- Write your migration here

DROP TABLE IF EXISTS cohort_group CASCADE;
CREATE TABLE cohort_group (
       id bigint generated by default as identity primary key,
       name text not null,
       description jsonb not null default '[]'::jsonb,
       ordering int not null default 1,
       is_public boolean not null default true,
       tenant bigint references tenant
);
revoke ALL ON TABLE cohort_group from anonymous;
grant select ON TABLE cohort_group TO anonymous;
GRANT ALL ON TABLE cohort_group TO administrator;

alter table skupiny drop column if exists cohort_group cascade;
alter table skupiny add column cohort_group bigint references cohort_group null default null;
