--! Previous: sha1:a20ba927828e25186cc212247b7301fcd725ffbe
--! Hash: sha1:5bd863eeb007c778a751f756b4ae67b8c4a202a0

--! split: 1-current.sql
-- Drop dependent functions so we can replace the announcement view
-- with a real table while keeping callers intact.
drop function if exists public.archived_announcements();
drop function if exists public.sticky_announcements(boolean);
drop function if exists public.my_announcements(boolean, boolean);
drop function if exists public.archived_announcement_new();
drop function if exists public.sticky_announcement_new();
drop function if exists public.my_announcement_new(boolean);

do $$
begin
  if exists (select 1 from pg_views where viewname = 'announcement') then
    drop view if exists announcement;
  end if;
  if exists (select 1 from pg_Tables where tablename = 'upozorneni') and exists (select 1 from pg_tables where tablename = 'announcement') then
    drop table if exists announcement;
  end if;
end;
$$;

create table if not exists public.announcement (
  id bigint generated by default as identity,
  tenant_id bigint not null default public.current_tenant_id(),
  author_id bigint,
  title text not null,
  body text not null,
  is_locked boolean not null default false,
  is_visible boolean not null default true,
  is_sticky boolean not null default false,
  created_at timestamptz not null default CURRENT_TIMESTAMP,
  updated_at timestamptz,
  scheduled_since timestamptz,
  scheduled_until timestamptz,
  constraint announcement_pkey primary key (id),
  constraint announcement_tenant_id_fkey foreign key (tenant_id) references public.tenant(id) on delete cascade,
  constraint announcement_author_id_fkey foreign key (author_id) references public.users(u_id) on update restrict on delete restrict
);

grant all on table public.announcement to anonymous;

alter table public.announcement enable row level security;
select app_private.drop_policies('public.announcement');

create policy admin_all on public.announcement to administrator using (true) with check (true);
create policy current_tenant on public.announcement as restrictive using ((tenant_id = public.current_tenant_id()));
create policy member_view on public.announcement for select to member using (true);

create index if not exists announcement_author_id_idx on public.announcement (author_id);
create index if not exists announcement_created_at_idx on public.announcement (created_at);
create index if not exists announcement_tenant_id_idx on public.announcement (tenant_id);

drop trigger if exists _100_timestamps on public.announcement;
create trigger _100_timestamps
  before insert or update on public.announcement
  for each row execute function app_private.tg__timestamps();

create or replace function public.on_update_author_announcement() returns trigger
    language plpgsql
    as $$
begin
  if new.author_id is null then
    new.author_id = current_user_id();
  end if;
  return new;
end;
$$;
select verify_function('public.on_update_author_announcement', 'public.announcement');

drop trigger if exists on_update_author_announcement on public.announcement;
create trigger on_update_author_announcement
  before insert or update on public.announcement
  for each row execute function public.on_update_author_announcement();

insert into public.announcement (
  id,
  tenant_id,
  author_id,
  title,
  body,
  is_locked,
  is_visible,
  is_sticky,
  created_at,
  updated_at,
  scheduled_since,
  scheduled_until
)
select
  up_id,
  tenant_id,
  up_kdo,
  up_nadpis,
  up_text,
  up_lock,
  coalesce(is_visible, true),
  sticky,
  created_at,
  updated_at,
  scheduled_since,
  scheduled_until
from public.upozorneni
on conflict (id) do update set
  tenant_id = excluded.tenant_id,
  author_id = excluded.author_id,
  title = excluded.title,
  body = excluded.body,
  is_locked = excluded.is_locked,
  is_visible = excluded.is_visible,
  is_sticky = excluded.is_sticky,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  scheduled_since = excluded.scheduled_since,
  scheduled_until = excluded.scheduled_until;

do $$
declare
  seq text;
  max_id bigint;
begin
  select pg_get_serial_sequence('public.announcement', 'id') into seq;
  if seq is not null then
    select coalesce(max(id), 0) into max_id from public.announcement;
    if max_id = 0 then
      execute format('select setval(%L, 1, false);', seq);
    else
      execute format('select setval(%L, %s, true);', seq, max_id);
    end if;
  end if;
end;
$$;

create or replace function public.archived_announcements() returns setof public.announcement
    language sql stable
    as $$
  select announcement.*
  from public.announcement
  where is_visible = false
     or (scheduled_until is null or scheduled_until >= now())
  order by created_at desc;
$$;
grant all on function public.archived_announcements() to anonymous;

create or replace function public.sticky_announcements(order_by_updated boolean default false) returns setof public.announcement
    language sql stable
    as $$
  select announcement.*
  from public.announcement
  where is_visible = true and is_sticky = true
    and (scheduled_since is null or scheduled_since <= now())
    and (scheduled_until is null or scheduled_until >= now())
  order by
    case when order_by_updated then updated_at else created_at end desc,
    created_at desc;
$$;
grant all on function public.sticky_announcements(order_by_updated boolean) to anonymous;

create or replace function public.my_announcements(archive boolean default false, order_by_updated boolean default false) returns setof public.announcement
    language sql stable
    as $$
  select announcement.*
  from public.announcement
  where is_visible = not archive and is_sticky = false
    and (scheduled_since is null or scheduled_since <= now())
    and (scheduled_until is null or scheduled_until >= now())
  order by
    case when order_by_updated then updated_at else created_at end desc,
    created_at desc;
$$;
grant all on function public.my_announcements(archive boolean, order_by_updated boolean) to anonymous;
