--! Previous: sha1:4bb4fd6dadb86e22e4fd85c5cfa708c9d13c9409
--! Hash: sha1:bf5fe0c2ec1095bc783aae399898b8462c82589c

--! split: 1-current.sql
comment on table public.event_instance_registration is E'@omit create,update,delete\n@simpleCollections both';

comment on function public.register_to_event_many(public.register_to_event_type[]) is '@omit';
comment on function public.edit_registration(bigint, text) is '@omit';
comment on function public.cancel_registration(bigint) is '@omit';

do $$
begin
  if not exists (
    select 1
    from pg_catalog.pg_type type
    join pg_catalog.pg_namespace namespace on namespace.oid = type.typnamespace
    where namespace.nspname = 'public'
      and type.typname = 'event_registration_source'
  ) then
    create type public.event_registration_source
      as enum ('self', 'manager', 'cohort');
  end if;
end;
$$;

alter table public.event_instance_registration
  add column if not exists source public.event_registration_source;

create table if not exists public.event_instance_target_cohort (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default public.current_tenant_id()
    references public.tenant(id) on update cascade on delete cascade,
  instance_id bigint not null
    references public.event_instance(id) on update cascade on delete cascade,
  cohort_id bigint not null
    references public.cohort(id) on update cascade on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (instance_id, cohort_id)
);

comment on constraint event_instance_target_cohort_instance_id_fkey
  on public.event_instance_target_cohort is
  E'@fieldName instance\n@foreignFieldName targetCohorts';

comment on table public.event_instance_target_cohort is E'@omit create,update,delete\n@behavior -query:resource:list -query:resource:connection -query:resource:single\n@simpleCollections only';
grant all on table public.event_instance_target_cohort to anonymous;
grant usage, select on sequence public.event_instance_target_cohort_id_seq to anonymous;
alter table public.event_instance_target_cohort enable row level security;

create index if not exists event_instance_target_cohort_tenant_id_idx
  on public.event_instance_target_cohort (tenant_id);
create index if not exists event_instance_target_cohort_cohort_id_idx
  on public.event_instance_target_cohort (cohort_id);

drop trigger if exists _100_timestamps on public.event_instance_target_cohort;

do $$
begin
  if exists (
    select 1 from pg_constraint
    where conname = 'event_instance_registration_target_cohort_id_fkey'
      and conrelid = 'public.event_instance_registration'::regclass
      and confrelid = 'public.event_target_cohort'::regclass
  ) then
    insert into public.event_instance_target_cohort (
      tenant_id, instance_id, cohort_id, created_at, updated_at
    )
    select target.tenant_id, instance.id, target.cohort_id,
      target.created_at, target.updated_at
    from public.event_target_cohort target
    join public.event_instance instance on instance.event_id = target.event_id
    on conflict (instance_id, cohort_id) do nothing;

    alter table public.event_instance_registration
      drop constraint event_instance_registration_target_cohort_id_fkey;

    alter table public.event_instance_registration disable trigger _100_timestamps;
    update public.event_instance_registration registration
    set target_cohort_id = target.cohort_id
    from public.event_target_cohort target
    where target.id = registration.target_cohort_id;
    alter table public.event_instance_registration enable trigger _100_timestamps;

    alter table public.event_instance_registration
      add constraint event_instance_registration_target_cohort_id_fkey
      foreign key (target_cohort_id) references public.cohort(id)
      on update cascade on delete restrict;
  end if;
end;
$$;

alter table public.event_instance_registration disable trigger _100_timestamps;
update public.event_instance_registration
set source = 'cohort'
where parent_registration_id is null
  and target_cohort_id is not null
  and source is null;
alter table public.event_instance_registration enable trigger _100_timestamps;

create trigger _100_timestamps before insert or update on public.event_instance_target_cohort
  for each row execute function app_private.tg__timestamps();

drop trigger if exists _500_register_members on public.event_target_cohort;
drop trigger if exists _500_unregister_members on public.event_target_cohort;

--! Included policies/event_instance_target_cohort.sql
select app_private.drop_policies('public.event_instance_target_cohort');

create policy current_tenant on public.event_instance_target_cohort as restrictive
  using (tenant_id = (select public.current_tenant_id()));
create policy admin_all on public.event_instance_target_cohort to administrator using (true);
create policy trainer_select on public.event_instance_target_cohort for select to trainer
  using (app_private.can_trainer_edit_instance(instance_id));
create policy trainer_insert on public.event_instance_target_cohort for insert to trainer
  with check (app_private.can_trainer_edit_instance(instance_id));
create policy trainer_update on public.event_instance_target_cohort for update to trainer
  using (app_private.can_trainer_edit_instance(instance_id))
  with check (app_private.can_trainer_edit_instance(instance_id));
create policy trainer_delete on public.event_instance_target_cohort for delete to trainer
  using (app_private.can_trainer_edit_instance(instance_id));
create policy member_view on public.event_instance_target_cohort for select to member
  using (instance_id in (select id from public.event_instance));
--! EndIncluded policies/event_instance_target_cohort.sql
--! Included functions/sync_eir_registrations.sql
create or replace function app_private.sync_eir_registrations(reg_ids bigint[])
  returns void
  language plpgsql
  security definer
  set search_path = pg_catalog, public, pg_temp
as $$
begin
  -- Legacy targetless registrations do not record who created them, so their
  -- source stays null; cohort-backed roots can be classified exactly.
  insert into event_instance_registration
    (legacy_registration_id, tenant_id, instance_id, event_id, couple_id,
      target_cohort_id, source, note)
  select er.id, er.tenant_id, ei.id, er.event_id, er.couple_id,
    target.cohort_id,
    case when target.cohort_id is not null then 'cohort'::event_registration_source end,
    er.note
  from event_registration er
  join event_instance ei on ei.event_id = er.event_id
  left join event_target_cohort target on target.id = er.target_cohort_id
  where er.couple_id is not null and er.id = any (reg_ids)
  on conflict (legacy_registration_id, instance_id, (coalesce(person_id, -1))) do update
    set event_id = excluded.event_id,
        couple_id = excluded.couple_id,
        note = excluded.note;

  insert into event_instance_registration
    (legacy_registration_id, parent_registration_id, tenant_id, instance_id, event_id, person_id, status)
  select er.id, unit.id, er.tenant_id, ei.id, er.event_id, people.person_id, 'unknown'
  from event_registration er
  join event_instance ei on ei.event_id = er.event_id
  join event_instance_registration unit
    on unit.legacy_registration_id = er.id and unit.instance_id = ei.id and unit.person_id is null
  cross join lateral app_private.event_registration_person_ids(er) as people(person_id)
  where er.couple_id is not null and er.id = any (reg_ids)
  on conflict (legacy_registration_id, instance_id, (coalesce(person_id, -1))) do update
    set parent_registration_id = excluded.parent_registration_id,
        event_id = excluded.event_id;

  insert into event_instance_registration
    (legacy_registration_id, tenant_id, instance_id, event_id, person_id, status,
      note, target_cohort_id, source)
  select er.id, er.tenant_id, ei.id, er.event_id, er.person_id, 'unknown', er.note,
    target.cohort_id,
    case when target.cohort_id is not null then 'cohort'::event_registration_source end
  from event_registration er
  join event_instance ei on ei.event_id = er.event_id
  left join event_target_cohort target on target.id = er.target_cohort_id
  where er.couple_id is null and er.id = any (reg_ids)
  on conflict (legacy_registration_id, instance_id, (coalesce(person_id, -1))) do update
    set event_id = excluded.event_id,
        note = excluded.note,
        parent_registration_id = excluded.parent_registration_id,
        couple_id = excluded.couple_id;

  delete from event_instance_registration registration
  where registration.legacy_registration_id = any (reg_ids)
    and not exists (
      select 1
      from event_registration er
      join event_instance ei on ei.event_id = er.event_id
      where er.id = registration.legacy_registration_id
        and ei.id = registration.instance_id
        and (
          (registration.person_id is null and er.couple_id is not null)
          or registration.person_id in (select app_private.event_registration_person_ids(er))
        )
    );
end;
$$;

select verify_function('app_private.sync_eir_registrations');
grant all on function app_private.sync_eir_registrations(bigint[]) to anonymous;
--! EndIncluded functions/sync_eir_registrations.sql
--! Included functions/reconcile_event_instance_cohort_registrations.sql
create or replace function app_private.reconcile_event_instance_cohort_registrations(
  p_instance_ids bigint[],
  p_person_ids bigint[] default null
) returns void
  language sql
  security definer
  set search_path = pg_catalog, public, pg_temp
as $$
  select instance.id
  from event_instance instance
  where instance.id = any (p_instance_ids)
  order by instance.id
  for update;

  with desired as (
    select target.instance_id, membership.person_id,
      min(target.cohort_id) as target_cohort_id
    from event_instance_target_cohort target
    join event_instance instance on instance.id = target.instance_id
    join cohort_membership membership on membership.cohort_id = target.cohort_id
    where target.instance_id = any (p_instance_ids)
      and instance.since >= now()
      and membership.status = 'active'
      and membership.active_range @> now()
      and (p_person_ids is null or membership.person_id = any (p_person_ids))
    group by target.instance_id, membership.person_id
  )
  update event_instance_registration r
  set registration_status = 'active',
      source = 'cohort',
      target_cohort_id = desired.target_cohort_id
  from desired
  where r.instance_id = desired.instance_id
    and r.person_id = desired.person_id
    and r.parent_registration_id is null
    and r.source = 'cohort'
    and (r.registration_status, r.target_cohort_id)
      is distinct from (
        'active'::event_instance_registration_status,
        desired.target_cohort_id
      );

  with desired as (
    select target.instance_id, instance.tenant_id, membership.person_id,
      min(target.cohort_id) as target_cohort_id
    from event_instance_target_cohort target
    join event_instance instance on instance.id = target.instance_id
    join cohort_membership membership on membership.cohort_id = target.cohort_id
    where target.instance_id = any (p_instance_ids)
      and instance.since >= now()
      and membership.status = 'active'
      and membership.active_range @> now()
      and (p_person_ids is null or membership.person_id = any (p_person_ids))
    group by target.instance_id, instance.tenant_id, membership.person_id
  )
  insert into event_instance_registration (
    tenant_id, instance_id, person_id, target_cohort_id,
    source, status
  )
  select desired.tenant_id, desired.instance_id, desired.person_id,
    desired.target_cohort_id, 'cohort', 'unknown'
  from desired
  where not exists (
    select 1
    from event_instance_registration r
    where r.instance_id = desired.instance_id
      and r.person_id = desired.person_id
      and r.parent_registration_id is null
  );

  update event_instance_registration r
  set registration_status = 'cancelled'
  from event_instance instance
  where r.instance_id = instance.id
    and r.instance_id = any (p_instance_ids)
    and r.parent_registration_id is null
    and r.source = 'cohort'
    and r.registration_status = 'active'
    and instance.since >= now()
    and (p_person_ids is null or r.person_id = any (p_person_ids))
    and not exists (
      select 1
      from event_instance_target_cohort target
      join cohort_membership membership
        on membership.cohort_id = target.cohort_id
       and membership.person_id = r.person_id
      where target.instance_id = r.instance_id
        and membership.status = 'active'
        and membership.active_range @> now()
    );
$$;
revoke execute on function app_private.reconcile_event_instance_cohort_registrations from public, anonymous;

create or replace function app_private.tg_event_instance_target_cohort__reconcile()
  returns trigger
  language plpgsql
  security definer
  set search_path = pg_catalog, public, pg_temp
as $$
begin
  if tg_op = 'DELETE' then
    perform app_private.reconcile_event_instance_cohort_registrations(array[old.instance_id]);
    return old;
  end if;

  perform app_private.reconcile_event_instance_cohort_registrations(
    case when tg_op = 'UPDATE' and old.instance_id <> new.instance_id
      then array[old.instance_id, new.instance_id]
      else array[new.instance_id]
    end
  );
  return new;
end;
$$;
revoke execute on function app_private.tg_event_instance_target_cohort__reconcile()
  from public, anonymous;

select verify_function(
  'app_private.tg_event_instance_target_cohort__reconcile',
  'public.event_instance_target_cohort'
);

drop trigger if exists _500_reconcile_registrations on public.event_instance_target_cohort;
create trigger _500_reconcile_registrations
  after insert or delete or update of instance_id, cohort_id
  on public.event_instance_target_cohort
  for each row execute function app_private.tg_event_instance_target_cohort__reconcile();
--! EndIncluded functions/reconcile_event_instance_cohort_registrations.sql
--! Included functions/tg_cohort_membership__on_status.sql
CREATE or replace FUNCTION app_private.tg_cohort_membership__on_status()
  RETURNS trigger LANGUAGE plpgsql
  security definer
  SET search_path = pg_catalog, public, app_private
  AS $$
declare
  instance_ids bigint[];
  person_ids bigint[];
begin
  select array_agg(distinct target.instance_id)
  into instance_ids
  from event_instance_target_cohort target
  join event_instance instance on instance.id = target.instance_id
  where target.cohort_id = any (
    case when tg_op = 'INSERT' then array[new.cohort_id]
      when tg_op = 'DELETE' then array[old.cohort_id]
      else array[old.cohort_id, new.cohort_id]
    end
  ) and instance.since >= now();

  if instance_ids is not null then
    person_ids := case when tg_op = 'INSERT' then array[new.person_id]
      when tg_op = 'DELETE' then array[old.person_id]
      else array[old.person_id, new.person_id]
    end;
    perform app_private.reconcile_event_instance_cohort_registrations(instance_ids, person_ids);
  end if;

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

grant all on function app_private.tg_cohort_membership__on_status to trainer;
select verify_function('app_private.tg_cohort_membership__on_status', 'cohort_membership');

DROP TRIGGER IF EXISTS _500_on_status ON public.cohort_membership;
CREATE TRIGGER _500_on_status
  AFTER INSERT OR DELETE OR UPDATE OF status, cohort_id, person_id, since, until
  ON public.cohort_membership
  FOR EACH ROW EXECUTE FUNCTION app_private.tg_cohort_membership__on_status();
--! EndIncluded functions/tg_cohort_membership__on_status.sql
--! Included functions/event_instance_target_cohorts.sql
drop function if exists public.event_instance_target_cohorts(public.event_instance);

create function public.event_instance_target_cohorts(inst public.event_instance)
  returns setof public.event_instance_target_cohort
  language sql stable as $$
  select * from public.event_instance_target_cohort where instance_id = inst.id;
$$;

comment on function public.event_instance_target_cohorts(public.event_instance)
  is '@omit';
grant all on function public.event_instance_target_cohorts(public.event_instance) to anonymous;
--! EndIncluded functions/event_instance_target_cohorts.sql
--! Included functions/scoreboard.sql
drop view if exists scoreboard;
drop function if exists scoreboard_entries;

create or replace function scoreboard_entries(
  since date,
  until date,
  cohort_id bigint default null
)
returns setof scoreboard_record
language sql
stable
as $$
  with membership as (
    select cm.person_id, cm.cohort_id
    from current_cohort_membership cm
    where (cm.cohort_id = scoreboard_entries.cohort_id or scoreboard_entries.cohort_id is null)
  ),
  instances as (
    select
      i.id as instance_id,
      i.since,
      i.until,
      i.type as event_type
    from event_instance i
    where not i.is_cancelled
      and i.since >= scoreboard_entries.since::timestamptz
      and i.until  < scoreboard_entries.until::timestamptz
      and i.type <> 'reservation'
  ),
  member_people as (
    select distinct person_id
    from membership
  ),
  attendance as materialized (
    select
      ea.person_id,
      scoreboard_entries.cohort_id as cohort_id,
      case when inst.event_type = 'lesson' then 1 else 0 end as lesson_score,
      case when inst.event_type = 'group' then floor((extract(epoch from (inst.until - inst.since)) / 60)::numeric / 45::numeric) else 0 end as group_score,
      case when inst.event_type = 'camp'  then 3 + 2 * ((extract(epoch from (inst.until - inst.since)) > 86400)::int) else 0 end as event_score,
      date_trunc('day', inst.since)::date as day
    from instances inst
    join event_instance_registration ea
      on ea.instance_id = inst.instance_id and ea.person_id is not null
    left join event_instance_registration registration
      on registration.id = ea.parent_registration_id
    left join cohort tc
      on tc.id = coalesce(ea.target_cohort_id, registration.target_cohort_id)
    where
      ea.registration_status = 'active'
      and ea.status <> 'cancelled'
      and (ea.status = 'attended' or inst.event_type = 'lesson')
      and ea.person_id = any (select person_id from member_people)
      and (scoreboard_entries.cohort_id is null or tc.id = scoreboard_entries.cohort_id)
  ),
  per_day as (
    select
      person_id,
      cohort_id,
      least(sum(lesson_score), 4) as lesson_score,
      sum(group_score) as group_score,
      sum(event_score) as event_score
    from attendance
    group by person_id, cohort_id, day
  ),
  aggregated as (
    select
      person_id,
      cohort_id,
      coalesce(sum(lesson_score), 0)::bigint as lesson_total_score,
      coalesce(sum(group_score), 0)::bigint as group_total_score,
      coalesce(sum(event_score), 0)::bigint as event_total_score
    from per_day
    group by person_id, cohort_id
  ),
  manual as (
    select
      sma.person_id,
      case
        when scoreboard_entries.cohort_id is null then null
        else coalesce(sma.cohort_id, scoreboard_entries.cohort_id)
      end as cohort_id,
      sum(sma.points)::bigint as manual_total_score
    from scoreboard_manual_adjustment sma
    where sma.tenant_id = current_tenant_id()
      and sma.awarded_at >= scoreboard_entries.since
      and sma.awarded_at < scoreboard_entries.until
      and (
        scoreboard_entries.cohort_id is null or
        sma.cohort_id is null or
        sma.cohort_id = scoreboard_entries.cohort_id
      )
      and exists (
        select 1
        from membership mem
        where mem.person_id = sma.person_id
          and (
            (scoreboard_entries.cohort_id is null and sma.cohort_id is null)
            or mem.cohort_id is not distinct from coalesce(sma.cohort_id, scoreboard_entries.cohort_id)
          )
      )
    group by 1, 2
  ),
  totals as (
    select
      coalesce(a.person_id, m.person_id) as person_id,
      coalesce(a.cohort_id, m.cohort_id) as cohort_id,
      coalesce(a.lesson_total_score, 0)::bigint as lesson_total_score,
      coalesce(a.group_total_score, 0)::bigint as group_total_score,
      coalesce(a.event_total_score, 0)::bigint as event_total_score,
      coalesce(m.manual_total_score, 0)::bigint as manual_total_score,
      (
        coalesce(a.lesson_total_score, 0)::bigint +
        coalesce(a.group_total_score, 0)::bigint +
        coalesce(a.event_total_score, 0)::bigint +
        coalesce(m.manual_total_score, 0)::bigint
      ) as total_score
    from aggregated a
    full join manual m using (person_id, cohort_id)
  )
  select
    person_id,
    cohort_id,
    lesson_total_score,
    group_total_score,
    event_total_score,
    manual_total_score,
    total_score,
    rank() over (order by total_score desc, person_id) as ranking
  from totals
  order by total_score desc, person_id;
$$;

comment on function scoreboard_entries is '@simpleCollections only';

grant all on function scoreboard_entries to anonymous;
--! EndIncluded functions/scoreboard.sql
--! Included functions/set_event_instance_registration.sql
drop function if exists public.set_event_instance_registration(bigint, bigint, bigint, boolean);

create or replace function public.set_event_instance_registration(
  p_instance_id bigint,
  p_person_id bigint,
  p_couple_id bigint,
  p_is_registered boolean,
  p_note text default null
) returns public.event_instance_registration
  language plpgsql
  security definer
  set search_path = pg_catalog, public, pg_temp
as $$
declare
  target_instance event_instance;
  registration event_instance_registration;
  registration_found boolean;
  required_capacity integer;
  remaining_capacity integer;
begin
  if p_is_registered is null or num_nonnulls(p_person_id, p_couple_id) <> 1 then
    raise exception 'INVALID_REGISTRANT' using errcode = '22023';
  end if;

  if (p_person_id is not null
      and p_person_id <> all(coalesce(current_person_ids(), '{}'::bigint[])))
    or (p_couple_id is not null
      and p_couple_id <> all(coalesce(current_couple_ids(), '{}'::bigint[]))) then
    raise exception 'ACCESS_DENIED' using errcode = '42501';
  end if;

  select * into target_instance
  from event_instance
  where id = p_instance_id
    and tenant_id = current_tenant_id()
  for update;

  if not found then
    raise exception 'INSTANCE_NOT_FOUND' using errcode = '22023';
  end if;
  if target_instance.is_locked then
    raise exception 'NOT_ALLOWED' using errcode = '28000';
  end if;

  select * into registration
  from event_instance_registration
  where instance_id = p_instance_id
    and parent_registration_id is null
    and person_id is not distinct from p_person_id
    and couple_id is not distinct from p_couple_id;
  registration_found := found;

  if not p_is_registered then
    if not registration_found then
      raise exception 'REGISTRATION_NOT_FOUND' using errcode = '22023';
    end if;

    update event_instance_registration
    set registration_status = 'cancelled',
        target_cohort_id = null,
        source = case when id = registration.id
          then 'self'::event_registration_source end
    where id = registration.id or parent_registration_id = registration.id;

    select * into registration from event_instance_registration where id = registration.id;
    return registration;
  end if;

  if registration_found and registration.registration_status = 'active' then
    if p_note is not null then
      update event_instance_registration set note = p_note where id = registration.id
      returning * into registration;
    end if;
    return registration;
  end if;

  if target_instance.is_cancelled
    or target_instance.until <= now()
    or not (
      coalesce(target_instance.is_public, false)
      or (
        coalesce(target_instance.is_visible, false)
        and current_tenant_id() = any(my_tenants_array())
      )
    ) then
    raise exception 'NOT_ALLOWED' using errcode = '28000';
  end if;

  remaining_capacity := event_instance_remaining_person_spots(target_instance);
  required_capacity := case
    when target_instance.capacity_unit = 'people' and p_couple_id is not null then 2
    else 1
  end;
  if remaining_capacity is not null and remaining_capacity < required_capacity then
    raise exception 'CAPACITY_EXCEEDED' using errcode = '22023';
  end if;

  if registration_found then
    update event_instance_registration
    set registration_status = 'active',
        target_cohort_id = null,
        source = case when id = registration.id
          then 'self'::event_registration_source end
    where id = registration.id or parent_registration_id = registration.id;

    if p_note is not null then
      update event_instance_registration set note = p_note where id = registration.id;
    end if;
  else
    insert into event_instance_registration (
      instance_id, person_id, couple_id, source, status, note
    ) values (
      p_instance_id, p_person_id, p_couple_id, 'self',
      case when p_person_id is not null then 'unknown'::attendance_type end,
      p_note
    ) returning * into registration;

    insert into event_instance_registration (
      instance_id, parent_registration_id, person_id, status
    )
    select p_instance_id, registration.id, person.person_id, 'unknown'
    from couple
    cross join lateral unnest(array[couple.man_id, couple.woman_id]) person(person_id)
    where couple.id = p_couple_id;
  end if;

  select * into registration from event_instance_registration where id = registration.id;
  return registration;
end;
$$;

select verify_function('public.set_event_instance_registration');
grant execute on function public.set_event_instance_registration(bigint, bigint, bigint, boolean, text)
  to anonymous;
--! EndIncluded functions/set_event_instance_registration.sql
--! Included functions/update_event_instance_details.sql
drop function if exists public.update_event_instance_details(
  bigint, timestamptz, timestamptz, text, public.event_type, bigint, text,
  boolean, boolean, boolean, bigint[]
);
drop function if exists public.update_event_instance_details(
  bigint, timestamptz, timestamptz, text, public.event_type, bigint, text,
  boolean, boolean, boolean, bigint[], public.quick_event_registration_input[]
);
drop function if exists public.update_event_instance_details(
  bigint, timestamptz, timestamptz, text, public.event_type, bigint, text,
  boolean, boolean, boolean, bigint[], public.quick_event_registration_input[],
  integer, public.event_capacity_unit, boolean
);
drop function if exists public.update_event_instance_details(
  bigint, timestamptz, timestamptz, text, public.event_type, bigint, text,
  boolean, boolean, boolean, bigint[], public.quick_event_registration_input[],
  integer, public.event_capacity_unit, boolean, integer[]
);

create or replace function public.update_event_instance_details(
  p_instance_id bigint,
  p_since timestamptz,
  p_until timestamptz,
  p_name text,
  p_type public.event_type,
  p_location_id bigint,
  p_location_text text,
  p_is_visible boolean,
  p_is_public boolean,
  p_is_cancelled boolean,
  p_trainer_person_ids bigint[] default null,
  p_registrations public.quick_event_registration_input[] default null,
  p_capacity integer default null,
  p_capacity_unit public.event_capacity_unit default null,
  p_is_locked boolean default null,
  p_trainer_lessons_offered integer[] default null,
  p_cohort_ids bigint[] default null
) returns public.event_instance
  language plpgsql
as $$
declare
  updated_instance public.event_instance;
begin
  if p_registrations is not null then
    perform registration.id
    from public.event_instance_registration registration
    where registration.instance_id = p_instance_id
    order by registration.id
    for update;
  end if;

  update public.event_instance
  set
    since = p_since,
    until = p_until,
    name = p_name,
    type = p_type,
    location_id = p_location_id,
    location_text = coalesce(p_location_text, ''),
    is_visible = coalesce(p_is_visible, is_visible),
    is_public = coalesce(p_is_public, is_public),
    capacity = coalesce(p_capacity, capacity),
    capacity_unit = coalesce(p_capacity_unit, capacity_unit),
    is_locked = coalesce(p_is_locked, is_locked),
    is_cancelled = p_is_cancelled
  where id = p_instance_id
  returning * into updated_instance;

  if not found then
    raise exception 'event instance % not found', p_instance_id;
  end if;

  if p_registrations is not null then
    with desired as (
      select distinct registration.person_id, registration.couple_id
      from unnest(p_registrations) registration
    ), roots as (
      select existing.id
      from public.event_instance_registration existing
      where existing.instance_id = p_instance_id
        and existing.parent_registration_id is null
        and not exists (
          select 1
          from desired
          where desired.person_id is not distinct from existing.person_id
            and desired.couple_id is not distinct from existing.couple_id
        )
    )
    update public.event_instance_registration registration
    set registration_status = 'cancelled',
        target_cohort_id = null,
        source = case when registration.id = roots.id
          then 'manager'::public.event_registration_source end
    from roots
    where registration.registration_status <> 'cancelled'
      and (
        registration.id = roots.id
        or registration.parent_registration_id = roots.id
      );

    with desired as (
      select distinct registration.person_id, registration.couple_id
      from unnest(p_registrations) registration
    ), roots as (
      select existing.id
      from public.event_instance_registration existing
      join desired
        on desired.person_id is not distinct from existing.person_id
        and desired.couple_id is not distinct from existing.couple_id
      where existing.instance_id = p_instance_id
        and existing.parent_registration_id is null
    )
    update public.event_instance_registration registration
    set registration_status = 'active',
        target_cohort_id = null,
        source = case when registration.id = roots.id
          then 'manager'::public.event_registration_source end
    from roots
    where registration.registration_status <> 'active'
      and (
        registration.id = roots.id
        or registration.parent_registration_id = roots.id
      );

    with desired as (
      select distinct registration.person_id, registration.couple_id
      from unnest(p_registrations) registration
    ), roots as (
      insert into public.event_instance_registration (
        instance_id, person_id, couple_id, source, status
      )
      select
        p_instance_id,
        desired.person_id,
        desired.couple_id,
        'manager',
        case when desired.person_id is not null then 'unknown'::public.attendance_type end
      from desired
      where not exists (
        select 1
        from public.event_instance_registration existing
        where existing.instance_id = p_instance_id
          and existing.parent_registration_id is null
          and existing.person_id is not distinct from desired.person_id
          and existing.couple_id is not distinct from desired.couple_id
      )
      returning id, couple_id
    )
    insert into public.event_instance_registration (
      instance_id, parent_registration_id, person_id, status
    )
    select p_instance_id, roots.id, person.person_id, 'unknown'
    from roots
    join public.couple couple on couple.id = roots.couple_id
    cross join lateral unnest(array[couple.man_id, couple.woman_id]) person(person_id);
  end if;

  if p_cohort_ids is not null then
    insert into public.event_instance_target_cohort (tenant_id, instance_id, cohort_id)
    select distinct updated_instance.tenant_id, p_instance_id, desired.cohort_id
    from unnest(p_cohort_ids) desired(cohort_id)
    where desired.cohort_id is not null
    on conflict (instance_id, cohort_id) do nothing;

    delete from public.event_instance_target_cohort target
    where target.instance_id = p_instance_id
      and not exists (
        select 1
        from unnest(p_cohort_ids) desired(cohort_id)
        where desired.cohort_id = target.cohort_id
      );
  end if;

  if p_trainer_person_ids is not null then
    if p_trainer_lessons_offered is not null
      and cardinality(p_trainer_lessons_offered) <> cardinality(p_trainer_person_ids) then
      raise exception 'trainer lesson offers must match trainers';
    end if;

    delete from public.event_instance_trainer
    where instance_id = p_instance_id
      and not exists (
        select 1 from unnest(p_trainer_person_ids) person(id)
        where person.id = event_instance_trainer.person_id
      );

    insert into public.event_instance_trainer (instance_id, person_id, lessons_offered)
    select distinct on (input.person_id)
      p_instance_id,
      input.person_id,
      case when p_trainer_lessons_offered is null then 0
        else input.lessons_offered end
    from (
      select p_trainer_person_ids[i] person_id,
        p_trainer_lessons_offered[i] lessons_offered
      from generate_subscripts(p_trainer_person_ids, 1) item(i)
    ) input
    where input.person_id is not null
    order by input.person_id
    on conflict (instance_id, person_id) do update
    set lessons_offered = case when p_trainer_lessons_offered is null
      then event_instance_trainer.lessons_offered
      else excluded.lessons_offered end;
  end if;

  if p_registrations is not null or p_cohort_ids is not null then
    select * into updated_instance
    from public.event_instance
    where id = p_instance_id;
  end if;

  return updated_instance;
end;
$$;

select verify_function('public.update_event_instance_details');
grant all on function public.update_event_instance_details to anonymous;
--! EndIncluded functions/update_event_instance_details.sql
--! Included functions/quick_create_event_instances.sql
create or replace function quick_create_event_instances(
  events quick_event_input[],
  parent_id bigint default null
) returns setof event_instance
  language plpgsql
as $$
declare
  quick_event quick_event_input;
  created_instance event_instance;
begin
  foreach quick_event in array coalesce(events, '{}'::quick_event_input[]) loop
    insert into event_instance (
      parent_id, since, until, name, type, location_id, location_text,
      capacity, capacity_unit, is_visible, is_public, is_locked, enable_notes,
      description, summary
    ) values (
      parent_id, quick_event.since, quick_event.until, '',
      coalesce(quick_event.type, 'lesson'), quick_event.location_id,
      coalesce(quick_event.location_text, ''),
      case when coalesce(quick_event.type, 'lesson') = 'lesson' then 2 else 0 end,
      'people', true, false, false, false, '', ''
    )
    returning * into created_instance;

    with roots as (
      insert into event_instance_registration (
        instance_id, person_id, couple_id, source, status
      )
      select created_instance.id, registration.person_id, registration.couple_id,
        'manager',
        case when registration.person_id is not null then 'unknown'::attendance_type end
      from unnest(quick_event.registrations) registration
      returning id, couple_id
    )
    insert into event_instance_registration (
      instance_id, parent_registration_id, person_id, status
    )
    select created_instance.id, root.id, person.person_id, 'unknown'
    from roots root
    join couple couple on couple.id = root.couple_id
    cross join lateral unnest(array[couple.man_id, couple.woman_id]) person(person_id)
    where root.couple_id is not null;

    insert into event_instance_trainer (instance_id, person_id)
    select distinct created_instance.id, trainer.person_id
    from unnest(quick_event.trainer_person_ids) trainer(person_id)
    where trainer.person_id is not null;

    return next created_instance;
  end loop;
end;
$$;

select verify_function('quick_create_event_instances');
grant execute on function quick_create_event_instances to anonymous;
--! EndIncluded functions/quick_create_event_instances.sql
--! Included functions/detach_event_instance.sql
CREATE OR REPLACE FUNCTION public.detach_event_instance(
  p_instance_id     bigint,
  p_new_event_name  text   DEFAULT NULL
)
  RETURNS public.event
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
  v_old_event_id bigint;
  v_new_event_id bigint;
  v_old_att jsonb;
  v_old_demands jsonb;
BEGIN
  -- Lock the instance and fetch old event_id
  SELECT ei.event_id
  INTO v_old_event_id
  FROM public.event_instance ei
  WHERE ei.id        = p_instance_id
    FOR UPDATE;

  IF v_old_event_id IS NULL THEN
    RAISE EXCEPTION 'detach_event_instance: instance % not found', p_instance_id;
  END IF;

  -- Also lock the parent event row (prevents concurrent edits during cloning)
  PERFORM 1
  FROM public.event e
  WHERE e.id = v_old_event_id
    FOR UPDATE;

  -- Snapshot attendance state for this instance so it can be restored after
  -- the legacy registration bridge is rebuilt for the cloned event.
  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'reg_person_id', er.person_id,
    'reg_couple_id', er.couple_id,
    'attendee_person_id', eir.person_id,
    'registration_status', eir.registration_status,
    'source', eir.source,
    'target_cohort_id', eir.target_cohort_id,
    'status', eir.status,
    'attendance_note', eir.attendance_note,
    'attendance_created_at', eir.attendance_created_at,
    'attendance_updated_at', eir.attendance_updated_at
  )), '[]'::jsonb)
  INTO v_old_att
  FROM public.event_instance_registration eir
  JOIN public.event_registration er ON er.tenant_id = eir.tenant_id AND er.id = eir.legacy_registration_id AND er.event_id = v_old_event_id
  WHERE eir.instance_id = p_instance_id;

  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'reg_person_id', er.person_id,
    'reg_couple_id', er.couple_id,
    'trainer_id', trainer.id,
    'lesson_count', demand.lesson_count,
    'created_at', demand.created_at
  )), '[]'::jsonb)
  INTO v_old_demands
  FROM public.event_lesson_demand demand
  JOIN public.event_instance_registration eir ON eir.id = demand.registration_id
  JOIN public.event_registration er ON er.id = eir.legacy_registration_id
  JOIN public.event_instance_trainer trainer ON trainer.id = demand.trainer_id
  WHERE eir.instance_id = p_instance_id
    AND eir.parent_registration_id IS NULL;

  -- Reparenting synchronizes the new registrations before sweeping the old
  -- bridge rows, which would collide on the instance/person unit key.
  DELETE FROM public.event_instance_registration eir
  WHERE eir.instance_id = p_instance_id
    AND eir.event_id = v_old_event_id
    AND eir.legacy_registration_id IS NOT NULL;

  -- Clone the event (explicit column list, but short and stable in compact.sql)
  INSERT INTO public.event (
    name, location_text, description, capacity, files_legacy,
    updated_at, is_locked, is_visible, summary, is_public, enable_notes, tenant_id,
    type, location_id, created_at
  )
  SELECT
    COALESCE(p_new_event_name, e.name), e.location_text, e.description, e.capacity, e.files_legacy,
    now(), e.is_locked, e.is_visible, e.summary, e.is_public, e.enable_notes, e.tenant_id,
    e.type, e.location_id, now()
  FROM public.event e
  WHERE e.id = v_old_event_id
  RETURNING id INTO v_new_event_id;

  -- Copy event_target_cohort (natural key: cohort_id)
  INSERT INTO public.event_target_cohort (event_id, cohort_id, created_at, updated_at)
  SELECT v_new_event_id, etc.cohort_id, now(), now()
  FROM public.event_target_cohort etc
  WHERE etc.event_id = v_old_event_id
  ON CONFLICT (event_id, cohort_id) DO NOTHING;

  -- Copy event_trainer (natural key: person_id)
  INSERT INTO public.event_trainer (event_id, person_id, created_at, updated_at, lessons_offered)
  SELECT v_new_event_id, et.person_id, now(), now(), et.lessons_offered
  FROM public.event_trainer et
  WHERE et.event_id  = v_old_event_id
  ON CONFLICT (event_id, person_id) DO NOTHING;

  -- Re-point the instance and its denormalized trainer event IDs.
  UPDATE public.event_instance ei
  SET event_id   = v_new_event_id
  WHERE ei.id        = p_instance_id
    AND ei.event_id  = v_old_event_id;

  UPDATE public.event_instance_trainer
  SET event_id = v_new_event_id
  WHERE instance_id = p_instance_id;

  -- Copy registrations: map target_cohort_id by cohort_id (old_tc -> new_tc)
  INSERT INTO public.event_registration (
    event_id, target_cohort_id, couple_id, person_id, note, created_at
  )
  SELECT v_new_event_id, new_tc.id, er.couple_id, er.person_id, er.note, er.created_at
  FROM public.event_registration er
  LEFT JOIN public.event_target_cohort old_tc ON old_tc.tenant_id = er.tenant_id AND old_tc.id = er.target_cohort_id
  LEFT JOIN public.event_target_cohort new_tc ON new_tc.tenant_id = er.tenant_id AND new_tc.event_id  = v_new_event_id AND new_tc.cohort_id = old_tc.cohort_id
  WHERE er.event_id  = v_old_event_id
  ON CONFLICT (event_id, person_id, couple_id) DO NOTHING;

  INSERT INTO public.event_lesson_demand (
    trainer_id, registration_id, lesson_count, created_at, event_id
  )
  SELECT trainer.id, new_eir.id, old.lesson_count, old.created_at, v_new_event_id
  FROM jsonb_to_recordset(v_old_demands) AS old(
    reg_person_id bigint,
    reg_couple_id bigint,
    trainer_id bigint,
    lesson_count integer,
    created_at timestamptz
  )
  JOIN public.event_instance_trainer trainer
    ON trainer.id = old.trainer_id
   AND trainer.instance_id = p_instance_id
  JOIN public.event_registration new_reg
    ON new_reg.event_id = v_new_event_id
   AND new_reg.person_id IS NOT DISTINCT FROM old.reg_person_id
   AND new_reg.couple_id IS NOT DISTINCT FROM old.reg_couple_id
  JOIN public.event_instance_registration new_eir
    ON new_eir.instance_id = p_instance_id
   AND new_eir.legacy_registration_id = new_reg.id
   AND new_eir.parent_registration_id IS NULL
  ON CONFLICT (registration_id, trainer_id) DO NOTHING;

  -- Restore per-person attendance on the newly generated bridge rows.
  UPDATE public.event_instance_registration eir
  SET registration_status = oa.registration_status,
      source = oa.source,
      target_cohort_id = oa.target_cohort_id,
      status = oa.status,
      attendance_note = oa.attendance_note
  FROM jsonb_to_recordset(v_old_att) AS oa(
    reg_person_id bigint,
    reg_couple_id bigint,
    attendee_person_id bigint,
    registration_status public.event_instance_registration_status,
    source public.event_registration_source,
    target_cohort_id bigint,
    status public.attendance_type,
    attendance_note text
  )
  JOIN public.event_registration new_reg ON new_reg.event_id = v_new_event_id AND new_reg.person_id IS NOT DISTINCT FROM oa.reg_person_id AND new_reg.couple_id IS NOT DISTINCT FROM oa.reg_couple_id
  WHERE eir.instance_id     = p_instance_id
    AND eir.legacy_registration_id = new_reg.id
    AND eir.person_id IS NOT DISTINCT FROM oa.attendee_person_id;

  -- Restoring status/note correctly counts as an update for the new bridge row,
  -- so restore the original attendance audit lifecycle in a separate statement.
  UPDATE public.event_instance_registration eir
  SET attendance_created_at = oa.attendance_created_at,
      attendance_updated_at = oa.attendance_updated_at
  FROM jsonb_to_recordset(v_old_att) AS oa(
    reg_person_id bigint,
    reg_couple_id bigint,
    attendee_person_id bigint,
    attendance_created_at timestamptz,
    attendance_updated_at timestamptz
  )
  JOIN public.event_registration new_reg ON new_reg.event_id = v_new_event_id AND new_reg.person_id IS NOT DISTINCT FROM oa.reg_person_id AND new_reg.couple_id IS NOT DISTINCT FROM oa.reg_couple_id
  WHERE eir.instance_id = p_instance_id
    AND eir.legacy_registration_id = new_reg.id
    AND eir.person_id IS NOT DISTINCT FROM oa.attendee_person_id;

  return (select event from public.event where id = v_new_event_id);
END;
$$;

select verify_function('public.detach_event_instance');
grant execute on function detach_event_instance to anonymous;
--! EndIncluded functions/detach_event_instance.sql
--! Included functions/upsert_event.sql
drop function if exists upsert_event;

drop type if exists event_type_input;
drop type if exists event_instance_type_input;
drop type if exists event_instance_trainer_type_input;
drop type if exists event_trainer_type_input;
drop type if exists event_target_cohort_type_input;
drop type if exists event_registration_type_input;

CREATE TYPE public.event_type_input AS (
  id bigint,
  name text,
  summary text,
  description text,
  type public.event_type,
  location_id bigint,
  location_text text,
  capacity integer,
  is_visible boolean,
  is_public boolean,
  is_locked boolean,
  enable_notes boolean
);

CREATE TYPE public.event_instance_trainer_type_input AS (
  id bigint,
  person_id bigint,
  lessons_offered integer
);

CREATE TYPE public.event_instance_type_input AS (
  id bigint,
  since timestamp with time zone,
  until timestamp with time zone,
  is_cancelled boolean,
  trainers event_instance_trainer_type_input[]
);

CREATE TYPE public.event_trainer_type_input AS (
  id bigint,
  person_id bigint,
  lessons_offered integer
);

CREATE TYPE public.event_registration_type_input AS (
  id bigint,
  person_id bigint,
  couple_id bigint
);

CREATE OR REPLACE FUNCTION upsert_event(
  info event_type_input,
  event_instances event_instance_type_input[],
  trainers event_trainer_type_input[],
  registrations event_registration_type_input[]
) RETURNS event LANGUAGE plpgsql AS $$
declare
  instance event_instance_type_input;
  trainer event_trainer_type_input;
  instance_trainer event_instance_trainer_type_input;
  v_event event;
  v_instance_id bigint;
begin
  if cardinality(registrations) > 0 then
    raise exception 'event registrations must be edited on the event instance';
  end if;

  if info.id is null then

    insert into event (
      name,
      summary,
      description,
      type,
      location_id,
      location_text,
      capacity,
      is_visible,
      is_public,
      is_locked,
      enable_notes
    )
    values (
      info.name,
      info.summary,
      info.description,
      info.type,
      info.location_id,
      info.location_text,
      info.capacity,
      info.is_visible,
      info.is_public,
      info.is_locked,
      info.enable_notes
    )
    returning * into v_event;
  else
    update event set
      name=info.name,
      summary=info.summary,
      description=info.description,
      type=info.type,
      location_id=info.location_id,
      location_text=info.location_text,
      capacity=info.capacity,
      is_visible=info.is_visible,
      is_public=info.is_public,
      is_locked=info.is_locked,
      enable_notes=info.enable_notes
    where id=info.id
    returning * into v_event;

    if not found then
      raise exception 'event % not found', info.id;
    end if;
  end if;

  foreach instance in array coalesce(event_instances, '{}'::event_instance_type_input[]) loop
    if instance.id is null then
      insert into event_instance (event_id, since, until, is_cancelled)
      values (v_event.id, instance.since, instance.until, instance.is_cancelled)
      returning id into v_instance_id;
    elsif instance.since is null and instance.until is null then
      delete from event_instance where id=instance.id;
      v_instance_id := null;
    else
      update event_instance
      set since=instance.since, until=instance.until, is_cancelled=instance.is_cancelled
      where id=instance.id
      returning id into v_instance_id;
    end if;

    if v_instance_id is not null then
      foreach instance_trainer in array coalesce(instance.trainers, '{}'::event_instance_trainer_type_input[]) loop
        if instance_trainer.id is null then
          insert into event_instance_trainer (instance_id, person_id, lessons_offered)
          values (v_instance_id, instance_trainer.person_id, instance_trainer.lessons_offered)
          on conflict (instance_id, person_id) do update
            set lessons_offered = excluded.lessons_offered;
        elsif instance_trainer.person_id is null then
          delete from event_instance_trainer where id=instance_trainer.id;
        else
          update event_instance_trainer
          set person_id = instance_trainer.person_id,
              lessons_offered = instance_trainer.lessons_offered
          where id = instance_trainer.id and instance_id = v_instance_id;
        end if;
      end loop;
    end if;
  end loop;

  foreach trainer in array coalesce(trainers, '{}'::event_trainer_type_input[]) loop
    if trainer.id is null then
      insert into event_trainer (event_id, person_id, lessons_offered)
      values (v_event.id, trainer.person_id, trainer.lessons_offered)
      on conflict (event_id, person_id) do update
        set lessons_offered = trainer.lessons_offered;
    elsif trainer.person_id is null then
      delete from event_trainer where id=trainer.id;
    else
      update event_trainer set lessons_offered=trainer.lessons_offered where id=trainer.id;
    end if;
  end loop;

  return v_event;
end;
$$;

select verify_function('public.upsert_event');

COMMENT ON FUNCTION public.upsert_event is null;
GRANT ALL ON FUNCTION public.upsert_event TO anonymous;
--! EndIncluded functions/upsert_event.sql
