--! Previous: sha1:87f56e3b07dc33f83d62b34b41af157d2b22369a
--! Hash: sha1:8d07717c264de7529f2348927aef77890f085d64

--! split: 1-current.sql
create table if not exists public.event_series (
  id bigint primary key generated by default as identity,
  tenant_id bigint not null default public.current_tenant_id()
    references public.tenant (id) on update cascade on delete cascade,
  name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint event_series_tenant_id_id_key unique (tenant_id, id)
);

create or replace trigger _100_timestamps
  before insert or update on public.event_series
  for each row execute function app_private.tg__timestamps();

comment on table public.event_series is E'@behavior -query:resource:list -query:resource:connection -query:resource:single';
comment on constraint event_series_tenant_id_fkey on public.event_series is
  E'@fieldName tenant\n@foreignFieldName eventSeries';

grant all on table public.event_series to anonymous;
grant usage, select on sequence public.event_series_id_seq to anonymous;
alter table public.event_series enable row level security;

alter table public.event_instance
  add column if not exists series_id bigint;
comment on column public.event_instance.series_id is
  'Groups related events without supplying inherited event values.';

alter table public.event_series disable trigger _100_timestamps;
insert into public.event_series (
  id, tenant_id, name, created_at, updated_at
) overriding system value
select event.id, event.tenant_id, event.name,
  coalesce(event.created_at, now()), coalesce(event.updated_at, event.created_at, now())
from public.event event
where exists (
  select 1 from public.event_instance instance where instance.event_id = event.id
)
on conflict (id) do nothing;
alter table public.event_series enable trigger _100_timestamps;

select setval(
  pg_get_serial_sequence('public.event_series', 'id'),
  coalesce((select max(id) from public.event_series), 1),
  exists (select 1 from public.event_series)
);

alter table public.event_instance disable trigger _100_timestamps;
update public.event_instance
set series_id = event_id
where series_id is null and event_id is not null;
alter table public.event_instance enable trigger _100_timestamps;

create index if not exists event_instance_tenant_series_idx
  on public.event_instance (tenant_id, series_id);

alter table public.event_instance
  drop constraint if exists event_instance_series_fkey;
alter table public.event_instance
  add constraint event_instance_series_fkey
  foreign key (tenant_id, series_id)
  references public.event_series (tenant_id, id)
  on update cascade
  on delete set null (series_id)
  not valid;

alter table public.event_instance
  validate constraint event_instance_series_fkey;
comment on constraint event_instance_series_fkey on public.event_instance is
  E'@fieldName series\n@foreignFieldName events';

--! Included policies/event_series.sql
select app_private.drop_policies('public.event_series');

create policy current_tenant on public.event_series as restrictive
  using (tenant_id = (select public.current_tenant_id()))
  with check (tenant_id = (select public.current_tenant_id()));
create policy admin_all on public.event_series to administrator
  using (true) with check (true);
create policy trainer_all on public.event_series to trainer
  using (true) with check (true);
create policy member_view on public.event_series for select to member
  using (exists (
    select 1 from public.event_instance instance
    where instance.series_id = event_series.id
  ));
create policy public_view on public.event_series for select to anonymous
  using (exists (
    select 1 from public.event_instance instance
    where instance.series_id = event_series.id
  ));
--! EndIncluded policies/event_series.sql

alter table public.event_instance_trainer
  disable trigger _500_refresh_manager_person_ids;
insert into public.event_instance_trainer (
  tenant_id, instance_id, person_id, lessons_offered
)
select trainer.tenant_id, instance.id, trainer.person_id, trainer.lessons_offered
from public.event_instance instance
join public.event_trainer trainer on trainer.event_id = instance.event_id
where not exists (
  select 1 from public.event_instance_trainer exact
  where exact.instance_id = instance.id
)
on conflict (instance_id, person_id) do nothing;
alter table public.event_instance_trainer
  enable trigger _500_refresh_manager_person_ids;

--! Included functions/event_instance_trainers.sql
create or replace function app_private.event_instance_trainers_at(
  v_instance event_instance,
  v_at timestamptz
)
  returns setof tenant_trainer
  language sql stable
as $$
select distinct on (tt.tenant_id, tt.person_id) tt.*
from event_instance_trainer k
join tenant_trainer tt on tt.tenant_id = k.tenant_id and tt.person_id = k.person_id
where k.instance_id = v_instance.id
  and tt.active_range @> v_at
order by tt.tenant_id, tt.person_id, lower(tt.active_range) desc;
$$;
grant all on function app_private.event_instance_trainers_at to anonymous;

create or replace function public.event_instance_trainers(v_instance event_instance)
  returns setof tenant_trainer
  language sql stable
as $$
select * from app_private.event_instance_trainers_at(v_instance, v_instance.since);
$$;

grant all on function event_instance_trainers(event_instance) to anonymous;
comment on function event_instance_trainers(event_instance) is '@simpleCollections only';
--! EndIncluded functions/event_instance_trainers.sql
--! Included functions/can_trainer_edit_instance.sql
create or replace function app_private.can_trainer_edit_instance(iid bigint)
  returns boolean
  language sql stable security definer leakproof parallel safe
  set search_path = pg_catalog, pg_temp
as $$
  with recursive chain as (
    select i.id, i.parent_id from public.event_instance i where i.id = iid
    union all
    select p.id, p.parent_id from public.event_instance p join chain c on p.id = c.parent_id
  ),
  trainers as (
    select person_id from public.event_instance_trainer where instance_id in (select id from chain)
  )
  select exists (
    select 1 from trainers where person_id = any ((select public.current_person_ids())::bigint[])
  ) or not exists (
    select 1 from trainers
  );
$$;

grant all on function app_private.can_trainer_edit_instance(bigint) to anonymous;
--! EndIncluded functions/can_trainer_edit_instance.sql
--! Included functions/tg_event_instance__refresh_manager_person_ids.sql
create or replace function app_private.event_instance_manager_person_ids(p_instance_id bigint, p_event_id bigint)
  returns bigint[] language sql stable parallel safe as $$
  with recursive chain as (
    select id, parent_id
    from public.event_instance where id = p_instance_id
    union all
    select parent.id, parent.parent_id
    from public.event_instance parent
    join chain child on child.parent_id = parent.id
  ), managers as (
    select distinct person_id from public.event_instance_trainer
    where instance_id in (select id from chain)
  )
  select coalesce(array_agg(person_id order by person_id), '{}'::bigint[])
  from managers;
$$;

create or replace function app_private.refresh_event_instance_manager_person_ids(p_instance_id bigint, p_event_id bigint)
  returns boolean language sql security definer
  set search_path = pg_catalog, pg_temp as $$
  with recursive affected as (
    select id, event_id from public.event_instance where id = p_instance_id
    union all
    select child.id, child.event_id
    from public.event_instance child
    join affected parent on child.parent_id = parent.id
  ), desired as (
    select id, app_private.event_instance_manager_person_ids(id, event_id) as person_ids
    from affected
  ), changed as (
    update public.event_instance instance
    set manager_person_ids = desired.person_ids
    from desired
    where instance.id = desired.id
      and instance.manager_person_ids is distinct from desired.person_ids
    returning 1
  )
  select exists(select 1 from changed);
$$;

create or replace function app_private.tg_event_instance__refresh_manager_person_ids()
  returns trigger language plpgsql as $$
begin
  perform app_private.refresh_event_instance_manager_person_ids(new.id, new.event_id);
  return null;
end;
$$;
select verify_function('app_private.tg_event_instance__refresh_manager_person_ids', 'public.event_instance');
revoke execute on function app_private.tg_event_instance__refresh_manager_person_ids()
  from public, anonymous;

drop trigger if exists _500_refresh_manager_person_ids_from_parent on public.event_instance;
create trigger _500_refresh_manager_person_ids_from_parent
  after insert or update of parent_id on public.event_instance
  for each row execute function app_private.tg_event_instance__refresh_manager_person_ids();
--! EndIncluded functions/tg_event_instance__refresh_manager_person_ids.sql
--! Included functions/event_instances_for_range.sql
CREATE or replace FUNCTION public.event_instances_for_range(
  only_type public.event_type,
  start_range timestamp with time zone,
  end_range timestamp with time zone DEFAULT NULL::timestamp with time zone,
  trainer_ids bigint[] = null,
  participant_ids bigint[] = null,
  only_mine boolean = false,
  parent_id bigint = null
) RETURNS SETOF event_instance as $$
  select i.*
  from event_instance i
  where i.tenant_id = current_tenant_id()
    and (only_type IS NULL OR i.type = only_type)
    and i.parent_id is not distinct from $7
    and i.since < coalesce(end_range, 'infinity'::timestamptz)
    and i.until > start_range
    and (trainer_ids is null
      or exists (select 1 from event_instance_trainer where instance_id = i.id and person_id = any (trainer_ids)))
    and (participant_ids is null
      or exists (select 1 from event_instance_registration where instance_id = i.id and person_id = any (participant_ids) and registration_status = 'active' and status <> 'cancelled'))
    and (only_mine is false
      or exists (select 1 from event_instance_registration where instance_id = i.id and person_id = any ((select current_person_ids())::bigint[]) and registration_status = 'active' and status <> 'cancelled')
      or i.manager_person_ids && ((select current_person_ids())::bigint[]));
$$ stable language sql;

COMMENT ON FUNCTION public.event_instances_for_range IS '@simpleCollections only';
GRANT ALL ON FUNCTION public.event_instances_for_range TO anonymous;
--! EndIncluded functions/event_instances_for_range.sql
--! Included functions/move_event_instance.sql
create or replace function public.move_event_instance(
  id bigint,
  since timestamptz,
  until timestamptz,
  trainer_person_id bigint default null,
  location_id bigint default null,
  location_text text default null
) returns public.event_instance
  language plpgsql
as $$
declare
  inst public.event_instance;
begin
  update public.event_instance
  set since = move_event_instance.since,
      until = move_event_instance.until,
      location_id = case
        when move_event_instance.location_id is not null then move_event_instance.location_id
        when move_event_instance.location_text is not null then null
        else event_instance.location_id
      end,
      location_text = case
        when move_event_instance.location_id is not null then ''
        else coalesce(move_event_instance.location_text, event_instance.location_text)
      end
  where event_instance.id = move_event_instance.id
  returning * into inst;

  if not found then
    raise exception 'Event instance % not found', move_event_instance.id;
  end if;

  if trainer_person_id is not null then
    update public.event_instance_trainer
    set person_id = trainer_person_id
    where instance_id = inst.id
      and 1 = (select count(*) from public.event_instance_trainer where instance_id = inst.id);

    if not found
      and not exists (select 1 from public.event_instance_trainer where instance_id = inst.id)
    then
      insert into public.event_instance_trainer (instance_id, person_id)
      values (inst.id, trainer_person_id);
    end if;
  end if;

  return (select instance from public.event_instance instance where instance.id = inst.id);
end;
$$;

select verify_function('public.move_event_instance');
grant execute on function public.move_event_instance(
  bigint, timestamptz, timestamptz, bigint, bigint, text
) to anonymous;
--! EndIncluded functions/move_event_instance.sql
--! Included functions/quick_create_event_instances.sql
create or replace function quick_create_event_instances(
  events quick_event_input[],
  parent_id bigint default null
) returns setof event_instance
  language plpgsql
as $$
declare
  quick_event quick_event_input;
  created_instance event_instance;
begin
  foreach quick_event in array coalesce(events, '{}'::quick_event_input[]) loop
    insert into event_instance (
      parent_id, since, until, name, type, location_id, location_text,
      capacity, capacity_unit, is_visible, is_public, is_locked, enable_notes,
      description, summary
    ) values (
      parent_id, quick_event.since, quick_event.until, '',
      coalesce(quick_event.type, 'lesson'), quick_event.location_id,
      coalesce(quick_event.location_text, ''),
      case when coalesce(quick_event.type, 'lesson') = 'lesson' then 2 else 0 end,
      'people', true, false, false, false, '', ''
    )
    returning * into created_instance;

    with roots as (
      insert into event_instance_registration (
        instance_id, person_id, couple_id, source, status
      )
      select created_instance.id, registration.person_id, registration.couple_id,
        'manager',
        case when registration.person_id is not null then 'unknown'::attendance_type end
      from unnest(quick_event.registrations) registration
      returning id, couple_id
    )
    insert into event_instance_registration (
      instance_id, parent_registration_id, person_id, status
    )
    select created_instance.id, root.id, person.person_id, 'unknown'
    from roots root
    join couple couple on couple.id = root.couple_id
    cross join lateral unnest(array[couple.man_id, couple.woman_id]) person(person_id)
    where root.couple_id is not null;

    insert into event_instance_trainer (instance_id, person_id)
    select distinct created_instance.id, trainer.person_id
    from unnest(quick_event.trainer_person_ids) trainer(person_id)
    where trainer.person_id is not null;

    return next created_instance;
  end loop;
end;
$$;

select verify_function('quick_create_event_instances');
grant execute on function quick_create_event_instances to anonymous;
--! EndIncluded functions/quick_create_event_instances.sql
--! Included functions/upsert_event.sql
drop function if exists upsert_event;

drop type if exists event_type_input;
drop type if exists event_instance_type_input;
drop type if exists event_instance_trainer_type_input;
drop type if exists event_trainer_type_input;

CREATE TYPE public.event_type_input AS (
  id bigint,
  name text,
  summary text,
  description text,
  type public.event_type,
  location_id bigint,
  location_text text,
  capacity integer,
  is_visible boolean,
  is_public boolean,
  is_locked boolean,
  enable_notes boolean
);

CREATE TYPE public.event_instance_trainer_type_input AS (
  id bigint,
  person_id bigint,
  lessons_offered integer
);

CREATE TYPE public.event_instance_type_input AS (
  id bigint,
  since timestamp with time zone,
  until timestamp with time zone,
  is_cancelled boolean,
  trainers event_instance_trainer_type_input[]
);

CREATE TYPE public.event_trainer_type_input AS (
  id bigint,
  person_id bigint,
  lessons_offered integer
);

CREATE OR REPLACE FUNCTION upsert_event(
  info event_type_input,
  event_instances event_instance_type_input[],
  trainers event_trainer_type_input[]
) RETURNS event LANGUAGE plpgsql AS $$
declare
  instance event_instance_type_input;
  trainer event_trainer_type_input;
  instance_trainer event_instance_trainer_type_input;
  v_event event;
  v_instance_id bigint;
  v_series_id bigint;
begin
  if info.id is null then

    insert into event (
      name,
      summary,
      description,
      type,
      location_id,
      location_text,
      capacity,
      is_visible,
      is_public,
      is_locked,
      enable_notes
    )
    values (
      info.name,
      info.summary,
      info.description,
      info.type,
      info.location_id,
      info.location_text,
      info.capacity,
      info.is_visible,
      info.is_public,
      info.is_locked,
      info.enable_notes
    )
    returning * into v_event;

    insert into event_series (tenant_id, name)
    values (v_event.tenant_id, v_event.name)
    returning id into v_series_id;
  else
    update event set
      name=info.name,
      summary=info.summary,
      description=info.description,
      type=info.type,
      location_id=info.location_id,
      location_text=info.location_text,
      capacity=info.capacity,
      is_visible=info.is_visible,
      is_public=info.is_public,
      is_locked=info.is_locked,
      enable_notes=info.enable_notes
    where id=info.id
    returning * into v_event;

    if not found then
      raise exception 'event % not found', info.id;
    end if;

    select event_instance.series_id into v_series_id
    from event_instance
    where event_id = v_event.id and series_id is not null
    order by id
    limit 1;

    if v_series_id is null then
      insert into event_series (tenant_id, name)
      values (v_event.tenant_id, v_event.name)
      returning id into v_series_id;
    end if;
  end if;

  foreach instance in array coalesce(event_instances, '{}'::event_instance_type_input[]) loop
    if instance.id is null then
      insert into event_instance (event_id, series_id, since, until, is_cancelled)
      values (v_event.id, v_series_id, instance.since, instance.until, instance.is_cancelled)
      returning id into v_instance_id;
    elsif instance.since is null and instance.until is null then
      delete from event_instance where id=instance.id;
      v_instance_id := null;
    else
      update event_instance
      set since=instance.since, until=instance.until, is_cancelled=instance.is_cancelled
      where id=instance.id
      returning id into v_instance_id;
    end if;

    if v_instance_id is not null then
      foreach instance_trainer in array coalesce(instance.trainers, '{}'::event_instance_trainer_type_input[]) loop
        if instance_trainer.id is null then
          insert into event_instance_trainer (instance_id, person_id, lessons_offered)
          values (v_instance_id, instance_trainer.person_id, instance_trainer.lessons_offered)
          on conflict (instance_id, person_id) do update
            set lessons_offered = excluded.lessons_offered;
        elsif instance_trainer.person_id is null then
          delete from event_instance_trainer where id=instance_trainer.id;
        else
          update event_instance_trainer
          set person_id = instance_trainer.person_id,
              lessons_offered = instance_trainer.lessons_offered
          where id = instance_trainer.id and instance_id = v_instance_id;
        end if;
      end loop;
    end if;
  end loop;

  foreach trainer in array coalesce(trainers, '{}'::event_trainer_type_input[]) loop
    if trainer.id is null then
      insert into event_trainer (event_id, person_id, lessons_offered)
      values (v_event.id, trainer.person_id, trainer.lessons_offered)
      on conflict (event_id, person_id) do update
        set lessons_offered = trainer.lessons_offered;
    elsif trainer.person_id is null then
      delete from event_trainer where id=trainer.id;
    else
      update event_trainer set lessons_offered=trainer.lessons_offered where id=trainer.id;
    end if;
  end loop;

  return v_event;
end;
$$;

select verify_function('public.upsert_event');

COMMENT ON FUNCTION public.upsert_event is null;
GRANT ALL ON FUNCTION public.upsert_event TO anonymous;
--! EndIncluded functions/upsert_event.sql
--! Included functions/detach_event_instance.sql
create or replace function public.detach_event_instance(
  p_instance_id bigint,
  p_new_event_name text default null
)
  returns public.event
  language plpgsql
  security definer
  set search_path = pg_catalog, pg_temp
as $$
declare
  v_tenant_id bigint;
  v_old_event_id bigint;
  v_new_event_id bigint;
  v_result public.event;
begin
  select instance.tenant_id, instance.event_id
  into v_tenant_id, v_old_event_id
  from public.event_instance instance
  where instance.id = p_instance_id
  for update;

  if not found or v_old_event_id is null then
    raise exception 'INSTANCE_NOT_FOUND' using errcode = '22023';
  end if;
  if v_tenant_id <> public.current_tenant_id() then
    raise exception 'ACCESS_DENIED' using errcode = '42501';
  end if;

  if not (
    coalesce(app_private.is_system_admin(public.current_user_id()), false)
    or exists (
      select 1
      from public.current_tenant_administrator administrator
      where administrator.person_id = any (
        coalesce(public.current_person_ids(), '{}'::bigint[])
      )
        and administrator.active_range @> now()
    )
    or (
      exists (
        select 1
        from public.current_tenant_trainer trainer
        where trainer.person_id = any (
          coalesce(public.current_person_ids(), '{}'::bigint[])
        )
          and trainer.active_range @> now()
      )
      and app_private.can_trainer_edit_instance(p_instance_id)
    )
  ) then
    raise exception 'ACCESS_DENIED' using errcode = '42501';
  end if;

  perform 1
  from public.event event
  where event.id = v_old_event_id
    and event.tenant_id = v_tenant_id
  for update;

  if not exists (
    select 1
    from public.event_instance sibling
    where sibling.event_id = v_old_event_id
      and sibling.id <> p_instance_id
  ) then
    raise exception 'CANNOT_DETACH_ONLY_INSTANCE' using errcode = '22023';
  end if;

  insert into public.event (
    name, location_text, description, capacity, files_legacy,
    is_locked, is_visible, summary, is_public, enable_notes, tenant_id,
    type, location_id
  )
  select coalesce(p_new_event_name, event.name), event.location_text,
    event.description, event.capacity, event.files_legacy, event.is_locked,
    event.is_visible, event.summary, event.is_public, event.enable_notes,
    event.tenant_id, event.type, event.location_id
  from public.event event
  where event.id = v_old_event_id
  returning id into v_new_event_id;

  insert into public.event_trainer (
    tenant_id, event_id, person_id, lessons_offered
  )
  select trainer.tenant_id, v_new_event_id, trainer.person_id,
    trainer.lessons_offered
  from public.event_instance_trainer trainer
  where trainer.instance_id = p_instance_id;

  update public.event_instance_registration exact
  set event_id = v_new_event_id,
      legacy_registration_id = null
  where exact.instance_id = p_instance_id
    and (exact.event_id is distinct from v_new_event_id
      or exact.legacy_registration_id is not null);

  update public.event_instance instance
  set event_id = v_new_event_id,
      series_id = null
  where instance.id = p_instance_id;

  update public.event_instance_trainer trainer
  set event_id = v_new_event_id
  where trainer.instance_id = p_instance_id
    and trainer.event_id is distinct from v_new_event_id;

  update public.event_lesson_demand demand
  set event_id = v_new_event_id
  from public.event_instance_registration registration
  where registration.id = demand.registration_id
    and registration.instance_id = p_instance_id
    and demand.event_id is distinct from v_new_event_id;

  select event.* into strict v_result
  from public.event event
  where event.id = v_new_event_id;

  return v_result;
end;
$$;

select verify_function('public.detach_event_instance');
revoke execute on function public.detach_event_instance(bigint, text)
  from public, anonymous, member;
grant execute on function public.detach_event_instance(bigint, text)
  to trainer;
--! EndIncluded functions/detach_event_instance.sql

drop trigger if exists _600_sync_eir_registration_ins
  on public.event_registration;
drop trigger if exists _600_sync_eir_registration_upd
  on public.event_registration;
drop trigger if exists _600_sync_eir_registration_del
  on public.event_registration;
drop trigger if exists _600_sync_eir_instance_ins
  on public.event_instance;
drop trigger if exists _600_reparent_eir_instance
  on public.event_instance;
drop function if exists app_private.tg_event_registration__sync_eir();
drop function if exists app_private.tg_event_instance__sync_eir();
drop function if exists app_private.tg_event_instance__reparent_eir();
drop function if exists app_private.sync_eir_registrations(bigint[]);
drop function if exists app_private.event_registration_person_ids(
  public.event_registration
);

drop trigger if exists _500_refresh_manager_person_ids
  on public.event_trainer;
drop function if exists app_private.tg_event_trainer__refresh_manager_person_ids();

-- Manager access is derived only from the now-complete occurrence trainer lists.
alter table public.event_instance disable trigger _100_timestamps;
update public.event_instance instance
set manager_person_ids = app_private.event_instance_manager_person_ids(
  instance.id,
  instance.event_id
)
where instance.manager_person_ids is distinct from
  app_private.event_instance_manager_person_ids(instance.id, instance.event_id);
alter table public.event_instance enable trigger _100_timestamps;

do $$
begin
  if exists (
    select 1
    from public.event_instance instance
    where instance.event_id is not null
      and instance.series_id is distinct from instance.event_id
  ) then
    raise exception 'Legacy-backed event instances were not mapped to their event series';
  end if;

  if exists (
    select 1
    from public.event_instance instance
    join public.event_trainer trainer on trainer.event_id = instance.event_id
    where not exists (
      select 1 from public.event_instance_trainer exact
      where exact.instance_id = instance.id
    )
  ) then
    raise exception 'Legacy event trainer fallback was not fully materialized';
  end if;
end;
$$;
