<h1>Nabízíme</h1>
<h2>Lekce pro začátečníky</h2>
<ul class="list">
	<li>vhodné pro všechny, kteří ještě netančili nebo prošli kurzy v tanečních</li>
	<li>vyučujeme základní figury a techniky standardních a latinskoamerických
		tanců, držení těla, souhru s partnerem a soulad s hudbou</li>
	<li>vyučuje mladý proškolený trénérský kolektiv, složený z mistrů České republiky a
		tanečníků mezinárodní třídy</li>
</ul>
<hr/>
<h2>Zázemí pro taneční sport</h2>
<ul class="list">
	<li>vhodné pro pokročilé tanečníky se soutěžními ambicemi od dětí po dospělé</li>
	<li>tréninkový plán je zaměřený na výuku techniky standardních a
		latinskoamerických tanců, kondiční a fyzickou přípravu
		(pilates, atletická průprava) a soutěžní podání tanečního sportu</li>
	<li>vyučují extérní lektoři z Prahy, Brna, Ostravy - trenéři nejlepších párů a
		mistrů České republiky</li>
	<li>volné tréninky pro vlastní samostatné trénování, možnost individuálních
		lekcí s extérními trenéry</li>
</ul>
<hr/>
<h2>Tancování pro děti</h2>
<ul class="list">
	<li>vhodné pro děti od 8 do 14 let</li>
	<li>pohybová a taneční průprava, základní figury a techniky standardních a
		latinskoamerických tanců</li>
	<li>možné jako kroužek i příprava na taneční sport</li>
	<li>vyučuje mladý proškolený trénérský kolektiv, složený z mistrů České
		republiky a tanečníků mezinárodní třídy</li>
</ul>
<hr/>
<h2>Přípravka pro nejmenší</h2>
<ul class="list">
	<li>vhodné pro děti od 5 do 7 let</li>
	<li>taneční a pohybové hry, seznámení s hudbou a základními kroky</li>
	<li>vyučuje mladý proškolený trénérský kolektiv v kombinaci se zkušenými učiteli</li>
</ul>