/* DO NOT EDIT! This file is auto-generated by graphql-code-generator - see `codegen.yml` */
/* eslint-disable */
import * as Types from './index';

import { useQuery, useMutation, UseQueryOptions, UseMutationOptions } from '@tanstack/react-query';
import { fetcher } from 'lib/query';
export type CohortFragment = { __typename: 'Skupiny', sId: string, sName: string, sDescription: string, sLocation: string, sVisible: boolean, sColorRgb: string };

export type CohortListQueryVariables = Types.Exact<{
  visible?: Types.InputMaybe<Types.Scalars['Boolean']>;
}>;


export type CohortListQuery = { __typename?: 'Query', skupinies: { __typename?: 'SkupiniesConnection', nodes: Array<{ __typename: 'Skupiny', sId: string, sName: string, sDescription: string, sLocation: string, sVisible: boolean, sColorRgb: string, platbyGroupSkupinasByPgsIdSkupina: { __typename?: 'PlatbyGroupSkupinasConnection', nodes: Array<{ __typename?: 'PlatbyGroupSkupina', pgsIdGroup: string }> } }> } | null };

export type CohortMembersQueryVariables = Types.Exact<{
  id: Types.Scalars['BigInt'];
}>;


export type CohortMembersQuery = { __typename?: 'Query', members: { __typename?: 'MembersConnection', nodes: Array<{ __typename?: 'Member', uJmeno: string | null, uPrijmeni: string | null, uRodneCislo: string | null, uTelefon: string | null, uEmail: string | null }> } | null };

export type CohortQueryVariables = Types.Exact<{
  id: Types.Scalars['BigInt'];
}>;


export type CohortQuery = { __typename?: 'Query', skupiny: { __typename: 'Skupiny', sId: string, sName: string, sDescription: string, sLocation: string, sVisible: boolean, sColorRgb: string } | null };

export type CreateCohortMutationVariables = Types.Exact<{
  input: Types.SkupinyInput;
}>;


export type CreateCohortMutation = { __typename?: 'Mutation', createSkupiny: { __typename: 'CreateSkupinyPayload' } | null };

export type UpdateCohortMutationVariables = Types.Exact<{
  id: Types.Scalars['BigInt'];
  patch: Types.SkupinyPatch;
}>;


export type UpdateCohortMutation = { __typename?: 'Mutation', updateSkupiny: { __typename: 'UpdateSkupinyPayload' } | null };

export type DeleteCohortMutationVariables = Types.Exact<{
  id: Types.Scalars['BigInt'];
}>;


export type DeleteCohortMutation = { __typename?: 'Mutation', deleteSkupiny: { __typename: 'DeleteSkupinyPayload' } | null };

export const CohortFragmentDoc = `
    fragment Cohort on Skupiny {
  __typename
  sId
  sName
  sDescription
  sLocation
  sVisible
  sColorRgb
}
    `;
export const CohortListDocument = `
    query CohortList($visible: Boolean) {
  skupinies(condition: {sVisible: $visible}) {
    nodes {
      ...Cohort
      platbyGroupSkupinasByPgsIdSkupina {
        nodes {
          pgsIdGroup
        }
      }
    }
  }
}
    ${CohortFragmentDoc}`;
export const useCohortListQuery = <
      TData = CohortListQuery,
      TError = unknown
    >(
      variables?: CohortListQueryVariables,
      options?: UseQueryOptions<CohortListQuery, TError, TData>
    ) =>
    useQuery<CohortListQuery, TError, TData>(
      variables === undefined ? ['CohortList'] : ['CohortList', variables],
      fetcher<CohortListQuery, CohortListQueryVariables>(CohortListDocument, variables),
      options
    );

useCohortListQuery.getKey = (variables?: CohortListQueryVariables) => variables === undefined ? ['CohortList'] : ['CohortList', variables];
;

useCohortListQuery.fetcher = (variables?: CohortListQueryVariables, options?: RequestInit['headers']) => fetcher<CohortListQuery, CohortListQueryVariables>(CohortListDocument, variables, options);
export const CohortMembersDocument = `
    query CohortMembers($id: BigInt!) {
  members(condition: {sId: $id}) {
    nodes {
      uJmeno
      uPrijmeni
      uRodneCislo
      uTelefon
      uEmail
    }
  }
}
    `;
export const useCohortMembersQuery = <
      TData = CohortMembersQuery,
      TError = unknown
    >(
      variables: CohortMembersQueryVariables,
      options?: UseQueryOptions<CohortMembersQuery, TError, TData>
    ) =>
    useQuery<CohortMembersQuery, TError, TData>(
      ['CohortMembers', variables],
      fetcher<CohortMembersQuery, CohortMembersQueryVariables>(CohortMembersDocument, variables),
      options
    );

useCohortMembersQuery.getKey = (variables: CohortMembersQueryVariables) => ['CohortMembers', variables];
;

useCohortMembersQuery.fetcher = (variables: CohortMembersQueryVariables, options?: RequestInit['headers']) => fetcher<CohortMembersQuery, CohortMembersQueryVariables>(CohortMembersDocument, variables, options);
export const CohortDocument = `
    query Cohort($id: BigInt!) {
  skupiny(sId: $id) {
    ...Cohort
  }
}
    ${CohortFragmentDoc}`;
export const useCohortQuery = <
      TData = CohortQuery,
      TError = unknown
    >(
      variables: CohortQueryVariables,
      options?: UseQueryOptions<CohortQuery, TError, TData>
    ) =>
    useQuery<CohortQuery, TError, TData>(
      ['Cohort', variables],
      fetcher<CohortQuery, CohortQueryVariables>(CohortDocument, variables),
      options
    );

useCohortQuery.getKey = (variables: CohortQueryVariables) => ['Cohort', variables];
;

useCohortQuery.fetcher = (variables: CohortQueryVariables, options?: RequestInit['headers']) => fetcher<CohortQuery, CohortQueryVariables>(CohortDocument, variables, options);
export const CreateCohortDocument = `
    mutation CreateCohort($input: SkupinyInput!) {
  createSkupiny(input: {skupiny: $input}) {
    __typename
  }
}
    `;
export const useCreateCohortMutation = <
      TError = unknown,
      TContext = unknown
    >(options?: UseMutationOptions<CreateCohortMutation, TError, CreateCohortMutationVariables, TContext>) =>
    useMutation<CreateCohortMutation, TError, CreateCohortMutationVariables, TContext>(
      ['CreateCohort'],
      (variables?: CreateCohortMutationVariables) => fetcher<CreateCohortMutation, CreateCohortMutationVariables>(CreateCohortDocument, variables)(),
      options
    );
useCreateCohortMutation.getKey = () => ['CreateCohort'];

useCreateCohortMutation.fetcher = (variables: CreateCohortMutationVariables, options?: RequestInit['headers']) => fetcher<CreateCohortMutation, CreateCohortMutationVariables>(CreateCohortDocument, variables, options);
export const UpdateCohortDocument = `
    mutation UpdateCohort($id: BigInt!, $patch: SkupinyPatch!) {
  updateSkupiny(input: {sId: $id, patch: $patch}) {
    __typename
  }
}
    `;
export const useUpdateCohortMutation = <
      TError = unknown,
      TContext = unknown
    >(options?: UseMutationOptions<UpdateCohortMutation, TError, UpdateCohortMutationVariables, TContext>) =>
    useMutation<UpdateCohortMutation, TError, UpdateCohortMutationVariables, TContext>(
      ['UpdateCohort'],
      (variables?: UpdateCohortMutationVariables) => fetcher<UpdateCohortMutation, UpdateCohortMutationVariables>(UpdateCohortDocument, variables)(),
      options
    );
useUpdateCohortMutation.getKey = () => ['UpdateCohort'];

useUpdateCohortMutation.fetcher = (variables: UpdateCohortMutationVariables, options?: RequestInit['headers']) => fetcher<UpdateCohortMutation, UpdateCohortMutationVariables>(UpdateCohortDocument, variables, options);
export const DeleteCohortDocument = `
    mutation DeleteCohort($id: BigInt!) {
  deleteSkupiny(input: {sId: $id}) {
    __typename
  }
}
    `;
export const useDeleteCohortMutation = <
      TError = unknown,
      TContext = unknown
    >(options?: UseMutationOptions<DeleteCohortMutation, TError, DeleteCohortMutationVariables, TContext>) =>
    useMutation<DeleteCohortMutation, TError, DeleteCohortMutationVariables, TContext>(
      ['DeleteCohort'],
      (variables?: DeleteCohortMutationVariables) => fetcher<DeleteCohortMutation, DeleteCohortMutationVariables>(DeleteCohortDocument, variables)(),
      options
    );
useDeleteCohortMutation.getKey = () => ['DeleteCohort'];

useDeleteCohortMutation.fetcher = (variables: DeleteCohortMutationVariables, options?: RequestInit['headers']) => fetcher<DeleteCohortMutation, DeleteCohortMutationVariables>(DeleteCohortDocument, variables, options);