/* DO NOT EDIT! This file is auto-generated by graphql-code-generator - see `codegen.yml` */
/* eslint-disable */
import * as Types from './index';

import { useQuery, useMutation, UseQueryOptions, UseMutationOptions } from '@tanstack/react-query';
import { fetcher } from 'lib/query';
export type CoupleListQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type CoupleListQuery = { __typename?: 'Query', activeCouples: { __typename?: 'PariesConnection', totalCount: number, nodes: Array<{ __typename?: 'Pary', pId: string, userByPIdPartner: { __typename?: 'User', uJmeno: string, uPrijmeni: string } | null, userByPIdPartnerka: { __typename?: 'User', uJmeno: string, uPrijmeni: string } | null }> } | null };

export type CreateCoupleMutationVariables = Types.Exact<{
  man: Types.Scalars['BigInt'];
  woman: Types.Scalars['BigInt'];
}>;


export type CreateCoupleMutation = { __typename?: 'Mutation', createCouple: { __typename?: 'CreateCouplePayload', paries: Array<{ __typename?: 'Pary', pId: string }> | null } | null };

export type DeleteCoupleMutationVariables = Types.Exact<{
  id: Types.Scalars['BigInt'];
}>;


export type DeleteCoupleMutation = { __typename?: 'Mutation', deletePary: { __typename: 'DeleteParyPayload' } | null };

export type FixUnpairedCouplesMutationVariables = Types.Exact<{ [key: string]: never; }>;


export type FixUnpairedCouplesMutation = { __typename?: 'Mutation', fixUnpairedCouples: { __typename?: 'FixUnpairedCouplesPayload', paries: Array<{ __typename?: 'Pary', pId: string }> | null } | null };


export const CoupleListDocument = `
    query CoupleList {
  activeCouples {
    totalCount
    nodes {
      pId
      userByPIdPartner {
        uJmeno
        uPrijmeni
      }
      userByPIdPartnerka {
        uJmeno
        uPrijmeni
      }
    }
  }
}
    `;
export const useCoupleListQuery = <
      TData = CoupleListQuery,
      TError = unknown
    >(
      variables?: CoupleListQueryVariables,
      options?: UseQueryOptions<CoupleListQuery, TError, TData>
    ) =>
    useQuery<CoupleListQuery, TError, TData>(
      variables === undefined ? ['CoupleList'] : ['CoupleList', variables],
      fetcher<CoupleListQuery, CoupleListQueryVariables>(CoupleListDocument, variables),
      options
    );

useCoupleListQuery.getKey = (variables?: CoupleListQueryVariables) => variables === undefined ? ['CoupleList'] : ['CoupleList', variables];
;

useCoupleListQuery.fetcher = (variables?: CoupleListQueryVariables, options?: RequestInit['headers']) => fetcher<CoupleListQuery, CoupleListQueryVariables>(CoupleListDocument, variables, options);
export const CreateCoupleDocument = `
    mutation CreateCouple($man: BigInt!, $woman: BigInt!) {
  createCouple(input: {man: $man, woman: $woman}) {
    paries {
      pId
    }
  }
}
    `;
export const useCreateCoupleMutation = <
      TError = unknown,
      TContext = unknown
    >(options?: UseMutationOptions<CreateCoupleMutation, TError, CreateCoupleMutationVariables, TContext>) =>
    useMutation<CreateCoupleMutation, TError, CreateCoupleMutationVariables, TContext>(
      ['CreateCouple'],
      (variables?: CreateCoupleMutationVariables) => fetcher<CreateCoupleMutation, CreateCoupleMutationVariables>(CreateCoupleDocument, variables)(),
      options
    );
useCreateCoupleMutation.getKey = () => ['CreateCouple'];

useCreateCoupleMutation.fetcher = (variables: CreateCoupleMutationVariables, options?: RequestInit['headers']) => fetcher<CreateCoupleMutation, CreateCoupleMutationVariables>(CreateCoupleDocument, variables, options);
export const DeleteCoupleDocument = `
    mutation DeleteCouple($id: BigInt!) {
  deletePary(input: {pId: $id}) {
    __typename
  }
}
    `;
export const useDeleteCoupleMutation = <
      TError = unknown,
      TContext = unknown
    >(options?: UseMutationOptions<DeleteCoupleMutation, TError, DeleteCoupleMutationVariables, TContext>) =>
    useMutation<DeleteCoupleMutation, TError, DeleteCoupleMutationVariables, TContext>(
      ['DeleteCouple'],
      (variables?: DeleteCoupleMutationVariables) => fetcher<DeleteCoupleMutation, DeleteCoupleMutationVariables>(DeleteCoupleDocument, variables)(),
      options
    );
useDeleteCoupleMutation.getKey = () => ['DeleteCouple'];

useDeleteCoupleMutation.fetcher = (variables: DeleteCoupleMutationVariables, options?: RequestInit['headers']) => fetcher<DeleteCoupleMutation, DeleteCoupleMutationVariables>(DeleteCoupleDocument, variables, options);
export const FixUnpairedCouplesDocument = `
    mutation FixUnpairedCouples {
  fixUnpairedCouples(input: {}) {
    paries {
      pId
    }
  }
}
    `;
export const useFixUnpairedCouplesMutation = <
      TError = unknown,
      TContext = unknown
    >(options?: UseMutationOptions<FixUnpairedCouplesMutation, TError, FixUnpairedCouplesMutationVariables, TContext>) =>
    useMutation<FixUnpairedCouplesMutation, TError, FixUnpairedCouplesMutationVariables, TContext>(
      ['FixUnpairedCouples'],
      (variables?: FixUnpairedCouplesMutationVariables) => fetcher<FixUnpairedCouplesMutation, FixUnpairedCouplesMutationVariables>(FixUnpairedCouplesDocument, variables)(),
      options
    );
useFixUnpairedCouplesMutation.getKey = () => ['FixUnpairedCouples'];

useFixUnpairedCouplesMutation.fetcher = (variables?: FixUnpairedCouplesMutationVariables, options?: RequestInit['headers']) => fetcher<FixUnpairedCouplesMutation, FixUnpairedCouplesMutationVariables>(FixUnpairedCouplesDocument, variables, options);