<?php
return array(
    array(
        'Uživatelé',
        '/admin/users',
        array()
    ),
    array(
        'Skupiny',
        '/admin/skupiny',
        array()
    ),
    array(
        'Platby',
        '/admin/platby',
        array()
    ),
    array(
        'Páry',
        '/admin/pary',
        array()
    ),
    array(
        'Články',
        '/admin/aktuality',
        array()
    ),
    array(
        'Nástěnka',
        '/admin/nastenka',
        array()
    ),
    array(
        'Rozpis',
        '/admin/rozpis',
        array()
    ),
    array(
        'Nabídka',
        '/admin/nabidka',
        array()
    ),
    array(
        'Akce',
        '/admin/akce',
        array()
    ),
    array(
        'Galerie',
        '/admin/galerie',
        array()
    ),
    array(
        'Dokumenty',
        '/admin/dokumenty',
        array()
    ),
    array(
        'Oprávnění',
        '/admin/permissions',
        array()
    ),
    array(
        'Konzole',
        '/admin/konzole',
        array()
    )
);
