<?php
return array(
    array(
        'Novinky',
        '/member/home',
        array()
    ),
    array(
        'Nástěnka',
        '/member/nastenka',
        array()
    ),
    array(
        'Rozpis',
        '/member/rozpis',
        array()
    ),
    array(
        'Nabídka',
        '/member/nabidka',
        array()
    ),
    array(
        'Akce',
        '/member/akce',
        array()
    ),
    array(
        'Dokumenty',
        '/member/dokumenty',
        array()
    ),
    array(
        'Žebříček',
        '/member/pary',
        array()
    ),
    array(
        'Přehled členů',
        '/member/clenove/structure',
        array()
    ),
    array(
        'Profil',
        '/member/profil',
        array()
    ),
);