<div class="container">
  <div class="row">
    <div class="col-12 col-md-6">
      <p>
        <h2>Taneční centrum při FZŠ Holečkova</h2>
        Holečkova 10, 779 00 Olomouc<br>
        (vchod brankou u&nbsp;zastávky <i>Povel, škola</i>)<br>
        <a href="http://www.zsholeckova.cz/">http://www.zsholeckova.cz/</a>
      </p>
      <div id="holeckova" style="height:194px;margin-bottom:2rem"></div>
    </div>
    <div class="col-12 col-md-6">
      <img style="max-width:100%" alt="" src="/images/sal-holeckova-small.jpg">
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-md-6">
      <p>
        <h2>Tělocvična Slovanského gymnázia</h2>
        Jiřího z Poděbrad 13, 779 00 Olomouc<br>
        (vchod bránou z&nbsp;ulice <i>U reálky</i>)<br>
        <a href="http://www.sgo.cz/">http://www.sgo.cz/</a>
      </p>
      <div id="slovan" style="height:194px;margin-bottom:2rem"></div>
    </div>
    <div class="col-12 col-md-6">
      <img style="max-width:100%" alt="" src="/images/sal-sgo-small.jpg">
    </div>
  </div>
</div>
