<div style="text-align:center;font-size:130%;margin:5px 100px;">
<img alt="" src="/images/underconstruction.png" style="float:left;width:140px;"/>
Stránky jsou v rekonstrukci, vraťte se prosím později.<br/><br/>
Stávající členové TK Olymp, prosím, registrujte se.
</div>
<hr style="clear:both;margin:15px 0;"/>
<div style="text-align:center;margin:0 auto;font-size:150%;">
Přejeme Vám<br/>
pohodové tancování<br/>
v roce 2012
</div>
<img alt="" src="/images/pernik.jpg" style="margin:25px auto;display:block;width:350px;" />