<?php header_main('Odkazy');?>
<ul class="list">
	<li><a href="http://www.csts.cz/">Český svaz tanečního sportu</a></li>
	<li><a href="http://www.worlddancesport.org/">World DanceSport Federation</a></li>
	<li><a href="http://www.dancesportinfo.net/">Dancesport info - The Dancers´ Website</a></li>
	<li><a href="http://tanecni-olomouc.cz/">Taneční škola Progress Olomouc</a></li>
	<li><a href="http://talidance.wz.cz/">Tali Dance - taneční obuv</a></li>
	<li><a href="http://www.henzely.cz/">Dance-point - obchody s tanečním zbožím</a></li>
	<li><a href="http://www.hellerdance.cz/">Heller Dance and Fashion</a></li>
	<li><a href="http://www.spaeker.de/">Heinz Spaeker - DanceSport Services</a></li>
	<li><a href="http://www.majkluvsvet.cz/">Majklův svět - Tanec v obrazech</a></li>
	<li><a href="http://dalibor-trojan.cz/">Dalibor Trojan Photography</a></li>
</ul>