<?php
header_main('Pro nové zájemce');
?>
<p>Každý školní rok začínáme náborem nových členů. Podle počtu
přihlášených nováčků vytváříme nové tréninkové skupiny. Ve školním roce
2011/2012 se do skupiny začátečníků přihlásilo 23 nováčků ve věku od 13
do 30 let. Vedené tréninky probíhají každé úterý (18:45) a čtvrtek
(19:00), dále mají nováčci možnost využívat tréninkových prostor pro
vlastní trénink a našich trenérů k individuálním lekcím.</p>
<br/>
<?php header_main('Často kladené otázky');?>
<p>
	<span class="big">Mohu se přihlásit i v průběhu roku?</span>
	<br/>
	<img style="margin: 0 5px -6px 0;" alt="" src="/images/tick.jpg"/>
	Ano, kontaktujte nás a my s Vámi na základě
	Vašich požadavků vybereme nejlepší způsob, jak u nás začít.
</p>
<p>
	<span class="big">Musím do klubu vstoupit s partnerem/partnerkou?</span>
	<br/>
	<img style="margin: 0 5px -5px 0;" alt="" src="/images/tick.jpg"/>
	Není to vysloveně nutné, ale určitě je to
	lepší. Můžete mít štěstí a na nového partnera narazíte u nás v
	klubu,také můžete využít možnosti naší
	<a href="http://www.tkolymp.cz/inzerce/posledni">seznamky</a>. Pokud
	nemůžete na žádného partnera narazit, kotaktujte odpovědou osobu z
	klubu, rádi Vám pomůžeme.
</p>
<p>
	<span class="big">Jak mám přijít oblečený(á)? </span>
	<br/>
	<img style="margin: 0 5px -6px 0;" alt="" src="/images/tick.jpg"/>
	Oblečení, obzvlášť pro začátečníky, nijak
	podmíněné. Oblečení na tréninky zvolte polospolečenské, pohodlné,
	prostě takové, abyste se cítili příjemně.
</p>
<p>
	<span class="big">Musím si hned od začátku pořídit taneční obuv?</span>
	<br/>
	<img style="margin: 0 5px -6px 0;" alt="" src="/images/tick.jpg"/>
	Není nutné mít hned od začátku speciální
	taneční obuv. Pokud to s tancem budete myslet vážně, určitě si ji
	pořídíte. Sami nejlépe poznáte, kdy přijde ten správný čas. Pro začátek
	postačí běžná sálová sportovní obuv.
</p>
<p>
	<span class="big">Pokud chci začít navštěvovat kurz až v jeho průběhu,
		budu platit plnou cenu?</span>
	<br/>
	<img style="margin: 0 5px -6px 0;" alt="" src="/images/tick.jpg"/>
	Ne, uděláme
	Vám poměrnou cenu podle toho, kdy začnete navštěvovat naše kurzy.
</p>

